### ISSUE TITLE
Trim Analyzer and Trimmer warning parity

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#101149]
Tracking issue for all discrepancies between Trim analyzer and Trimmer warnings in Mono.Linker.Tests.Cases

- [ ] [Missing support for DynamicDependency in trim analyzer](https://github.com/dotnet/runtime/issues/83080)
- [ ] [Analyzer processes expression tree construction data flow differently from linker](https://github.com/dotnet/linker/issues/3172)
- [ ] [Trimming: Reflection access to compiler generated methods produces warnings](https://github.com/dotnet/runtime/issues/85042)
- [ ] [Analyzer doesn't warn about reflection access to generated backing fields](https://github.com/dotnet/linker/issues/2628)
- [ ] [Trim analyzer doesn't recognize Linq Expressions translations](https://github.com/dotnet/runtime/issues/101148)
- [ ]
