### ISSUE TITLE
Implement support for Swift frozen structs in Mono runtime

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#102077]
# Description

This issue tracks the implementation of the Swift frozen struct lowering in Mono runtime. The Swift runtime enregisters frozen structs as a set of primitives if the sequence <= 4 machine words. The Mono runtime should utilize [the lowering API](https://github.com/dotnet/runtime/pull/99439) and implements the same behavior as the Swift runtime when interoperating with Swift in JIT/AOT and interpreter configurations.

The lowering algorithm is implemented in . The Mono runtime should utilize the lowering API and have the same behavior as Swift runtime when interop with Swift in JIT/AOT and interpreter configurations. 

 
The existing [runtime tests](https://github.com/dotnet/runtime/tree/main/src/tests/Interop/Swift/SwiftAbiStress) should be used for validation.

## Tasks
 - [x] https://github.com/dotnet/runtime/pull/102143
 - [x] Support Swift frozen struct returns for pinvokes in JIT/AOT and interpreter configurations https://github.com/dotnet/runtime/pull/104389
     - [ ] Refactor implementation of Swift frozen struct lowering in pinvokes from IR to IL level to match with the implementation of callback lowering
 - [x] Support Swift frozen struct for callbacks in JIT/AOT and interpreter configurations https://github.com/dotnet/runtime/pull/104437
 - [x] Support Swift frozen struct for callbacks returns in JIT/AOT and interpreter configurations https://github.com/dotnet/runtime/pull/104949
 - [ ] (optional) Add cache that maps structs to computed lowering (`SwiftPhysicalLowering`). The goal is to eliminate repeated runs of lowering algorithm for "known" structs.

**Comment by kotlarmilos** [comment]
Moving the following to the next release.

- [ ] `(optional) Add cache that maps structs to computed lowering (SwiftPhysicalLowering). The goal is to eliminate repeated runs of lowering algorithm for "known" structs.`
