### ISSUE TITLE
Target .NET 10 / net10.0

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#105343]
This issue tracks the infrastructure work that is required to target net10.0 for producing .NET 10 builds. The work tracked here usually starts happening when we branch-off main for .NET 9 RC2 in mid August.

### Phase 1 - Branding

The branding work needs to happen in a separate PR from the re-targeting work and **must not** update the assembly version. This means that the `AssemblyVersion` property needs to be hardcoded to 9.0.0.0 here: https://github.com/dotnet/runtime/blob/d8a642fb46a6a047ef7c6c9c0e16b09674570c33/eng/Versions.props#L22

- [x] Status box. Tick to mark phase 1 as completed.

### Phase 2 - Re-targeting

After the branding work is done, the TFM re-targeting work can happen. There's a long list of things to do. For reference, [here's the PR from last year for net9.0](https://github.com/dotnet/runtime/pull/90880).

- [x] Add dotnet10 & dotnet10-transport NuGet feeds.
- [x] Update [TFM properties](https://github.com/dotnet/runtime/blob/d8a642fb46a6a047ef7c6c9c0e16b09674570c33/Directory.Build.props#L89-L104) so that `NetCoreAppCurrent=net10.0`, `NetCoreAppPrevious=net9.0` and `NetCoreAppMinimum=net8.0`.
- [x] Update [the globally set AssemblyVersion](https://github.com/dotnet/runtime/blob/d8a642fb46a6a047ef7c6c9c0e16b09674570c33/eng/Versions.props#L22) back to `$(MajorVersion).$(MinorVersion).0.0`.
- [x] [Update the ApiCompat baseline versions](https://github.com/dotnet/runtime/blob/d8a642fb46a6a047ef7c6c9c0e16b09674570c33/Directory.Build.props#L125-L126) to the latest officially released package version (should be P7 if this is worked on in August). Add a TODO marker and file an issue to track updating this version to 9.0.0 GA in November.
- [x] Update hardcoded 9.0.0.0 assembly versions in CompatibilitySuppressions.xml files (APICompat config).
- [x] [Remove the `DisablePackageBaselineValidation` property](https://github.com/search?q=repo%3Adotnet%2Fruntime%20DisablePackageBaselineValidation&type=code) and its comment so that we have APICompat validation for new packages during re-targeting.

WIP - Add more to this list

### Phase 3 - Clean-up

- [x] Eventually remove net9.0 NuGet feeds when all moving dependencies are on the dotnet10 feeds: https://github.com/dotnet/runtime/issues/106593
- [x] Change `set(PRERELEASE 1)` to 0 in eng/native/configureplatform.cmake in the `release/9.0` branch so new compiler warnings don't fail the servicing build.

**Comment by akoeplinger** [comment]
I think everything was done here, closing.
