### ISSUE TITLE
JIT: overview of proposed local var reference count changes

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#10702]
This issue proposes a series of changes to reduce the overhead and increase the fidelity of local variable reference counts in the jit. The main idea is to get rid of the current costly and buggy incremental count maintenance in favor of batch updates that are done just before accurate ref counts are needed.

See discussion in dotnet/runtime#8715 for background.

Expected impact is:
* 4-5% improvement in tier0 / minopts / debug throughput
* minimal impact to optimized jit throughput
* smaller frame sizes in some cases where reference counts are currently inflated
* removal of workarounds to artificially inflate reference counts to avoid asserts

The more accurate reference counts and weighted counts are likely to cause widespread codegen diffs. Hopefully these will mostly be improvements, but some regressions are certainly possible.

Proposed steps are:
- [x] encapsulate accesses to `lvRefCnt` and `lvRefCntWtd` in an API, make backing fields private (#18979)
- [x] characterize when ref count access and update is invalid, and update API to flag invalid access (#19068)
- [x] classify invalid accesses and figure out strategies for removing them (#19012)
- [x] once all invalid accesses are removed, add appropriate asserts to catch invalid accesses (#19068)
- [x] figure out what actions under `lvaMarkRefs` are required for all compilations vs only needed when optimizing (#19103, dotnet/coreclr#19240)
- [x] figure out minopts / debug codegen approach (#19103)
- [x] ensure we have an algorithm that can properly recompute counts from scratch (#19240)
- [x] recompute counts after lower (#19325)
- [x] change from incremental updates to batched updates (#19345)
- [x] decide how often counts need to be made current (or track if they've possibly gone stale) (#19345)
- [x] sort through codegen diffs resulting from more accurate ref counts and fix what can be fixed (#19345)
- [ ] try and clean up the logic in `lvaMarkRefs` to split out ref counting from other activities

cc @dotnet/jit-contrib 

category:implementation
theme:ir
skill-level:expert
cost:large

**Comment by AndyAyersMS** [comment]
This is basically done, so will close.
