### ISSUE TITLE
[cdac] Deploy cdac with SOS and CLRMA in .NET 11

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#108720]
Part of #99298 

We would like to ship the cdac together with [SOS](https://github.com/dotnet/diagnostics/tree/main/src/SOS) and to allow SOS to load and use the cdac instead of the brittle DAC in .NET 11.  This issue tracks the runtime changes necessary, and summarizes the SOS changes.

* [ ] Remove brittle DAC ability to load & delegate to cDAC
* [ ] Remove the `cdacreader_` entrypoints from mscorcdac
* [ ] [Support all API's called by SOS](https://github.com/dotnet/runtime/issues/117782)
* [ ] [Support all API's called by CLRMD](https://github.com/dotnet/runtime/issues/124535)

**Comment by lambdageek** [comment]
The entrypoint would be

```c
STDAPI CLRDataCreateInstance(REFIID iid, ICLRDataTarget* target, void** iface);
```

Where iid will be one of the ISOSDacInterfaceNN interfaces

The cdac as currently imagined needs two things to get going: 
1. A way to read from the target address space
2. The address of the contract descriptor which is a symbol with the name `DotNetRuntimeContractDescriptor`

We can get the former using `ICLRDataTarget::ReadVirtual` and the latter using something like this:
 
```cxx
interface ICLRDataTarget4 : ICLRDataTarget3
{
   HRESULT TryGetSymbol([in] LPCSTR symbolName, [out] CLRDATA_ADDRESS* address);
}
```

**Comment by noahfalk** [comment]
I assume when SOS is targetting downlevel runtimes it would still load an older brittle DAC?

**Comment by lambdageek** [comment]
> I assume when SOS is targetting downlevel runtimes it would still load an older brittle DAC?

I think there's two separate answers:
1. In the long term, SOS should have some kind of a policy. For example: try the cdac and if it returns E_NOTIMPL or some other error code, try a brittle DAC.  (I'm not sure what a reasonable policy might be)
2. For the purposes of trying things out, @mikem8361  and I were talking about having some gesture (ie: you have to run some SOS command) to opt into the cdac.

**Comment by mikem8361** [comment]
> We can get the former using `ICLRDataTarget::ReadVirtual` and the latter using something like this:
> 
> interface ICLRDataTarget4 : ICLRDataTarget3
> {
>    HRESULT TryGetSymbol([in] LPCSTR symbolName, [out] CLRDATA_ADDRESS* address);
> }

Now I'm thinking this should be more like ICLRRuntimeLocator and not inherit with only TryGetSymbol on it.  It would allow a more minimal data target impl for cases that are only going to use the cDAC (like in testing, etc.). SOS will have to implement all the interfaces it does now and it would be easy to add this one more.  We can call it something like ICLRRuntimeSymbol.

**Comment by jkoritzinsky** [comment]
What about for diagnostic experiences that currently depend on contracts not defined by `ISOSDacInterfaceX` interfaces? In particular, there are a few that depend on the "SOS Breaking Change Version".

Some of these APIs are relatively easily representable in cDAC contracts with a managed API but projecting them through an unmanaged interface could be expensive. Is there some way we could come up with a solution that wouldn't require going through an unmanaged API?

**Comment by lambdageek** [comment]
> What about for diagnostic experiences that currently depend on contracts not defined by `ISOSDacInterfaceX` interfaces? In particular, there are a few that depend on the "SOS Breaking Change Version".
> 
> Some of these APIs are relatively easily representable in cDAC contracts with a managed API but projecting them through an unmanaged interface could be expensive. Is there some way we could come up with a solution that wouldn't require going through an unmanaged API?

I think mscorcdac and Microsoft.Diagnostics.DataContractReader are separate products (that happen to be built from substantially similar sources).  We could have a separate plan for how we ship the managed library.

**Comment by AaronRobinsonMSFT** [comment]
> mscorcdac.dll

This name is a bit suspect. We've removed "ms" from many places - `mscorlib` being the most obvious example. Another issue with this name is that it is far too similar to existing names. That "c" in the middle is doing a lot to lifting to handle the disambiguation when quickly reading names. I would suggest something like spelling out the "dac" or even just dropping the "ms" - `cordac` or perhaps `diagnostic.access.control`?

**Comment by mikem8361** [comment]
I'm not hung up on the name.  I suggested something similar to the existing DAC name, but not for any good reason. I guess I assumed that "ms" was supposed to be in the name.

**Comment by noahfalk** [comment]
> diagnostic.access.control

The original acronym DAC stands for "Data Access Component". Its a pretty generic name :) I'd avoid "access control" as that term is strong connotations of security authentication and authorization. Any of these names sounded fine to me:
cdac.dll, cordac.dll, contractdac.dll

**Comment by am11** [comment]
@steveisok, @jkoritzinsky, can we now include mscorcdac to shared framework and resolve this TODO: https://github.com/dotnet/runtime/blob/e8812e7419db9137f20b990786a53ed71e27e11e/src/libraries/externals.csproj#L91-L94 To enable cdac, it still requires setting `DOTNET_ENABLE_CDAC`, so it should be safe while the remaining APIs required by SOS are being implemented?

**Comment by jkotas** [comment]
I do not think we want to be shipping duplicate DAC binaries in the shared framework just so we can resolve a TODO.

**Comment by am11** [comment]
I meant for .NET 11, is it still too early?

**Comment by jkotas** [comment]
We haven’t finalized a plan yet for if or how cDAC will ship in .NET 11.
