### ISSUE TITLE
Intel architecture improvements for .NET 10

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#108869]
This issue describes planned improvements to Intel architecture (x86, x64) ISA support for .NET 10.

The primary addition will be APX support, which is expected to be available in .NET 10 but considered "Experimental", and possibly requiring explicit opt-in via some kind of configuration option, pending available hardware, testing, and completion status.

For reference, here is the corresponding .NET 9 issue for Intel architecture improvements: https://github.com/dotnet/runtime/issues/93196

## APX

APX is a new ISA extension (see [here](https://www.intel.com/content/www/us/en/developer/articles/technical/advanced-performance-extensions-apx.html) for a summary and links to specifications). Notably, it doubles the number of general-purpose registers from 16 to 32, as well as adding new encodings and instructions.

There is an "apx" label that should be added to any APX related GitHub issue. Here is a query showing all such issues: https://github.com/dotnet/runtime/labels/apx.

Work items:
- [ ] Enable CPUID detection and XSAVE features. PR: https://github.com/dotnet/runtime/pull/104637.
- [ ] Upgrade LSRA to allow EGPRs when APX is available. PR: https://github.com/dotnet/runtime/pull/108799.
- [ ] Enable REX2 encoding to use EGPRs. PR: https://github.com/dotnet/runtime/pull/106557.
- [ ] Enable VEX/EVEX encoding to use EGPRs [Planned Q4'24]
- [ ] Enable EVEX encoding promotion for legacy instructions. PR: https://github.com/dotnet/runtime/pull/108796.
- [ ] Enable EVEX NS form encoding promotion for legacy instructions. [Planned Q4'24]
- [ ] Optimize register allocator for with PUSH2/POP2.
- [ ] Optimize register allocator for EGPR performance/cost tradeoff.
- [ ] Tune generalized NDD form optimization (through promoted EVEX).
- [ ] Add new conditional instructions (CCMP, CFCMOV, etc.) [Planned Q4'24]
- [ ] Implement if-conversion optimizations (utilize existing peephole and ARM lowering) [Planned Q4'24]
- [ ] Diagnostics support. For reference, here is a PR that added AVX-512 breakpoints support: https://github.com/dotnet/runtime/pull/89705.
- [ ] GC info support for new registers.
		
## .NET 9 carryover work

The following work was specified for .NET 9 but pushed to the future.

**This work should be analyzed to determine if it should be added to .NET 10, left to future, or deleted**

### Libraries work

- [ ] Light up IndexOfAnyAsciiSearcher for AVX512. https://github.com/dotnet/runtime/issues/93222 (@MihaZupan) 
- [ ] Consider SIMD JSON acceleration **(Owner: Intel)**
- [ ] Consider XML API acceleration **(Owner: Intel)**
- [ ] (**Help Wanted**) Light up Utf8/Utf16 code with Vector512. https://github.com/dotnet/runtime/issues/86119
- [ ] (**Help Wanted**) Light up Ascii.Utility methods with Vector512 code paths. https://github.com/dotnet/runtime/issues/89280
  - https://github.com/dotnet/runtime/pull/99982
  - https://github.com/dotnet/runtime/pull/88532 
  - https://github.com/dotnet/runtime/pull/89892

### AVX10

- [ ] Allow embedded rounding for YMM/ZMM (related: https://github.com/dotnet/runtime/issues/93154) (**Owner: Intel**, Starting AVX10.2)
- [ ]  (**Help Wanted**) Convert remaining AVX2 implementations to Vector256 https://github.com/dotnet/runtime/issues/101251

### RyuJIT feature work

- [ ] `Vector512.Dot`: AVX-512 specific light-up for `Vector512.Dot` https://github.com/dotnet/runtime/issues/85207

## `Vector<T>`

- [ ] Consider `Vector<T>` expanding to `Vector512<T>`, either automatically or opt-in. (@tannergooding plans to get back to it as a best effort.)

## JCC erratum

- [ ] https://github.com/dotnet/runtime/issues/93243 (@TIHan)

### Debugging / diagnostics work (@BruceForstall)

- [ ] https://github.com/dotnet/runtime/issues/87854 (and related work for APX)
- [ ] Ensure ELT (enter/leave/tailcall hooks, for profiling) works.

**Comment by JulieLeeMSFT** [comment]
Changed the assignee for the JCC erratum to TBD. 
https://github.com/dotnet/runtime/issues/93243

**Comment by JulieLeeMSFT** [comment]
Closing this user story as all .NET10 work items are completed. Thanks all for the contributions.
