### ISSUE TITLE
Improve JIT loop optimizations (.NET 10)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#108901]
We plan to continue improving JIT optimization capabilities for loop code. An overview of many JIT optimization possibilities is [here](https://github.com/dotnet/runtime/issues/65342); this issue will focus on issues we choose to address in .NET 10.

Significant work was done in .NET 9; the list of work here for .NET 10 is much more modest.

The corresponding .NET 9 issue is https://github.com/dotnet/runtime/issues/93144.

# Planned for .NET 10

## Update loop inversion implementation
The current loop inversion algorithm is lexical. Convert it to be graph based. This is part of the JIT flowgraph modernization push, and is tracked by https://github.com/dotnet/runtime/issues/107749.

## Loop cloning
- [x] https://github.com/dotnet/runtime/issues/82946 Support loop cloning for Span
- [ ] https://github.com/dotnet/runtime/issues/77071 Support loop cloning of class member arrays
- [ ] https://github.com/dotnet/runtime/issues/85552 Support loop cloning with non-int iteration variables

## Multi-dimensional array improvements
- [ ] https://github.com/dotnet/runtime/issues/71674 RyuJIT: support cloning loop nests with multi-dimensional array accesses
- [ ] https://github.com/dotnet/runtime/issues/71676 Improve hoisting, CSE, LSRA for MD array accesses

## Induction variable optimizations
- [X] Support IV opts on CSE'd values (https://github.com/dotnet/runtime/pull/106637)

## Loop peeling
- [ ] (Stretch) https://github.com/dotnet/runtime/issues/93142 Implement loop peeling

**Comment by JulieLeeMSFT** [comment]
We will revisit loop optimizations in future releases.
