### ISSUE TITLE
CodeGen infrastructure work (.NET 10)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#108904]
This issue collects a set of desired CLR CodeGen (JIT) inner-loop infrastructure improvements.

We do not have any concrete plans to work on any of these for .NET 10 due to competing priorities. So, this list of work items should be viewed more as desired and opportunistic, rather than committed work.

# Work items

## SuperPMI-related features

- [ ] superpmi: automated TechEmpower collection https://github.com/dotnet/runtime/issues/47545
- [ ] SuperPMI: Investigate MISSING data for Linux/arm collection https://github.com/dotnet/runtime/issues/80162
- [ ] SPMI collections need to use release System.Private.Corelib https://github.com/dotnet/runtime/issues/60947
- [ ] Investigate including the SPMI collector as part of the core runtime https://github.com/dotnet/runtime/issues/85537
- [ ] SuperPMI: add JIT memory diff measurements in per-PR pipeline runs https://github.com/dotnet/runtime/issues/95767
- [ ] Enable post back of JIT test pipeline results to triggering GitHub PR https://github.com/dotnet/runtime/issues/93138
- [ ] SPMI: Give specific context examples for tpdiff https://github.com/dotnet/runtime/issues/85755
- [ ] SPMI: Enable replay filter by attribute or metric https://github.com/dotnet/runtime/issues/93140
- [ ] Add a SPMI collection for pre-AVX512 hardware https://github.com/dotnet/runtime/issues/87145

# Related

.NET 7 work was tracked with https://github.com/dotnet/runtime/issues/64832.
.NET 8 work was tracked with https://github.com/dotnet/runtime/issues/79018.
.NET 9 work was tracked with https://github.com/dotnet/runtime/issues/93141

**Comment by AndyAyersMS** [comment]
There aren't any product deliverables here, so I am going to close this; we'll pick this up again for .NET 11 over in [#118498](https://github.com/dotnet/runtime/issues/118498)
