### ISSUE TITLE
JIT Focus Area for .NET 10

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#108988]
# Focus Area

As we look forward to the advancements in .NET 10, there are several key areas of focus that will drive development and improvements within JIT. These priorities aim to enhance performance and overall efficiency, ensuring that JIT continues to meet the evolving needs of developers and the performance demands of various workloads. Here are some of the primary focus areas for JIT in .NET 10:

- Advaced architectural features
- De-Abstraction
- Foundational Optimizations

## Advanced Architecture
- [x] Intel APX https://github.com/dotnet/runtime/issues/108869
- [x] https://github.com/dotnet/runtime/issues/109652 

## De-Abstraction
- [x] https://github.com/dotnet/runtime/issues/108913
- Array Enumeration De-Abstraction
- Stack Allocation Improvements
- Delegate GDV Improvements
- PGO Improvements
- Inlining improvements with functions with exception handling (EH)

## JIT Foundational Optimizations
- [x] Flow Graph https://github.com/dotnet/runtime/issues/107749
- [x] PGO profile consistency and repair https://github.com/dotnet/runtime/issues/107749

## Opportunistic items
- [x] Struct improvements on physical promotion https://github.com/dotnet/runtime/issues/109635
- [x] Loop optimizations https://github.com/dotnet/runtime/issues/108901
- [x] CodeGen Infrastructure work https://github.com/dotnet/runtime/issues/108904

# Moved to Future 
## JIT Foundational Optimizations
- [ ] Inter-Procedural Analysis Framework (IPA) https://github.com/dotnet/runtime/issues/108931

## Opportunistic items
- [ ] [Experiment] RyuJIT as IL Scanner for ILC https://github.com/dotnet/runtime/issues/83021
- [ ] ABI Clean-up
- [ ] JitOptRepeat https://github.com/dotnet/runtime/issues/108902
- [ ] LSRA improvements
