### ISSUE TITLE
.NET 10 Telemetry Work Tracking

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#109396]
- [ ]  https://github.com/dotnet/runtime/issues/109388
- [ ]  https://github.com/dotnet/runtime/issues/102924
- [ ]  https://github.com/dotnet/runtime/issues/103245

**Comment by julealgon** [comment]
@tarekgh at this point, I'm assuming it is safe to say that 
- https://github.com/dotnet/runtime/issues/100317

will not make it into .NET10 timeframe?

Do you think it could come as an incremental upgrade next year, or will it only be considered again for the .NET 11 release?

**Comment by tarekgh** [comment]
@julealgon This is already listed as future consideration, so it is not part of .NET 10. 

> Do you think it could come as an incremental upgrade next year, or will it only be considered again for the .NET 11 release?

We cannot introduce any new APIs in the servicing phase, so if we decide to consider this, it won't be until .NET 11 at the earliest.

**Comment by julealgon** [comment]
@tarekgh 
> We cannot introduce any new APIs in the servicing phase

Oh, I didn't know this was the case for `Microsoft.Extensions.*` libraries as well. Bummer... 

Thanks for the update.
