### ISSUE TITLE
Improve/cleanup RyuJIT's IR handling of operand lists

### ISSUE THREAD

**Issue by mikedn** [dotnet/runtime#11058]
Some IR nodes require a variable number of operands and the current implementation uses linked lists of `GT_LIST` (or similar) nodes.

IR nodes knows to use such lists:
* `GT_CALL` - has a dedicated `this` argument operand and a list of operands for all other arguments
* `GT_PHI` - this is a `GTK_UNOP` node and its sole operand is a list
* `GT_HWINTRINSIC` - this is a `GTK_BINOP` node but if needs 3 operands or more the first operand is a list and the second is null
* `GT_FIELD_LIST` - a `GTK_BINOP` that acts both like an actual IR node or like a list node
* Anything else?

From the above only `GT_CALL` is reasonable, though it could probably be improved as well. The rest suffer from various issues:
* `GT_PHI` - this looks similar to `GT_CALL` on the surface but it lacks the special handling of calls throughout the JIT. Its list nodes end up in the linear order and they are visited by tree walking facilities like `GenTreeVisitor`. This is nonsense - these list nodes are an internal implementation detail of the `GT_PHI` node and they should not appear anywhere. They have no type, no VN, no nothing. They simply do not exists as far as the IR is concerned.
* `GT_HWINTRINSIC` suffers from the same problem as `GT_PHI`. It just makes it worse by sometimes using lists and sometimes not. And unlike `GT_PHI`, this lacks special handling in `gtDispTree` and dumps its list nodes.
* `GT_FIELD_LIST` IMO it would be better have a `GT_PACK` node with a list of `GT_FIELD_LIST` nodes.

- [x] Stop using `GT_LIST` in `GT_PHI` (#20266)
- [x] Stop using `GT_LIST` in `GT_CALL` (#26392)
- [x] Stop using `GT_LIST` in `GT_FIELD_LIST` (#26800)
- [ ] Stop using `GT_LIST` in `GT_SIMD` (https://github.com/dotnet/runtime/pull/1141)
- [ ] Stop using `GT_LIST` in `GT_HWINTRINSIC`
- [ ] Remove all the remaining `GT_LIST` code

category:implementation
theme:ir
skill-level:expert
cost:extra-large

**Comment by SingleAccretion** [comment]
I would like to finish this work, by deleting `GT_LIST` and using a array of operands for `GT_SIMD` and `GT_HWINTRINSIC`. The benefits have been enumerated in this issue already, but to summarize:

1) No special cases in IR of nodes that are not actual nodes, no two interpretations of a "use edge" (this, for example, allows to trivially fold `GenTree::TryGetUse` and `GenTree::gtGetChildPointer` into one function).
2) Much more efficient representation in terms of memory usage memory.
3) More efficient operand access.
4) As it turns out, cleaner and more streamlined code.
5) Some other more miscellaneous things like easy VN support for 3+ operand cases.

I propose the following design:
```c++
struct GenTreeMultiOp : GenTree
{
    uint8_t m_operandCount; // We have 3 spare bytes in the base GenTree, we'll use 1 to store the count.
}

struct GenTreeMultiOp : GenTree
{
    GenTree** m_operands;
}

struct GenTreeJitIntrinsic : GenTreeMultiOp
{
    GenTree* inlineOperands[2];
    // The rest of the data members fit into 8 bytes, making this a small node.
}
```
The `m_operands` array will either point to `inlineOperands` (when we are constructing a node with <= 2 operands), or a dynamically allocated array when we need more than two. This allows for the accessor function to be simply `m_operands[operandIndex]`, without the checks for the operand count. The downside is that the 3 operand case now needs a dynamic allocation, but I have [measured](https://gist.github.com/SingleAccretion/f83892a07748b0f214556799dccc5c5d) how many nodes will need 3+ operands and came to the conclusion that the faster accessor is a better tradeoff in this case.

I have also made the amount of inline operands configurable (that is why they live in a derived class and not in `GenTreeMultiOp` itself), so that it can be reused for nodes with a different requirement on the size of the inline array (for example, it would be interesting to see if we can use `GenTreeMultiOp` for `GT_PHI`, which could have up to 3 inline operands). It is possible/probable that is not needed, but it is also easy to change.

You can see the fully functional set of changes that will be required to implement this design [here](https://github.com/SingleAccretion/runtime/tree/Make-Intrinsic-Nodes-Multi-Op). It comes with a ~0.25% reduction in the number of retired instructions when replaying the x64 benchmarks collection, which is a nice bonus.

cc @dotnet/jit-contrib, @tannergooding

**Comment by tannergooding** [comment]
My own view here is that while this might be a general improvement, its not clear that its the right first step and doesn't look to take `GT_CALL` into account which is another common case for more than 2 operands.

In particular, I think part of the problem is that there are multiple ways to access and enumerate the operand nodes. That is, you can access the fields directly as `gtOp1`/`gtOp2`, you can use the helper functions `gtGetOp1()`/`gtGetOp2()`, you can enumerate them as part of the general "children" for a node, etc. How we do this throughout the JIT isn't consistent and that causes all the real problems. IIRC, last time we measured the throughput impact of GT_LIST was minimal compared to the more expensive parts of the JIT and so it wasn't worth focusing on immediately (the same was true of the hwintrinsic name recognition, where not having an optimized binary search barely showed up on the metrics).

Likewise, while we have `GenTreeUnOp` and `GenTreeOp`, these concepts are somewhat a lie and don't actually represent 1 or 2 operand cases. Instead, we have various special rules about when its `0`, `1`, `2`, or more operands and you somewhat need to "know" the expected way to check/handle everything. Instead, these two node kinds are largely used to separate some flags and general handling for when the node likely has 1 or 2 operands.

So I think that the right "first step" is to clean this dependence on "internals" up. That is, it shouldn't matter how we internally represent 0/1/2/3+ operands, this should be completely hidden to the general consumer. We should:
* explicitly have `gtOp1`/`gtOp2` be private fields
* expose some `OperandCount` property that indicates the number of operands tracked by the node
  * my thought is that this is "inputs" to the operation represented, so its everything other phases (like `valuenum`) need to correctly handle the node
* expose a way to get the operands by index and enumerate through them in order
  * I think its fine for there to still be named helpers for common cases like `Op1`/`Op2` or for say `Base`/`Index` on array accesses, etc

Once we have this and everything is going through these APIs for accessing and dealing with operands, then we no longer have any concern about how its implemented internally. We are free to have inline operands or linked lists or dynamically allocated arrays and to freely swap it around without worrying about `n` places in the JIT getting broken. Likewise, we can actually centralize handling for things like "this has 2 operands, is it commutative" or other "general" checks that are currently guessed at based on being `GenTreeOp` and which of the operands are `null` or their kind if not.

**Comment by SingleAccretion** [comment]
> So I think that the right "first step" is to clean this dependence on "internals" up. That is, it shouldn't matter how we internally represent 0/1/2/3+ operands, this should be completely hidden to the general consumer.

> Once we have this and everything is going through these APIs for accessing and dealing with operands, then we no longer have any concern about how its implemented internally. We are free to have inline operands or linked lists or dynamically allocated arrays and to freely swap it around without worrying about n places in the JIT getting broken.

I have been thinking about this for the past few days, and here's what what I came to.

First, what we cannot change:
1) We have to use specialized functions for getting the operands of any particular "class", because it requires knowledge of the node's layout (trivially, you cannot `gtGetOp1()` of a `GT_CALL` because it does not store the first operands the way a `GenTreeUnOp` does it, and switching on the oper is not a solution as it is unnecessarily inefficient, since in the vast majority of cases we know the type of the node in question).
2) We cannot make all opers use the same node layout for storing operands because, well, different opers have different needs (put another way, different `Use` classes). The `GenTreeOp` layout is "ideal" for the most common case of a binary/unary oper, the linked lists (with large `Use`s perhaps recording the argument info) are appropriate for calls, `GT_FIELD_LIST`'s `Use` needs a field type, a `PHI`s `Use` can be a simple `GenTree*` (if stored in an array, which may not necessarily be the most efficient representation when we consider the need to update `PHI`s). When speaking about iterating the operands, you need a `case` for each type of `Use` that is in an array (currently all those `Use`s are simple `GenTree*`s) and one more general case for a linked list (and, today, a special case for `GT_CALL` because it uses a mix of both approaches).

Given the above, I simply do not see a way to "fully" unify the operands iteration without TP impact (trivially, getting the `i`th operand of a linked list requires a linear traversal).

Aside from that, `GenTreeMultiOp` would only help us here, as it removes one special case - a non-`Use`-based linked list - and can be iterated the same way a "pure" inline array can (well, not truly, because `GTF_REVERSE_OPS` exists, but let's say for opers that do not use it...). For example, it allows to rewrite `GenTreeUseEdgeIterator` in a way that unifies `GenTreeMultiOp` and all the `TriOp/QuadOp` opers we have (`GT_ARR_OFFSET`/`GT_CMPXCHG` and some others). Whether that's worth it or not is not abundantly clear to me yet, considering the potential TP impact (not in a "real" sense because these opers are very rare, but in an abstract "are we doing the most efficient thing here" one (note that I say that not because I like premature optimization, but because we cannot have undue regressions in code that already works)), but it is something that will be made possible by the proposed changes.

> doesn't look to take GT_CALL into account which is another common case for more than 2 operands.

I note that I explicitly did not take calls into account because I do not think it is fruitful at this time to try and make them use arrays (for the reasons mentioned above). Calls have very different requirements to "primitive" operations like the intrinsics represent (which is to say they need "fat" `Use`s).

**Comment by tannergooding** [comment]
> and switching on the oper is not a solution as it is unnecessarily inefficient

I think this is worth validating. Ideally for all our scenarios the C++ methods are appropriately marked `const` and are inlineable in a fashion that this isn't a concern for the release binaries.

That is, having a `GenTree` level method that switches on the oper kind shouldn't really be an issue, we do this in tons of places already and solving the more general issue of ensuring correctness should be the bigger concern IMO.

Even `gtGetOp2` is part of `GenTree` today and it simply asserts the oper kind and does `AsOp()->gtOp2`. I don't see anything that would really prevent this or that would prevent the compiler from inlining the check for `UnOp vs BinOp vs MultiOp` (nor even for the "general" check to be slightly more expensive but having an identically named method on the proper tree kinds that's more efficient).

> We cannot make all opers use the same node layout for storing operands because, well, different opers have different needs (put another way, different Use classes).

Yes, but today these details on how its stored leak at every level and that's the main problem that I've seen. Because everything is exposed differently based on the node kind, you have to remember anytime you deal with operands that `GenTreeX` does it this way and `GenTreeY` does it this other way and that if `GenTreeY.SomeOtherField == ...` you need to also check for `Z`. Its just not tenable and causes a number of downstream complexities.

---

My main concern here is that `GT_LIST` itself, while not ideal, isn't that expensive compared to everything else the JIT does. So while its likely goodness, I'm worried its going to make solving the larger problem that we have with `GenTreeUnOp`, `GenTreeOp`, `GenTreeJitIntrinsic`, and `GenTreeCall` more difficult to handle or at the very least not address it at all.

**Comment by SingleAccretion** [comment]
With #59912 merged, this work has now been completed 🎉!

Remaining simplifications enabled by this change are tracked in source via `TODO-List-Cleanup`.
