### ISSUE TITLE
JIT: Physical promotion enhancements

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#110642]
This issue captures a list of potential enhancements to physical promotion, in no particular order.

**CQ**
* [ ] Decomposition via arithmetic
* [ ] Share backing storage when promoted locals are stack spilled
* [ ] Allow small-typed mismatches
* [ ] Support some bitcasts
* [ ] Partial lifetime promotion
* [ ] Allow promoted struct returns to stay in registers
* [ ] Custom class layouts with GC pointers (for some efficient decomposed copies) (#103362)
* [ ] Readback/writeback resolution
* [ ] Full support for `GetElemet`/`WithElement` for SIMDs (potentially as a separate pass)
* [ ] Assignment decomposition for `GetElement`/`WithElement` (https://github.com/dotnet/runtime/issues/87554)
* [ ] Field support for `LCL_ADDR` propagation (https://github.com/dotnet/runtime/issues/69254)

**Throughput**
* [ ] Stop tracking accesses early when we know we won't promote

**Related issues**
* [ ] https://github.com/dotnet/runtime/issues/69254

**Comment by jakobbotsch** [comment]
A case from @hez2010 where we don't get good codegen on SysV today because some struct fields do not map cleanly to parameter registers:
```csharp
public class Program
{
    public static void Main()
    {
        GetDistance<float>(default, default);
    }

    record struct Point<T>(T X, T Y) where T : INumberBase<T>, IRootFunctions<T>;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static T GetDistance<T>(Point<T> p1, Point<T> p2) where T : INumber<T>, IRootFunctions<T>
    {
        T dx = p1.X - p2.X;
        T dy = p1.Y - p2.Y;
        return T.Sqrt(dx * dx + dy * dy);
    }
}

```
