### ISSUE TITLE
Testing new EventCounter APIs

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#12252]
These (internal) APIs are added with https://github.com/dotnet/coreclr/pull/23077. The intent is that these APIs will go public for 3.0 timeframe.

This issue tracks adding tests that cover the following behavior of these APIs. 

EventCounter
- [x] New property - DisplayName
- [x] Payload correctness

PollingCounter
- [x] Basic constructor with a callback function. 
- [x] Payload correctness
- [x] Error handling

IncrementingPollingCounter
- [x] Basic constructor with a callback function. 
- [x] DisplayRateTimeScale property
- [x] Payload correctness
- [x] Error handling

IncrementingEventCounter
- [x] DisplayRateTimeScale property
- [x] Payload correctness
- [x] Error handling

**Comment by sywhang** [comment]
closing as done
