### ISSUE TITLE
A follow up to "Create the Concept of Multiple EventPipe Sessions #24417"

### ISSUE THREAD

**Issue by jorive** [dotnet/runtime#12746]
##### Correctness

- [x] Review if it is safe to call `EventPipe::Disable` on `EventPipe::Shutdown` (`EventPipe::Disable` removes the session from the container we are iterating on `EventPipe::Shutdown`)
- [x] `EventPipe::Shutdown` can be called concurrently from multiple threads, then EventPipe::s_pSessions could change from not-null to null, which could trigger an AV.
- [ ] Review why `EventPipe::WriteEvent` seems to be called after `EventPipe::Shutdown`
- [x] Need to make thread safe iterating over the `EventPipe::s_pSessions` under `EventPipe::WriteEventInternal`
- [x] Revert back EventPipeSessionID to be address of the pointer instead of the bit mask: https://github.com/dotnet/coreclr/pull/24417#discussion_r286384780.  Now tracked on dotnet/coreclr#25229

##### Contracts (Checked/Debug)

- [ ] Review EventPipe debug CONTRACTS: GC TRIGGER/NO TRIGGER, THROWS/NOTHROW, MODE PREEMTIVE/COOP/ANY, and made them more restrictive.
- [ ] Add appropriate contracts to `EventPipeThread::SetBufferList` and `EventPipeThread::SetWriteBuffer`. Currently there is a TRY/CATCH/IGNORE in those two methods because they are called from a method with a NOTHROW contract. Should we add STRESS_LOG to the catch block? What's appropriate?

##### Cleanup sessions

- [x] Add a mechanism that can notify EventPipe when there is an error on an active session, so it can be disposed properly from the list of active sessions.  Moved to dotnet/coreclr#25228.

##### Improvements

- [x] When calling `EventPipeConfiguration::Disable` we need to do a better job on reseting all keywords and levels for the remaining active sessions.
Track active listening sessions on `EventPipeEvent` (using a 64-bit mask). Currently, providers track listening session by using a 64-bit bitmask. We should track at the event level instead, so sessions will listen to the events they requested.  Now tracked on dotnet/coreclr#25232
- [ ] Break the lock when doing `EventPipe::Disable`, otherwise disabling a session will be able to block all other sessions from doing work for a long time.  Now tracked on dotnet/coreclr#25515.

#### Future

- [x] `EventPipe::Shutdown` seems to be called more than once
- [ ] Provider Keywords' are of type INT64 and UINT64. We should make them all UINT64.
- [ ] Improve the `PlatformSleep` used on the `EventPipeSession::ThreadProc` method. It is a naïve sleep that could be changed to a sleep the "remaining time", so that events are written to the IPC in a timely manner.
- [ ] Review why "catch all" providers set NULL as provider name, when user needs to specify `"*"`
- [ ] Add better error handling to SampleProfiler: on `SampleProfiler::Enable` the call to `LoadDependencies()` could fail and there is no error checking.
- [x] Allow user input to set the `rundownEnabled` parameter for a session.
- [ ] Consider adding a COMPLUS_* variable to control the SampleProfiler sampling rate (currently hardcoded). This would be for testing.
- [ ] On `EventPipe::DisableInternal` we send process info globally (to all active sessions). Maybe we could only send it to the session that it's been disabled (only once)?
