### ISSUE TITLE
Enable and fix/baseline worthwhile FXCop rules on CoreFX codebase

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#19511]
dotnet/coreclr#7880 covers this for mscorlib.

@alexperovich will drive this.

Suggested workflow
* Put checkboxes in this issue for all valuable rules (not any that are too noisy/not valuable)
* In one commit, enable a rule, fix any easy violations and baseline the rest. This prevents us going backwards.
* Open separate issue for someone to clear out the baseline for the rule/s.

Compiler Warning:

- [x] CS0162: Unreachable code detected
- [x] CS0429: Unreachable expression code detected
- [x] CS????: Remove unused locals

Assembly: System.Runtime.Analyzers
- [x] CA2002: Do not lock on objects with weak identity

Assembly: Microsoft.Maintainability.Analyzers

- [ ] CA1801: Review unused parameters
- [ ] CA1806: Do not ignore method results
- [ ] CA1812: Avoid uninstantiated internal classes
- [ ] CA1823: Avoid unused private fields

Assembly: Microsoft.QualityGuidelines.Analyzers

- [ ] CA1821: Remove empty finalizers

Not yet implemented analyzers:

- [ ] CA1811: Avoid uncalled private code dotnet/roslyn-analyzers#464

**Comment by joperezr** [comment]
I believe this was recently done by @stephentoub so closing for now.

**Comment by stephentoub** [comment]
Yup.  We might want to enable additional ones in time, but we've enabled all the important ones that currently exist, and we don't need an issue tracking enabling more.
