### ISSUE TITLE
Remove versioned defines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#20179]
We should migrate to versionless platform defines. @joperezr @weshaggard can we do this now if not what has to come first? I see you already renamed all the C# file suffixes to be versionless.

- [x]  #if netcoreapp11 -->  #if netcoreapp
- [ ]  #if netstandard17, #if netstandard10 --> #if netstandard
- [x] #if netcore50 --> #if uap
- [x] #if netcore50aot --> #if uapaot

incidentally
#if NET46 -> don't change

- [x] # if NET_4_5 -> dead

Perhaps you already have something tracking this kind of thing.

**Comment by jkotas** [comment]
The defines are in sync with the SDK ones now.
