### ISSUE TITLE
Enabling Android ARM64 for .NET Core

### ISSUE THREAD

**Issue by cydhaselton** [dotnet/runtime#2044]
This issue will be a list of tasks necessary to enable Android ARM64 for .NET Core, in the style of [Enabling Linux ARM32 for .NET Core](https://github.com/dotnet/core-setup/issues/725).  Please assign the `arm64`, `os-android` and `os-unsupported` labels, if appropriate.

**References**
- [Android: Next Steps](https://github.com/dotnet/coreclr/issues/9946#issuecomment-284232191)

## Common

- [ ] Refactor/merge build-android-rootfs.sh for core-setup if necessary. Use updated build-android-rootfs.sh for arm64 and arm (PR dotnet/corefx#16819)
- [ ] Add necessary files and directories to support android cross-build
- [ ] Fix build-android-rootfs.sh so that it pulls latest package version.

## CoreCLR

- [x] Update CoreCLR to generate Android-specific (?) nuget packages of CoreCLR (ref: dotnet/coreclr#8421, PR dotnet/coreclr#10286)

## CoreFX

- [x] Add RID for Android (PR dotnet/corefx#16729)
- [ ] Update CoreFX to generate Android-specific (?) nuget packages of CoreFX

## core-setup
- [ ] Add support for Android arm, arm64 RIDs (ref dotnet/core-setup#254)
- [ ] Add support for Android arm64 build from sources

## Porting To New Platform References
- dotnet/coreclr#917 (specifically [this comment](https://github.com/dotnet/coreclr/issues/917#issuecomment-229827373))
- dotnet/corefx#6770
- dotnet/corefx#15503
- dotnet/coreclr#6056
- dotnet/core-setup#254

cc\ @qmfrederik

**Comment by thebestnom** [comment]
It looks like a lot of it is done, can someone update this?

**Comment by nxrighthere** [comment]
I would like to see an update for this issue, please?

**Comment by ViktorHofer** [comment]
@marek-safar @steveisok can you please update this issue based on the work that your team has done in the last months?

**Comment by marek-safar** [comment]
I think we can close this issue as most of the infrastructure tasks have been completed. The plan is for .NET6 to officially support Android but the foundational pieces are all already in and we do run on Android dotnet/runtime PR changes today.

**Comment by qmfrederik** [comment]
@marek-safar Just to be sure, does this include support for running .NET console apps (e.g. via `adb shell` or Termux) on Android?

**Comment by marek-safar** [comment]
This issue does not cover .NET SDK or CLI integration and that part is planned for .NET6.

**Comment by qmfrederik** [comment]
This issue was opened (at the time) with Android CLI integration in mind.

That scenario worked at one point in time. You could `dotnet publish` a Hello World console app which targeted `android-arm64` and run it via `adb shell`. 

If the issue has been recycled to track something else, it may be worth to mention that in a comment or the description.

**Comment by marek-safar** [comment]
What I meant by CLI integration is smoother dev experience when targeting Android. You can do `dotnet publish` and manual `adb shell` today but that's not where we would like to land.

**Comment by marek-safar** [comment]
This will be addressed as part of #44654
