### ISSUE TITLE
Clean up dead code

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#20888]
After enabling the mono linker for our .NETCoreApp binaries it has identified a number of places where we have dead code.

These fall into 3 categories.
1. Truly dead code that isn't used anywhere in the assembly.
    - This can be deleted
2. Source files that are used in one build of the assembly, but not all.  Common source files where some project uses the source, but not all.
    - These can be better factored, split up to provide minimal source where needed. Or, they may contain truly dead code.
3. Compile time only source.  Internal constants that are represented as literals in calling IL and not exposed publicly.
    - These must remain.

### diffs
- [ ] [Microsoft.CSharp](http://tempcoverage.blob.core.windows.net/report2/Microsoft.CSharp.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/Microsoft.CSharp.diff.csv))
- [ ] [Microsoft.VisualBasic](http://tempcoverage.blob.core.windows.net/report2/Microsoft.VisualBasic.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/Microsoft.VisualBasic.diff.csv))
- [x] [System.Collections.Concurrent](http://tempcoverage.blob.core.windows.net/report2/System.Collections.Concurrent.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Collections.Concurrent.diff.csv))
- [x] [System.Collections](http://tempcoverage.blob.core.windows.net/report2/System.Collections.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Collections.diff.csv)) - PR dotnet/corefx#19140 by @YoupHulsebos
- [x] [System.Collections.Immutable](http://tempcoverage.blob.core.windows.net/report2/System.Collections.Immutable.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Collections.Immutable.diff.csv)) - Nothing to remove by @YoupHulsebos in https://github.com/dotnet/corefx/issues/17905#issuecomment-298154133
- [x] [System.Collections.NonGeneric](http://tempcoverage.blob.core.windows.net/report2/System.Collections.NonGeneric.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Collections.NonGeneric.diff.csv)) - Nothing to remove by @YoupHulsebos in https://github.com/dotnet/corefx/issues/17905#issuecomment-298154133
- [x] [System.Collections.Specialized](http://tempcoverage.blob.core.windows.net/report2/System.Collections.Specialized.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Collections.Specialized.diff.csv))
- [x] [System.ComponentModel.Annotations](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.Annotations.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.Annotations.diff.csv)) @norek
- [x] [System.ComponentModel](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.diff.csv))@norek
- [x] [System.ComponentModel.EventBasedAsync](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.EventBasedAsync.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.EventBasedAsync.diff.csv))@norek
- [x] [System.ComponentModel.Primitives](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.Primitives.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.Primitives.diff.csv))@norek
- [x] [System.ComponentModel.TypeConverter](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.TypeConverter.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.ComponentModel.TypeConverter.diff.csv))@norek
- [x] [System.Console](http://tempcoverage.blob.core.windows.net/report2/System.Console.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Console.diff.csv))
- [x] [System.Data.Common](http://tempcoverage.blob.core.windows.net/report2/System.Data.Common.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Data.Common.diff.csv)) - Fixed in dotnet/corefx#19141 by @YoupHulsebos
- [x] [System.Diagnostics.Debug](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Debug.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Debug.diff.csv))
- [x] [System.Diagnostics.DiagnosticSource](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.DiagnosticSource.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.DiagnosticSource.diff.csv))
- [x] [System.Diagnostics.FileVersionInfo](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.FileVersionInfo.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.FileVersionInfo.diff.csv))
- [x] [System.Diagnostics.Process](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Process.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Process.diff.csv))
- [x] [System.Diagnostics.StackTrace](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.StackTrace.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.StackTrace.diff.csv))
- [x] [System.Diagnostics.TextWriterTraceListener](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.TextWriterTraceListener.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.TextWriterTraceListener.diff.csv))
- [x] [System.Diagnostics.Tools](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Tools.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Tools.diff.csv))
- [x] [System.Diagnostics.TraceSource](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.TraceSource.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.TraceSource.diff.csv))
- [x] [System.Diagnostics.Tracing](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Tracing.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Diagnostics.Tracing.diff.csv))
- [x] [System.Drawing.Primitives](http://tempcoverage.blob.core.windows.net/report2/System.Drawing.Primitives.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Drawing.Primitives.diff.csv))
- [ ] [System.IO.Compression](http://tempcoverage.blob.core.windows.net/report2/System.IO.Compression.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.Compression.diff.csv))
- [x] [System.IO.Compression.ZipFile](http://tempcoverage.blob.core.windows.net/report2/System.IO.Compression.ZipFile.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.Compression.ZipFile.diff.csv))
- [ ] [System.IO.FileSystem.AccessControl](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.AccessControl.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.AccessControl.diff.csv))
- [ ] [System.IO.FileSystem](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.diff.csv))
- [x] [System.IO.FileSystem.DriveInfo](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.DriveInfo.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.DriveInfo.diff.csv))
- [x] [System.IO.FileSystem.Watcher](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.Watcher.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.Watcher.diff.csv))
- [x] [System.IO.IsolatedStorage](http://tempcoverage.blob.core.windows.net/report2/System.IO.IsolatedStorage.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.IsolatedStorage.diff.csv))
- [x] [System.IO.MemoryMappedFiles](http://tempcoverage.blob.core.windows.net/report2/System.IO.MemoryMappedFiles.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.MemoryMappedFiles.diff.csv))
- [x] [System.IO.Pipes](http://tempcoverage.blob.core.windows.net/report2/System.IO.Pipes.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.IO.Pipes.diff.csv))
- [x] [System.Linq](http://tempcoverage.blob.core.windows.net/report2/System.Linq.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Linq.diff.csv)) - Nothing to remove, https://github.com/dotnet/corefx/issues/17905#issuecomment-294286344 by @JonHanna
- [x] [System.Linq.Expressions](http://tempcoverage.blob.core.windows.net/report2/System.Linq.Expressions.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Linq.Expressions.diff.csv))
- [x] [System.Linq.Parallel](http://tempcoverage.blob.core.windows.net/report2/System.Linq.Parallel.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Linq.Parallel.diff.csv)) - Fixed in dotnet/corefx#19143 by @YoupHulsebos
- [x] [System.Linq.Queryable](http://tempcoverage.blob.core.windows.net/report2/System.Linq.Queryable.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Linq.Queryable.diff.csv)) - Nothing to remove - https://github.com/dotnet/corefx/issues/17905#issuecomment-294286344 by @JonHanna
- [ ] [System.Net.Http](http://tempcoverage.blob.core.windows.net/report2/System.Net.Http.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Http.diff.csv))
- [ ] [System.Net.HttpListener](http://tempcoverage.blob.core.windows.net/report2/System.Net.HttpListener.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.HttpListener.diff.csv))
- [x] [System.Net.Mail](http://tempcoverage.blob.core.windows.net/report2/System.Net.Mail.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Mail.diff.csv)) - Fixed in dotnet/corefx#19532 by @Ermiar
- [x] [System.Net.NameResolution](http://tempcoverage.blob.core.windows.net/report2/System.Net.NameResolution.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.NameResolution.diff.csv))
- [ ] [System.Net.NetworkInformation](http://tempcoverage.blob.core.windows.net/report2/System.Net.NetworkInformation.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.NetworkInformation.diff.csv))
- [x] [System.Net.Ping](http://tempcoverage.blob.core.windows.net/report2/System.Net.Ping.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Ping.diff.csv))
- [ ] [System.Net.Primitives](http://tempcoverage.blob.core.windows.net/report2/System.Net.Primitives.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Primitives.diff.csv))
- [ ] [System.Net.Requests](http://tempcoverage.blob.core.windows.net/report2/System.Net.Requests.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Requests.diff.csv))
- [ ] [System.Net.Security](http://tempcoverage.blob.core.windows.net/report2/System.Net.Security.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Security.diff.csv))
- [x] [System.Net.ServicePoint](http://tempcoverage.blob.core.windows.net/report2/System.Net.ServicePoint.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.ServicePoint.diff.csv))
- [ ] [System.Net.Sockets](http://tempcoverage.blob.core.windows.net/report2/System.Net.Sockets.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.Sockets.diff.csv))
- [ ] [System.Net.WebClient](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebClient.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebClient.diff.csv))
- [ ] [System.Net.WebHeaderCollection](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebHeaderCollection.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebHeaderCollection.diff.csv))
- [x] [System.Net.WebProxy](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebProxy.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebProxy.diff.csv))
- [ ] [System.Net.WebSockets.Client](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebSockets.Client.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebSockets.Client.diff.csv))
- [ ] [System.Net.WebSockets](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebSockets.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Net.WebSockets.diff.csv))
- [x] [System.Numerics.Vectors](http://tempcoverage.blob.core.windows.net/report2/System.Numerics.Vectors.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Numerics.Vectors.diff.csv))
- [x] [System.ObjectModel](http://tempcoverage.blob.core.windows.net/report2/System.ObjectModel.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.ObjectModel.diff.csv))
- [ ] [System.Private.DataContractSerialization](http://tempcoverage.blob.core.windows.net/report2/System.Private.DataContractSerialization.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Private.DataContractSerialization.diff.csv))
- [ ] [System.Private.Uri](http://tempcoverage.blob.core.windows.net/report2/System.Private.Uri.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Private.Uri.diff.csv))
- [x] [System.Private.Xml](http://tempcoverage.blob.core.windows.net/report2/System.Private.Xml.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Private.Xml.diff.csv))
- [x] [System.Private.Xml.Linq](http://tempcoverage.blob.core.windows.net/report2/System.Private.Xml.Linq.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Private.Xml.Linq.diff.csv))
- [x] [System.Reflection.DispatchProxy](http://tempcoverage.blob.core.windows.net/report2/System.Reflection.DispatchProxy.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Reflection.DispatchProxy.diff.csv))
- [x] [System.Reflection.Metadata](http://tempcoverage.blob.core.windows.net/report2/System.Reflection.Metadata.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Reflection.Metadata.diff.csv))
- [x] [System.Reflection.TypeExtensions](http://tempcoverage.blob.core.windows.net/report2/System.Reflection.TypeExtensions.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Reflection.TypeExtensions.diff.csv))
- [x] [System.Resources.Writer](http://tempcoverage.blob.core.windows.net/report2/System.Resources.Writer.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Resources.Writer.diff.csv))
- [x] [System.Runtime.CompilerServices.VisualC](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.CompilerServices.VisualC.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.CompilerServices.VisualC.diff.csv))
- [ ] [System.Runtime](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.diff.csv))
- [x] [System.Runtime.Extensions](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Extensions.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Extensions.diff.csv))
- [x] [System.Runtime.InteropServices](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.InteropServices.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.InteropServices.diff.csv))
- [x] [System.Runtime.InteropServices.RuntimeInformation](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.InteropServices.RuntimeInformation.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.InteropServices.RuntimeInformation.diff.csv))
- [x] [System.Runtime.Numerics](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Numerics.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Numerics.diff.csv))
- [x] [System.Runtime.Serialization.Formatters](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Serialization.Formatters.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Serialization.Formatters.diff.csv)) - Fixed in dotnet/corefx#19148 by @yaelkeemink
- [ ] [System.Runtime.Serialization.Primitives](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Serialization.Primitives.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Runtime.Serialization.Primitives.diff.csv))
- [ ] [System.Security.AccessControl](http://tempcoverage.blob.core.windows.net/report2/System.Security.AccessControl.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.AccessControl.diff.csv))
- [ ] [System.Security.Claims](http://tempcoverage.blob.core.windows.net/report2/System.Security.Claims.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Claims.diff.csv))
- [ ] [System.Security.Cryptography.Algorithms](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Algorithms.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Algorithms.diff.csv)) @mccbraxton
- [ ] [System.Security.Cryptography.Cng](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Cng.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Cng.diff.csv))
- [ ] [System.Security.Cryptography.Csp](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Csp.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Csp.diff.csv))
- [ ] [System.Security.Cryptography.Encoding](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Encoding.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Encoding.diff.csv))
- [ ] [System.Security.Cryptography.OpenSsl](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.OpenSsl.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.OpenSsl.diff.csv))
- [x] [System.Security.Cryptography.Primitives](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Primitives.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.Primitives.diff.csv))
- [x] [System.Security.Cryptography.X509Certificates](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.X509Certificates.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Cryptography.X509Certificates.diff.csv)) - Fixed in dotnet/corefx#19144 by @yaelkeemink 
- [x] [System.Security.Principal](http://tempcoverage.blob.core.windows.net/report2/System.Security.Principal.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Principal.diff.csv)) - Nothing to remove
- [x] [Microsoft.Win32.Primitives](http://tempcoverage.blob.core.windows.net/report2/Microsoft.Win32.Primitives.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/Microsoft.Win32.Primitives.diff.csv))
- [x] [Microsoft.Win32.Registry](http://tempcoverage.blob.core.windows.net/report2/Microsoft.Win32.Registry.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/Microsoft.Win32.Registry.diff.csv))
- [ ] [Microsoft.XmlSerializer.Generator](http://tempcoverage.blob.core.windows.net/report2/Microsoft.XmlSerializer.Generator.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/Microsoft.XmlSerializer.Generator.diff.csv))
- [x] [System.Security.Principal.Windows](http://tempcoverage.blob.core.windows.net/report2/System.Security.Principal.Windows.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Security.Principal.Windows.diff.csv)) - dotnet/corefx#18267
- [x] [System.Text.RegularExpressions](http://tempcoverage.blob.core.windows.net/report2/System.Text.RegularExpressions.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Text.RegularExpressions.diff.csv)) - dotnet/corefx#18134 
- [x] [System.Threading](http://tempcoverage.blob.core.windows.net/report2/System.Threading.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Threading.diff.csv)) - dotnet/corefx#18134 
- [x] [System.Threading.Overlapped](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Overlapped.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Overlapped.diff.csv)) - dotnet/corefx#18134 
- [x] [System.Threading.Tasks.Dataflow](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Tasks.Dataflow.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Tasks.Dataflow.diff.csv)) - dotnet/corefx#17998
- [x] [System.Threading.Tasks.Extensions](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Tasks.Extensions.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Tasks.Extensions.diff.csv)) - Nothing to remove
- [x] [System.Threading.Tasks.Parallel](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Tasks.Parallel.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Tasks.Parallel.diff.csv)) - Nothing to remove
- [x] [System.Threading.Thread](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Thread.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Threading.Thread.diff.csv))  - Nothing to remove
- [x] [System.Transactions.Local](http://tempcoverage.blob.core.windows.net/report2/System.Transactions.Local.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Transactions.Local.diff.csv))
- [x] [System.Web.HttpUtility](http://tempcoverage.blob.core.windows.net/report2/System.Web.HttpUtility.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Web.HttpUtility.diff.csv)) - Nothing to remove
- [x] [System.Xml.XPath.XDocument](http://tempcoverage.blob.core.windows.net/report2/System.Xml.XPath.XDocument.diff.html) ([csv](http://tempcoverage.blob.core.windows.net/report2/System.Xml.XPath.XDocument.diff.csv)) - Nothing to remove

### background
The reports were generated by enabling ILLink (mono linker build from codegen team /cc @erozenfeld) and diffing the output.  

The diffs are from a Windows build and constrained to only assemblies that are part of NETCore.App.

When the linker is enabled it will produce a "PreTrim" folder in the object folder of an assembly, for example `<corefx>\bin\obj\AnyOS.AnyCPU.Debug\Microsoft.CSharp\netstandard\PreTrim\Microsoft.CSharp.dll`.  

To enable a central copy of the trimmed assemblies you can set the property `BinPlaceILLinkTrimAssembly=true`,  This will copy all pretrimmed and trimmed assemblies to a folder under bin: `<corefx>\bin\ILLinkTrimAssembly\netcoreapp-Windows_NT-Debug-x64`.

To generate the reports linked in this issue you must have a copy of the AsmDiff.exe tool.  This tool isn't yet available for core, see (https://github.com/dotnet/buildtools/issues/1420).  If you have the desktop version of the tool you can enable the reporting by setting `AsmDiffCmd=<pathToAsmDiff.exe>`

The linker can be enabled for any project (not just those in NETCore.App) by building with `ILLinkTrimAssembly=true` after https://github.com/dotnet/corefx/pull/17825 is merged.

## how to tackle a library

Pick a library and make a note you're going to work on it. 

Open the html report above for the library. Look for lines in red. These are theoretically dead. Search for the code in the `src` folder of this repo and delete it. Continue through the report for the library and delete all the dead code like that.

BUT there ere are some special cases:

1. This is a very common one. Anything with “const”, please ignore. These are all fields inlined by the compiler, we want to keep them in the sources. Typically ints and strings.
1. Anything that is “static string” in “class SR” is special. Instead of editing a C# file you must find the matching entry in the .resx file and remove that. The .resx file for a library is in `src\<library>\src\Resources\strings.resx`. The build will regenerate SR after you do this. Ignore anything else in “class SR” -- there are several methods that may show up as dead.
1. Ignore any private parameterless constructors. We have these in the code to prevent accidentally instantiating the class, we want to keep them in the code.
1. Ignore any public parameterless constructors if there are no other constructors. These are not real.
1. Some code will not be under the library’s folder, it will be in src\common. This code may not actually be dead because another library may use it. Ideally, grep to see whether anyone else in the tree uses it -- if so, it can be deleted. Or, ignore it and we can do another pass later.
1. If the code is only used in Unix, UAP, etc do not delete it. It is likely not dead. You can tell whether it's of this type by being surrounded by eg `#if uap` or having a condition in the .csproj file like eg ` '$(TargetGroup)' == 'uap'"`

After you have removed the dead code from a library, make sure it builds (run “msbuild” in the “src” folder for the library). If it does not, go backwards. If it does build, next check the tests build and pass (run “msbuild /t:buildandtest” in the “tests” folder). Again if they do not, retrace your steps.

If that all looks good, you can put up a PR for the library. When the PR goes in, we can check it off here.

**Comment by danmosemsft** [comment]
I think this is done for now. Many thanks to all who contributed to make our codebase better!
