### ISSUE TITLE
Cleanup items for System.Drawing.Common

### ISSUE THREAD

**Issue by mellinoe** [dotnet/runtime#22129]
There are still some things that should be cleaned up and reorganized in the Windows version of System.Drawing.Common. Here is the list that I have developed while porting the code from the internal .NET Framework codebase:

* [x] Clean up the formatting of the XML doc comments. They are using some defunct syntax that doesn't work or make sense anymore. @mellinoe https://github.com/dotnet/corefx/pull/21589
* [x] Normalize comment style (lots of weird "block-style" header comments, weird comment spacing, etc.) @mellinoe https://github.com/dotnet/corefx/pull/21589
* [x] ~~Reorganize interop code to match corefx guidelines.~~ _Not really feasible given the manual function loading that is necessary._
* [ ] Remove unnecessary CodeAnalysis attributes.
* [x] Remove reference to System.Security.Permissions. https://github.com/dotnet/corefx/pull/22232
* [x] Remove System.Configuration.ConfigurationManager dependency. https://github.com/dotnet/corefx/issues/22233
* [x] Consider moving code into Windows-specific folders or filenames in preparation of x-plat version. 
* [x] Make sure that file names and file structure are consistent with the namespace and type names contained in each file. dotnet/corefx#20987 
* [ ] Enable or remove `FINALIZATION_WATCH` code blocks.
* [x] Enable or remove `FEATURE_SYSTEM_EVENTS` code blocks. Tracked by https://github.com/dotnet/corefx/issues/21319
* [ ] Use string resources in Unix version. Tracked by https://github.com/dotnet/corefx/issues/23749
* [ ] Do a dead-code pass after cleanup and reorganization. (Use ILLink to help) -- opened https://github.com/dotnet/corefx/issues/21296

**Comment by danmoseley** [comment]
Does not seem useful any more
