### ISSUE TITLE
Remove checks for impossible conditions from Microsoft.CSharp

### ISSUE THREAD

**Issue by JonHanna** [dotnet/runtime#22868]
dotnet/corefx#22456 removed some error codes that were never used, but there is other code in Microsoft.CSharp that checks for conditions that are irrelevant (can only happen when defining a type, constant operations, or other cases that only come up in static code) or impossible (lacking a mscorlib, types like `int` and `object` aren't available, in which case there would have been a fatal error before the code had a chance to run).

The removal of this dead code of course needs to be careful of removing a condition that actually could happen, in which case a test cases that hit it should be added or if that's difficult for some reason the condition should be clearly documented in a comment.

This issue is to track that.

The following is a list of all errors not currently hit during testing. This isn't a perfect to-do list (the same error could have both possible and impossible paths to it) and it includes some cases that I think should definitely be reachable (but they should be covered by tests anyway for dotnet/runtime#19616 and marked off as soon as confirmed as reachable, and besides I could be wrong), but it will serve as a gauge. There could also be cases that cannot be hit but should be, as per dotnet/corefx#22534)

- [x] CS0031 ConstOutOfRange (#25825)
- [x] CS0035 AmbigUnaryOp (#22549)
- [x] CS0038 WrongNestedThis (#26417)
- [x] CS0120 ObjectRequired (#22682)
- [x] CS0123 MethDelegateMismatch (#25217)
- [ ] CS0131 AssgLvalueExpected
- [x] CS0143 NoConstructors (#23069)
- [x] CS0148 BadDelegateConstructor (#23371)
- [x] CS0176 ObjectProhibited (#22682)
- [x] CS0192 RefReadonly (#25042)
- [ ] CS0198 AssgReadonlyStatic
- [x] CS0199 RefReadonlyStatic (#25042)
- [x] CS0205 AbstractBaseCall (#22518)
- [x] CS0206 RefProperty (#25042)
- [x] CS0218 MustHaveOpTF (#22782)
- [x] CS0221 ConstOutOfRangeChecked (#25825)
- [x] CS0229 AmbigMember (#25827)
- [x] CS0233 SizeofUnsafe (#22519)
- [x] CS0245 CallingFinalizeDepracated (#22518)
- [x] CS0250 CallingBaseFinalizeDeprecated (#22518)
- [x] CS0306 BadTypeArgument (#23286)
- [x] CS0307 TypeArgsNotAllowed (#23069)
- [x] CS0312 GenericConstraintNotSatisfiedNullableEnum (#23069)
- [x] CS0313 GenericConstraintNotSatisfiedNullableInterface (#23069)
- [x] CS0314 GenericConstraintNotSatisfiedTyVar (#23287)
- [x] CS0403 TypeVarCantBeNull (#23278)
- [x] CS0407 BadRetType (#23371)
- [x] CS0428 MethGrpToNonDel (#23371)
- [x] CS0452 RefConstraintNotSatisfied (#22549)
- [x] CS0518 PredefinedTypeNotFound (#22471)
- [ ] CS0570 BindToBogus
- [x] CS0571 CantCallSpecialMethod (#22549)
- [x] CS0648 BogusType (#22537)
- [x] CS0656 MissingPredefinedMember (#22541)
- [x] CS0664 LiteralDoubleCast (#22533)
- [x] CS0716 ConvertToStaticClass (#22549)
- [x] CS0718 GenericArgIsStaticClass (#23286)
- [x] CS0762 PartialMethodToDelegate (#22548)
- [x] CS1061 NoSuchMemberOrExtension (#22999)
- [x] CS1113 ValueTypeExtDelegate (#22999)
- [x] CS1503 BadArgType (#22748)
- [x] CS1510 RefLvalueExpected (#25042)
- [x] CS1545 BindToBogusProp2 (Should be used but wasn't, fixed in dotnet/corefx#22537)
- [x] CS1546 BindToBogusProp1 (Should be used but wasn't, fixed in dotnet/corefx#22537)
- [x] CS1594 BadDelArgTypes (#25218)
- [x] CS1604 AssgReadonlyLocal (#25042)
- [x] CS1605 RefReadonlyLocal (#25042)
- [x] CS1612 ReturnNotLValue (#26370)
- [x] CS1615 BadArgExtraRef (#22748)
- [x] CS1620 BadArgRef (#22748)
- [x] CS1648 AssgReadonly2 (#26370)
- [x] CS1649 RefReadonly2 (#25042)
- [x] CS1650 AssgReadonlyStatic2 (#26370)
- [x] CS1651 RefReadonlyStatic2 (#25042)
- [x] CS1656 AssgReadonlyLocalCause (#25214)
- [x] CS1657 RefReadonlyLocalCause (#25042)
- [x] CS1728 DelegateOnNullable (#23371)
- [x] CS1729 BadCtorArgCount (#23069)
- [x] CS1740 DuplicateNamedArgument (Enum value 5005) (#23281)
- [x] CS1744 NamedArgumentSpecificationBeforeFixedArgument (Enum value 5002) (#23281)
- [x] CS1928 BadExtensionArgTypes (#22999)
- [x] CS1929 BadInstanceArgType  (#22748)
- [x] CS1950 BadArgTypesForCollectionAdd (#22525)
- [x] CS1954 InitializerAddHasParamModifiers (#22525)
