### ISSUE TITLE
Need good diagnostics for missing dependencies

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#23766]
Where ever .NET Core has a requirement on some dependency, we should document it, and far as possible when at runtime it should indicate how to fix the problem.

1. Build time dependencies documented with good errors if not found (focus on CoreFX/CoreCLR repo):

- [ ] RHEL/Centos  ([here](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md))
- [ ] Fedora
- [ ] Debian
- [ ] Ubuntu
- [ ] Mint
- [ ] openSUSE, SLES
- [ ] macOS
- [ ] Windows ([here](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md))

2. Run time dependencies documented with good errors if not found:
- [ ] RHEL/Centos
- [ ] Fedora
- [ ] Debian
- [ ] Ubuntu
- [ ] Mint
- [ ] openSUSE, SLES
- [ ] macOS
- [ ] Windows 
- [ ] RaspberryPi ([here](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md))
- [ ] FreeBSD (pending)
- [x] System.Drawing (libgdiplus)  dotnet/corefx#24464
- [ ] System.Data.ODBC (unixODBC)

* Some of this information can be mined from our [docker files](https://github.com/dotnet/dotnet-docker).
* CoreFX build docs for Unix/macOS [here[](https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md) and Windows [here](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md)
* Out of date information: [1](https://github.com/dotnet/core/blob/master/Documentation/prereqs.md)
* Need to check on what the SDK/CLI documents and warns for.
