### ISSUE TITLE
Properly factor DllImports into Common\src\Interop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#28035]
We now have a bunch of libraries with their own DllImports, whereas the expected approach is that all DllImports in product src should be included from src\Common\src\Interop, appropriately factored by platform and library, and then those source files included into the relevant assemblies that need them.

- [ ] Microsoft.Diagnostics.Tracing.EventSource.Redist
- [ ] System.Data.SqlClient
- [x] System.Diagnostics.EventLog
- [ ] System.DirectoryServices
- [ ] System.DirectoryServices.AccountManagement
- [ ] System.DirectoryServices.Protocols
- [ ] System.Drawing.Common
- [x] System.IO.Compression
- [ ] System.IO.Compression.Brotli
- [ ] System.IO.Ports
- [x] System.Management
- [ ] System.Reflection.Metadata
- [x] System.Runtime.Caching
- [x] System.Security.Cryptography.Csp
- [x] System.Security.Cryptography.Pkcs
- [ ] System.Security.Cryptography.X509Certificates

This all needs to be refactored and dedup'd.

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md

**Comment by deeprobin** [comment]
I did a little [grep (in src/libraries excluding Common and tests)](https://gist.github.com/deeprobin/3f1b71e94aac4921b32824879dbd39a9) on the current library and dllimports. Is there a reason why we partly use DllImports in not generated code (are 5 references)?

Means, the following libraries still have to be re-factored:
* [ ] System.Data.OleDb
* [ ] System.Transactions.Local
* [ ] System.Diagnostics.EventLog
* [ ] System.DirectoryServices
* [ ] System.Drawing.Common
* [ ] System.Private.CoreLib (Shared)

**Comment by deeprobin** [comment]
I would take care of System.Data.OleDb if no one objects.

**Comment by danmoseley** [comment]
@deeprobin do you feel like doing any more?

**Comment by danmoseley** [comment]
Actually maybe this is basically done. @stephentoub do you see more than this left?
```
System.Transactions.Local\src\System\Transactions\DtcProxyShim\DtcProxyShimFactory.cs:    [DllImport(Interop.Libraries.Xolehlp, CharSet = CharSet.Unicode, ExactSpelling = true, PreserveSig = false)]
System.Data.OleDb\src\UnsafeNativeMethods.COMWrappers.cs:        [LibraryImport(Interop.Libraries.OleAut32)]
System.Diagnostics.EventLog\src\System\Diagnostics\Reader\UnsafeNativeMethods.cs:        [LibraryImport(Interop.Libraries.Wevtapi, SetLastError = true)]
System.Diagnostics.EventLog\src\System\Diagnostics\Reader\UnsafeNativeMethods.cs:        etc
System.DirectoryServices\src\Interop\SafeNativeMethods.cs:        [LibraryImport(global::Interop.Libraries.OleAut32)]
System.DirectoryServices\src\Interop\SafeNativeMethods.cs:        etc
System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\NativeMethods.cs:        [LibraryImport(global::Interop.Libraries.Netapi32, EntryPoint = "DsGetDcNameW", StringMarshalling = StringMarshalling.Utf16)]
System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\NativeMethods.cs:        etc
System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\UnsafeNativeMethods.cs:        [LibraryImport(global::Interop.Libraries.Activeds, EntryPoint = "ADsEncodeBinaryData", StringMarshalling = StringMarshalling.Utf16)]
System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\UnsafeNativeMethods.cs:        etc
```

**Comment by deeprobin** [comment]
@stephentoub Is anything left to factor into Common\.

As described in the comments of #109196, it is not really considered useful to move the LibraryImports to Common in a library that is considered legacy here. Also the wevtapi isn't used anywhere else.
/cc @ericstj @AaronRobinsonMSFT 

I think System.Transactions.Local is also kind of legacy (am I right?)?
So this would also apply to #109222.

Do we need to factor more LibraryImports to `Common\` or can we close this feature as completed?
