### ISSUE TITLE
Add cgroup v2 support to .NET Core

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#30337]
The Linux kernel includes a feature called "cgroup" (or "cgroups"). This allows managing - specially limiting - resources (cpu, memory, etc) for a collection of processes. This is one of the underlying technology pieces used by projects like docker, podman, kubernetes and systemd to limit various resources for processes.

The first version of cgroup has a number of design issues and a redesign, cgroup v2, was implemented in the Linux kernel. There are a number of incompatibilities between cgroup v1 and cgroup v2.

Complete documentation of cgroup v2 is available here: https://www.kernel.org/doc/Documentation/cgroup-v2.txt 

Both cgroup v1 and cgroup v2 may be enabled on a system at the same time. Container runtimes (`podman`, `docker`) will only use one.

Some Linux distributions, such as Fedora, are starting to switch to cgroup v2 as the default: https://fedoraproject.org/wiki/Changes/CGroupsV2. Even where it's not the default, adding `systemd.unified-cgroup-hierarchy=1` to the kernel command can be used to make it the default for testing.

A technique to disambiguate between cgroup v1 and cgroup v2 is documented here: https://systemd.io/CGROUP_DELEGATION/#three-different-tree-setups-

Currently, .NET Core doesn't support cgroup v2. This issue is for tracking the changes/fixes required across the different .NET Components.

CoreCLR:
- [x] Add cgroup v2 support to PAL's `cgroup.cpp` and gc's `cgroup.cpp`:  https://github.com/dotnet/runtime/pull/34334 (originally https://github.com/dotnet/coreclr/pull/25906, but not merged due to repo move)

CoreFx:
- [x] Fix reading the memory limit in `Interop.cgroups.cs`: https://github.com/dotnet/corefx/pull/39686
- [x] Fix `cgroup2fs` in the file system information in `Interop.MountPoints.FormatInfo.cs`: https://github.com/dotnet/corefx/pull/39633
- [x] Sync cgroup v2 implementation in corefx with that in coreclr: https://github.com/dotnet/runtime/pull/34665

**Comment by omajid** [comment]
I am going to close this issue now that all my initial patches have been merged.

Any further changes (features or bugfixes) should probably be handled separately.

**Comment by omajid** [comment]
Could someone please update the tags on this? I think this could be classified as `enhancement` and `os-linux`?
