### ISSUE TITLE
Static analysis for .NET 5

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#30740]
In FxCop's hey day, many rules were written to help validate the correctness and performance of .NET code.  .NET has evolved significantly since then, however, and the creation of new rules has not kept up with the times; we've added very few new analyzers to help validate the correctness and performance of code using the wealth of new types, methods, and patterns that have made their way into .NET in the interim.

**For .NET 5, we should augment https://github.com/dotnet/roslyn-analyzers/tree/master/src/Microsoft.NetCore.Analyzers with new analyzers to help further validate the correctness and improve the performance of code written for .NET.**

Guidelines:
- Every rule we add should be applicable to many libraries targeting netcoreapp and/or netstandard, including but not limited to those that compose .NET Core itself.
- Every rule we add should be done so with the goal of enabling it in all of the libraries that compose .NET Core itself.
- Any rule we add must have a _very_ low false positive rate.  We should be able to enable the rule in all of the libraries that compose .NET Core with few-to-no suppressions.
- Auto-fixes should be included whenever possible.  However, they should only trigger for cases of extremely high confidence that the revised code is as good or better than the original.
- When in doubt, heuristics should err on the side of not warning, i.e. we prefer false negatives over false positives.  If a "confidence" level system is ever added to analyzers, this can be revisited.

This issue exists to collect and catalog ideas for such rules to be implemented in the .NET 5 timeframe.

Note that the notes below are just starting ideas... cases called out may not be the right ones to check, may be missing additional cases of importance, etc.  When we decide to tackle one of these, part of the work item (which should be split off into a separate issue) will be determining the right heuristics to employ (and potentially even deciding that the false positive rate will be too high to include such a rule at all).

https://github.com/dotnet/runtime/labels/code-analyzer

<details>
<summary>Old List</summary>
#### System

- [ ] **HashCode usage**.  Find GetHashCode implementations doing manual hashcode combination and switch to HashCode.Combine.

- [ ] **ArgumentException arguments**.  Find places where `nameof(…)` is passed as the first (rather than second) argument to `ArgumentException`.  Also places where `nameof` is used as the argument name in an `ArgumentException` (or derived type) but where it's not referring to a parameter.

- [ ] **Local DateTime math**.  Find places where DateTimes known to be in local time (e.g. resulting from DateTime.Now) are used in math.

- [ ] **Buffer.BlockCopy**. The count argument is in bytes, but it's easy to accidentally do something like `Buffer.BlockCopy(src, 0, dst, 0, src.Length)`, and if src is an array of elements larger than bytes, this is a bug.

- [ ] **Structs passed to Object.ReferenceEquals**. Calls to `ReferenceEquals` where we can detect a value type is being passed in are invariably wrong, as the value type will be boxed, and regardless of its value, `ReferenceEquals` will always return `false`.

#### System.Buffers

- [ ] **ArrayPool misuse**.  The rule should flag cases where a buffer is potentially being returned to the shared pool multiple times, e.g. where a buffer is returned and then still used after the Return; where a method taking an array by ref Returns the array but doesn't null out the ref; where there's a Return call in a try block, where that same instance is also returned in a catch block, and where something after the Return call in the try block could cause an exception that would trigger the same instance to be returned again in the catch; etc.

- [x] **MemoryManager finalizers**.  Adding a finalizer to a `MemoryManager<T>`-derived type is likely an indication of a bug, as it suggests a native resource that could have been handed out in a `Span<T>` is getting cleaned up and potentially while it’s still in use by the `Span<T>`.

#### System.Linq

- [ ] **PLINQ nops**.  Using .AsParallel() at the end of a LINQ query, e.g. `foreach (var item in src.Select(…).Where(…).AsParallel(…))`, is a nop and should either be removed or the AsParallel moved earlier in the query.  I’ve even seen developers write `foreach (var item in src.AsParallel())` thinking it parallelizes the `foreach` loop, which it doesn’t… it’d be good to warn about such misuse.
- [ ] **OfType**.  Warn if use of `OfType` would provably result in an empty sequence, because we can see that the input type in the sequence will never be the specified type.

#### System.Runtime.InteropServices

- [ ] **P/Invoke errors**.  If https://github.com/dotnet/corefx/issues/40740 goes ahead, we should flag cases where we can detect very likely misuse.

#### System.Runtime.Intrinsics

- [ ] **Non-constant arguments to methods intended for use with constant arguments**.  Consider adding an `[Immediate]`/`[ConstantExpected` attribute that could be put on parameters to indicate that arguments should be constants rather than variables.  See https://github.com/dotnet/runtime/issues/30740#issuecomment-594111037 for details.

#### System.Text.Json

- [ ] **Utf8JsonReader misuse**.  The rule should flag cases where a reader is passed around by value.

#### System.Threading

- [ ] **readonly SpinLock fields**.  `SpinLock` is a mutable struct, meant only for advanced scenarios.  Accidentally making a `SpinLock` field `readonly` can result in silent but significant problems,  as any mutations to the instance (e.g. Enter, Exit) will be done on a compiler-generated copy and thus be ignored, making the lock an expensive nop. (It might make sense to extend this analyzer to additional mutable struct types where storing them in a readonly field is likely a bug, e.g. `GCHandle`.)
- [ ] **CancellationToken flowing**.  The rule should try to identify places where a `CancellationToken` should have been passed but wasn’t, e.g. in an async method that takes a `CancellationToken`, a method is called that has an overload that takes a `CancellationToken` but a shorter overload that doesn’t take a `CancellationToken` was used instead. cc: @marklio 

#### System.Threading.Tasks

- [ ] **Passing TaskContinuationOptions to `new TaskCompletionSource<T>(object state)`**.  TCS has a ctor that takes a `TaskCreationOptions options` and another ctor that takes an `object state`.  There’s a similar enum to `TaskCreationOptions` that’s only meant to be used with `ContinueWith`: `TaskContinuationsOptions`.  It’s easy to accidentally pass a `TaskContinuationOptions` to the TCS ctor, in which case it binds to the overload accepting an `object` and isn’t treating as options at all (and, adding insult to “your options aren’t respected” injury, it also boxes).
- [x] **`ValueTask`/`ValueTask<T>` correctness.** The rule should detect cases where there's a strong liklihood a `ValueTask{<T>}` is being used incorrectly, e.g. where a single instance may be awaited multiple times, where an instance may be awaited and then also returned out of a method, where an instance may have `.GetAwaiter().GetResult()` called on it when it's not obviously already completed, when one is stored into a static field or a dictionary or some other publishing mechanism, etc.

##### Span

- [ ] **string.Concat with substrings**.  The rule should flag instances of a pattern like `str1 + str2.Substring(…) + str3` or `string.Concat(str1, str2.Substring(…), str3)` and instead switch to using the span-based `string.Concat(str1, str2.AsSpan(…), str3)`.

- [ ] **AsSpan instead of Substring**.  Somewhat more generally, any time `string.Substring` is used as an argument to something where there's an equivalent overload that takes a `ReadOnlySpan<char>` (e.g. `StringBuilder.Append(string)` vs `StringBuilder.Append(ReadOnlySpan<char>)`), the case can be flagged to be changed to use `AsSpan` instead.

- [ ] **Span.SequenceEquals**.  Identify open-coded comparison loops between two spans/arrays and suggest replacing with SequenceEquals.

- [ ] **static `ReadOnlySpan<byte>` properties**.  With a pattern like `private static readonly byte[] s_array = new byte[] { ... }` where the `static readonly byte[]` is `internal`/`private`, all consumers of `s_array` could instead operate on a span, and the field is initialized to a new `byte[]` of constant values, it can be changed instead to `static ReadOnlySpan<byte> Data => new byte[] { ... }`, and the C# compiler will optimize the implementation.

- [ ] **Replace local allocations with span stackallocs.**.  Flag places where known small temporary arrays of primitives (e.g. with a small constant length / where the total size of sizeof(T)*length can be determined to be < some threshold) not inside any loop and not passed around could be replaced by span stackallocs.

- [ ] **Calling stackalloc in loop**. Calling stackalloc in a loop leads to stackoverflow. This bug is [easy to introduce](https://github.com/dotnet/runtime/pull/32025#issuecomment-586600268) with the above.

##### String

- [ ] **string.Concat consolidation**. Various patterns of string concatenation generate unnecessary intermediate strings, e.g. `string result = s1 + s2; return result + s3;` will create an unnecessary string allocation, as will `string result = s1 + s2; if (condition) result+= s3; return result;` which could be rewritten as `string result = condition ? s1 + s2 + s3 : s1 + s2;`.  The rule would find and offer fixes for such patterns.

- [ ] **Primitive substring parsing**.  The rule should flag instances of a pattern like `int.Parse(str.Substring(…))` and instead switch to using the span-based `int.Parse(str.AsSpan(…))`.  This would apply to all of the primitive types, and more generally potentially anything that has an overload taking a `ReadOnlySpan<char>` instead of a `string`.

- [ ] **String.IndexOf(...) == -1**.  Calls to `String.IndexOf(...)` where the result is then just compared to -1 can instead be replaced by calls to `String.Contains(...)`.

##### StringBuilder

- [ ] **StringBuilder.Append(char vs string)**. It's common to see calls to `StringBuilder.Append(string)` with a const `string` containing a single character, e.g. `","`.  These would be slightly cheaper as calls using a const `char` instead.

- [ ] **StringBuilder.Append(primitive.ToString())**.  The primitive should be passed directly instead.

##### Stream

- [ ] **Stream.ReadByte/WriteByte missing overrides**.  The rule should flag custom Stream-derived types that don’t override `ReadByte` or `WriteByte`.

- [ ] **Stream.ReadAsync/WriteAsync missing overrides**.  The rule should flag custom Stream-derived types that override `BeginRead/EndRead` or `BeginWrite/EndWrite` but that don’t override `ReadAsync` or `WriteAsync`.  And it should flag custom Stream-derived types that override the array-based `ReadAsync` or `WriteAsync` but that don’t override the `Memory`-based overloads of the same name. (Potentially the same should be done for the `Span`-based overloads, but as the array-based `Read` and `Write` methods are abstract and thus must be overridden, it’s harder to say whether those should be or not.)

- [ ] **Stream.Read/WriteAsync overload usage**.  Find places where `await stream.Read/WriteAsync(array, offset, length, …)` are used and recommend they be replaced by calls to the overloads that take `{ReadOnly}Memory<byte>`, to benefit from the return type being `ValueTask<int>`.

##### Tuples

- [ ] **Tuple instead of ValueTuple**. The rule should find and flag cases where a `Tuple<…>` is being used but where a `ValueTuple<…>` would suffice, ideally with the C# language syntax employed.  There are some cases where a `Tuple<…>` is beneficial, however, so the patterns identified here would be constrained.

##### Nullable

- [ ] **Nullable.GetValueOrDefault**. After checking a `Nullable<T>.HasValue`, it's common to see calls to `Nullable<T>.Value`; instead of calling `Value`, it's less work to call `GetValueOrDefault()`, as `Value` repeats the `HasValue` check.  It's possible a future JIT could optimize away the duplicate check, but if nothing else using `GetValueOrDefault()` makes the job of the JIT easier.

##### Other

- [ ] **params array allocation in loops**.  Find calls to System.* methods inside loops, where those methods take params arrays and those params arrays are being allocated, and hoist the allocation to before the loop if possible.

- [ ] **Lifting arrays of consts to statics**.  Arrays of consts passed to known methods on types like System.String (e.g. `string.IndexOfAny(new[] { ',', '.' })`) can be lifted out to static readonly fields.

- [ ] **Redundant virtual property calls**.  Virtual properties are rarely inlined by the JIT and result into expensive virtual calls. Detect cases where the call can be hoisted and the return value reused.

- [ ] **constructor parameters should match property names**. In general, constructor arguments who initialize should match properties (casing aside). There are also cases where serializers will match properties to constructor parameters in order to construct immutable types. This would address that too.

#### System.Collections

- [ ] **Dictionary.ContainsKey(key) followed by Dictionary.Remove(key)**.  The pair can be combined into just the `Remove` call.

- [ ] **Dictionary.ContainsKey(key) followed by Dictionary.this[key]**.  The pair can be combined into just a `TryGetValue` call.

- [ ] **!Dictionary.ContainsKey(key) followed by Dictionary.Add**.  The pair can be combined into just a `TryAdd` call.

- [ ] **Dictionary.ContainsKey(key), followed by Dictionary.this[key], followed by Dictionary.Remove(key)**.  The trio can be combined into just the `Remove` call, using the overload accepting `out TValue value`.

#### System.Collections.Concurrent

- [ ] **Count instead of IsEmpty**.  Find places where a concurrent collection’s Count is accessed and compared to 0, then replace with IsEmpty.

#### System.Runtime.InteropServices

- [ ] **sizeof vs Marshal.SizeOf**.  `sizeof` is much more efficient than `Marshal.SizeOf`.  In cases where they'll produce the same answer, the former should be preferred (it'll generally require using `unsafe`, though, so this should only fire if `unsafe` is allowed in the project).

#### System.Threading

- [ ] **Replace “old” synchronization primitives with newer ones.** e.g. find places where a ManualResetEvent is created without a name, where its never passed to WaitHandle.WaitAll/Any, etc., and replace usage with ManualResetEventSlim.

#### System.Threading.Tasks

- [ ] **Using `ValueTask<T>` instead of `Task<T>`**.  Flagging internal/private methods that returns `T`s that won’t be entirely cached (e.g. bool) and where every caller of the method only ever awaits its result directly.

- [ ] **Task.Delay in Task.WhenAny**.  Flag places where a Task.Delay is used as an argument to WhenAny and where that Task.Delay doesn’t take a cancellation token, in which case the Task.Delay is likely leaving a timer running for longer than is necessary.

- [ ] **Task.WhenAll with one argument**.  There’s no reason to call WhenAll with a single `Task`; just use the `Task`.

- [ ] **Task.WaitAll with one argument**.  `Task.Wait` can be used instead.

#### System.Runtime.InteropServices

- [ ] **DllImport defaults**.  Flag places where an attribute is set on a DllImport that’s already the default value.

#### System.Threading

- [ ] **CancellationToken.ThrowIfCancellationRequested**.  Flag code that does `if (token.IsCancellationRequested) throw new OperationCanceledException();` or `if (token.IsCancellationRequested) throw new OperationCanceledException(token);` and replace with `token.ThrowIfCancellationRequested();`.

</details>

cc: @jaredpar, @mavasani, @danmosemsft

**Comment by mjsabby** [comment]
@mavasani @genlu @sharwell have you taken a recent update from RoslynClrHeapAllocationAnalyzer? There have been some improvements in false positives. I would love to kill that repo and point them to these analyzers. Do we have an ETA for releasing the analyzers tracked in this issue and the one you're working on?

**Comment by jmarolf** [comment]
CC: @mikadumont

**Comment by genlu** [comment]
@mjsabby I will take a look at the improvements and port them over. The release of the analyzer package is currently blocked, we just need to figure out how do we want to ship the attribute (see https://github.com/dotnet/roslyn-analyzers/pull/3193). FYI @sharwell

**Comment by GrabYourPitchforks** [comment]
More __`string`__ goodness:

- [ ] For specific `string` APIs which default to culture-aware comparisons (`string.IndexOf(string)`, `string.StartsWith(string)`, ...), callers should avoid these methods and should instead call equivalents which take a `CultureInfo` or `StringComparison` overload. This rule should not trigger on methods which default to ordinal (non-linguistic) semantics, such as `string.Equals(string)` or `string.Contains(string)`.

**Comment by danmosemsft** [comment]
> For specific string APIs which default to culture-aware comparisons (string.IndexOf(string), string.StartsWith(string), ...), callers should avoid these methods and should instead call equivalents which take a CultureInfo or StringComparison overload

This is for explicitness/avoid inadvertent bugs right? Many uses may be fine and so the rule wouldn't meet the  "very low noise rate" criterion above. Maybe we should collect that category in another issue?

**Comment by GrabYourPitchforks** [comment]
> Many uses may be fine and so the rule wouldn't meet the "very low noise rate" criterion above.

I don't think so. In my experience it's almost never correct to call these APIs from Framework code. In fact when I did the sweep in the linked issue I flagged almost every single call site as a bug.

**Comment by stephentoub** [comment]
> from Framework code

What is "Framework" here? Are you talking about code in dotnet/runtime? We're talking about a set of rules that are enabled by default everywhere.

**Comment by stephentoub** [comment]
@GrabYourPitchforks, if your goal is actually to enable such a rule for dotnet/runtime, can we just fix CA1307 to do the right thing (e.g. only fire for a specific set of methods) and then we can turn it on for the repo?
cc: @mavasani, @eerhardt

**Comment by GrabYourPitchforks** [comment]
> What is "Framework" here? Are you talking about code in dotnet/runtime?

I meant library code as distinct from application code. Somewhat akin to when one should use `ConfigureAwait(false)`, I suppose. :)

Turning it on in the dotnet/\* repos without turning it on by default for the entire dotnet ecosystem is fine by me.

**Comment by stephentoub** [comment]
Can we fix CA1307 then to be what it should be? @masavani, the problem is it flags things it shouldn't flag, like saying using GetHashCode() is wrong because there's also a GetHashCode(StringComparison) overload.

**Comment by mavasani** [comment]
> Can we fix CA1307 then to be what it should be? @masavani, the problem is it flags things it shouldn't flag, like saying using GetHashCode() is wrong because there's also a GetHashCode(StringComparison) overload.

Yes, seems reasonable to update the defaults for the rule, while also making the rule configurable so end users can specify additional method names/signatures which should be validated. Can you file an issue on https://github.com/dotnet/roslyn-analyzers/issues/new?

**Comment by eerhardt** [comment]
Another offender for `CA1307` is `string.IndexOf(char)`. Logged here https://github.com/dotnet/roslyn-analyzers/issues/2581.

**Comment by stephentoub** [comment]
Thanks, @mavasani.  I re-opened https://github.com/dotnet/roslyn-analyzers/issues/2581 and added your comments.

**Comment by GrabYourPitchforks** [comment]
I captured my ideas for an improved CA1307 rule in the linked issue. Thanks all for the pointer. :)

**Comment by EgorBo** [comment]
Idea:
```csharp
static void ProcessData(int n)
{
    for (byte i = 0; i < n; i++)
    {
        Thread.Sleep(1);
    }
}
```
Warn if indexer is tested against a variable of a bigger integer so it will be always less and become an infinite loop due to indexer overflow, e.g. call the method above like this: `ProcessData(300)` and observe an infinite loop (I've seen such anti-patterns few times).

**Comment by mjsabby** [comment]
@stephentoub Are you accepting more rules for this issue?

Another one that is in our guidelines for C# 7.2+ but codifying it would be great,

A warning to be emitted when a method or property is called on an `in` argument if it is a value type (maybe of a certain size threshold?).

**Comment by stephentoub** [comment]
> Are you accepting more rules for this issue?

Absolutely.

However, I've been trying to keep it focused on rules specific to framework types rather than on language features. My hope has been that @jaredpar and @mavasani and co would similarly build rules related to language features.

The rule you suggest would also, I expect, be super noisy.

**Comment by jaredpar** [comment]
We're meeting with the analyzer team later this week to discuss how we can incorporate language rules into this analyzer package. It will effectively become what we've previously described as warning waves.

**Comment by GrabYourPitchforks** [comment]
We have scenarios (particularly in the _Intrinsics_ namespace) where certain APIs expect constant values as parameters. For instance, [`Sse2.ShiftLeftLogical(Vector, byte)`](https://apisof.net/catalog/System.Runtime.Intrinsics.X86.Sse2.ShiftLeftLogical(Vector128%3CInt16%3E,Byte)) expects a constant value for its last argument, as the constant value needs to be encoded as part of the instruction. You can pass a non-constant, but if you do this you'll get redirected to a jump table, which could kill your performance. And presumably you were using intrinsics because you wanted bare-metal performance. :)

As a strawman for an analyzer that could detect this, we could consider an `[Immediate]` attribute that could be placed on parameters and an analyzer that would flag call sites where a non-const is passed in for these parameters. Bruce had further suggested we could extend it with min and max properties if needed.

So, using the SSE2 example mentioned earlier, the annotation would appear as follows.

```cs
namespace System.Runtime.Intrinsics.X86
{
    public abstract class Sse2 : Sse
    {
        public static Vector128<short> ShiftLeftLogical(Vector128<short> value, [Immediate] byte count);
    }
}
```

**Comment by ellismg** [comment]
I've seen a few cases in the wild where there will be a call to `object.ReferenceEquals` where one or both of the arguments are value types.  Consider adding a rule that would fire in this case, since in these cases, the arguments are going to be boxed (since the method takes two `object`'s) and hence it can never return true.

**Comment by stephentoub** [comment]
Thanks, @GrabYourPitchforks  and @ellismg; I added them to the list.

**Comment by GrabYourPitchforks** [comment]
Another perf one for you. Replace this:

```cs
Span<T> theSpan = GetSpan();
theSpan.Fill(default(T));
```

With this:

```cs
Span<T> theSpan = GetSpan();
theSpan.Clear();
```

I see a handful of uses of `Fill(0)` or `Fill(default)` throughout the codebase (see [callers](https://source.dot.net/System.Private.CoreLib/R/ae132b20c11a88a5.html)). The `Clear()` method is potentially much more optimized than the `Fill` method depending on the _T_ in use.

**Comment by alrz** [comment]
Some of [JB annotations](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html) that I find useful at times:

- Lack of `InstantHandleAttribute﻿` on a delegate warns if we capture a disposed disposable object 
- Honor `PureAttribute` and warn if return value is not used.
- `StringFormatMethodAttribute﻿` verifies valid usage of string format.
- `RegexPatternAttribute﻿` validates (and highlights) regular expressions
- Warn if an explicit value is passed to `CallerPropertyName` parameters

**Comment by terrajobst** [comment]
Thanks for everyone who provided feedback!

I've split @stephentoub's list [into individual issues](https://github.com/dotnet/runtime/labels/code-analyzer). In the future, please file issues for any analyzer/fixer suggestions.

**Comment by danmosemsft** [comment]
Note this work is actively happening and you can track progress here: https://github.com/dotnet/runtime/projects/46
