### ISSUE TITLE
System.Reflection and S.R.Emit roadmap for 5.0 [WIP]

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#31895]
_[Work in Progress]_

To help with priority discussions, this issue is tracking design and functional issues.

In general, the issues fall into the following buckets:
- Design \ roadmap
- Features (large API additions to smaller functional features)
- Performance improvements
- Bugs (crashes, inconsistencies, ...)

# Areas of focus
1) Determine Reflection.Emit roadmap and usage scenarios.
2) Unblock .NET Framework migration scenarios.
3) Support other higher-level 5.0 initiatives (impact here TBD).
4) Improve quality by fixing bugs and increasing performance as necessary.

# Current Issues
### 5.0 Open Issues
Currently there are ~43 open issues for 5.0
[System.Reflection 5.0](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-System.Reflection+milestone%3A5.0)
[System.Reflection.Emit 5.0](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-System.Reflection.Emit+milestone%3A5.0)

### Future Open Issues 
Currently there are ~36 issues (a first pass was made for 5.0 inclusion; a second pass is planned):
[System.Reflection future](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-System.Reflection+milestone%3AFuture)
[System.Reflection.Emit future](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-System.Reflection.Emit+milestone%3AFuture)

# Planned work
For workload reasons, the following are non-trivial issues that currently are being scheduled or discussed for 5.0:

## P1 roadmap and usage scenarios.
- [ ] Determine Reflection.Emit roadmap. Reflection.Emit is not supported on key platforms. How can we support common scenarios that will unblock key scenarios? For example, the JSON Serializer uses emit to generate code that quickly sets\gets properties -- can we add a mechanism that doesn't require ref emit for this, which would allow the Serializer to be used on more platforms in a performant way?

Note these are related and may or may not be addressed pending discussion:
- [Proposal: Add new GetValue method to System.Reflection #19484](https://github.com/dotnet/runtime/issues/19484)
- [Proposal for high-performance codegen-less Reflection factory APIs #23716](https://github.com/dotnet/runtime/issues/23716)
- [Faster MethodInfo.Invoke #7560](https://github.com/dotnet/runtime/issues/7560)
- todo: proposal for fast property\field getter\setter without using ref.emit?

## P1 features
- [ ] (medium) [MetadataLoadContext to support dynamic assemblies #27803](https://github.com/dotnet/runtime/issues/27803)
- [x] (small) [Unable to read ReturnTypeCustomAttributes when using System.Reflection.MetadataLoadContext #30959](https://github.com/dotnet/runtime/issues/30959)

## P1 performance
- [x] (medium) [System.Reflection.MetadataLoadContext performance #30886](https://github.com/dotnet/runtime/issues/30886)

## P1 bugs
- [x] (medium) [Test Failed: System.AccessViolationException #13298](https://github.com/dotnet/runtime/issues/13298)
- [x] (small) [Add .Net Framework TFM to System.Reflection.MetadataLoadContext #30810](https://github.com/dotnet/runtime/issues/30810)
- [x] (?) [The dynamic type created is thrown Fileloadexception when using the GetCustomAttributes method #26912](https://github.com/dotnet/runtime/issues/26912)
- [x] (small-medium) [System.Reflection.DispatchProxy inconsistently fails for internal interfaces #30917](https://github.com/dotnet/runtime/issues/30917)
- [ ] (small) [Port CoreRT fix to System.Reflection.MetadataLoadContext #28046](https://github.com/dotnet/runtime/issues/28046)

## P2 features
- [ ] (very large; under discussion) [System.Reflection.Emit.AssemblyBuilder.Save #15704](https://github.com/dotnet/runtime/issues/15704)
- [ ] (large?) [WIP API Proposal - AssemblyBuilder.DefineDynamicAssembly for AssemblyLoadContext #29842](https://github.com/dotnet/runtime/issues/29842)

## P2 bugs
- [ ] (small) [31195 - CustomAttribute with Array Properties sets nulls incorrectly #31195](https://github.com/dotnet/runtime/issues/31195)
- [x] (small) [31127 - Mark Assembly.CodeBase as obsolete #31127](https://github.com/dotnet/runtime/issues/31127)
- [ ] (small) [parameterBuilder.SetConstant NullReferenceException #5987](https://github.com/dotnet/runtime/issues/5987)
- [x] (small) [ParameterInfo.HasDefaultValue throws System.FormatException on optional DateTime parameter #18844](https://github.com/dotnet/runtime/issues/18844)
- [x] (investigate) [DispatchProxy doesn't handle Span #28468](https://github.com/dotnet/runtime/issues/28468)
- [x] (investigate) [DispatchProxy doesn't handle ref returns #28467](https://github.com/dotnet/runtime/issues/28467)
- [ ] (investigate) [Constructor_String_LoadVersionTest failing on Fedora runs #27817](https://github.com/dotnet/runtime/issues/27817)
- [x] (investigate) [Reflection should check mscorlib for types #19689](https://github.com/dotnet/runtime/issues/19689)

**Comment by karelz** [comment]
@steveharter only 1 area label per issue please - see [why](https://github.com/dotnet/runtime/blob/master/docs/project/issue-guide.md#motivation-for-triage-rules).

**Comment by SingleAccretion** [comment]
@steveharter Given #12924 has been closed as by (unfortunate) design, should it be removed form the roadmap?

**Comment by steveharter** [comment]
Closing this for 5.0. 

For 6.0, a new Epic issue may or may not be created to track the high-level goals and backlog.

**Comment by danmosemsft** [comment]
Removing "Epic" so it isn't pulling children into the tree. We now have https://github.com/dotnet/runtime/issues/44655
