### ISSUE TITLE
Ensure correct packaging for iOS and Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#33690]
iOS and Android are going to create RuntimePacks that will be consumed by the Xamarin SDK's.  In order for the to happen, we must modify the installer to not be coreclr specific.  

- [x] Investigate the best way to alter the installer to take mono into account
- [x] Build installer for iOS
- [x] Validate the correct packages are created for iOS : https://github.com/dotnet/runtime/pull/34050
- [x] Build installer for android
- [x] Validate the correct packages are created for android : https://github.com/dotnet/runtime/pull/34192
- [x] Hook packages up to the correct feed.
