### ISSUE TITLE
Work that needs to happen for .NET 5 TFMs

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#34173]
The spec for .NET 5 TFMs can be found [here](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md).

### Runtime/SDK

* [x] [Ensure SDK explodes .NET 5 `TargetFramework` into `TargetFramework*` and `TargetPlatform*` properties](https://github.com/dotnet/sdk/issues/11231)
* [x] [Make the build fail when a TFM with an unsupported OS or OS version is being used](https://github.com/dotnet/sdk/issues/11232)
* [x] Update RIDs for Xamarin platforms
* [x] [Add preprocessor symbols for OS](https://github.com/dotnet/sdk/issues/11236)
* [x] [Handle new TFMs in runtimeconfig and host](https://github.com/dotnet/runtime/issues/34033)
* [x] [Produce a warning when a `net5.0` project references `netcoreapp3.1` (or earlier) with WPF/WinForms](https://github.com/dotnet/sdk/issues/11241)
* Cut
   - ~~Add shared framework for Xamarin platforms~~
   - ~~Add SDK-style build support for Xamarin~~

### NuGet

* [x] [net5 tfm: framework precedence rules](https://github.com/nuget/Home/issues/9436)
* [x] [net5 tfm: produce error when missing TPV](https://github.com/nuget/Home/issues/9441)
* [x] [net5 tfm: "hydrating" empty TargetPlatformVersions](https://github.com/nuget/Home/issues/9444)
* [x] [net5.0 VS APIs](https://github.com/nuget/Home/issues/9650)
* [x] [With multi targeted projects, NuGet should read the target framework related information from the inner build.](https://github.com/nuget/Home/issues/9756)
* [ ] [NuGet pack should catch incorrect omitting of the dot in version numbers](https://github.com/nuget/Home/issues/9215)
* Cut
    - ~~Make NuGet understand that the existing Xamarin TFMs can be installed into the new `net5.0-xxx` TFMs~~ (Xamarin is pushed to .NET 6)
    - ~~Fail pack when packing equivalent TFMs like `net5.0-ios` and `net5.0-ios13.0`~~ (this state is impossible now)
    - ~~Produce a warning when a project consumes a library with a higher `TargetPlatformMinVersion`~~ (handled by analyzer)
    - ~~[net5 tfm: TargetPlatformMinVersion in packed nuspec](https://github.com/nuget/Home/issues/9439)~~ (handled by analyzer)
* Future
    - [ ] [Add a TFM for Unity's DOTS profile](https://github.com/nuget/Home/issues/9347)

### MSBuild

* [x] [Allow TFM/TPM checks in a concise, understandable way](https://github.com/microsoft/msbuild/issues/5171)

### Project System

* [x] Pass the correct information to NuGet restore, specifically TFI, TFV, TPI, TPV

@rainersigwald @dsplaisted @rrelyea @ericstj @ViktorHofer Please help me complete the list of items. Also, we would make sure that each item is linked to a corresponding GitHub issue.

**Comment by marek-safar** [comment]
>  Add shared framework for Xamarin platforms

What do you mean by that?

> Add SDK-style build support for Xamarin

Don’t think this should be here, it’s not required for runtime but build on top of that as other workloads

**Comment by vitek-karas** [comment]
Should add whatever works comes out of this issue: https://github.com/dotnet/runtime/issues/34033

**Comment by hypeartist** [comment]
Is that related: https://github.com/dotnet/runtime/issues/34060 ?

**Comment by terrajobst** [comment]
> > Add shared framework for Xamarin platforms
> 
> What do you mean by that?

We need to figure out how a project targeting say `net5.0-ios13.0` references the platform, which includes both the BCL as well as the Xamarin specific bits on top. Implicit PackageReference? FrameworkReference?

> > Add SDK-style build support for Xamarin
> 
> Don’t think this should be here, it’s not required for runtime but build on top of that as other workloads

The point of this issue to group all the work that is happening for bring this work to life; the point is to design the items themselves. @mhutch, do you want to file a similar uber item for Xamarin work? It should track things like the SDK style project, how the framework is being referenced etc.

**Comment by danmosemsft** [comment]
cc @ViktorHofer

**Comment by steveisok** [comment]
+1 to the uber item for Xamarin.

**Comment by dsplaisted** [comment]
@terrajobst Additional item for NuGet (underway now):

- [ ] Update NuGet TargetFramework parsing to parse TargetPlatformIdentifier and TargetPlatformVersion

**Comment by danmosemsft** [comment]
@dsplaisted do you see any work here for the Mono or Libraries teams? My impression is no -- this is what I understand from @terrajobst last week as well.

**Comment by steveisok** [comment]
> * Add shared framework for Xamarin platforms

@terrajobst We're adding runtime packs for `Microsoft.NETCore.App.Runtime.<Mobile RID>` and Xamarin iOS/Android.  What do you mean by 'shared framework'?   Did you mean the same thing?  I could be misunderstanding the broader view.

**Comment by danmosemsft** [comment]
Linking the SDK epic https://github.com/dotnet/sdk/issues/11165

**Comment by zkat** [comment]
Linking the NuGet epic: https://github.com/NuGet/Home/issues/9089

**Comment by plamploika** [comment]
Sorry for the intrusion and maybe a stupid question but,
I read this [article](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md) and I was surprised by the following sentence: "Miguel is building Baby Shark, a popular iOS application. He started with .NET that supported iOS 13 but Apple just released iOS 14. He downloads the updated version of the .NET 5 SDK which now also includes support for iOS 14."
Does this mean that support and bindings for all platforms will ship together .net 5 sdk? Is it possible to ship support and bindings separately, for example through a nuget, as the blazor does?
It would bring the following benefits:
- smaller .net 5 sdk size. For example, I’m a web developer and I will never develop for mobile platforms, so I don’t need support for android and ios
- updating ios will result in updating the nuget-package, but not .net 5 sdk. For example, if a new ios update is released, the developer needs to update the nuget-package with bindings that will be released quickly, rather than waiting for the platform update

**Comment by svick** [comment]
@plamploika As far as I can tell, the plan is to distribute iOS support separate from the SDK, using a new concept called ["workload"](https://github.com/dotnet/designs/blob/master/accepted/2020/workloads/workloads.md).

**Comment by plamploika** [comment]
@svick, yes, it is great
But the problem remains with the long wait for the new version of the framework, which includes bundles for the new version of the OS.

I'm also interested in what will happen to the bindings after the release of the new version of the .net. For example, in the future, where there is .net9.0, the Apple provides iOS 16. Will .net5.0 be updated to support the bindings for iOS (in case I do not want to update the platform, but want to use the new features of iOS)?

Imho, separation contributes to general simplification: for example, you can leave only net5.0 tfm and install additional binders through a nuget, if necessary

**Comment by svick** [comment]
@plamploika 

> But the problem remains with the long wait for the new version of the framework, which includes bundles for the new version of the OS.

I don't think you will have to wait long. [From the document I linked above:](https://github.com/dotnet/designs/blob/master/accepted/2020/workloads/workloads.md#acquisition)

> Workloads will be updatable. The SDK will include a mechanism to discover if a workload manifest pack has been updated. An updated manifest could represent bug fixes or new features (like updated bindings for an operating system update). If a manifest has been updated, the user will be notified, and have the opportunity to acquire the new version. Updates will not be automatic.

---

> I'm also interested in what will happen to a new version of bindings after the release of the new version of the .net. For example, in the future, where there is .net9.0, the Apple provides iOS 16. Will .net5.0 be updated to support the bindings for iOS (in case I do not want to update the platform, but want to use the new features of iOS)?

If the release schedule proceeds according to [the current plan](https://github.com/dotnet/core/blob/master/roadmap.md#upcoming-ship-dates), .Net 9.0 will be released in 2024. By then, .Net 5.0 (which is not an LTS release) will be long out of support, and .Net 6.0 (which is LTS) will just slip out of support. So I don't think those will be updated with new iOS bindings at that point.

---

> Imho, separation contributes to general simplification

It's definitely not simpler to develop, if MS has to make new code compatible with many old frameworks.

**Comment by plamploika** [comment]
@svick, thanks for the answers, but I would like to clarify something else.
OS-bindings can be delivered through a special moniker or nuget.

> It's definitely not simpler to develop, if MS has to make new code compatible with many old frameworks.

So, how does delivering bindings through nuget lead to code incompatibility?

**Comment by danmosemsft** [comment]
@terrajobst can you confirm there's no remaining 5.0 work on platform (ie., dotnet/runtime) here? That seems to be the case. I'd like to know we're done at that layer.

**Comment by joperezr** [comment]
ping @terrajobst 😄 

Can we consider this done for 5.0 in terms of dotnet/runtime side?

**Comment by terrajobst** [comment]
Confirmed

**Comment by ericstj** [comment]
@terrajobst is there any work remaining here for any repos in 5.0 or should we close this?

**Comment by danmosemsft** [comment]
@terrajobst ?

**Comment by zkat** [comment]
https://github.com/nuget/Home/issues/9215 is still open, as is https://github.com/NuGet/Home/issues/9441, and we're still having discussions on how exactly to fix them, but they're relatively minor and imo shouldn't block things?

**Comment by danmosemsft** [comment]
If we have open issues for the last remaining work then we should close this epic issue as it is no longer useful...

**Comment by danmosemsft** [comment]
@zkat any objection to closing this? Are those appropriately tagged so they won't get lost for 5.0?

**Comment by ericstj** [comment]
Ping @zkat @terrajobst -- trying to close down active issues for 5.0 and need to understand if this needs to remain open.

**Comment by terrajobst** [comment]
I'm closing this as the only remaining in NuGet and that work is in-progress.

**Comment by danmosemsft** [comment]
Removing Epic so it's not pulling active children into the themes tree.
