### ISSUE TITLE
Epic: Track fully enabling libraries tests and enabling missing features for iOS, Android, and Xam.Mac 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#35410]
This epic serves as a libraries POV as we work towards full test coverage and add missing features for mobile in .NET 5.  

### Testing
- [ ] Fully integrate the test runner into the libraries build https://github.com/dotnet/runtime/issues/35123
- [ ] Alter the helix integration to accept apps as part of the helix work items
- [ ] Analyze test results, identify issues to fix 

### ICU
- [ ] Build ICU for iOS/tvOS https://github.com/dotnet/runtime/issues/33654
- [ ] Do not package w/ Invariant mode enabled https://github.com/dotnet/runtime/issues/35090

### Networking
- [ ] iOS/tvOS specific define to create `Foundation.NSUrlSessionHandler`

### Testing
- [ ] Fully integrate the test runner into the libraries build https://github.com/dotnet/runtime/issues/35262
- [ ] Piggyback on iOS helix integration (should be little to no extra work)
- [ ] Analyze test results, identify issues to fix

### Security
- [ ] Establish a process surrounding how we will manage the OpenSSL dependency
- [ ] When the android runner is available, run existing tests w/ OpenSSL.  Identify missing features

### Networking
- [ ] Android specific define to create `AndroidClientHandler`

### Testing
- [ ] Enable in-tree runtime pack for desktop mono https://github.com/dotnet/runtime/issues/35247
- [ ] Ensure SDK can find the mono runtime pack (**Blocked** on TFM/TPI integration)
