### ISSUE TITLE
[Mono] Add QCalls to the runtime

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#36449]
In CoreCLR QCalls ([documented in botr](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/corelib.md#calling-from-managed-to-native-code)) are one way to call back into the runtime from managed code.  They are basically P/Invokes, but with a lookup that goes through a runtime table.

Supporting QCalls in Mono will have a couple of benefits:
1. Less churn on the managed side of S.P.C when it makes sense we can just share managed declarations instead of having to mark them with `[MethodImpl (MethodImplOptions.InternalCall)]` for Mono and as a QCall for CoreCLR.
2. We won't need to make the native symbols visible - right now for `DllImport (__Internal)` - which we've used for the ICU shims and some System.Native methods that we link into the MonoVM, we rely on `dlsym` which means the symbol needs to be visible.  And also we have to do hacks for `RTLD_LOCAL` in order for lookups to work both in the runtime and in the embedding host on Android, OSX, etc.  With QCalls the lookup logic doesn't depend on dlsym - we just build a table at runtime.
3. Ability to share more native code - since QCalls are just PInvokes they will run in GC Safe mode and will need to switch to GC Unsafe when they call into the runtime APIs.  This is similar to how these methods behave in CoreCLR, so for projects like the EventPipe C implementation we can have uniform logic around thread GC state transitions.

Downsides:
1. Transitions from GC Unsafe (which managed code uses) to GC Safe (when going to a P/Invoke) aren't free.  Which is why CoreCLR has a `SuppressGCTransitionAttribute` https://github.com/dotnet/runtime/issues/30741 attribute which we should also implement.
2. A table in the runtime means we'll need to do `#ifdef` stuff to remove definitions for methods that shouldn't be in a particular runtime configuration.  Can't just rely on not linking the functions into the final binary.
3. There will still be differences in how the native code is implemented. For passing object references to native code, CLR uses a [`REF<T>`](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/vars.hpp#L228)  C++ template (or rather specific the base class `OBJECTREF` or instances like `SAFEHANDLEREF`) and we won't be able to make use of it in Mono directly.  Which means that sharing will only be possible in native code like the EventPipe C impl that already takes great care to abstract over the differences between CoreCLR and MonoVM

Tasks:
- [x] Add support for registering and looking up QCalls
- [x] Add support for `SuppressGCTransitionAttribute`
- [x] Share the `QCallHandles` structs https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/QCallHandles.cs
   - ~Add special marshalling support for these (or do they just work - unclear)~ these should just work
   - we will need some implementations of `GetUnderlyingNativeHandle` for `Module` and `Assembly` in our System.Reflection implementation.
- [ ] Design and implement some analog of the `REF<T>` template that we can use to pass object references to the C code in a relatively painless way.  ideally something that works with our `object-internals.h` and `handles.h` types.  Although the ideal with QCalls is to pass only a very limited number of object references to native code if it can be at all avoided.

**Comment by lambdageek** [comment]
We wouldn't duplicate the full list of S.P.C qcalls from CoreCLR since they don't always make sense for Mono, but for reference the list is https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/ecalllist.h

**Comment by jkoritzinsky** [comment]
All of the QCall handle types marshal as any other structure with the same field layout would. There’s no special handling.

**Comment by lambdageek** [comment]
Thanks @jkoritzinsky. Not sure why I thought otherwise - I see `Unsafe.AsPointer` is doing all the heavy lifting.

**Comment by thaystg** [comment]
-> Add support for SuppressGCTransitionAttribute
This was already done and working, this is the PR: https://github.com/mono/mono/pull/17534
