### ISSUE TITLE
Port netfx configuration changes to master

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#36840]
For packages that still build in 5.0 bring forward servcing changes from 3.x that added netfx configurations.

- [ ] Microsoft.XmlSerializer.Generator
- [ ] System.Collections.Immutable
- [ ] System.Composition.AttributedModel
- [ ] System.Composition.Convention
- [ ] System.Composition.Hosting
- [ ] System.Composition.Runtime
- [ ] System.Composition.TypedParts
- [ ] System.Diagnostics.DiagnosticSource
- [ ] System.IO.Pipelines
- [ ] System.Net.Http.Json
- [ ] System.Net.Http.WinHttpHandler
- [ ] System.Net.WebSockets.WebSocketProtocol
- [ ] System.Numerics.Tensors
- [ ] System.Reflection.Metadata
- [ ] System.Reflection.MetadataLoadContext
- [ ] System.Resources.Extensions
- [ ] System.Text.Encoding.CodePages
- [ ] System.Text.Encodings.Web
- [ ] System.Threading.Channels
- [ ] System.Threading.Tasks.Dataflow

**Comment by joperezr** [comment]
I thought I had an issue for this already, thanks for logging @ericstj I'll take care of it.
