### ISSUE TITLE
[mono] Tracking: covariant return methods support

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#37509]
This is a tracking issue for the implementation of [Covariant Return Methods](https://github.com/dotnet/runtime/blob/master/docs/design/features/covariant-return-methods.md) Mono

Tasks:

- [ ] Implement [PreserveBaseOverrideAttribute](https://github.com/dotnet/runtime/issues/35315)
   Goal is to pass [AttributeTesting.il](https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/src/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/AttributeTesting.il)
- [ ] Pass "positive" covariant returns [unit tests](https://github.com/dotnet/runtime/tree/master/src/coreclr/tests/src/Loader/classloader/MethodImpl/CovariantReturns)   (ie we set up the vtable correctly and `callvirt` calls the right method)
- [ ] Pass "negative" unit tests (ie we throw the correct exception for unsupported scenarios or incorrect overrides)

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by SamMonoRT** [comment]
moving tracking issues to 8.0.0
