### ISSUE TITLE
[mono] Full support for System.Reflection.Emit

### ISSUE THREAD

**Issue by alexischr** [dotnet/runtime#37794]
Mono's support for System.Reflection.Emit must be brought to the same level as CoreCLR's. From the top down, this requires:

- [ ] Filling in remaining non-implemented System.Reflection.Emit API as documented in https://github.com/mono/mono/issues/14788
- [ ] Developing Mono to pass the remaining System.Reflection.Emit library tests (tracked in https://github.com/dotnet/runtime/issues/2389/ & https://github.com/dotnet/runtime/issues/2383) for:
    - [ ] MethodBuilder
    - [ ] ConstructorBuilder
    - [ ] EnumBuilder
    - [ ] FieldBuilder
    - [ ] GenericTypeParameterBuilder
    - [ ] ModuleBuilder
    - [ ] PropertyBuilder
    - [ ] TypeBuilder
    - [ ] ILGenerator
    - [ ] SignatureHelper
- [ ] Exploring all opportunities to share code with CoreCLR

### Known Issues

* No lexical scope support for MethodBuilder/ILGenerator: Our implementation does not support using namespaces for resolving locals, and BeginScope()/EndScope() are no-ops currently.
* The following methods do not have tests/meaningful usage within `dotnet/runtime`:
     - ModuleBuilder.GetFieldToken
     - ModuleBuilder.GetSignatureToken(byte[], int)
     - ILGenerator.UsingNamespace
     - ILGenerator.EndScope

### Known issues with sharing code

* `interface ISymbolWriter` is both tied heavily with coreclr (see `CreateISymWriterForDynamicModule`) and ILGenerator/MethodBuilder.
* Mono's ModuleBuilder must match memory layouts with the Mono internal struct `MonoModule`.

### Discussion

We can share progress/ask questions in the comments.

**Comment by steveharter** [comment]
Changing area to interop-Mono. Please add a "reflection.emit-Mono" area if desired.

**Comment by fanyang-mono** [comment]
Low priority - Moving to Milestone 8.0.0

**Comment by lambdageek** [comment]
This is a tracking issue. individual problems are tracked separately.
