### ISSUE TITLE
Remove workarounds and cleanup source to meet dotnet/runtime analyzer requirements.

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#37821]
Keeping track of miscellaneous cleanup tasks leftover from Extensions consolidation:
 
#### Code Cleanups:
- [x] Move shared files between Configuration projects to Common folder (https://github.com/dotnet/runtime/pull/33844#discussion_r395899095) -> (addressed by https://github.com/dotnet/runtime/pull/42788)
- [x] Delete duplicate files or those not used (https://github.com/dotnet/runtime/pull/33816#discussion_r395300670) (addressed by #40091)
- [x] Removing styling and whitespace nit errors skipped using NoWarns (refer to [Directory.Build.props]( https://github.com/dotnet/runtime/blob/master/src/libraries/Directory.Build.props#L10))

#### Leftover PR feedback:

- [x] Remove files: https://github.com/dotnet/runtime/pull/33494#discussion_r391572247 (addressed by #40091)

#### Tests:
- [x] Enable Performance tests into dotnet/performance repo:
Primitives: https://github.com/dotnet/performance/pull/1288
Later:  DI, Logging and Hosting
- [ ] Enable DI perf tests requiring InternalsVisibleTo - covered by https://github.com/dotnet/performance/issues/1583
- [ ] Enable FunctionalTests/TestApp on Hosting: https://github.com/dotnet/runtime/issues/34090

#### Docs:
Migrate docs from source -> docs repo

It looks like extensions is still using in-source triple-slash docs.  We should work with @carlossanlop to do a one time insertion of these to the docs-repo then set up the packages to consume the docs from docs repo.

- [x] https://github.com/dotnet/dotnet-api-docs/pull/4104
- [x] https://github.com/dotnet/dotnet-api-docs/pull/4105
- [x] https://github.com/dotnet/dotnet-api-docs/pull/4107
- [x] https://github.com/dotnet/dotnet-api-docs/pull/4106

**Comment by maryamariyan** [comment]
closing as remaining work is covered by other issues now.
