### ISSUE TITLE
[Wasm] Tracking active test failures 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#38422]
We began running tests for wasm on CI, however not all test suites currently pass.  This issue tracks what's failing:

OOB = out of box library

### Suites that contain 1 or more failures
- [x] Common.Tests (https://github.com/dotnet/runtime/pull/38667)
- [x] OOB: Microsoft.Extensions.Configuration.FileExtensions.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.Configuration.Ini.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.Configuration.Json.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.Configuration.UserSecrets.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.Configuration.Xml.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.Configuration.Functional.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.DependencyModel.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.FileProviders.Physical.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] OOB: Microsoft.Extensions.Hosting.Unit.Tests (https://github.com/dotnet/runtime/pull/38721)
- [x] Microsoft.VisualBasic.Core.Tests (https://github.com/dotnet/runtime/pull/39276)
- [x] OOB: System.CodeDom.Tests (https://github.com/dotnet/runtime/pull/39626 )
- [x] System.Collections.NonGeneric.Tests (https://github.com/dotnet/runtime/pull/39020)
- [x] System.Collections.Specialized.Tests (https://github.com/dotnet/runtime/pull/39012)
- [x] System.Collections.Tests (https://github.com/dotnet/runtime/pull/38976)
- [x] System.ComponentModel.Annotations.Tests (https://github.com/dotnet/runtime/pull/39228)
- [x] System.ComponentModel.Primitives.Tests (https://github.com/dotnet/runtime/pull/39427)
- [x] System.ComponentModel.TypeConverter.Tests (https://github.com/dotnet/runtime/pull/39710)
- [x] System.Data.Common.Tests (https://github.com/dotnet/runtime/pull/39463)
- [x] System.Diagnostics.DiagnosticSource.Switches.Tests (requires runtimeconfig.template.json support - https://github.com/dotnet/runtime/pull/39952) 
- [x] System.Diagnostics.FileVersionInfo.Tests (https://github.com/dotnet/runtime/pull/39088)
- [x] System.Diagnostics.Process.Tests (https://github.com/dotnet/runtime/pull/39088)
- [x] System.Diagnostics.StackTrace.Tests (https://github.com/dotnet/runtime/pull/39226)
- [x] System.Diagnostics.TextWriterTraceListener.Tests (https://github.com/dotnet/runtime/pull/39186)
- [x] System.Diagnostics.TraceSource.Tests (https://github.com/dotnet/runtime/pull/39224)
- [x] System.Diagnostics.Tracing.Tests (https://github.com/dotnet/runtime/pull/39271)
- [x] OOB: System.Drawing.Common.Tests (https://github.com/dotnet/runtime/pull/38999)
- [x] System.Formats.Asn1.Tests (https://github.com/dotnet/runtime/pull/39104)
- [x] System.Globalization Invariant.Tests (https://github.com/dotnet/runtime/pull/39814)
- [ ] System.Globalization.CalendarsWithConfigSwitch.Tests (requires runtimeconfig.template.json support)
- [x] System.Globalization.Calendars.Tests (https://github.com/dotnet/runtime/pull/37971)
- [x] System.Globalization.Extensions.Tests (https://github.com/dotnet/runtime/pull/37971)
- [x] System.Globalization.Tests (https://github.com/dotnet/runtime/pull/37971)
- [x] System.IO.Compression.Brotli.Tests (https://github.com/dotnet/runtime/pull/38941)
- [x] System.IO.Compression.ZipFile.Tests (https://github.com/dotnet/runtime/pull/39092)
- [x] System.IO.Compression.Tests (https://github.com/dotnet/runtime/pull/39231)
- [x] System.IO.FileSystem.DriveInfo.Tests (https://github.com/dotnet/runtime/pull/39276)
- [x] System.IO.FileSystem.Tests (https://github.com/dotnet/runtime/pull/39768)
- [x] System.IO.IsolatedStorage.Tests (https://github.com/dotnet/runtime/pull/38898)
- [x] System.IO.MemoryMappedFiles.Tests (https://github.com/dotnet/runtime/pull/39355)
- [x] OOB: System.IO.Packaging.Tests (https://github.com/dotnet/runtime/pull/39427)
- [x] System.IO.Pipes.Tests (https://github.com/dotnet/runtime/pull/39089)
- [x] System.Linq.Expressions.Tests (https://github.com/dotnet/runtime/pull/39772)
- [x] System.Memory.Tests (https://github.com/dotnet/runtime/pull/39319)
- [ ] System.Net.Http.Functional.Tests @akoeplinger
- [x] System.Net.Http.Unit.Tests (https://github.com/dotnet/runtime/pull/39181)
- [x] System.Net.Mail.Unit.Tests (https://github.com/dotnet/runtime/pull/38207)
- [x] System.Net.NameResolution.Functional.Tests (https://github.com/dotnet/runtime/pull/39219)
- [x] System.Net.NameResolution.Pal.Tests (https://github.com/dotnet/runtime/pull/39219)
- [x] System.Net.Ping.Functional.Tests (https://github.com/dotnet/runtime/pull/39091)
- [x] System.Net.Primitives.Functional.Tests (https://github.com/dotnet/runtime/pull/39748)
- [x] System.Net.Primitives.Pal.Tests (https://github.com/dotnet/runtime/pull/39748)
- [x] System.Net.Security.Tests (https://github.com/dotnet/runtime/pull/39358) 
- [x] System.Net.Sockets.Tests (https://github.com/dotnet/runtime/pull/39346)
- [ ] System.Net.WebSockets.Client.Tests @akoeplinger 
- [x] System.ObjectModel.Tests (https://github.com/dotnet/runtime/pull/39849)
- [x] System.Private.Uri.Functional.Tests
- [x] System.Xml.XmlSerializer.ReflectionOnly.Tests (https://github.com/dotnet/runtime/pull/39767)
- [x] System.Xml.XmlSerializer.Tests (https://github.com/dotnet/runtime/pull/39767)
- [x] System.Xml.Xsl.XslCompiledTransformApi.Tests (https://github.com/dotnet/runtime/pull/39427)
- [x] System.Xml.Xsl.XslTransformApi.Tests (https://github.com/dotnet/runtime/pull/39427)
- [x] System.Reflection.Metadata.Tests (https://github.com/dotnet/runtime/pull/39696)
- [x] OOB: System.Reflection.MetadataLoadContext.Tests (https://github.com/dotnet/runtime/pull/39651)
- [x] System.Reflection.CoreCLR.Tests (https://github.com/dotnet/runtime/pull/39696)
- [x] System.Reflection.Tests (https://github.com/dotnet/runtime/pull/39696)
- [x] OOB: System.Resources.Extensions.Tests (will be fixed by the ICU PR: https://github.com/dotnet/runtime/pull/37971) + https://github.com/dotnet/runtime/pull/39513
- [x] System.Resources.Reader.Tests (https://github.com/dotnet/runtime/pull/39427)
- [x] System.Resources.ResourceManager.Tests (will be fixed by the ICU PR: https://github.com/dotnet/runtime/pull/37971) + https://github.com/dotnet/runtime/pull/39513
- [x] OOB: System.Runtime.Caching.Tests (https://github.com/dotnet/runtime/pull/38386)
- [x] System.Runtime.Extensions.Tests (https://github.com/dotnet/runtime/pull/38996)
- [x] System.Runtime.InteropServices.RuntimeInformation.Tests (https://github.com/dotnet/runtime/pull/39073)
- [x] System.Runtime.InteropServices.Tests (https://github.com/dotnet/runtime/pull/39188)
- [x] System.Runtime.Loader.DefaultContext.Tests (https://github.com/dotnet/runtime/pull/39204)
- [x] System.Runtime.Loader.Tests (https://github.com/dotnet/runtime/pull/39306)
- [x] System.Runtime.Serialization.Formatters.Tests (https://github.com/dotnet/runtime/pull/38948)
- [x] System.Runtime.Serialization.Json.ReflectionOnly.Tests (https://github.com/dotnet/runtime/pull/39193)
- [x] System.Runtime.Serialization.Json.Tests (https://github.com/dotnet/runtime/pull/39193)
- [x] System.Runtime.Serialization.Primitives.Tests (https://github.com/dotnet/runtime/pull/39264)
- [x] System.Runtime.Serialization.Xml.ReflectionOnly.Tests (https://github.com/dotnet/runtime/pull/39262)
- [x] System.Runtime.Serialization.Xml.Tests (https://github.com/dotnet/runtime/pull/39262)
- [x] System.Runtime.Tests (https://github.com/dotnet/runtime/pull/39344)
- [x] OOB: System.Security.Permissions.Tests (https://github.com/dotnet/runtime/pull/39767 )
- [x] System.Text.RegularExpressions.Tests (https://github.com/dotnet/runtime/pull/39470)
- [x] System.Threading.Thread.Tests (https://github.com/dotnet/runtime/pull/39826) 
- [x] System.Transactions.Local.Tests (https://github.com/dotnet/runtime/pull/39427)

### Suites that do not produce results

These tests most likely contain >= 1 thread related failures and need to be skipped
- [x] OOB: System.Configuration.ConfigurationManager.Tests (https://github.com/dotnet/runtime/pull/38749) 
- [x] System.Net.Http.Json.Functional.Tests (https://github.com/dotnet/runtime/pull/38733)
- [x] System.Net.Mail.Functional.Tests (https://github.com/dotnet/runtime/pull/38207)
- [x] System.Net.NetworkInformation.Functional.Tests (https://github.com/dotnet/runtime/pull/38928)
- [x] System.Net.Requests.Tests (https://github.com/dotnet/runtime/pull/38674)
- [x] System.Net.WebClient.Tests (https://github.com/dotnet/runtime/pull/38857)
- [x] System.Net.WebSockets.Tests (https://github.com/dotnet/runtime/pull/38808)
- [x] OOB: System.Net.WebSockets.WebSocketProtocol.Tests (https://github.com/dotnet/runtime/pull/38854)
- [x] System.Text.Json.Tests  (https://github.com/dotnet/runtime/pull/38663/)
- [x] System.Threading.Tasks.Tests  (https://github.com/dotnet/runtime/pull/38355) Needs another look after async Task 
- [x] System.Threading.Channels.Tests (https://github.com/dotnet/runtime/pull/38849)
- [x] System.Threading.Tasks.Dataflow.Tests (https://github.com/dotnet/runtime/pull/38723)
- [x] System.Threading.Tasks.Extensions.Tests (https://github.com/dotnet/runtime/pull/38815)

### Flaky suites

- [ ] System.Linq.Parallel.Tests, passes but had to be disabled again to crashes: https://github.com/dotnet/runtime/pull/39305

**Comment by safern** [comment]
> System.Globalization.CalendarsWithConfigSwitch.Tests
> System.Globalization.Calendars.Tests
> System.Globalization.Extensions.Tests
> System.Globalization.Tests

Synced up with @steveisok and @tarekgh and it makes sense to keep them disabled from CI until ICU is turned on and then we can adjust/skip tests based on the ICU globalization story for WASM. If we want to get more test coverage when running on Invariant mode, we can add those tests to [`System.Globalization/tests/Invariant/Invariant.Tests.csproj`](https://github.com/dotnet/runtime/blob/e9bb3b18f69a6671431f8a90f5f491cf583cec85/src/libraries/System.Globalization/tests/Invariant/Invariant.Tests.csproj)

**Comment by akoeplinger** [comment]
There are still three test suites we need to enable and also take a look at the flaky System.Linq.Parallel.Tests, keeping it open and in 6.0

**Comment by lewing** [comment]
@steveisok what is the state of this now?

**Comment by steveisok** [comment]
Once you get runtimeconfig.json support, the calendar test should light up. Mostly good it looks like.  Probably can close this and deal with the few remaining in another issue.

**Comment by lewing** [comment]
> Once you get runtimeconfig.json support, the calendar test should light up. Mostly good it looks like. Probably can close this and deal with the few remaining in another issue.

yeah I think this is safe to close not that we are tracking the remaining work elsewhere
