### ISSUE TITLE
Master tracking issue for removing BinaryFormatter usage from dotnet libs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#39287]
This issue tracks the tagging and removal of `BinaryFormatter`-related code paths from various _dotnet_ org repos. See https://github.com/dotnet/designs/pull/141 for more information.

## dotnet/runtime

- [x] https://github.com/dotnet/runtime/issues/39289 - usage in `DataSet`
- [x] https://github.com/dotnet/runtime/issues/39290 - usage in `ResourceReader`
- [x] https://github.com/dotnet/runtime/issues/39292 - usage in _System.Resources.Extensions_
- [x] https://github.com/dotnet/runtime/issues/39293 - usage in _System.ComponentModel.TypeConverter_ (#48527)
- [x] https://github.com/dotnet/runtime/issues/39295 - usage in _System.Configuration.ConfigurationManager_ (#50531)
- [ ] https://github.com/dotnet/runtime/issues/43482 - Exception serialization without BinaryFormatter

## Documentation of Breaking Changes

As part of the definition of done for each of these items, we must identify possibilities where changing serialization formats could be a breaking change for customers. For instance, if the serialized output could have been persisted to disk, we will likely need to document where the deserialization of persisted data could be affected.

**Comment by adamsitnik** [comment]
@jeffhandley should we close this issue and move the remaining work to a new one? Or just move it to 9.0?

**Comment by jeffhandley** [comment]
Let's just move it to 9.0.0. Done.
