### ISSUE TITLE
Developers using FileStream find it to be high performance and robust

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#40359]
(Note `.CopyToAsync` is pretty good; for certain combinations of flags)

## P0

* [x] Win32 FileStream turns async reads into sync reads #16341
* [x] FileStream.FlushAsync ends up doing synchronous writes #27643
* [x] Win32 FileStream will issue a seek on every ReadAsync and WriteAsync call #16354
* [x] FileStream.Windows useAsync WriteAsync calls blocking apis #25905
* [x] Avoid expensive `GetFileInformationByHandleEx` syscall if possible #49541
* [x] Asynchronous random file access with FileStream Read vs ReadAsync in a loop / parallel (ReadAsync is slow) #27047
* [x] Reduce FileStream allocations #49539

## P1

* [x] Avoid unnecessary allocations when using FileStream #15088
* [x] FileStream file preallocation performance https://github.com/dotnet/runtime/issues/45946

## P2

* [x] Use PreallocatedOverlapped when internal FileStream buffer isn't being used on Windows #25074
* [x] File.WriteAllTextAsync performance issues #23196
* [x] Implement new FileStreamStrategy for Unix #53809

## Moved to Future

* File.ReadAllTextAsync not behaving asynchronously when called on inaccessible network files #25314

Rosyln has [their own workarounds](https://github.com/dotnet/roslyn/blob/cb7bdffa1b17b2684083f5201153a976c04dd580/src/Workspaces/Core/Portable/Workspace/FileTextLoader.cs#L108-L173) for FileStream issues; and NuGet recently moved to mmap for better performance https://github.com/NuGet/NuGet.Client/pull/3524

_Edit by carlossanlop: To focus on the Async/Sync improvements, I'm removing 3 issues from the list that are separate from that topic._
_Edit by @adamsitnik: Proiorities

**Comment by danmosemsft** [comment]
Thanks for collecting these into an “epic” 🙂 This is a candidate for some code debt work before 6.0 feature work starts.

**Comment by danmosemsft** [comment]
@JeremyKuhne you've been a vocal advocate of improving FileStream in the past. Is there anything you want to add to this meta-issue?

**Comment by carlossanlop** [comment]
Thank you @benadams for compiling the list.

May I suggest to focus this epic specifically for improving sync/async in `FileStream`, which seems to be the main topic of most of those issues? If agreed, then these issues can be removed from the epic and addressed separately:

- https://github.com/dotnet/runtime/issues/8307  `FileStream.SetLength` doesn't return file pointer to original value on failure.
- https://github.com/dotnet/runtime/issues/29173 `FileStream.Lock(Int64, Int64)` failure on Linux - always uses `F_WRLCK`.
- https://github.com/dotnet/runtime/issues/28444 `FileStream.Flush(true)` doesn't flush device buffer on macOS, while it does so on Windows.

**Comment by jeffhandley** [comment]
@stephentoub What do you think about #8307, #29173, and #28444 -- do you think those are standalone enough to treat separately from the bigger collection of issues?  If so, we can go ahead and get started on those soon.

**Comment by stephentoub** [comment]
> do you think those are standalone enough to treat separately from the bigger collection of issues?

Yes

**Comment by danmosemsft** [comment]
Changed title to "user story terms" even though it's clearly not describing the current state.

**Comment by benaadams** [comment]
`io_uring` for file I/O on Linux? 😉 https://www.scylladb.com/2020/05/05/how-io_uring-and-ebpf-will-revolutionize-programming-in-linux/

**Comment by Tragetaschen** [comment]
Since this is also about robustness: Writing files synchronously on Linux (at least with ext4) doesn't follow Posix to call `fsync`. This has (at least for me) resulted in a corrupt files (zero length) from otherwise valid code.

https://github.com/dotnet/runtime/issues/32600
