### ISSUE TITLE
[mono] Enable -Werror on all CI lanes

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#41357]
This will make warnings into errors on CI, helping catch when we accidentally introduce them in platforms other than the one we're developing on. 

https://github.com/dotnet/runtime/pull/41233 will get us to 0 warnings on OSX and enable it there, but ultimately we want this for every platform.

If I missed a platform, feel free to add it.

Lanes:
- [ ] Windows x64 Debug
- [ ] Windows x64 Release
- [x] OSX x64 Debug
- [x] OSX x64 Release
- [x] OSX x64 LLVM AOT Debug
- [x] OSX x64 LLVM JIT Release
- [ ] Linux x64 Debug
- [ ] Linux x64 Release
- [ ] Linux arm64 Debug
- [ ] Linux arm64 Release
- [ ] Linux arm Debug
- [ ] Linux x64 LLVM AOT Release
- [ ] Linux x64 LLVM AOT Release (why are there two of these, named differently?)
- [ ] Linux arm64 LLVM AOT Release
- [ ] Linux x64 LLVM JIT Debug
- [ ] Linux arm64 LLVM JIT Debug
- [ ] Linux x64 musl Release
- [ ] Android x86 Debug
- [ ] Android x64 Release
- [ ] Android arm Release
- [ ] Android arm64 Debug
- [ ] iOS x86 Debug
- [ ] iOS x64 Release
- [ ] iOS arm Release
- [ ] iOS arm64 Debug
- [ ] tvOS x64 Debug
- [ ] tvOS arm64 Release
- [x] Browser wasm Release

**Comment by SamMonoRT** [comment]
Moving to 8.0
