### ISSUE TITLE
Annotate remainder of .NET Core assemblies for nullable reference types

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#41720]
Across .NET Core 3.0 and .NET 5.0, we annotated 94% of the `netcoreapp` assemblies for nullable reference types.  In .NET 6.0, we plan to annotate the remaining 6% of that surface area and continue through other assemblies built from the dotnet/runtime repo.

This issue represents the assemblies previously tracked in #2339 that did not get completed in .NET 5.0. Following the same practices we used in .NET 5.0, we will:

* Submit individual PRs, one for each assembly. Each PR should include changes to both the src and the ref. Each PR should contain only changes related to the nullable annotations/attributes, no other changes.
* PRs can be merged once the annotations have been appropriately reviewed in PR.

*In .NET 5.0, as was tracked in #2339, we completed groups 1-8, most of group 9, all of group 10, and some items in groups 11 and 12*

#### Group 9 ####
- [ ] System.ComponentModel.TypeConverter (will be annotated in 6.0; in progress by @safern)

#### Group 11 (not part of netcoreapp but reference netcoreapp) ####
- [ ] System.DirectoryServices
- [ ] System.Diagnostics.EventLog
- [ ] System.DirectoryServices.Protocols
- [ ] System.Security.Permissions
- [ ] System.Windows.Extensions

#### Group 12 (built from dotnet/runtime but not in netcoreapp and reference netstandard) ####
With netstandard not annotated, we will need to be cognizant of the fact that all dependencies will be viewed as oblivious:
- [ ] System.CodeDom => netstandard
- [ ] System.ComponentModel.Composition.Registration => netstandard, System.Reflection.Context
- [ ] System.Composition.AttributedModel => netstandard
- [ ] System.Composition.Convention => netstandard, System.Composition.AttributedModel
- [ ] System.Composition.Hosting => netstandard, System.Composition.Runtime
- [ ] System.Composition.Runtime => netstandard
- [ ] System.Composition.TypedParts => netstandard, System.Composition.Runtime, System.Composition.AttributedModel, System.Composition.Hosting
- [ ] System.Configuration.ConfigurationManager => netstandard, System.Security.Cryptography.ProtectedData
- [ ] System.Diagnostics.PerformanceCounter => System.Configuration.ConfigurationManager
- [ ] System.DirectoryServices.AccountManagement => System.Configuration.ConfigurationManager
- [ ] System.IO.Ports => netstandard
- [ ] System.Management => System.CodeDom
- [ ] System.Runtime.Caching => netstandard, System.Configuration.ConfigurationManager
- [ ] System.Security.Cryptography.Xml => netstandard
- [ ] System.ServiceModel.Syndication => netstandard

#### Lastly ####
- [ ] Remove `#nullable enable` from individual files after all dependent projects annotated

**Comment by jeffhandley** [comment]
@ericstj Do you think we should include the `Microsoft.Extensions` assemblies in our nullable annotations for 6.0?

**Comment by danmosemsft** [comment]
> Do you think we should include the Microsoft.Extensions assemblies in our nullable annotations for 6.0?

I wonder whether the path is smooth enough now (and our [guidance up to date](https://github.com/dotnet/runtime/blob/c87e75e8ef260ccc6e979f9df1cc012536ee036f/docs/coding-guidelines/api-guidelines/nullability.md#L1)?) that community members could help with annotating those. We've had community folks in the past be happy to help with eg dead code and cleaning up analyzer warnings. I know one concern in the past was that it's hard to review/evaluate community PR's for annotations.

**Comment by jeffhandley** [comment]
Good suggestion, @danmosemsft. We'll put some effort into ensuring the guidance is fully up to date. I intend do to some more project planning around this and probably spawn issues for each assembly to annotate, with them all on a project board. When we do that, we can consider which of them could be marked as `up-for-grabs`.

**Comment by daniel-white** [comment]
I'd be happy to pick up one.

**Comment by safern** [comment]
I also opened: https://github.com/dotnet/runtime/issues/41724 to keep track of validation.

**Comment by maryamariyan** [comment]
> I'd be happy to pick up one.

@daniel-white items under Group 1 in issue https://github.com/dotnet/runtime/issues/43605 are also up for grabs.

**Comment by krwq** [comment]
@jeffhandley Group 9 is done, I do not believe we will do remainder of Group 11 in 6.0

**Comment by jeffhandley** [comment]
For .NET 6.0, the project templates now reflect `<Nullable>enable</Nullable>` making use of the nullable annotations on by default for new 6.0 projects.

We will continue with Groups 11 and 12 in .NET 7.0, but as Priority 3. Within each of those groups, we can order the libraries by number of downloads on nuget.org (per suggestion from @krwq).

**Comment by elachlan** [comment]
Should this be moved to the .NET8 milestone? Is this still being worked on?

**Comment by mairaw** [comment]
I'm cleaning up the .NET 6 project. This shows as completed on the project dashboard but still open here. Not sure if remaining work should be moved to a new issue @jeffhandley?

**Comment by jeffhandley** [comment]
@mairaw I'm sure the checkboxes on this issue description are out of date, but also not entirely completed. We completed our checkpoints for 6.0 and 7.0, so it's accurate that the card was completed on the project board. I'd prefer to leave this issue open though, and I'll leave this on my todo list to update this, refine the list of what's left, and decide what to do from there.

**Comment by mairaw** [comment]
Sounds good @jeffhandley.
