### ISSUE TITLE
Source generation of ILStub for DllImport

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#43060]
The [Roslyn source generator][source_gen_announcement] feature has created an opportunity for the Interop team to consider the generation of the P/Invoke ILStub at compile time instead of during run time. A proposal for this work can be found [here][spec_for_dllimport_source_gen].

Prototyping is occurring in the [`dotnet/runtimelab`][source_gen_repo].

## Goals

- Remove run time overhead of ILStub generation.
- No observable degradation in performance of replaced P/Invoke calls.
- Generated code is semantically equivalent to build-in ILStub code gen.
- Support >= 80 % of P/Invoke patterns in `NetCoreApp`.
    - Stretch goal is to support 100 % in `NetCoreApp`.
- Cross-platform support.
- Ability to innovate in support of modern .NET types (e.g., `ReadOnlySpan<T>`/`Span<T>`).
- Analyzer to ensure consumption success.
- Have a scenario agnostic code generation (Roslyn APIs) library for marshalling.
- Testable
    - Ability to create comprehensive test matrix.
    - High confidence in generated code through quantifiable unit testing metrics not "most common scenario" testing.

## Non-Goals

- Support P/Invoke signatures not found in `NetCoreApp`.
- Alter built-in ILStub generation.
- Support COM interop.

## Prototype exit criteria

- [x] Proposal for new runtime APIs - see list below.
- [x] Source generator and Analyzer in NuGet package that can be consumed by `NetCoreApp` in a local build.
    - 80 % of P/Invokes in `NetCoreApp` can be updated with confidence.
    - Accounting of potential tenet deficiencies (e.g., performance, functional failures, semantic inconsistencies with built-in system).
- [x] Add one high-value marshaller that does not exist today (e.g., `Span<T>`). https://github.com/dotnet/runtimelab/pull/1222
- [x] Tooling to examine .NET assembly and indicate issues relying on source generator.
- [x] Comprehensive unit test and integration matrix for all supported scenarios.
- [x] Design documents contained within [`designs/`](https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator/designs) folder in repository.
- [x] Determine the size impact of the generated code on `NetCoreApp`
  - ~550kB (SPCL is not entirely converted) 
- [x] Validate performance impact to IDE scenarios for projects in `NetCoreApp`. See https://github.com/dotnet/runtime/pull/50741 for concern.
   - We will need to move to the Incremental Generator V2 API to get the required performance for large projects - https://github.com/dotnet/runtimelab/pull/1374
- [x] Create a plan for transitioning from the prototype to a shipping release - https://github.com/dotnet/runtimelab/pull/1378.
- [x] Share a local build of `NetCoreApp` using the source generator prototype with stakeholders.

# Source generator prototype

All work is current taking place in [`dotnet/runtimelab`][source_gen_repo].

- [x] Collect needed scope of support in `NetCoreApp` - https://github.com/dotnet/runtimelab/pull/146
- Authoring of needed marshallers.
    - [x] Blittable types
    - [x] Non-Blittable types - https://github.com/dotnet/runtimelab/pull/302
    - [x] `bool`
    - [x] `Delegate`
    - [x] `SafeHandle` - https://github.com/dotnet/runtimelab/pull/133
    - [x] `char` - https://github.com/dotnet/runtimelab/pull/212
    - [x] `string` - https://github.com/dotnet/runtimelab/pull/249, https://github.com/dotnet/runtimelab/pull/288
    - [x] `Array`
        - [x] - by value in, all by ref, return - https://github.com/dotnet/runtimelab/pull/272
        - [x]  - by value out (e.g., `[Out] Foo[]`) - https://github.com/dotnet/runtimelab/pull/380
    - [x] Experimental - (e.g., `Span<T>` or `ReadOnlySpan<T>`) - https://github.com/dotnet/runtimelab/pull/1222
    - [x] Explicitly handle all [`DllImportAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute) options (support, pass-through, or error).
        - [x] `PreserveSig` - https://github.com/dotnet/runtimelab/pull/323
        - [x] `BestFitMapping`, `ThrowOnUnmappableChar`, and `LCIDConversion` - https://github.com/dotnet/runtimelab/pull/291
        - [x] `SetLastError` - https://github.com/dotnet/runtimelab/pull/360
        - [x] `ExactSpelling`, `EntryPoint`, `CharSet`, `CallingConvention` - Pass through to blittable `DllImport` P/Invoke.
    - Stub performance follow-ups
        - [x] Apply [`SkipLocalInitAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.skiplocalsinitattribute) to stubs - https://github.com/dotnet/runtimelab/pull/377
- Diagnostics:
    - [x] Properly update Roslyn Diagnostics - https://github.com/dotnet/runtimelab/pull/158
    - What are the development mechanisms for diagnosing/debugging issue?
    -  [x] Adorn all generated source with the `// <auto-generated/>` comment. - https://github.com/dotnet/runtimelab/pull/1209
- Testing:
    - [x] Integration testing. - https://github.com/dotnet/runtimelab/pull/149
    - [x] XUnit for Integration testing is the default, but other methods should be possible.
        1. Use test runner in Visual Studio/VSCode to debug and run all tests. - https://github.com/dotnet/runtimelab/pull/149
        1. Run individual test outside of testing harness - `F5` to treat test like an "exe". - [`Demo` project](https://github.com/dotnet/runtimelab/blob/DllImportGenerator/DllImportGenerator/Demo/Program.cs)
    - [x] Leverage [`DNNE`](https://github.com/AaronRobinsonMSFT/DNNE) to avoid native build system support.
    - [x] Performance testing using [`BenchmarkDotNet`](https://github.com/dotnet/BenchmarkDotNet).
        - [x] Test performance against the built-in DllImport stubs - https://github.com/dotnet/runtimelab/pull/538	
        - [x] Create assembly for P/Invoke targets.
        - [x] Create project of tests destined for https://github.com/dotnet/performance.
        - [x] Add `EventSource` events for indicating DllImport source generator begin/end. - https://github.com/dotnet/runtimelab/pull/258
- Deployment logistics
    - [x] [Arcade](https://github.com/dotnet/arcade/) – Integrate with https://github.com/dotnet/runtimelab/pull/238 https://github.com/dotnet/runtimelab/pull/308
    - [x] NuGet - Publish as “Non-shipping” - https://github.com/dotnet/runtimelab/pull/327
    - Analyzer vs Source Generator vs new Attributes
        - [x] Determine where do these go. Moving into dotnet/runtime - see [guidelines](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/project-guidelines.md).
        - [x] Investigate separation for COM generation option. https://github.com/dotnet/runtimelab/pull/1119.
- Porting support
    - [x] `MarshalEx` => `Marshal`. - https://github.com/dotnet/runtimelab/pull/458
    - [x] "Generate Forwarder" configured at runtime instead of a `#define`. - https://github.com/dotnet/runtimelab/pull/458
    - [x] Analyzer/Fixer to help switch from `DllImport` <=> `GeneratedDllImport`.
        - Analyzer: https://github.com/dotnet/runtimelab/pull/367
        - Fixer: https://github.com/dotnet/runtimelab/pull/564 
     
# New .NET APIs

New APIs that will need to be introduced - remember to consider Linker semantics:
- [x] Ability to set the thread-centric error code (e.g., [`SetLastError()`](https://docs.microsoft.com/windows/win32/api/errhandlingapi/nf-errhandlingapi-setlasterror)). https://github.com/dotnet/runtime/issues/46843.
- [x] Instantiation of [`SafeHandle`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.safehandle)s. https://github.com/dotnet/runtime/issues/46830.
- [x] `GeneratedDllImport` attribute and analyzer. https://github.com/dotnet/runtime/issues/46822.
- [x] Struct marshalling attributes and analyzer for usage support. https://github.com/dotnet/runtime/issues/46838.
- [x] Provide mechanism to avoid relying on the [`CallingConvention`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute.callingconvention) enumeration. https://github.com/dotnet/runtime/issues/51156.

All above APIs have inefficient but semantically correct implementations in the [`Ancillary.Interop`](https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator/DllImportGenerator/Ancillary.Interop) project.

Once prototyping has completed the above APIs will go through an official API review in `dotnet/runtime`.

[source_gen_announcement]: https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/

[spec_for_dllimport_source_gen]: https://github.com/dotnet/runtime/tree/master/docs/design/features/source-generator-pinvokes.md

[source_gen_repo]: https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator/DllImportGenerator

**Comment by jkotas** [comment]
Would it make sense to add "Enable evolution of PInvoke marshalling" to the list of goals?

If yes, it would be nice to have "Add one high-value marshaller that does not exist today" to the exit criteria list. My pick would be marshaller for `ReadOnlySpan/Span<T>`. It would simplify quite a bit of code under `src/libraries` in this repo.

**Comment by AaronRobinsonMSFT** [comment]
>Would it make sense to add "Enable evolution of PInvoke marshalling" to the list of goals?

Doh! That was the section I couldn't think of but knew I was missing something - innovation. Yes, that should be added.

**Comment by lambdageek** [comment]
Interesting!

Thanks for the nice example in the design doc. To make sure I followed completely - the runtime will still generate a P/Invoke wrapper, it's just that we're guaranteed to only see blittable types?  @marek-safar this dovetails nicely with the discussion we had about partitioning `marshal.c` to remove fancy marshalling --- on some targets that won't need it --- in order to get the runtime size down.

From the FAQ:
> > Can the above API be used to provide a reverse P/Invoke stub?
> No. Reverse P/Invoke invocation is performed via a delegate and integrating this proposal would prove difficult.

😞 so we can only get rid of half of `marshal-ilgen.c`

**Comment by AaronRobinsonMSFT** [comment]
>the runtime will still generate a P/Invoke wrapper, it's just that we're guaranteed to only see blittable types?

Right. Presently there is a level of indirection between the managed invocation and the native call - typically called an IL Stub. The IL Stub marshals the input types to appropriate blittable types and then makes the native call via `calli`. When an IL Stub isn't needed the CoreCLR JIT optimizes that scenario and inlines the IL Stub and passes the arguments straight through the native function call.

In this model the so IL Stub is generated at compile time and a P/Invoke with all blittable types is created. We leverage the JIT's optimization of inlining P/Invoke calls with all blittable types. This inlining optimization is typically only available on Release builds.

There are several nice things about this approach, but one of the ones I accidentally discovered was that this model permits more inlining in more cases. The following signature `void(int, ref int)` can't be inined with the current approach but in this model can be - yay!

>this dovetails nicely with the discussion we had about partitioning marshal.c to remove fancy marshalling --- on some targets that won't need it --- in order to get the runtime size down.

Nice to hear. CoreCLR has no plans on changing any of the built-in system. This model is interesting and being explored primarily for AOT and innovation possibilities.

>😞 so we can only get rid of half of marshal-ilgen.c

Generating a Reverse P/Invoke stub is actually possible using this methodology in some scenarios - consider callbacks being passed to native - one could imagine a solution there. The other type of Reverse P/Invoke would be the native export of a manage function - this is probably the one being alluded to here. Utilizing the code generation approach it should be possible to extend the [`DNNE`](https://github.com/AaronRobinsonMSFT/DNNE/) project to insert the generated marshalling. That avenue will need to be explored at a later date though.

**Comment by jkotas** [comment]
We should iscourage use of delegates for reverse P/Invoke and encourage use of function pointer instead Maybe the analyzer that comes with this should be emitting warnings for delegate marshaling?

**Comment by AaronRobinsonMSFT** [comment]
>Maybe the analyzer that comes with this should be emitting warnings for delegate marshaling?

@jkoritzinsky We should consider this after we ensure we have symmetry with the current system. Perhaps we could defer creating a Delegate marshaller entirely for now?

**Comment by marek-safar** [comment]
Nice to see this moving forward! A few questions

- I'm not sure I understand "Support >= 80 % of P/Invoke patterns in NetCoreApp" goal? What is NetCoreApp in this context?
- What is the size impact of this change?
- How is it going to work with [DllImport("__Internal")]? /cc @lambdageek
- Is this approach going to respect attributes like MarshalAs ?
- Nit: the label should perhaps be `area-Interop` because it's not CoreCLR specific, right?

@lambdageek I think on platforms we need to cut the size we can rely on the analyzer to block reverse P/Invoke.

**Comment by AaronRobinsonMSFT** [comment]
> I'm not sure I understand "Support >= 80 % of P/Invoke patterns in NetCoreApp" goal? What is NetCoreApp in this context?

`NetCoreApp` is the base framework.

> What is the size impact of this change?

That is mentioned in the exit criteria as something we need to track.

> How is it going to work with [DllImport("__Internal")]? /cc @lambdageek

This should have no impact on that as defined. If this changes to `GeneratedDllImport` then it would probably "just work" since the IL Stub would be source generated and then dispatched to a `[DllImport("__Internal")]` version that contained only blittable types.

> Is this approach going to respect attributes like MarshalAs ?

Yes. This is intended as a drop in replacement for `DllImport` for any signatures contained in the `NetCoreApp` framework. Going forward as we handle more scenarios in the wild some features of `MarshalAs` may not be supported however. None of that is defined, but one can imagine that the `IUnknown` option wouldn't be supported and may never be supported. That is based on community need.

**Comment by AaronRobinsonMSFT** [comment]
> Which is one of our largest current problems, it's not really ideal that marshalling code is rebuilt every keypress.

Great feedback on source generators - @chsienki any thoughts here?

> How will this work regarding being valid C#? will a method be generated, which will be called by the runtime for marshalling (not sure how this would work, since generally there is both setup and cleanup code)?

All generated code is going to be valid C#. The only issue with previous tooling solutions not being able to have pure C# was `calli` and `ldftn` support. Both of those can now be expressed in C# so the entire IL Stub can be generated in C# and based directly to the Roslyn compiler.

**Comment by tannergooding** [comment]
I think, somewhat touching on what @HurricanKai was discussing, there are scenarios where you can't use `DllImport` such as with [vkGetInstanceProcAddr](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetInstanceProcAddr.html) which is used to resolve various optional extensions.

Does this also cover generating wrappers for function pointers? Would it alternatively be possible to allow hooking into export resolution much as we all hooking into library resolution via [NativeLibrary.SetDllImportResolver](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=netcore-3.1#System_Runtime_InteropServices_NativeLibrary_SetDllImportResolver_System_Reflection_Assembly_System_Runtime_InteropServices_DllImportResolver_)?

**Comment by AaronRobinsonMSFT** [comment]
>Does this also cover generating wrappers for function pointers?

This sounds like having the ability to create an IL Stub that can be used outside of `DllImport`? If so that would be the symmetric part of the Reverse P/Invoke scenario I mentioned at https://github.com/dotnet/runtime/issues/43060#issuecomment-703998208. Something to consider for the future but orthogonal to this work to handle the `DllImport` side of things. We are designing the code generation side of this to be agnostic of `DllImport` scenarios - think of it like a marshalling code gen library. A new source generator for these scenarios would be able to reuse the code generator for the marshalling code.

>Would it alternatively be possible to allow hooking into export resolution much as we all hooking into library resolution via NativeLibrary.SetDllImportResolver?

This will continue to work with this current model. We are using the existing model of export discovery so all these callbacks will continue to be respected.

**Comment by Perksey** [comment]
+1 on Tanner's comment - At Silk.NET we have to maintain and swap out different native function tables for each Vulkan instance and device. OpenXR has similar restrictions, not to mention OpenGL's platform-specific loading strategies.

NativeLibrary has helped with this in that we can control what function pointers P/Invoke is fed and we use NativeLibrary where available, but until .NET 6 Silk.NET is restricted to .NET Standard because of mobile support, so we have to manually load in using libdl or kernel32 on non-.NET Core platforms.

Today's challenges is P/Invoke simply doesn't offer the level of freedom advanced scenarios such as these require, where the underlying native function addresses are context-dependent (this is why Silk.NET exposes its native functions through instances instead of static functions) and need to be directly accessed in some cases (a la function pointers)

Massively thankful to Kai for championing SilkTouch and thankful to the C# LDM and Roslyn teams for making SilkTouch possible - our solution before this was a much slower System.Reflection.Emit-based approach (called [SuperInvoke](https://github.com/Ultz/SuperTools) in order to wield calli and do the marshalling we needed.

**Comment by tannergooding** [comment]
> This will continue to work with this current model. We are using the existing model of export discovery so all these callbacks will continue to be respected.

I was asking if it would be possible to expose a hook for resolving a `DllImport` function (as I believe the current API only works for resolving the library). This would allow, for example:

```cs
[DllImport("vulkan", ExactSpelling = true)]
public static extern VkResult vkCreateDebugReportCallbackEXT(IntPtr instance, VkDebugReportCallbackCreateInfoEXT* pCreateInfo, VkAllocationCallbacks* pAllocator, ulong* pCallback);
```

Where `vkCreateDebugReportCallbackEXT` isn't part of the standard library exports (it can't be resolved via `GetProcAddress`) and must be resolved via `vkGetInstanceProcAddr` instead.

This would, for example, allow the general `DllImport` logic to work with the above scenario and would only exclude things like callbacks.

**Comment by jkotas** [comment]
> I was asking if it would be possible to expose a hook for resolving a DllImport function

You can do it using function pointers today. It is a niche case - it was discussed before. I do not think it is worth the complexity.

**Comment by tannergooding** [comment]
Fair enough, that just relegates it to potentially future source generator support around function pointers.

**Comment by AaronRobinsonMSFT** [comment]
>Fair enough, that just relegates it to potentially future source generator support around function pointers.

Yes. That is one of the reasons we will be ensuring a final marshalling code library is `DllImport` agnostic.

**Comment by jkoritzinsky** [comment]
> > Maybe the analyzer that comes with this should be emitting warnings for delegate marshaling?
> 
> @jkoritzinsky We should consider this after we ensure we have symmetry with the current system. Perhaps we could defer creating a Delegate marshaller entirely for now?

Since a very large portion of P/Invokes in Microsoft.NETCore.App use delegate callbacks and we've already added the support for Delegate marshalling, I suggest we keep it, at least for v1 where we're trying to do a drop-in replacement for DllImport.

I wouldn't be against emitting a warning, although I think we should hold off on that until we have some sort of reverse P/Invoke generation.

**Comment by jkotas** [comment]
> Since a very large portion of P/Invokes in Microsoft.NETCore.App use delegate callbacks

FWIW, the number of P/Invokes in Microsoft.NETCore.App use delegate callbacks is relatively small, and I plan to convert majority of them to use function pointers now that we have the Roslyn with the final syntax.

**Comment by benaadams** [comment]
Will this cover the ownership transfer for SafeHandles
```csharp
// Release on failure
using (safeHandle)
{
    if (nativeCall(safeHandle))
    {
        // The handle ownership has been transferred; don't release.
        safeHandle.SetHandleAsInvalid();
    }
}
```
As used in 

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ExportProvider.cs#L67-L76

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslX509ChainProcessor.cs#L471-L476

https://github.com/dotnet/runtime/blob/f93c0e674dcbce57a4cc11bfec47358f6525a2d1/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs#L200-L206

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslX509ChainProcessor.cs#L1153-L1162

https://github.com/dotnet/runtime/blob/f9a8abc8a5d9981e25f898181e734dc77c7e15e4/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CachedSystemStoreProvider.cs#L202-L211

etc

**Comment by jkoritzinsky** [comment]
@benaadams I've taken another look and I believe that a marshaler that handles that case (SafeHandle either transferred ownership or released) would be possible for a developer to write with the source generator's custom marshalling model.

**Comment by GavinRay97** [comment]
Based on this comment:

> Utilizing the code generation approach it should be possible to extend the DNNE project to insert the generated marshalling. That avenue will need to be explored at a later date though.

This would mean that code like this, would be able to be simplified to what look like managed types on the surface, and the marshalling and forced conversion/check for blittability (is this a word? blittableness? 😅) would happen under the hood?

https://gist.github.com/GavinRay97/b3e92ca3245319eb358e4a882ab5c942
