### ISSUE TITLE
Superhost for Windows & Mac

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#43071]
All native runtime libraries should be statically linked into a single file host for Windows & Mac.

- [X] Make `clrjit` and `coreclr` friendlier to static linking on multiple platforms. #43423
- [x] Statically link `clrjit` and `coreclr` into singlefile host #43072 
- [x] Link native libraries in a way that is multiplatform friendly. #41299
- [x] Statically link native libraries on Windows, OSX and other platforms that we test/support. #43699
- [x] Move build of hosts to clr partition. #43700
 (not a requirement but will make things simpler going forward, hard to do though before we do the above)
- [x] Signing on MacOS https://github.com/dotnet/runtime/issues/3671
- [x] Investigate compression of hosts

Partner dependencies:

- [x] Debugging support (WinDbg/lldb)
- [ ] Watson support

**Comment by danmosemsft** [comment]
Making user story so it appears in the tree

**Comment by vitek-karas** [comment]
I added another work item: validate that the superhost we produce (when used in an application) works will with AVs - that is, doesn't get marked as a virus. Apparently this has already been a problem for at least some users: https://www.reddit.com/r/csharp/comments/k9pnn0/net_5_single_file_trim_self_contained_detected_as/ with out relatively small host.

This is mostly Windows-only work item I think.

**Comment by agocke** [comment]
Closing with a tracking issue for the remaining Watson work https://github.com/dotnet/runtime/issues/53832
