### ISSUE TITLE
Developers want to be confident that their apps run successfully when trimmed to avoid debugging trimming related problems at runtime

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#43078]
In 5.0 we introduced linker capability to warn about code and patterns which are not trimming safe. We will build on top of that feature to resolve all warnings in our core SDKs to allow developers to enable this linker capability for their code and 3rd party libraries to give them confidence that trimming does not alter their app behaviour unexpectedly.

We'll also work on further enhancing the warning user experience to give the developers feedback about potential problems in their app as early as possible.

The primary goal for .NET6 is to have all linker related warnings resolved for core SDKs for all workloads which use publish with trimming enabled by default. In particular following workloads

* Blazor Client/WebAssembly
* Mobile iOS/tvOS (Xamarin.iOS)
* Mobile Android (Xamarin.Android)
* macOS UI (Xamarin.Mac)
* Hybrid Blazor (optional)

## Work Items

- [x] Regression test for console app warnings https://github.com/dotnet/sdk/issues/13994
- [x] Linker lazy loading https://github.com/mono/linker/issues/1164
- [x] Support for startup hook feature #36526
- [ ] Add analyzers for all linker warnings
- [x] List and categorize all netcoreapp linker warnings #44035
- [x] Fix warnings in .NET Libraries #45623
- [x] End-to-end experience for "publish feature" analyzers including trimming https://github.com/dotnet/sdk/issues/14562
- [x] Default values for feature switches in trimmed console apps https://github.com/dotnet/sdk/issues/14475
- [x] EventSource linkability
- [x] COM linkability #36659
- [x] Mitigations for DCS #36154
- [x] Mitigations for Xml serializer #41389
- [ ] Trimming tests for all configurations https://github.com/dotnet/runtime/issues/39274

Partner dependencies:
- [x] Roslyn support for suppression using `UnconditionalSuppressAttribute` https://github.com/dotnet/roslyn/issues/48885
- [ ] Roslyn support Flow attributes on generic types to compiler generated constructs https://github.com/dotnet/roslyn/issues/46646

MaciOS

- [ ] https://github.com/xamarin/xamarin-macios/issues/11449
- [ ] https://github.com/xamarin/xamarin-macios/issues/11985
- [ ] https://github.com/xamarin/xamarin-macios/issues/9573
- [ ] https://github.com/xamarin/xamarin-macios/issues/9612

**Comment by danmosemsft** [comment]
@eerhardt this would be the parent story for most of your v-team's work -- any sub work items can be children of this (they will appear in [themes tree](https://themesof.net/?q=is:open%20kinds:teuib)) or at least checkboxes in this or a child issue similar to what we did for Nullability annotations. When you are ready to can you please link such child items, etc so all necessary work is represented here or in its children?

**Comment by eerhardt** [comment]
> at least checkboxes in this or a child issue similar to what we did for Nullability annotations

For the ILLink warnings burndown, I've created https://github.com/dotnet/runtime/issues/45623 (which is linked above). It will be used to check off assemblies as we get them ILLink warning "clean".

**Comment by marek-safar** [comment]
Changed priority to P0 to align with Xamarin needs

**Comment by Tomkaa** [comment]
Is there a plan to make trimming feature available not only for self-contained deployments?

**Comment by marek-safar** [comment]
@Tomkaa what would be the scenario where you would like to use the trimming?

**Comment by Tomkaa** [comment]
@marek-safar For example: I am developing ASP.NET Core application which has some NuGet packages installed and use framework-dependent deployment model.  Some of the assemblies from NuGet are only used as middleware for local debugging. I have these middleware registrations surrounded with `#if DEBUG`, so in `Release` build these assemblies are technically not referenced anywhere, but I still have them in `csproj` so they get copied anyway. Current solution is to surround the `<PackageReference ...>` with `<ItemGroup>` and add `Condition` attribute that includes it only when configuration is `DEBUG`.  However I think it would be great quality of life improvement if these could be trimmed automatically, even for framework dependent deployment.

**Comment by eerhardt** [comment]
@agocke - do you think this issue can now be closed? The only issue under "Work Items" that is still open is #39274. We can track adding other platforms in that issue.

**Comment by agocke** [comment]
Yup, I think this is ready to close.
