### ISSUE TITLE
Stabilize performance measurement

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#43227]
The code quality and performance of RyuJIT is tracked internally by running [MicroBenchmarks](https://github.com/dotnet/performance/tree/master/src/benchmarks/micro) in our performance lab.  We regularly triage the [performance issues](https://github.com/dotnet/runtime/issues?q=%22%5BPerf%22+in%3Atitle+author%3ADrewScoggins) opened by the .NET performance team. After going through these issues for past several months, we have identified some key points.

### Stability
Many times, the set of commits that are flagged as introducing regression in a benchmark, do not touch the code that is tested in the benchmark. In fact, the assembly code generated for the .NET code that is being tested is often identical and yet the measurements show differences. Some of our investigation reveals that the fluctuation in the benchmark measurements happen because of the misalignment of generated JIT code in process memory. Below is an example of [LoopReturn](https://github.com/dotnet/performance/blob/8aed638c9ee65c034fe0cca4ea2bdc3a68d2a6b5/src/benchmarks/micro/runtime/Layout/SearchLoops.cs#L30) benchmark that shows such behavior. 

![image](https://user-images.githubusercontent.com/12488060/95612182-cf194f00-0a17-11eb-84fe-cd6831006501.png)

It is very time consuming for .NET developers to do the analysis of benchmarks that regressed because of things that are out of control of .NET runtime. In the past, we have closed several issues like https://github.com/dotnet/runtime/issues/13770, https://github.com/dotnet/runtime/issues/39721 and https://github.com/dotnet/runtime/issues/39722 because they were regressions because of code alignment. A great example that we found out while investigating those issues was the change introduced in https://github.com/dotnet/runtime/pull/38586 eliminated a `test` instruction and should have showed improvement in the benchmarks, but introduced regression because the code (loop code inside method) now gets misaligned and the method runs slower.

Alignment issues was brought up few times in https://github.com/dotnet/runtime/issues/9912 and https://github.com/dotnet/runtime/issues/8108 and this issue tracks the progress towards the goal of stabilizing and possibly improving the performance of .NET apps that are heavily affected because of code alignment.

### Performance lab infrastructure
Once we address the code alignment issue, the next big thing will be to identify and make required infrastructure changes in our performance lab to make sure that it can easily flag such issues without needing much interaction from .NET developers. For example, https://github.com/dotnet/BenchmarkDotNet/issues/1513 proposes to make memory alignment in the benchmark run random to catch these issues early and once we address the underlying problem in .NET, we should never see bimodal behavior of those benchmarks. After that, if the performance lab does find a regression in the benchmark, we need to have robust tooling support to get possible metrics from performance runs so that a developer doing the investigation can easily identify the cause of regression. For example, identifying the time spent in various phases of .NET runtime like Jitting, Jit interface, Tier0/Tier1 JIT code, hot methods, instructions retired during benchmark execution and so forth.

### Reliable benchmarks collection
Lastly, for developers working on JIT, we want to identify set of benchmarks that are stable enough and can be trusted to give us reliable measurement whenever there is a need to verify the performance for changes done to the JIT codebase. This will help us conduct performance testing ahead of time and identify potential regressions rather than waiting it to happen in performance lab.

Here are set of work items that we have identified to achieve all the above:

### Code alignment work
* [x] Make method entries of JIT code having loops aligned at 32-byte boundary for xarch. This is done in https://github.com/dotnet/runtime/pull/42909.
* [ ] Make method entries of JIT code having loops aligned at relevant boundary for arm32/arm64.
* [ ] Devise a mechanism to identify inner loops (the ones that don't have more loops inside) present in a method.
* [ ] Experiment with heuristics that should decide if a particular inner loop needs alignment or not.
* [ ] Calculate the padding that needs to be added to align the identified inner loop.
* [ ] Basic: Add the padding near the loop header (either at the end of previous block or at the beginning of the loop header).
* [ ] Advanced: If padding proves to be costly, have a way to spread the padding throughout the method so the loop header gets aligned. Account the padding while doing branch tensioning.
* [ ] Identify benchmarks that get stabilized or whose performance is improved by the above work.

### Performance tooling work
* [ ] Add random memory alignment. Tracked by https://github.com/dotnet/BenchmarkDotNet/issues/1513
* [ ] Add various tooling in PerfView, BenchmarkDotNet analyzers to add the required metric.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib , @danmosemsft

**Comment by danmosemsft** [comment]
cc @DrewScoggins @billwert @adamsitnik

**Comment by danmosemsft** [comment]
To state the obvious (I think) -- I believe we have good data to suggest that alignment is the dominant reason for bimodality. I'm not sure though that we can be sure there aren't other common causes for bimodality -- my assumption is that we'll find out how much is left when you've completed some of this work.

**Comment by kunalspathak** [comment]
> To state the obvious (I think) -- I believe we have good data to suggest that alignment is the dominant reason for bimodality. I'm not sure though that we can be sure there aren't other common causes for bimodality -- my assumption is that we'll find out how much is left when you've completed some of this work.

Yes, there will definitely be more reason for bimodality, but alignment will fix most of the obvious ones that we know of and then, it will be easier for us to focus one remaining ones. Currently, there are just [too many bimodal benchmarks](https://github.com/drewScoggins/performance-2/issues?q=is%3Aopen+is%3Aissue+label%3ABimodal).

**Comment by JulieLeeMSFT** [comment]
Bolded WIP texts in the plan.

**Comment by kunalspathak** [comment]
With the #44370, we will start aligning inner loops at 32B boundary with padding up to 16 bytes. 

The code size impact on .NET libraries (from pmi runs)

```
Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 51622033
Total bytes of diff: 51639087
Total bytes of delta: 17054 (0.03% of base)
    diff is a regression.

```

```
Summary of Allocation Size diffs:
(Lower is better)

Total bytes of base: 51940550
Total bytes of diff: 51957619
Total bytes of delta: 17069 (0.03% of base)
    diff is a regression.
```

Details : https://github.com/dotnet/runtime/pull/44370#issuecomment-749263096

Out of 380K+ methods of .NET libraries (using PMI), based on loop alignment heuristics, we will align 1766 loops in 1515 methods. Details: https://github.com/dotnet/runtime/pull/44370#issuecomment-758133875

**Comment by danmosemsft** [comment]
@DrewScoggins it will be interesting to see whether you start seeing less noise tomorrow.

**Comment by kunalspathak** [comment]
Below is weekly comparison:

Linux x64:

![image](https://user-images.githubusercontent.com/12488060/105545987-9c871f80-5cb1-11eb-97f5-f44a3af74756.png)

https://pvscmdupload.blob.core.windows.net/reports/01_18_2021/report_Weekly_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=tiered-RunKind=micro_2021-01-18.html#Improvements

Windows x64:

![image](https://user-images.githubusercontent.com/12488060/105546016-a872e180-5cb1-11eb-9570-01ce05bf2513.png)

https://pvscmdupload.blob.core.windows.net/reports/01_18_2021/report_Weekly_ca=x64_cb=refs-heads-master_co=Windows1018362_cr=dotnetruntime_cc=CompliationMode=tiered-RunKind=micro_2021-01-18.html

Windows x86:

![image](https://user-images.githubusercontent.com/12488060/105546589-6bf3b580-5cb2-11eb-96cd-019a55edbfb7.png)


https://pvscmdupload.blob.core.windows.net/reports/01_18_2021/report_Weekly_ca=x86_cb=refs-heads-master_co=Windows1018362_cr=dotnetruntime_cc=CompliationMode=tiered-RunKind=micro_2021-01-18.html

Some of the improvements about comes from @stephentoub 's  https://github.com/dotnet/runtime/pull/46895. But, the next thing I will do is analyze the regressions.

**Comment by adamsitnik** [comment]
@kunalspathak from the reports that you have provided, the following benchmarks look fishy to me:

```log
# Linux x64
System.Memory.Span<Int32>.SequenceEqual(Size: 512)
System.Memory.Span<Int32>.EndsWith(Size: 512)
Span.IndexerBench.KnownSizeCtor2(length: 1024)
System.Memory.Span<Byte>.SequenceEqual(Size: 512)
System.MathBenchmarks.Single.Max // this can be a benchmark regression, but not actual product code regression
Benchstone.BenchI.LogicArray.Test
# Windows x64
System.Text.Json.Tests.Utf8JsonReaderCommentsTests.Utf8JsonReaderCommentParsing(CommentHandling: Skip, SegmentSize: 0, TestCase: LongMultiLine)
System.Collections.ContainsFalse<String>.ICollection(Size: 512)  // this can be a benchmark regression, but not actual product code regression
# Windows x86
System.Collections.ContainsKeyFalse<String, String>.Dictionary(Size: 512)
PerfLabTests.CastingPerf.CheckObjIsInterfaceYes // this can be a benchmark regression, but not actual product code regression
PerfLabTests.CastingPerf.CheckIsInstAnyIsInterfaceNo // this can be a benchmark regression, but not actual product code regression
PerfLabTests.CastingPerf.CheckObjIsInterfaceNo // this can be a benchmark regression, but not actual product code regression
```

but there is much more improvements than regressions!

**Comment by danmosemsft** [comment]
It's interesting that some of the regressing scenarios have also started becoming noisy eg [System.MathBenchmarks.Single.Max](https://pvscmdupload.blob.core.windows.net/reports/01_18_2021/report_Weekly_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=tiered-RunKind=micro_2021-01-18.html#Improvements)

**Comment by kunalspathak** [comment]
Thanks @adamsitnik . Could you please explain the data point that makes you think "this can be a benchmark regression, but not actual product code regression". It will help me in quicker investigation for these benchmarks on my part. Here is couple of benchmarks that investigated yesterday:

### System.Text.Json.Tests.Utf8JsonReaderCommentsTests.Utf8JsonReaderCommentParsing(CommentHandling: Skip, SegmentSize: 0, TestCase: LongMultiLine)


This looks like a real regression because of the execution of `align` instruction inside `JsonReaderHelper::CountNewLines`.
![image](https://user-images.githubusercontent.com/12488060/105876341-bd9e8780-5fb3-11eb-99f3-4f28d26b38a9.png)

It was improved in November after https://github.com/dotnet/runtime/pull/42909 change, but with loop alignment changes, it went into higher end. 
In below screenshot:
1. is the method alignment change
2. is the loop alignment change.

![image](https://user-images.githubusercontent.com/12488060/105876416-d018c100-5fb3-11eb-9ff9-6ab78ccfbb31.png)

From Vtune:

![image](https://user-images.githubusercontent.com/12488060/105876510-e6268180-5fb3-11eb-8eff-528ce73f7ae0.png)

I am not sure how much vtune points to the `nop` execution contribution, but my guess is that it contributes to the slowness, given that `CountNewLines` is the hottest method.

![image](https://user-images.githubusercontent.com/12488060/105876862-37cf0c00-5fb4-11eb-8b6b-25df632c2604.png)

### System.Collections.ContainsFalse<String>.ICollection(Size: 512) 

I was not able to reproduce this on my machine. I also compared the disassembly and we don't add `align` instruction in the benchmark code or methods that we are testing. My initial guess is that it could be because of data alignment since we allocate array during setup. 

Here is the history of that test which confirms the bimodality.

![image](https://user-images.githubusercontent.com/12488060/105877328-b5931780-5fb4-11eb-8ae7-2e80fa25a434.png)

If there was any code alignment issue (which I will dig more later today), the loop alignment would have addressed it and the benchmark went to the slower numbers, but data alignment in future runs might change it and we might again see the bimodality. 

![image](https://user-images.githubusercontent.com/12488060/105877393-cba0d800-5fb4-11eb-84d5-ea37cf5f0d5b.png)

@danmosemsft - Thanks for pointing it out. Even we noticed it and it is interesting because it shouldn't be affected by the data alignment. I will investigate further.

**Comment by adamsitnik** [comment]
> Could you please explain the data point that makes you think "this can be a benchmark regression, but not actual product code regression"

Sure! Some of these benchmarks have loops inside them (while they [should not](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#Loops)) like the [casting benchmark](https://github.com/dotnet/performance/blob/4e14ecc54759224121b807c70e46fb1d9ee0e7d6/src/benchmarks/micro/runtime/perflab/CastingPerf.cs#L309-L316):

```cs
[Benchmark]
public bool CheckObjIsInterfaceYes()
{
    bool res = false;
    for (int i = 0; i < InnerIterationCount; i++)
        res = myClass1 is IMyInterface1;
    return res;
}
```
By "this can be a benchmark regression, but not actual product code regression" I meant that the part of the product that the benchmark is trying to measure has not regressed (casting in this example), but it's exercised in a loop, which shows benchmark regression.

**Comment by kunalspathak** [comment]
> Some of these benchmarks have loops inside them (while they should not)

Do we have plan to fix them?

Also, we noticed the following numbers for bubblesort2. The benchmark is less bimodal after loop alignment, but the remaining swing might be because of data alignment since we create an array inside the benchmark.

https://github.com/dotnet/performance/blob/a25a963e3f14214102207a2b75a5ece25162a333/src/benchmarks/micro/runtime/Benchstones/BenchI/BubbleSort2.cs#L32

Here is the overall history:

![image](https://user-images.githubusercontent.com/12488060/105897439-031b7e80-5fcd-11eb-8543-3c321b35e863.png)

and then zoomed in to the loop alignment impact:

![image](https://user-images.githubusercontent.com/12488060/105897506-1c242f80-5fcd-11eb-8daa-c0c262c3a851.png)

**Comment by kunalspathak** [comment]
I went through most of the regressions in https://github.com/dotnet/runtime/issues/43227#issuecomment-765684981 and here is my analysis.

## Summary

-  As @adamsitnik pointed out, many benchmark code contains loop and the improvement/regression were mostly because those loops got aligned. The disassembly of library method that was being tested was identical (with some exceptions, see below). Best example of this is `MathBenchmark.Single.Max`. @danmosemsft .

- There were benchmarks that are heavily impacted by data alignment because of allocation happening in benchmark code itself. Most of the array benchmarks fall in this category. So the stability might have not impacted because of loop alignment or in certain cases, the numbers were more stable than before, but the additional bimodality is because of data alignment. E.g. Bubble sort (see below).

- For x86, we should improve the encoding we use for multiple size `NOP` instructions. Today, we just output [repeated single byte](https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/emitxarch.cpp#L9265-L9269) `90` , but could do better like we do for x64. 

- Lastly, there are places that I have noticed, where we emit "align" instruction in blocks that are expensive. We should find a way to instead put it either after "jmp" or "ret" instruction that comes before the "align" instruction (so the `NOP` are never fetched by the decoder and decoded) or add them in one of the preceding blocks that has lower weight. We already have a work item "Advanced padding" to do the part of squeezing pads after `jmp` or `ret` (wherever possible), but sometimes we might not find such instructions that provides blind spot to insert `align` instruction. In such case, we should do best effort to insert `align` in a block that has lower weight than the one that precedes immediately the loop block. Most prominent reason to do this work is because currently many hot SpanHelper APIs like `IndexOf`, `IndexOfAny`, `Contains` and `SequenceCompare`  include `align` instruction that is greater than 4 bytes. Placing the `align` instruction appropriately should hopefully improve these methods.

To conclude, I did not see any surprises in my analysis and we would expect these results from loop alignment. I am working with @DrewScoggins  to get similar report on how much stability did "loop alignment" improved.

## Benchmark's analysis

### CastingPerf2.CastingPerf.ObjO

We do not do any loop alignment in benchmark code because the loop has calls. Historically, the test is very flaky.

![image](https://user-images.githubusercontent.com/12488060/105931391-f5332100-5fff-11eb-9dbf-34a21b4b5c0e.png)


### KnownSizeCtor2

I am not sure why the benchmark calls into [a test method that contains the actual benchmark code](https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/runtime/Span/Indexer.cs#L326-L347). But @adamsitnik  is right about this benchmark. We add 4 bytes of NOP compensation during the prolog and then 4 bytes of alignment before the 2nd loop, but then, none of the alignment happens for the actual library code (`new Span()`) that the benchmark is testing. So the regression might be from the extra 8 bytes of NOP/align instruction, but it shouldn't affect the library code. Perhaps, we should change this benchmark to not have loop and just have benchmark code in the method that is annotated with `[Benchmark]`.

### JsonNet_

These might be real regression, although from Vtune profiling, it was not that obvious. However, key observation was that we added `align` instruction in some of the hot libraries methods and by doing "advanced padding", we will be able to get back some of the regressions. For instance, in assembly code for [SpanHelpers.Contains()](https://source.dot.net/#System.Private.CoreLib/SpanHelpers.T.cs,48), we added `align` instruction in a block that had weight of 4 although there were colder blocks before it where we could have added this `align` instruction.


<details>
<summary>SpanHelpers.Contains assembly code</summary>

```asm
; Assembly listing for method System.SpanHelpers:Contains(byref,ushort,int):bool
; Emitting BLENDED_CODE for generic X86 CPU - Windows
;
; Lcl frame size = 40

G_M35514_IG01:              ;; offset=0000H
       55           push     ebp
       8BEC         mov      ebp, esp
       57           push     edi
       56           push     esi
       53           push     ebx
       83EC28       sub      esp, 40
       C5F877       vzeroupper 
       33C0         xor      eax, eax
       8945F0       mov      dword ptr [ebp-10H], eax
       8BD9         mov      ebx, ecx
       8BFA         mov      edi, edx
       8B7508       mov      esi, dword ptr [ebp+08H]
						;; bbWeight=1    PerfScore 8.25
G_M35514_IG02:              ;; offset=0018H
       8BCE         mov      ecx, esi
       F7D1         not      ecx
       C1E91F       shr      ecx, 31
       8B153820A306 mov      edx, gword ptr [06A32038H]      ''
       85C9         test     ecx, ecx
       7507         jne      SHORT G_M35514_IG04
						;; bbWeight=1    PerfScore 5.75
G_M35514_IG03:              ;; offset=0029H
       8BCA         mov      ecx, edx
       E858598CF8   call     System.Diagnostics.Debug:Fail(System.String,System.String)
						;; bbWeight=0.25 PerfScore 0.31
G_M35514_IG04:              ;; offset=0030H
       895DF0       mov      bword ptr [ebp-10H], ebx
       8D0473       lea      eax, [ebx+2*esi]
       83FE20       cmp      esi, 32
       7C55         jl       SHORT G_M35514_IG07
						;; bbWeight=1    PerfScore 2.75
G_M35514_IG05:              ;; offset=003BH
       8BCB         mov      ecx, ebx
       83E11F       and      ecx, 31
       8BD1         mov      edx, ecx
       C1EA1F       shr      edx, 31
       03CA         add      ecx, edx
       D1F9         sar      ecx, 1
       8BF1         mov      esi, ecx
       F7DE         neg      esi
       83C610       add      esi, 16
       83E60F       and      esi, 15
       83FE04       cmp      esi, 4
       7C3D         jl       SHORT G_M35514_IG08
						;; bbWeight=0.50 PerfScore 2.88
G_M35514_IG06:              ;; offset=0058H
       83C6FC       add      esi, -4
       0FB7D7       movzx    edx, di
       0FB70B       movzx    ecx, word  ptr [ebx]
       3BD1         cmp      edx, ecx
       0F84FE000000 je       G_M35514_IG17
       0FB74B02     movzx    ecx, word  ptr [ebx+2]
       3BD1         cmp      edx, ecx
       0F84F2000000 je       G_M35514_IG17
       0FB74B04     movzx    ecx, word  ptr [ebx+4]
       3BD1         cmp      edx, ecx
       0F84E6000000 je       G_M35514_IG17
       0FB74B06     movzx    ecx, word  ptr [ebx+6]
       3BD1         cmp      edx, ecx
       0F84DA000000 je       G_M35514_IG17
       83C308       add      ebx, 8
						;; bbWeight=2    PerfScore 27.50
G_M35514_IG07:              ;; offset=0090H
       83FE04       cmp      esi, 4
       7DC3         jge      SHORT G_M35514_IG06
						;; bbWeight=16    PerfScore 20.00
G_M35514_IG08:              ;; offset=0095H
       85F6         test     esi, esi
       7E20         jle      SHORT G_M35514_IG10
       0FB7D7       movzx    edx, di
       90909090     align    
						;; bbWeight=4    PerfScore 7.00

```
</details>

For this particular benchmark, I gathered all the `align` instruction we added in various methods that were JITted during the execution of the benchmark. Note that, some of them might not be contributing to the benchmark measurement.

| Method Name                                                                                                 | Align bytes | Block weight |
|-------------------------------------------------------------------------------------------------------------|-------------|--------------|
| System.SpanHelpers:SequenceCompareTo(byref,int,byref,int):int                                               | 4           | 0.5          |
| System.SpanHelpers:IndexOfAny(byref,ushort,ushort,ushort,int):int                                           | 3           | 0.5          |
| System.SpanHelpers:Contains(byref,ushort,int):bool                                                          | 4           | 4            |
| Newtonsoft.Json.DefaultJsonNameTable:Add(System.String):System.String:this                                  | 7           | 0.5          |
| System.SpanHelpers:IndexOf(byref,ubyte,int):int                                                             | 5           | 2            |
| Newtonsoft.Json.Utilities.JavaScriptUtils:ShouldEscapeJavaScriptString(System.String,System.Boolean[]):bool | 3           | 0.5          |
| System.SpanHelpers:IndexOfAny(byref,ushort,ushort,int):int                                                  | 12          | 0.5          |
| Newtonsoft.Json.DefaultJsonNameTable:Add(System.String):System.String:this                                  | 7           | 0.5          |

### CheckObjIsInterfaceYes

This one was little surprising as the benchmark is straightforward. We do not align the loop inside benchmark because of the presence of call. So I am not sure why it would regress.

```cs
public bool CheckObjIsInterfaceYes()
{
    bool res = false;
    for (int i = 0; i < InnerIterationCount; i++)
        res = myfoo is IFoo;
    return res;
}
```

### Single.Max

Like previous one, this too has a loop and as @adamsitnik  pointed, although the benchmark regresses, the product code doesn't. In this benchmark, we disable VEX prefix encoding optimization for 2 instructions that are part of benchmark code. Then we add `1 byte` align instruction. So the regression is coming from it.

![image](https://user-images.githubusercontent.com/12488060/105933145-ce2a1e80-6002-11eb-9bab-c291cb9721b1.png)

![image](https://user-images.githubusercontent.com/12488060/105933155-cff3e200-6002-11eb-9dc2-e4d486c25fdf.png)

### LogicArray

As I mentioned earlier, this is a typical array benchmark that contains allocation (and hence data alignment issues). In this benchmark, we align the inner loop, but there is an enclosing loop that would process the added padding for alignment.

![image](https://user-images.githubusercontent.com/12488060/105933280-016cad80-6003-11eb-9784-4dce54f13055.png)

![image](https://user-images.githubusercontent.com/12488060/105933287-03367100-6003-11eb-9a65-7a57bbf50ded.png)


### HeapSort

Here too, we "align" inner loop, but those padding instructions get executed by the outer loop and might have seen regression. 

![image](https://user-images.githubusercontent.com/12488060/105933447-455fb280-6003-11eb-81f6-d49c315ce646.png)

![image](https://user-images.githubusercontent.com/12488060/105933452-47297600-6003-11eb-9297-29935a427ac7.png)


### BenchJagged

We should just delete this benchmark or trim it. This does array allocation inside benchmark code and the measurements can be prone to GC behavior, data alignment, etc. I didn't deep dive into this one looking at the historical data of it.

![image](https://user-images.githubusercontent.com/12488060/105933380-2a8d3e00-6003-11eb-9d7d-8ab740762028.png)

### Bubble sort

This one too has data alignment, but after fixing the code alignment, we see less swing of measurements.

![image](https://user-images.githubusercontent.com/12488060/105933574-8a83e480-6003-11eb-92ba-195fc2defbab.png)


Thanks to @adamsitnik  for helping me do faster analysis by pointing at the presence of loop inside benchmark code.

**Comment by danmosemsft** [comment]
Nice analysis @kunalspathak. There were 2 or 3 todo's in your summary above, do they need issues, and listing in the tracking list at the top of this issue? I am happy to see this continuing progress.

As an aside, is there more than BDN can do to help regularize data alignment, when the buffer is allocated by the test and reused? Presumably by doing some tricks with padding in a struct and some unsafe code one can organize an array to have a certain alignment. Maybe BDN could handle such ugly tricks and expose an API for a test to allocate an array nicely aligned. @adamsitnik

**Comment by kunalspathak** [comment]
Another benchmark that I would like to highlight the impact on stability and performance is `LoopReturn`:

Ubuntu x64

![image](https://user-images.githubusercontent.com/12488060/106020775-f3f20a80-6078-11eb-9a7d-07c8524f2d46.png)

Source: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmaster_x64_ubuntu%2018.04%2fLayout.SearchLoops.LoopReturn.html


Windows x64

![image](https://user-images.githubusercontent.com/12488060/106020704-e76db200-6078-11eb-984e-d6de18c340f3.png)

Source: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmaster_x64_Windows%2010.0.18362%2fLayout.SearchLoops.LoopReturn.html

**Comment by kunalspathak** [comment]
> There were 2 or 3 todo's in your summary above, do they need issues, and listing in the tracking list at the top of this issue?

Some of them were tracked in this issue's description. I have updated it to include my other findings.

**Comment by danmosemsft** [comment]
> As an aside, is there more than BDN can do to help regularize data alignment, when the buffer is allocated by the test and reused?

Never mind, I forgot about https://github.com/dotnet/performance/pull/1587 etc. we're attacking both sides. 😊

**Comment by kunalspathak** [comment]
Another round of analysis. 

## Stability

I went through the stability data for [windows x64](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_Windows%2010.0.18362/AllTestindex.html) and [linux x64](https://pvscmdupload.blob.core.windows.net/reports/01_18_2021/report_Weekly_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=tiered-RunKind=micro_2021-01-18.html#Improvements) that @DrewScoggins  shared with me. In this report, "regression" means that loop alignment introduced more variance to the measurements and thus made the benchmark instable, while "improvements" meant that the loop alignment work actually stabilized the benchmark and reduced the variance. I analyzed around 150 benchmarks to see if the regressions were real by checking at the historical data of [Windows x64](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_Windows%2010.0.18362/AllTestindex.html) and [Linux x64](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu%2018.04/AllTestindex.html) for each of the 150 benchmark. If I see that the benchmark had lot of variance historically, I concluded that the loop alignment didn't added to the variance. There were few exceptions like `Perf_Enumerable.Count` and `Single.Max` where post-loop alignment we saw some variance, but other than that, most of the regression pointed out in report were not related to the loop alignment work.

## Performance

Here are some of the take away points:
- JIT maintains a loop table to track all the loops it has seen and use it to perform various optimizations and analysis. It turns out that there is a bug (or a missing feature, whatever you call) where we do not record the cloned loop inside loop table. With that, we miss out opportunities to do the required analysis on cloned loops. Tracking issue: https://github.com/dotnet/runtime/issues/43713

- We sometimes add "NOP compensation" for the over-estimated instruction. Most of the over-estimated instructions are jumps and that that happens because branch tightening happens before loop alignment adjustment phase. In branch tightening we adjust the size of jump instructions depending on the target offset, but later, the loop alignment adjustment can further shorten the IG offsets resulting in over-estimated jump instruction. To address this, we need to combine branch tightening and loop alignment adjustment in same phase rather than separating them. I have updated the work item list to capture this explicitly. After doing this, we might further think about adding the compensation behind `jmp` or in cold block.

- Often the encoding of jump instruction before vs. after loop alignment might increase because of added padding instructions. I do not think we can do much about it.

### FannkuchRedux_9

![image](https://user-images.githubusercontent.com/12488060/106822899-dacafa00-6634-11eb-8cb1-b04ddde9263f.png)

The regression happens because of extra padding we added to align some of the loops inside benchmark code. Asmdiffs: https://www.diffchecker.com/ryZqqO6I. 


### MulMatrix

![image](https://user-images.githubusercontent.com/12488060/106822997-0a7a0200-6635-11eb-8ba8-ef14f24e69b5.png)

The regression happens because of addition of 5 "NOP overestimate compensation" in hot blocks. The overestimation happened for jump instructions. The way to address is by combining branch tightening with loop alignment adjustments (already planned work). Asmdiffs: https://www.diffchecker.com/IcktyNPi


### TryGetUInt16:

![image](https://user-images.githubusercontent.com/12488060/106823269-7b211e80-6635-11eb-8b4b-ac6e37c361bb.png)

In this method, `TryParseUInt16D()` is the hot method as seen from VTune screenshot:

![image](https://user-images.githubusercontent.com/12488060/106823363-a9066300-6635-11eb-9af3-66c59035bc18.png)
![image](https://user-images.githubusercontent.com/12488060/106823367-ab68bd00-6635-11eb-91c3-7d0d4d80a5ac.png)

With loop alignment, we ended up adding padding at the end of hot block that VTune pointed above (Block 2). 
Asmdiffs: https://www.diffchecker.com/jHt5pv99

### GetTypeCode

![image](https://user-images.githubusercontent.com/12488060/106823797-62fdcf00-6636-11eb-88f6-c1158cdf8cd8.png)

Although this shows regression, I verified that there is no loop inside the benchmark, nor a loop in the libraries method that it test. Further, I also compared the asm diffs and there is no "align" instruction.

### ContainsTrue/ContainsFalse


![image](https://user-images.githubusercontent.com/12488060/106800888-e529cb80-6615-11eb-82d1-d6c35d93cbd8.png)

![image](https://user-images.githubusercontent.com/12488060/106800925-f07cf700-6615-11eb-8363-9f4d4bf541d3.png)

![image](https://user-images.githubusercontent.com/12488060/106800954-fb378c00-6615-11eb-9ae1-cbd1e33a749d.png)

This one is interesting. The hot method for all these benchmarks is [GenericEqualityComparer`1[__Canon][System.__Canon]:IndexOf](https://source.dot.net/#System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.CoreCLR.cs,19). In this method, we clone a loop, but later decide to not align it because it had call. However, we do not record that fact in the cloned loop because of which we have to align the cloned loop containing call. Additionally, until we emit the padding in the cloned loop, we have to also compensate the over-estimated instructions. One of the place where such overestimated instruction is compensated happen to be the actual hot loop that the method executes. You can see my detail analysis in https://github.com/dotnet/runtime/issues/43713#issuecomment-772781240.

**Comment by JulieLeeMSFT** [comment]
Good analysis that loop alignment work didn’t introduce regression.

What is cloned loop in the loop table?

Thanks,
Julie
________________________________

**Comment by kunalspathak** [comment]
> What is cloned loop in the loop table? Thanks, Julie

Sometimes, if a loop has checks like array's bound check, we will clone a loop. One variant of the loop will have no bound checks (and hence will be fast loop) while other variant will have bound checks (and will be a slow loop). Depending on the input, we decide whether to execute fast loop or the cloned (slow) loop. You can see an example [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAZgAJiAmcgYXIG8BYAKHPcoEYlKVyBZTgAoAlgDsMAbQC65ADYwAZhjTlxU2VBEBzABYYAlKw6NjJjoujlREteQC85AAwBuOwB5yAVjciA1H5GbObszMEhJgrKkiKyjpwuZhEcWnpSsQ7kCUnmAL45ueSsuUA===). Here, fast loop is `L003e ~ L0058` while cloned slow loop is `L005c ~ L0080`. During JIT, we track all the loops in a data structure called `optLoopTable`. Whenever we want to do any analysis on loops, we iterate over this table to decide whether the given loop needs any update/optimization. When we clone a loop, we do not inserted an entry of cloned loop inside `optLoopTable` because of which further analysis doesn't happen on cloned loop. Towards the end of my comment in https://github.com/dotnet/runtime/issues/43713#issuecomment-772781240, I have listed what type of analysis we miss out on cloned loop because of lack of recording its entry inside `optLoopTable`.

**Comment by JulieLeeMSFT** [comment]
Moved future since .NET 6 scope items are complete now.

**Comment by MithrilMan** [comment]
I read your article here about loop alignment here <https://devblogs.microsoft.com/dotnet/loop-alignment-in-net-6/> and it mentions that a loop like this
```
for (int l = 0; l < M; l++) {
        // body
        OtherMethod();
    }
```
isn't a candidate for inlining because contains a call to a method
What about methods that are inlined?
Shouldn't inline method be considered like loop body and be eligible for alignment if their body is small enough?

**Comment by kunalspathak** [comment]
> What about methods that are inlined?

Inlining decision happens in early phase of compilation and when we decide whether to align a loop or not, we already know that it was inlined or not. We won't align the loop if we know for sure that the method will not be inlined.
