### ISSUE TITLE
[LSRA][RyuJIT] Tune register selection heuristics

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#43318]
The current register allocation selection heuristics are less than optimal. At the very least, they result in poor selection in the face of heavy register pressure, as seen in #8846, and more broadly described in #6824.

The plan for addressing this is:
- [x] Merge the methods that allocate registers from the free and busy sets and refactor to make it easier to reason about and reconfigure the criteria (#9399, in progress). This must be done with minimal impact on throughput, and the initial implementation should preserve existing behavior (i.e. zero diffs) to allow distinguishing impacts of changing heuristics from the changes to the underlying implementation of them. Done in https://github.com/dotnet/runtime/pull/45135
- [x] Refactor the code so that heuristics can be applied in different and dynamic order. Done in https://github.com/dotnet/runtime/pull/52832
- [x] For experimentation purpose, expose `COMPlus_` variable(s) that will change the order in which heuristics will be applied. Done in https://github.com/dotnet/runtime/pull/52832
- [ ] Experiment with various ordering and gather data from Superpmi / PerfScore to determine which ordering is beneficial or which heuristics should stay closer to each other.  (**Experiments done. TODO: In .NET 6, write a report on findings and outcome**)
- [x] Design a mechanism for specifying alternate heuristic configurations (weights or ordering) via one or more `COMPlus` variables. Done in https://github.com/dotnet/runtime/pull/52832
- [x] Extract/refactor the heuristic analysis in such a way that the fast-path (existing heuristic) remains fast, but an alternative config-specified path is available. Done in  https://github.com/dotnet/runtime/pull/52832
- [x] Modify the fast path to reflect the auto-tuning best result. This should include short-circuiting the analysis, or otherwise unnecessarily evaluating the criteria for registers already known to be less desirable (#6705)

## Future work
- [ ] Design and implement an auto-tuning framework, e.g. using SuperPMI with PerfScore as the objective metric. (Opened https://github.com/dotnet/runtime/issues/55374 to track the progress in Future release).
- [ ] Do some initial tuning of the heuristics, minimally addressing #8846.

Additional issues that should be considered and/or addressed: #7999 (heuristics for incoming parameters), #7996 (include encoding size in heuristics, beyond `REG_VAR_ORDER`)

General register allocation issues that should be analyzed to determine if tuning the heuristics will address them: 
- [x] #7809
- [x] #7447

category:cq
theme:register-allocator
skill-level:expert
cost:large

**Comment by kunalspathak** [comment]
Closing this as there are no more work items to be done in .NET 6.
