### ISSUE TITLE
Single-file everything

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#43331]
As of .NET 5 only applications are support in single-file publish. Components (plugins, or similar) can only be published as multiple files. This can be cumbersome for even small plugins with just a few files, but it can be rather problematic for either large components or when we actually implement self-contained components which would include 100s of files.

* [ ] Single-file managed plugins - `AssemblyDependencyResolver` - like support
* [ ] Single-file components loaded via native hosting APIs
  * [ ] Added bonus - single-file self-contained components
* [ ] Single-file applications loaded via native hosting APIs - currently native hosting APIs don't work on single-file applications. 
  * [ ] Single-file FDD app - this should be doable
  * [ ] Single-file SCD app - this is potentially problematic, probably a non-goal
* [ ] Single-file libraries with native binary exports - either [DNNE](https://github.com/AaronRobinsonMSFT/DNNE) or similar
  * [ ] Added bonus - single-file self-contained native libraries implemented in C# (non-AOT)

**Comment by Nirmal4G** [comment]
Currently `NuGet.Build.Tasks.Pack` uses it to pack dependencies into single assembly so that it can be loaded across MSBuild versions, I think! _I tagged relevant people in the linked issue_.

I want to ship portable MSBuild Tasks (_that's my first scenario_) that should be able to load across MSBuild versions. We also maintain a multi-file editor internally for our test files for testing an experimental file system, where the app is extended using plugin for each category of file types which provide IO profiling, file container and metadata support.

For this "application", we have migrated parts of it to .NET Standard and some parts to .NET Core while the core app uses Mono/NETFX because of its plugin system. We want to migrate it to .NET Core but one blocker is that we want to load the plugins without any issues. Currently with a test project, conflicts appear in loading plugins having same dependencies with multiple versions.

Since these plugins are one-off work, there might not be sources for some versions, only NuGet packages which is also making migration harder. With ILMerge we did make it work for some of the assemblies but some required de-compilation. We also saw that the ILMerge is now archived. So, it would be helpful for .NET linker to do something similar to ILMerge!

Roughly, these two requests _in theory_ seem to solve our problems as well.

- Single-file components loaded via native hosting APIs
- Single-file managed plugins - `AssemblyDependencyResolver` - like support

**Comment by Nirmal4G** [comment]
> `AssemblyLoadContext`

Yes, we did but there were some issues. We are still in the process of migrating the plugins. I still don't know the reason but the test app crashed gloriously when hitting ALC APIs sometimes even before (_might be a different issue_). I'll provide a detailed issue if you can point me how to debug/trace intermittent crashes in .NET runtime.

We also have our internal shared framework which we migrated to .NET Standard/Core thanks to work done in .NET Core 3.1 `FrameworkReference` and targeting packs. But on the deployment side, we want to be able to ship as a single file framework either trimmed with reference to the App being deployed or a full fat assembly. And possibly provide patches with the least disk footprint.

**Comment by vitek-karas** [comment]
> I'll provide a detailed issue if you can point me how to debug/trace intermittent crashes in .NET runtime.

If it's a hard crash that would be really weird - in any case I would be definitely interested in any kind of repro or dump of that.
