### ISSUE TITLE
[HTTP/3] Developers can build libraries for HTTP/3 to meet their client/server needs

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#43546]
HTTP3 is the next major version of HTTP and the successor to HTTP2. It is in the final stages of standardization in the IETF. Some browsers (notably Chrome) already support draft versions of HTTP3. HTTP3 runs over QUIC, which replaces TCP as the underlying transport. QUIC is also in the final stages of standardization in the IETF. It provides secure, multiplexed streams over UDP. QUIC is a general-purpose, extensible transport protocol and we expect it to be used by other application protocols aside from HTTP3.

## Work Items
- [ ] A set of public classes for using the QUIC protocol on either client or server. This is System.Net.Quic. It is the equivalent of System.Net.Sockets for the QUIC protocol.
- [x] HTTP3 client support in HttpClient/SocketsHttpHandler.
- [x] Linux support
- [ ] MacOS support

### P0
- [x] #2262 - Improve QuicListener API to not have non-functional properties
- [x] #31695 - Use GCHandles
- [x] #32050 - Fix stream read returning 0 on connection abort
- [ ] #32066 - Improve error messages and move to resources
- [ ] #32071 - TLS server options
- [ ] #32072 - Handle exceptions within MsQuic callbacks
- [x] #32073 - Fix QuicListener disposal leaking MsQuic handles
- [x] #32075 - Finalize "abortive dispose" model
- [x] #32079 - Implement stream availability events
- [ ] #32142 - Finalize dispose model
- [x] #44580 - Update MsQuic
- [ ] #756 - Finalize shutdown behavior
- [ ] Add tests
- [ ] #32069 - TLS client options
- [x] #32077 - Implement Write cancellation support
- [ ] #43000 - Make RemoteEndPoint an IPEndPoint

### P1
- [x] #32575 - Implement platform compatibility detection
- [x] #42651 - Optimized stream reads
- [ ] #32068 - Remove duplicate SOCKADDR code
- [ ] #32076 - Optimize synchronous QuicStream APIs
- [ ] #43792 - (Decide if needed and) Implement sync APIs
- [ ] #42642 - (Decide if needed and) Split out configuration APIs
- [ ] #44782 - Implement flush capability

### P2
- [ ] #43061 - (Decide if needed and) Participate in QUIC interop testing

We have already made some progress on this in .NET 5.0 and are delivering HTTP3 support in a “preview”, unsupported capacity. There is no public API for QUIC in .NET 5.0.

We intend to share as much HTTP3 code as is reasonably possible between the client and server implementation.

**Comment by danmosemsft** [comment]
@scalablecory @geoffkizer @karelz as a P0 story, we need to get a[ t-shirt cost ](https://github.com/dotnet/runtime/labels?q=cost) for this by 11/13. 

I am assuming that includes the first two of the list above.

@Pilchie who will cost the third one -- the work on the Kestrel side?

**Comment by Pilchie** [comment]
I expect @jkotalik is the best person on our side.

**Comment by jkotalik** [comment]
I marked this as XL (it's XL even for just the Kestrel work).

**Comment by danmosemsft** [comment]
Is there some reasonable way to break this into child items, @jkotalik ? (For example, one item per entry in the list above, or more)

**Comment by jkotalik** [comment]
We are tracking this in the aspnetcore repo as well: https://github.com/dotnet/aspnetcore/issues/15271. I'd put it on the runtime folks to determine if/how the want to split it up.

**Comment by jkotalik** [comment]
I'd cost adding HTTP/3 to Kestrel at ~20 weeks for everything (including perf/stress tests, implementation, abstractions, etc.)

**Comment by danmosemsft** [comment]
Alright, I parented that under this. It's labeled Epic, but fine.

**Comment by scalablecory** [comment]
I think 12 weeks is enough for QUIC (MsQuic implementation) and client-side H3. @geoffkizer how do you feel about that?

**Comment by geoffkizer** [comment]
That seems a bit short to me.

I also think we should break out the MsQuic work vs the H3 work.

**Comment by danmosemsft** [comment]
@scalablecory (or @geoffkizer ) could you please open (or link) appropriate user stori(es) for our work, similar to how the Kestrel one is linked above? Just tag with "User Story". Then we have a place for our own cost.

**Comment by samsp-msft** [comment]
@geoffkizer - Can we flush this out to sub issues?

**Comment by karelz** [comment]
6.0 work has been finished -- all features we wanted are in. HTTP/3 is opt-in Preview feature in 6.0.

We will keep working on HTTP/3 and QUIC (incl. public APIs) during .NET 7.0 timeframe. We will use new tracking User Story for that - @samsp-msft will create it.
Closing.
