### ISSUE TITLE
User Story: .NET 6 will take the first steps to enable Native AOT

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#43591]
The demand for JIT-less native AOT is growing, and not having a solution will drive customers to other platforms such as Rust & GoLang. A trend that we are seeing across the industry is that for security reasons hosting environments are setting requirements that code pages need to be read-only which prevent the JIT-ing model which is core to .NET code execution. 

We cannot afford to ignore the native AOT scenario, nor can we go dark and wait for a complete implementation. We need to evolve this area in Runtime Labs, and grow the capabilities to support additional work loads, with the expectation that it will not be for everyone - .NET needs to have both JIT and AOT capabilities to enable the broadest cross-section of solutions. This high level section sets our intention to invest in native AOT scenarios and more definition from the teams will be needed to define our phased approach over the next few .NET releases.

# Work Items

- [ ] Developer experience
  - [ ] Developers have a way to tell IDE that they are targeting Native AOT 
  - [ ] Developers should be shown errors/warnings for AOT incompatible code during development
  - [ ] Inner loop experience for AOT projects
- [ ] Framework annotations - shared with Trimming
  - [ ] Additional annotations for Native AOT specific problem areas
- [ ] Blazor Experience
