### ISSUE TITLE
Epic: Expand platform compat annotations to cover more configurations

### ISSUE THREAD

**Issue by cathysull** [dotnet/runtime#43616]
In .NET 5 we started with annotations for features and APIs which are not universally available everywhere. We picked Windows and browsers as the initial targets for the experience. To make the experience complete we need to continue annotating remaining platforms we support (e.g. Linux-specific APIs that we expect to add). It goes beyond this as well.  It's certainly a "last mile" experience, but for example today you won't get any warnings if you try to use MemoryMappedFile.CreateNew(string, ...) with a non-null string path, even though only a null string path is supported on Linux and macOS. The current platform analyzer doesn't account for such possibilities, with annotations done to just say "if any usage of this API works on a platform, then consider it supported on that platform". We should look at what APIs fall into those partially-supported buckets and consider ways of improving the experience around them. This might be the next issue developers porting to .NET 5 get hung up on from a cross-platform perspective.

We also realized that the platform vertical is not the only limiting factor for APIs availability. There are others based primarily on workload limitations which should offer developers the same experience. We will expand compatibility annotations to cover configurations such as AOT, self-contained bundles and single file.

The projects which benefits most from the annotations are large scale solutions with many dependencies which are usually not available as a source code implementation. Exploring how to run the analysis on the final output would further improve the impact of tooling.

# Work Items

- [x] Windows developers get warnings when call APIs that aren't available on the OS version they want to target #45192
- [ ] Xamarin developers get warnings when they call APIs that aren't available on the OS version they target #45193
- [x] Blazor developers get warnings when they call APIs that aren't available on WebAssembly #42335
- [x] Some of platform specific builds in runtime repo causing CA1416 #44231
- [x] Developers get warnings when they misuse [SupportedOSPlatform] or [UnsupportedOSPlatform] attributes #44914
- [x] Analyzer for methods with PlatformNotSupportedException body but missing platform attributes #42967
- [x] Improve diagnostic messages dotnet/roslyn-analyzers#4021
- [ ] Identify more places to apply [SupportedOSPlatform] and [UnsupportedOSPlatform] attributes for Windows and Linux #44916
- [x] Flag diagnostics when unsupported types are used as generic type parameters dotnet/roslyn-analyzers#4362
- [ ] ~Developers can easily resolve Platform Compatibility warnings with a code fixer #44919~
- [ ] ~Developers can verify their app NuGet dependencies compatibility against target platform #44920~
- [x] Developers need more flexibility to annotate their code for platform supported/unsupported scenarios to reduce issues warnings noise #44922
- [ ] ~Flag platform specific constructor called implicitly in derived types dotnet/roslyn-analyzers#4404~

**Comment by jeffhandley** [comment]
Can we also consider integrating the OSPlatform support attributes into the .NET Portability Analyzer so that the report can show the APIs that are available in .NET Core but have limited OSPlatform support?

**Comment by danmosemsft** [comment]
@jeffhandley @cathysull we can mark this as Committed on the .NET 6.0 board, I guess? Note this is marked P1 but has P0 children (which by definition are committed).
