### ISSUE TITLE
Epic: Deliver on developers' top-requested System.Text.Json features and improvements

### ISSUE THREAD

**Issue by cathysull** [dotnet/runtime#43620]
There are about 200 open issues for JSON and community engagement continues to be high along with direct asks from authors like NSwag. There are still have some missing features that prevents System.Text.Json to be successful as the standard JSON stack for .NET.

# User Stories

- [x] Developers can convert between JSON data and C# `dynamic`, and also have a mutable JSON DOM type https://github.com/dotnet/runtime/issues/45188
- [x] Developers using JsonSerializer can handle common F# types well https://github.com/dotnet/runtime/issues/29812
- [x] Developers using JsonSerializer can asynchronously (de)serialize IAsyncEnumerable<T> https://github.com/dotnet/runtime/issues/1570 -- needed by ASP.NET
- [x] Developers using System.Text.Json have their top requests addressed so that they can use STJ in more scenarios  https://github.com/dotnet/runtime/issues/45190
- [ ] Developers using JsonSerializer have full polymorphic support https://github.com/dotnet/runtime/issues/45189

**Comment by danmosemsft** [comment]
@ericstj @layomia as you determine the prioritized list of work for JSON for 6.0 please extend the list above so it links up in https://themesof.net/. It would be great to add a Cost label to each.

**Comment by danmosemsft** [comment]
@terrajobst proposes that the headings above (Eg Extend polymorphic support) be User STories themselves, so they can group their child issues in the tree.

**Comment by paul1956** [comment]
VB.Net support most/all functions even if its a different interface. Specifically use of Ref parameters.

**Comment by danmosemsft** [comment]
@ericstj I suggest transmuting this into an Epic, directly parented by https://github.com/dotnet/core/issues/5366, and then its children can be massaged into stories (maybe just cleaning up their titles)

**Comment by layomia** [comment]
@danmosemsft - agreed. I've updated this issue and it's children per your suggestion.

I think this issue is better qualified as an Epic given the nature of the work. Also, being parented by https://github.com/dotnet/core/issues/5366 fits better since we didn't promise these work items in .NET 5 (as was implied by the previous nesting under https://github.com/dotnet/core/issues/5395).

**Comment by danmosemsft** [comment]
@layomia looks good, I took the liberty of tuning some of the user stories so that they are statements that become true when the user story is completed. We do it like that so the focus is on the final state we are aiming for.

**Comment by layomia** [comment]
We can consider this work done for .NET 6.0. Polymorphic support is being planned for .NET 7 (https://github.com/dotnet/runtime/issues/45189).
