### ISSUE TITLE
Epic: Replace Crossgen with Crossgen2

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#43653]
As part of .NET 5 we introduced Crossgen2 to pre-compile assemblies. As part of .NET 6 Crossgen2 will replace Crossgen1 within the runtime and SDK. This contributes towards this Theme: https://github.com/dotnet/core/issues/5438

### Functionality
- [x] [Migration-blocking bugs](https://github.com/dotnet/runtime/labels/crossgen2-migration-blocking) fixed / triaged
- [x] x86 / arm32 support
- [x] Apple Silicon parity with Crossgen
- [x] PDB generation [Tomas]
- [x] Cross-compilation support (arm64 -> arm32, x64 -> x86) [David]
- [x] Version resiliency testing [Simon]
- [x] SDK support for cross-architecture compilation [Anton]
- [x] Add Arcade support for building R2R images with CG2 [Anton]
- [x] Perfmap generation and integration into perfcollect
- [ ] PGO block count handling
- [x] Support using Crossgen2 for compiling System.Private.CoreLib in CoreCLR build #43810
- [ ] More options for performing JIT. [AB#1244349](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1244349)

### Testing
- [x] [Crossgen2 tests](https://dev.azure.com/dnceng/public/_build?definitionId=674&_a=summary) pass > 99%
- [x] [Crossgen2 outerloop tests](https://dev.azure.com/dnceng/public/_build?definitionId=701) pass > 99%
- [x] [Stress tests](https://dev.azure.com/dnceng/public/_build?definitionId=886) passing > 99%
- [ ] Set of methods compiled by CG2 matches CG1 (via R2RDump), https://github.com/dotnet/runtime/issues/50124
- [ ] At runtime, set of methods executed as R2R matches CG1 (via ETW), https://github.com/dotnet/runtime/issues/50125
- [x] x86 / arm32 Testing (improved CI testing from minimal)

### Performance
- [x] Small file compilation performance improvements
- [ ] Define real-world code sign-off criteria (WPF, Powershell startup, ASP.NET startup / throughput, eg)
- [x] Compiler throughput >= Crossgen1
- [x] R2R image sizes <= Crossgen1 [Simon]

### Rollout (and Exit Criteria)
- [x] S.P.C AOT'd with CG2 [Tomas]
- [ ] Add library test CI run using CG2-compiled framework, https://github.com/dotnet/runtime/issues/50127
- [x] Libraries AOT'd with CG2 (staggered by architecture?)
- [x] Switch SDK default to CG2
- [x] Remove crossgen from runtime repo

**Comment by mangod9** [comment]
I am closing this userstory since we have specifically completed the following (we will track some of the remaining work as separate issues): 

 ```
Switch SDK default to CG2
Remove crossgen from runtime repo
```

Thanks @dotnet/crossgen-contrib for getting us here :).
