### ISSUE TITLE
Epic: Expand .NET WebAssembly Capabilities

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#43767]
We shipped the first fully .NET Core based version of WebAssembly for Blazor in .NET 5. We had to make a few compromises and cut several features to meet the deadline. One of the major features postponed from .NET 5 was AOT support for WebAssembly. We want to keep investing and improving WebAssembly support to make our .NET solutions on the web complete and competitive. 

# Goals

## Native WebAssembly / AOT Support

We have customer evidence and have done our performance measurements of Blazor scenarios. In several areas, there is a large gap between client and server performance which limits the potential of the .NET WebAssembly platform to be used for a broader range of applications. We have improved performance for several scenarios in .NET 5 release but many of them remain to be much slower compared to our server implementation or JavaScript frameworks. 

## Web Cryptographic Support

The .NET APIs have been designed with the desktop mindset first. For that reason, we had to make few critical APIs not supported when running .NET inside the browser in .NET 5 release and made libraries like Azure Cosmos DB which need cryptographic support to do add extra compatibility code to work inside the browser. We need to revisit that decision as it makes the migration between server and client Blazor more complicated and adds fragmentation angle to .NET ecosystem. We will focus on bringing cryptography support to WebAssembly in the way it's compatible with other .NET workloads. 

## Smaller Globalization Dependencies

Globalization libraries typically add significant size to applications. Globalization invariant mode enables developers to ships smaller apps, but offers essentially no globalization support at all. Globalization invariant mode could offer more functionality, with a fraction of the size required. We’ve talked about doing this for Wasm and Docker. We need to determine if we can decide a cluster of globalization functionality that solves customer problems and that appeals to at least some regions. 

## General App Size Reduction 

In Blazor scenario reducing app size in every new version is equally important to the developers as the performance improvements we make. We regressed the final size for most of these apps in .NET 5 compared to Blazor 3.2. In the next release, we are aiming to reduce the final compressed size for typical Blazor workloads by at least 20%. We'll need to keep in mind that if we enable AOT support for wasm by default in, the size is likely going to grow not to shrink and more mitigations will need to be put in place.

## Unmarshalled interop

When running on Blazor WebAssembly, it's possible to make unmarshalled calls from .NET to JavaScript. These are synchronous calls that don't perform JSON serialization of arguments or return values. All aspects of memory management and translations between .NET and JavaScript representations are left up to the developer. While using unmarshalled interop has the least overhead of the JavaScript interop approaches, the JavaScript APIs required to interact with these APIs are currently undocumented and not officially supported. Various users have reported that these APIs are absolutely required to satisfy their requirements. For .NET 6 we will finalize these APIs and document unmarshalled interop as a supported feature.

# Users Stories
- [x] Developers can AOT compile .NET apps into WebAssembly format #44316
- [x] Browser developers want smaller published output to speed up their apps load time #44317 
- [ ] ~Using Web Crypto APIs for browser-wasm cryptography implementation #40074~
- [x] Developers need more flexibility for globalization settings to fulfil their needs on the web #44321
- [ ] ~Developers needs faster interop between JavaScript and C# to be able to port large apps to webassembly #44330~
- [ ] Developers can easily use NuGets with native libraries to build fast wasm projects #44636
- [x] Blazor client developers can use Parallel.For in their applications to share more code with server #43411
- [ ] ~Developers can employ EventSource APIs when publishing for AOT targets to be able to use .NET tracing capabilities #43390~

**Comment by samsp-msft** [comment]
Can we add Blazor to the title?

**Comment by danmosemsft** [comment]
@marek-safar should make each of the sub issues into User Stories so they can get individual costs and maybe priorities.

**Comment by marek-safar** [comment]
@samsp-msft WebAssemly != Blazor so I'd keep it this way as it has a broader impact.

@danmosemsft I think it'd be better to make this item Epic

**Comment by danmosemsft** [comment]
@marek-safar fine, but I think it needs child user stories - I don't see how we can cost this as a whole.

**Comment by danmosemsft** [comment]
@danroth27 are you the PM for this one?

**Comment by danroth27** [comment]
@danmosemsft Yup

**Comment by samsp-msft** [comment]
Changed the link for the Blazor source generators as it was moved to aspnetcore repo.

**Comment by RChrisCoble** [comment]
Given the Epic's top description of improving performance compared to backend execution .Net Core performance, I'm somewhat surprised you're not doing work to enable this in Blazor:  (or maybe you are and I' m missing it?)

[Real multithreading (on supported browsers) #17730](https://github.com/dotnet/aspnetcore/issues/17730)

**Comment by danroth27** [comment]
@RChrisCoble Much of the work to support multithreading in .NET on WebAssembly has been done, but browser support still isn't fully available. Safari in particular hasn't reenabled support for shared array buffers yet. How useful is multithreading support for your scenarios if it only worked in Chromium based browsers, and not Safari?

**Comment by RChrisCoble** [comment]
> @RChrisCoble Much of the work to support multithreading in .NET on WebAssembly has been done, but browser support still isn't fully available. Safari in particular hasn't reenabled support for shared array buffers yet. How useful is multithreading support for your scenarios if it only worked in Chromium based browsers, and not Safari?

I replied to your Microsoft email directly for this response, as it requires divulging future release dates and intended scope.

Thanks for the follow up, greatly appreciated!

**Comment by plaisted** [comment]
This may be outside scope but would love the ability to interop in some way to WASM from .net code (all of the above goals are really targeting scenarios where .net code is running in a WASM environment). There are some community projects out there experimenting with this this through WASM->CIL conversion. Since many languages now compile to WASM it would make importing JS / Rust / Go / etc libraries possible with some work.

**Comment by jeromelaban** [comment]
@plaisted this is already possible: https://jaylee.org/archive/2020/03/22/csharp-interop-with-c-cpp-and-rust-in-webassembly.html, through p/invoke. This is what SkiaSharp uses, same for SQLitePCL.

**Comment by plaisted** [comment]
I was under the impression that only worked when running in a mono webassembly environment... I'll dig in again and take a look. My suggestion was to be able to effectively P/Invoke a WASM binary while running under net core (or transpile it to a DLL ahead of time and then import as normal).

**Comment by jeromelaban** [comment]
It's running as well in a NET 6 environment, though the current tooling in main does not allow for it. I added that support in the [uno wasm bootstrapper](https://github.com/unoplatform/Uno.Wasm.Bootstrap) and it works for both mono/mono and dotnet/runtime.

**Comment by ChristianWeyer** [comment]
Thanks for the link and the article @jeromelaban - did you ever get to rite the follow-up "how to use strings back and forth in both environments"?
