### ISSUE TITLE
MonoVM runtime size-reduction for WebAssembly

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#43778]
Native code reduction:

### .NET 6 Preview 1
- [x] #43691 - [wasm] Add flag to remove non-blittable marshaling functionality from the runtime
- [x] #43690 - [wasm] Selectively strip the Name section of the wasm blob
- [x] #43783 - [wasm] Enable relinking of the wasm binary at build time
- [x] #44859 - Remove assumption that Array has to implement all interfaces for MonoVM

### .NET 6 Preview 2
- [x] #43689 - [wasm] Ensure ICU is fully linked out in invariant mode
- [x] #44795 - Move System.Threading.Event/Mutex/Semaphore support to managed code
- [x] #48061 - dotnet.timezones.blat file size has increased 34% since net5.0

### .NET 6 Preview 3
- [x] #48056 - [mono] Remove w32 subsystem on wasm
- [x] #48031 - [mono] Switch to shared implementation of LowLevelLock
- [x] #45454 - Remove dependency on USE_ZLIB from browser wasm build
- [x] #43694 - [wasm] Experiment with emscripten settings to shrink binary size
- [x] #48355 - [wasm] Estimate ICU data size savings when only shipping English

### .NET 6 Preview 4
- [x] #48225 - Avoid bundling unnecessary functionality in the wasm published output
- [x] #49220 - [wasm] Try to get sharding working for ICU
- [x] #49221 - [wasm] Investigate what parts of the data file map to what APIs
- [x] #49224 - [wasm] Shrink data section in dotnet.wasm

### Future
- [x] #43693 - [wasm] Experiment with getting rid of SHA1Transform in the runtime
- [x] #47875 - Experiment with icu4x usage for wasm
- [x] #45034 - [mono] Remove framework-specific code and unnecessary MonoDomain usage
- [x] #48016 - Some .c and .h files are being published for Blazor WASM apps
- [ ] #48058 - [mono] Port managed Monitor implementation from NativeAOT
- [ ] #49222 - [wasm] Custom compression pass for wasm
- [ ] #48349 - Document wasm relinking functionality

**Comment by sajjadarashhh** [comment]
a true way to solve this problem is using native-aot for wasm
we dont need dotnet.wasm when browsers is already have built-in runtimes

**Comment by SamMonoRT** [comment]
@lewing @steveisok - please can one of you take ownership of this.
