### ISSUE TITLE
Epic: GC Regions Support

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#43844]
[AB#1244342](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1244342)
We are switching segments to regions for managing memory on the GC heap. Segments have their own benefits, eg, checking if an address is in ephemeral requires comparing with 2 values (in Workstation case) but regions enable many optimizations that we've been wanting to have for a while. For example -

+ Currently there’s no way to exchange memory between different generations without a compacting GC so if BGC builds up a lot of free space in gen2/LOH and gen2 has a lot more free spaces than LOH, there’s not a way to repurpose memory in gen2 for LOH. Another example is we often observe a lot of free spaces in gen0 due to pinning and we cannot repurpose it for other generations. With regions we can repurpose empty regions to any generation which will solve both problems. We could also choose to decommit these free spaces but that would require its own bookkeeping and we might as well just switch to regions.
+ This will also help with container perf - because we repurpose free spaces to other generations, we can regulate the memory usage much more easily without incurring full compacting GCs. 
+ One of the evolutions I’d like to make in GC is to decouple the GC threads and their respective heaps and this will allow that to happen a lot more naturally. 
+ This will build a solid foundation for new flavors of GCs like incremental/concurrent compacting GCs.

**Functionality**
- [x] Enable support wks
- [x] Enable support srv
- [x] Enable Regions by default in Standalone GC (clrgc.dll)

**Testing**
- [x] P0/P1 Tests passing
- [x] CI/CD InnerLoop Testing enabled with Regions
- [x] CI/CD OuterLoop Testing enabled with Regions
- [x] CI/CD Stress testing enabled

**Stability**
- [x] Basic tests passing rate > 99%
- [x] GCStress tests passing rate > 99%
- [x] All tests passing rate > 99.9%

**Performance**
- [x] TE Performance is comparable to segments
- [x] Micro benchmarks dont show any major performance regressions. 

**Release**
- [x] CLRGC available within installers/gzips.

**Comment by En3Tho** [comment]
@mangod9 been wondering about this for a while. Any info you might share?)

**Comment by mangod9** [comment]
Hey @En3Tho, we are just getting started and will add more details as we make progress. If there are any specific details you are interested in please let us know. Thx!

**Comment by En3Tho** [comment]
@mangod9 Thank you for an answer. For now, I guess it would be really cool if you could at least briefly describe what this is about (a new under-the-hood mechanism to make GC even faster or a new kinda "give me a memory region, let me so my stuff and have it back", api, sorta like arraypool/malloc, but more general version.
For now we can only wonder.

**Comment by Maoni0** [comment]
it's my fault - I was supposed to write the description. I'll edit the 1st comment on the thread with the description.

**Comment by BreyerW** [comment]
Hoh last bullet sounds particularly interesting of course others sound nice too. The only thing sour is new flavors of gc are multiyears efforts on their own i suspect never mind switch to regions itself. Maybe im too pessimistic?

**Comment by tannergooding** [comment]
@Maoni0, do you think regions would make it easier to support custom alignments (such as 16 or 32-byte alignments) for objects/arrays?

Or would that still be relegated to the POH and extending the `GC.AllocateArray` method to support specifying alignments?

**Comment by Maoni0** [comment]
@tannergooding those are orthogonal features. the reason we haven't enabled alignment is just because we haven't had time due to other more urgent work. it's something I want to enable because it's clearly useful for some (very specific) scenarios. I know you care about it a lot 😃 it's in the queue... just haven't got there yet.

**Comment by mjsabby** [comment]
Will regions be helpful in supporting safe memory mapped files as byte arrays?

**Comment by Maoni0** [comment]
@mjsabby what kind of issues do you hit currently doing that? are you talking about ro segments or something else?

**Comment by mjsabby** [comment]
It’s not safe. It can be made safe if memory mapped files are backed by GC regions.

There was a discussion on GitHub with @GrabYourPitchforks  and @jkotas

**Comment by Maoni0** [comment]
regions make no difference for that particular issue - I presume you are talking about [#37227](https://github.com/dotnet/runtime/issues/37227). I don't think GC is actually a big part in that issue - essentially from GC's POV, if it gets more ro segs it's not a big deal - we don't reclaim ro segs anyway (they can only be removed by the user code). all GC cares about is if an object points to something on the ro segs it needs to be a legit object. I saw that @jkotas already said the special treatment of Dispose was too expensive.

**Comment by mjsabby** [comment]
Today we look at the stack for by refs, couldn't we also look at another special location for memory mapped files? I thought GC regions could accomplish that in a more natural way, maybe not, and the discussion can then stay in that thread.

**Comment by jkotas** [comment]
@mjsabby Let's keep this discussion in #37227. Regions do not help with this at all.

**Comment by sirinath** [comment]
Regarding GC can a truly pauseless GC be introduced. E.g. Azul has [C4: The Continuously Concurrent Compacting Collector](https://www.azul.com/files/c4_paper_acm1.pdf)

**Comment by InCerryGit** [comment]
> 关于GC，可以引入真正无暂停的GC。例如，Azul 具有[C4：连续并发压缩收集器](https://www.azul.com/files/c4_paper_acm1.pdf)



> Regarding GC can a truly pauseless GC be introduced. E.g. Azul has [C4: The Continuously Concurrent Compacting Collector](https://www.azul.com/files/c4_paper_acm1.pdf)

i think so

**Comment by mangod9** [comment]
Regions are now enabled by default in main. Standalone GC has been switched to use segments to enable backcompat issues (if any). It can be configured using (though clrgc.dll is not shipped with the sdk, and will need to be manually built if required): 

`set COMPLUS_GCName=clrgc.dll`

**Comment by mangod9** [comment]
@datduyng, you could get it to work with .net 6 but will have to build runtime repo manually and use the built clrgc.dll with `dotnet_gcname=clrgc.dll`

**Comment by mangod9** [comment]
Closing this since the regions enablement is now complete.

**Comment by realivanjx** [comment]
@mangod9 i noticed lower memory usage but higher cpu usage with net 7 preview 6 asp net core compared with net 6 (observed with `docker stats` though). is this to be expected? thanks.

**Comment by mangod9** [comment]
hi @realivanjx, is there a repro you can share? With preview6 in fact we had a working set regression as noted here: https://github.com/dotnet/runtime/issues/72557 which is fixed in preview7, but we havent observed higher cpu for our asp.net based benchmarks. Thanks.

**Comment by realivanjx** [comment]
@mangod9 not at the moment since it is the production program im using. im running it inside a docker with max memory of 300 MB so it is really a memory constrained environment (raspberry pi 4). i will try to create an empty asp net core project to see if it still happen. thanks

**Comment by mangod9** [comment]
Ok, could you also quantify how much increase in cpu utilization are you noticing? It could be specific to your scenario.

**Comment by realivanjx** [comment]
sorry i was completely blundered. the memory was actually increased. here is the top result (typical):
net 6
![net6](https://user-images.githubusercontent.com/12814796/181180394-cea7d463-3265-4d34-8293-6d5ca633d8f1.png)

net 7
![net7](https://user-images.githubusercontent.com/12814796/181180414-98341316-041d-4c67-aa77-dcce32876396.png)

**Comment by mangod9** [comment]
yeah that memory regression should hopefully be fixed in preview7. We will have to get more info to investigate the cpu regression.
