### ISSUE TITLE
Change IAsyncResult APIs in System.Net.Sockets to wrap Task APIs

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#43845]
We should change all the old IAsyncResult APIs in System.Net.Sockets to simply wrap the equivalent Task APIs, as we do in general.

Unfortunately, some of the current Task APIs actually use these IAsyncResult APIs. There is planned work to change this.

Specifically, we should do this for the following Socket APIs:

- [x] [Begin/End]Connect -- done in https://github.com/dotnet/runtime/pull/43661
- [x] [Begin/End]Accept -- done in https://github.com/dotnet/runtime/pull/51212
- [x] [Begin/End]Send -- done in #43886 
- [x] [Begin/End]Receive -- done in #43886 
- [x] [Begin/End]SendTo -- blocked on https://github.com/dotnet/runtime/issues/41502
- [x] [Begin/End]ReceiveFrom -- blocked on https://github.com/dotnet/runtime/issues/41502
- [x] [Begin/End]ReceiveMessageFrom -- blocked on https://github.com/dotnet/runtime/issues/41502
- [x] [Begin/End]SendFile -- blocked on https://github.com/dotnet/runtime/issues/42591
- [x] [Begin/End]Disconnect -- done in #51213

~And these UdpClient APIs:~

~- [ ] [Begin/End]Send~
~- [ ] [Begin/End]Receive~

### EDIT (by @antonfirsov )

As per https://github.com/dotnet/runtime/issues/43845#issuecomment-774327188, we don't need to do anything with UdpClient.

- ~We need to fix #47905~ Update API docs: https://github.com/dotnet/dotnet-api-docs/issues/6658

**Comment by antonfirsov** [comment]
> And these UdpClient APIs: [...]

@geoffkizer I'm not sure what do you mean by those work items. `UdpClient`'s `[Begin/End][Receive/Send]` methods are thin wrappers over the `Socket` counterparts. Is there any specific work we need to take care of I'm missing?

**Comment by geoffkizer** [comment]
> UdpClient's [Begin/End][Receive/Send] methods are thin wrappers over the Socket counterparts. You say it's worth to refactor them to wrap their own Task-based methods instead?

No, you're right, I don't think we actually need to refactor these. I probably didn't look closely at what they do when I added them to the list.

**Comment by karelz** [comment]
Seems to be finished, closing.
