### ISSUE TITLE
[browser] Tests aren't resolving promises correctly

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#43958]
When running tests using XHARNESS_COMMAND=test-browser we're still not able to test some of the browser apis because the tests hang when using promises.

**Comment by lewing** [comment]
@akoeplinger I suspect this is caused by the threadless runner pumping the queues and not actually yielding.

**Comment by lewing** [comment]
https://github.com/dotnet/xharness/blob/f4af4bc86a20b4d0805c8fd97393dd13dd267d08/src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs#L63..L70 is blocking the promises but yielding there still doesn't work because runtime-test.js doesn't handle async main methods correctly.  We need to fix that then fix xharness.

**Comment by lewing** [comment]
- [ ] The fix for async main is #44045
- [ ] The harness fix is dotnet/xharness#345
- [ ] The response to the xharness change is #44046

**Comment by lewing** [comment]
Final fix landed in #44046
