### ISSUE TITLE
Categorize linking warnings for netcoreapp

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#44035]
To make netcoreapp linkable we need to:

- [x] Get a list of all warnings produced when linking netcoreapp
- [x] Categorize the warnings by product area/namespace
- [x] Identify the cause of the warnings, and propose a fix

**Comment by LakshanF** [comment]
Below is the full linker warnings from netcoreapp (699 total)

[link.out.txt](https://github.com/dotnet/runtime/files/5466863/link.out.txt)

And the [warning](https://github.com/mono/linker/blob/master/docs/error-codes.md#warning-codes) breakdown

Warning | Count
-- | --
IL2075 | 164
IL2060 | 158
IL2070 | 140
IL2026 | 53
IL2055 | 41
IL2057 | 35
IL2072 | 33
IL2067 | 23
IL2080 | 20
IL2077 | 15
IL2050 | 5
IL2082 | 3
IL2059 | 2
IL2065 | 1
IL2087 | 1
IL2090 | 1
IL2091 | 1
IL2079 | 1
IL2064 | 1
IL2085 | 1

**Comment by LakshanF** [comment]
Warnings by assemblies (low counts are ignored),

Assembly | Total Warnings | Wrn | Count | Wrn2 | Count3 | Wrn3 | Count4 | Wrn4 | Count5
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
System.Private.DataContractSerialization | 118 | IL2075 | 41 | IL2055 | 33 | IL2060 | 22 | IL2070 | 16
System.Linq.Queryable | 110 | IL2060 | 109 | IL2067 | 1 |   |   |   |  
System.Linq.Expressions | 72 | IL2075 | 30 | IL2070 | 22 | IL2060 | 14 | IL2077 | 4
System.Private.Xml | 67 | IL2070 | 26 | IL2075 | 22 | IL2026 | 5 | IL2072 | 4
System.ComponentModel.TypeConverter | 60 | IL2075 | 17 | IL2057 | 15 | IL2070 | 8 | IL2080 | 5
System.Private.CoreLib   (Runtime) | 46 | IL2075 | 14 | IL2026 | 13 | IL2055 | 6 | IL2057 | 3
System.Reflection.TypeExtensions | 31 | IL2070 | 29 | IL2026 | 2 |   |   |   |  
Microsoft.CSharp | 25 | IL2075 | 14 | IL2072 | 3 | IL2070 | 3 | IL2055 | 2
Microsoft.VisualBasic.Core | 25 | IL2075 | 10 | IL2070 | 8 | IL2072 | 2 | IL2080 | 1
System.Security.Cryptography.Algorithms | 25 | IL2026 | 19 | IL2075 | 4 | IL2080 | 2 |   |  
System.Data.Common | 24 | IL2057 | 9 | IL2072 | 6 | IL2077 | 4 | IL2080 | 3
System.Private.CoreLib | 16 | IL2072 | 4 | IL2075 | 3 | IL2057 | 3 | IL2070 | 3
System.Text.Json | 16 | IL2070 | 7 | IL2075 | 4 | IL2026 | 2 | IL2060 | 2
System.ComponentModel.Annotations | 11 | IL2072 | 4 | IL2070 | 4 | IL2077 | 2 | IL2080 | 1
System.Reflection.DispatchProxy | 11 | IL2067 | 7 | IL2072 | 1 | IL2070 | 1 | IL2060 | 1
System.Runtime.Serialization.Formatters | 10 | IL2070 | 3 | IL2026 | 2 | IL2075 | 2 | IL2067 | 1
System.Text.RegularExpressions | 8 | IL2060 | 5 | IL2070 | 2 | IL2067 | 1 |   |  
System.Net.Http.Json | 6 | IL2072 | 4 | IL2077 | 1 | IL2091 | 1 |   |  
[NO ASSEMBLY INFO] | 5 | IL2050 | 5 |   |   |   |   |   |  
[Common] | 4 | IL2070 | 2 | IL2075 | 2 |   |   |   |  
System.Diagnostics.DiagnosticSource | 2 | IL2070 | 2 |   |   |   |   |   |  
System.Diagnostics.TraceSource | 2 | IL2026 | 1 | IL2070 | 1 |   |   |   |  
System.ObjectModel | 2 | IL2079 | 1 | IL2057 | 1 |   |   |   |  
System.Runtime.InteropServices | 2 | IL2070 | 1 | IL2075 | 1 |   |   |   |  
System.Security.Cryptography.Csp | 1 | IL2026 | 1 |   |   |   |   |   |

**Comment by marek-safar** [comment]
Can we please do it for important RIDs first (each rid can give you different results)

**Comment by danmosemsft** [comment]
added Drawing to table above.

**Comment by agocke** [comment]
@LakshanF It looks like this is done -- are we ready to close this issue out or is there more investigation necessary for the issues?

**Comment by LakshanF** [comment]
https://github.com/vitek-karas/designs/blob/1d55edf52b4b25e67133ccb82672b2dd170e53aa/accepted/2020/linking-libraries.md gives guidance on fixing warnings
