### ISSUE TITLE
Reconsider assert(!"Message") usage in coreclr.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#44132]
- [x]  There are at least 3 asserts that are always true, because of a forgotten `!` before the message, when fixed they fail on some tests, see https://github.com/dotnet/runtime/pull/44095, PTAL @tannergooding.

- [ ] `PORTABILITY_ASSERT(message)` (108 usages) are quite confusing because they don't check a condition and fail always. They could be replaced by `unreached` or `unimplemented` methods, also this block looks pretty outdated:
https://github.com/dotnet/runtime/blob/df8e3f629afcf24e222b3d10d6c1061e4234b17e/src/coreclr/src/inc/palclr.h#L103-L111
are not other platforms finished now? 
PTAL @BruceForstall, @davidwrighton, you had a similar discussion about IMPL_LIMIT recently, do you have preferences about assert/unimplemented/unreached usages?

- [ ] There are 6 usages of `ASSERT(!"message")` and 360 usages of `ASSERT("message")` with different defines, probably replace both with better debug only `unreached("message")`?

cc @dotnet/jit-contrib

**Comment by jkotas** [comment]
> `PORTABILITY_ASSERT(message)` 

The purpose of these is to mark places that need to be filled in for new platform ports. I do not think we should replace them with the generic `unreached`. We would lose the purpose. Renaming them to reduce confusion sounds good.

> this block looks pretty outdated

Yes, this shoud be flipped to #if 1 since we do not have any platform ports in progress currently, and anything that does not compile fixed.

**Comment by sandreenko** [comment]
> Yes, this shoud be flipped to #if 1 since we do not have any platform ports in progress currently, and anything that does not compile fixed.

I have seen only 2 failures so far:
https://github.com/dotnet/runtime/blob/ecd979c9860caee8326f8678736ae98a77bdae5b/src/coreclr/src/debug/di/valuehome.cpp#L454-L457

https://github.com/dotnet/runtime/blob/ecd979c9860caee8326f8678736ae98a77bdae5b/src/coreclr/src/vm/threadsuspend.cpp#L5128-L5144

**Comment by jkotas** [comment]
threadsuspend.cpp: The ifdef should be changed to just `#if !defined(FEATURE_EH_FUNCLETS)` and the else part of the ifdef should be deleted.

Not sure about the right fix for valuehome.cpp.

**Comment by davidwrighton** [comment]
@sandreenko, looking at the valuehome code it's doing save/restore of the x87 registers. I believe we don't use them anymore for x86 codegen, and instead use the SSE registers. I suppose it might be there to support mixed mode debugging, but I don't have confidence in that. I would guess that this code in theory is used to modify register state in the registers window, or possibly to handle some optimized debugging scenarios that I suspect don't work very well.

@tommcdon might have some context.

**Comment by davidwrighton** [comment]
Also my general opinion is that a better name would be good, but something like unreached causes a bunch of compiler warning spew that is different between various compilers and optimization levels. I'd like to see what sort of changes are needed to get a clean PR build before having an opinion on that.

**Comment by tannergooding** [comment]
> I believe we don't use them anymore for x86 codegen, and instead use the SSE registers

The x86 (but not x64) ABI still requires floating-point values to be returned in `ST(0)`, so maybe it needs to account for that?

**Comment by tommcdon** [comment]
Adding @sdmaclea to comment on the debugger ARM64 NYI assert https://github.com/dotnet/runtime/blob/ecd979c9860caee8326f8678736ae98a77bdae5b/src/coreclr/src/debug/di/valuehome.cpp#L454-L457

**Comment by BruceForstall** [comment]
> There are 6 usages of ASSERT(!"message") and 360 usages of ASSERT("message") with different defines, probably replace both with better debug only unreached("message")?

The `ASSERT("message")` cases are all in the PAL, which is "unique". The VM cases of `ASSERT(!"message")` maybe could be changed to use `_ASSERTE` like most everything else. It's not clear there's value in making it unreached, which as David says can cause warning problems with various compilers.
