### ISSUE TITLE
User Story: WebAssembly developers want smaller published output to speed up their apps load time

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44317]
In the .NET 5 release, we established a baseline of 2.2 MB for the fully compressed output of the default Blazor template running with .NET Core setup. For .NET 6 version, we are aiming to reduce that size by at least 20% for the same template to address size regression compare to .NET Core 3.x where the default template size was 1.7 MB. This is an ambitious goal, and will likely require numerous aggressive approaches to achieve it, including the removal of numerous non-essential features.

The only concern here is the wire size with full compression (at the moment, Brotli). The size or the required computation on either end is unimportant.

There is a dashboard available for historical size tracking at https://aka.ms/dotnetperfstatus. The case we care about is file type `.br`, `.NET 6`. Of particular note is the currently largest files: dotnet.wasm at 0.9 MB, System.Private.CoreLib.dll at 0.4 MB, and icudt.dat at 0.3 MB. No other file is above 0.1 MB, but combined they are around 0.6 MB.

# Work Items
- [x] MonoVM runtime size-reduction tracking #43778
- [x] Core Managed libraries size-reduction #44530 
- [x] Blazor specific libraries work
	- [x] Enable trimming of all Blazor libraries https://github.com/dotnet/aspnetcore/issues/30286
	- [ ] ~Add option to disable logging in sample Blazor app https://github.com/dotnet/aspnetcore/issues/27721~
	- [x] Excessive managed libraries dependencies https://github.com/dotnet/aspnetcore/issues/30098
- [x] Always run native linker for release/publish outputs https://github.com/dotnet/runtime/issues/43783
- [x] Add size tracking for WebAssembly functional tests
- [x] Include more Blazor apps in the size tracking dashboard

**Comment by SambhavSacheti** [comment]
> In the .NET 5 release, we established a baseline of 2.2 MB for the fully compressed output of the default Blazor template. For a future .NET version, we are aiming to get that down to 0.5 MB for the same template. This is an ambitious goal, and will likely require numerous aggressive approaches to achieve it, including removal of numerous non-essential features.
> 
> The only concern here is the wire size with full compression (at the moment, Brotli). The size or the required computation on either end is unimportant.
> 
> There is a dashboard available for historical size tracking at https://aka.ms/dotnetperfstatus. The case we care about is file type `.br`, `.NET 6`. Of particular note is the currently largest files: dotnet.wasm at 0.9 MB, System.Private.CoreLib.dll at 0.4 MB, and icudt.dat at 0.3 MB. No other file is above 0.1 MB, but combined they are around 0.6 MB.
> 
> # Work Items
> * [ ]  MonoVM runtime size-reduction tracking #43778
> * [ ]  Core Managed libraries size-reduction #44530
> * [ ]  Blazor specific libraries size-reduction [dotnet/aspnetcore#27668](https://github.com/dotnet/aspnetcore/issues/27668)
> * [ ]  Add option to disable logging in sample Blazor app [dotnet/aspnetcore#27721](https://github.com/dotnet/aspnetcore/issues/27721)
> * [ ]  Add size tracking for WebAssembly functional tests

Hi @marek-safar - The link  https://aka.ms/dotnetperfstatus is not working :-(

**Comment by marek-safar** [comment]
It does for me but it probably requires different permissions (we'll need to check)

**Comment by SamMonoRT** [comment]
@SambhavSacheti does this link work for you - https://aka.ms/blazorwasmsize  ?

**Comment by lewing** [comment]
Nothing left is targeting 6.0
