### ISSUE TITLE
Developers need faster interop between JavaScript and C# to be able to port large apps to webassembly

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44330]
As Browser based .NET applications continue to grow in complexity so does the desire for high performance interaction with the JavaScript host environment. Blazor provides public API for specific use cases and the .NET runtime implements internal methods for low level interaction. We should provide developers with supported APIs to implement high performance unmarshalled host interoperation.

## Work Items

- Performance
    - [x] Improved JS->C# call marshalling
    - [x] Better support for optimized string marshalling
- Testing
    - [x] Improved coverage in libraries tests
    - [x] Performance tests to prevent regression
- API
    - [x] API review for new public surface
