### ISSUE TITLE
Team Epic: .NET Runtime Repo Developer Inner Loop Productivity

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#44393]
In .NET 6 timeframe we intend to improve on the following aspects of developer inner loop productivity based on feedback regarding common pain points:

- Reduce manual steps needed for unit testing of private coreclr dev bits from 4 to 1
- Coreclr up-to-date check takes < 5s on an average dev machine
- Local build time
- Local build reliability and consistency
- Telemetry

**Unit testing**

- [ ] Define a msbuild hooks that allows you to replace the runtime and host inside a retail dotnet sdk install. This will enable 'overriding' runtime components with private developer flies.
- [ ] Produce a dev-inner loop based off of single file. The single file host includes various runtime components compiled into a static library.  This removes the need of manual patching of files. 
- [ ] Build on top of the prototype to extend to other areas of the runtime, such as using different libraries.  

**Local build time**

- [x] (P1) Improve local build by switching over to Ninja on Windows, https://github.com/dotnet/runtime/issues/33872
- [ ] (Incremental, P1) Investigate reducing complexity of test build / execution; https://github.com/dotnet/runtime/issues/36295

**Local build reliability and consistency** (5 weeks total)

- [ ] (1 week, P2) Failure in build-runtime.cmd related to missing UCRT in Windows; https://github.com/dotnet/runtime/issues/42774
- [ ] (2 days, P1) Failure in enforcepgo doesn't fail the build; https://github.com/dotnet/runtime/issues/35089
- [ ] (2 days, P2) Sharing violation reading pgd file in parallel coreclr local builds; https://github.com/dotnet/runtime/issues/46018
- [ ] (2 days, P2) Spurious mkdir error message during Linux build; https://github.com/dotnet/runtime/issues/34342
- [x] (2 days) installer.tasks.dll not found in local runtime build; https://github.com/dotnet/runtime/issues/46020
- [ ] (2 days, P1) Obsolete warnings in clean build; https://github.com/dotnet/runtime/issues/39976
- [ ] (2 days, P1) Test run files should be arch/OS distinguished; https://github.com/dotnet/runtime/issues/1737
- [ ] (1 week, P2) Enable more MSVC warnings; https://github.com/dotnet/runtime/issues/42767
- [ ] (1 week, P2) Per-component (coreclr, libraries, installer, mono?) cmake args; https://github.com/dotnet/runtime/issues/42711

**Documentation** (2 days total)

- [ ] (2 days, P1) Build doesn't see libs subset even though it's been built; https://github.com/dotnet/runtime/issues/36528

**Comment by hoyosjs** [comment]
Related: https://github.com/dotnet/runtime/issues/47022
