### ISSUE TITLE
Improvements to single-file analysis

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#44488]
The existing single-file analyzer covers the top issues customers will likely hit with single-file, but it has some shortcomings.

## Goals

- [x] Single-file analyzer is moved next to the trimming analyzer in the `mono/linker` repo
- [x] Single-file analyzer is enabled in the `dotnet/runtime` repo to identify problems in the framework
- [x] Users can annotate their own APIs as being not compatible with single-file

## Work

- [x] Add an attribute similar to `RequiresUnreferencedCode` (code, ref assemblies)
- [x] Annotate low-level APIs with the attribute - One more run over all "dangerous" APIs
  - [x] Make sure that the attributes show up in ref assemblies.
  - [x] Validate that the ref assembly validator in dotnet/runtime enforces inclusion of this attribute (we had issues with this for `RequiresUnreferencedCode`)
 - [x] At least plan on adding a docs page on the topic with some thoughts/guides on how to “fix” – ideally link to this from the attributes (see https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility)
- [ ] Synchronize with mono/Xamarin to annotate low level APIs which are problematic because of mono/Xamarin single-bundle publishing (mono itself can do a single-file bundle similar to CoreCLR's single-file, but Xamarin has other single-file like bundles for devices - Android, iOS).
- [x] Improve existing [Roslyn analyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Publish/AvoidAssemblyLocationInSingleFile.cs)
  - [x] Move the analyzer next to the trimming analyzer in the `mono/linker` repo
  - [x] Support for the new attribute
    - [x] Implicit suppression on annotated methods
- [x] Integrate the analyzers with SDK - probably conditioned on `PublishSingleFile` property - warnings on-by-default??? (they already are for user code, what about whole-program analysis done by linker)
- [x] Enable Roslyn analyzer on dotnet/runtime repo (similar to TrimAnalysis) - probably add baselines as well (not sure how to do baselines for Roslyn analyzer - `.cs` file with `SuppressMessage` attributes which will be removed by compilation?)
- [x] Go over reported warnings from within the framework in dotnet/runtime and “do something about them” (suppress, propagate to public API via attributes)
  - [x] Ideally also look through other features which might be affected by single-file and annotate
- [ ] ?? Run the analysis on higher-level frameworks – ASP.NET, WinForms, WPF and file issues as appropriate

**Comment by vitek-karas** [comment]
As part of the "Users can annotated their own APIs" we will introduce an attribute similar to `RequiresUnreferencedCode` and it will need almost identical treatment by the linker.

https://github.com/mono/linker/issues/1607 will probably force us to move analysis around `RequiresUnreferencedCode` into a different place in the linker - so we might as well make it an extensibility point (of sorts) and then implement both there.

**Comment by danmosemsft** [comment]
Should something like this be parented under a single file user story?

**Comment by agocke** [comment]
Probably a question for @samsp-msft

**Comment by danmosemsft** [comment]
I think we're all just figuring out what is useful to us, hence the question. I'm going to be bold and make it a user story under the single file epic. I think in general 'significant work items' make sense to have in the tree. Feel free to change.

**Comment by danmosemsft** [comment]
Making story so it appears in the tree  -- but now I see you have removed it @marek-safar ?

**Comment by agocke** [comment]
Update: cutting whole-program analysis of single-file for 6.0. Telemetry shows that most users are not using linking in conjunction with PublishSingleFile, so adding single-file analysis in the linker could produce several downsides, including slowing down publish significantly.

As a longer-term plan, adding the analysis to either a separate tool or inside crossgen is likely a better path here.
