### ISSUE TITLE
EventSourceLogger improvements

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#44515]
This issue helps keep track of open issues on making improvements for EventSourceLogger

- [ ] #33486 - Propagate state during ActivityStart
- [ ] #34739 - Improve exception serialization
- [ ] #36515 - Memory allocation improvement

cc: @shirhatti

**Comment by danmosemsft** [comment]
We're not using Team Epic -- @jeffschwMSFT I wonder whether we can delete it now to avoid this confusion

**Comment by danmosemsft** [comment]
@maryamariyan should this be tagged 'bottom up'? also stories should have an epic parent - presumably https://github.com/dotnet/runtime/issues/44314 here.

**Comment by jeffschwMSFT** [comment]
I flipped all the 'Team Epic's (which I saw) to 'user story' + 'bottom up work'
