### ISSUE TITLE
Users benefit from faster runtime startup due to reductions in runtime startup overhead

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44598]
.NET processes are spun up repeatedly as part of a developer's inner loop development process, including for the app itself being debugged.  We want to drive down the overheads across all tools employed as part of inner loop, and that includes reducing runtime startup costs wherever possible.

### Issues:
- [x] [TPA list building is contributing large % of time to startup](https://github.com/dotnet/runtime/issues/44545)
- [ ] [Environment.GetEnvironmentVariables() called multiple times during MVC app startup](https://github.com/dotnet/runtime/issues/44733)
- [ ] [Implement EventSource generator](https://github.com/dotnet/runtime/pull/45699)
- [ ] [Speed up type loading with R2R images](https://github.com/dotnet/runtime/issues/45066)
- [x] [Remove unnecessary regex from ASP.NET startup](https://github.com/dotnet/aspnetcore/pull/30855)
- [ ] [Improve startup time for EventSources](https://github.com/dotnet/runtime/pull/45105)
- [ ] [Avoid EventSource contention at startup](https://github.com/dotnet/runtime/issues/45059)
- [ ] [Exception performance with debugger attached](https://github.com/dotnet/runtime/issues/47617)
- [X] [Eliminate low-hanging fruit in Hello, World startup](https://github.com/dotnet/runtime/pull/44469)
- [X] [Allocations in Hello, World from Console.Write](https://github.com/dotnet/runtime/pull/44597)
- [X] [Allocations in ManifestBuilder.CreateManifestString in EventSource startup](https://github.com/dotnet/runtime/pull/44532) 
- [X] [Closure allocations from ServiceCollectionDescriptorExtensions at MVC startup](https://github.com/dotnet/runtime/pull/44696)
- [X] [Allocations from GetCustomAttributes impacting MVC startup](https://github.com/dotnet/runtime/pull/44694)
- [X] [Avoiding LINQ overheads in JsonConfiguration](https://github.com/dotnet/runtime/pull/44734)
- [X] [Avoiding string-related allocation in LogValuesFormatter ctor during startup](https://github.com/dotnet/runtime/pull/44746)
- [X] [Reduce Process.Start overhead](https://github.com/dotnet/runtime/pull/44691)
- [X] [Avoid allocations in LoggerRuleSelector in MVC startup](https://github.com/dotnet/runtime/pull/44753)
- [X] [Avoid CallSiteFactory allocations in MVC startup](https://github.com/dotnet/runtime/pull/44755)
- [X] [Avoid empty ParameterInfo[] allocations at startup](https://github.com/dotnet/runtime/pull/44759)
- [X] [Avoid string concats in CreateDefaultLogMessage](https://github.com/dotnet/runtime/pull/44765)
- [X] [Remove most LINQ usage from Microsoft.Extensions.Configuration](https://github.com/dotnet/runtime/pull/44825)
- [X] [Avoid expensive CertificateManager work when it's not enabled](https://github.com/dotnet/aspnetcore/pull/27956)
- [X] [Reduce Guid parsing times during startup](https://github.com/dotnet/runtime/pull/44918)
- [X] [Avoid LINQ usage in EnvironmentVariablesConfigurationProvider](https://github.com/dotnet/runtime/pull/44923)
- [X] [Improve throughput of GetEnvironmentVariables](https://github.com/dotnet/runtime/pull/45057)
- [X] [Skip invariant init test for Invariant](https://github.com/dotnet/runtime/pull/45064)
- [X] [Reduce MakeGenericType overhead impacting startup](https://github.com/dotnet/runtime/pull/45137)
- [X] [Reduce SafeHandles created enumerating certificates at startup](https://github.com/dotnet/runtime/pull/45166)
- [X] [Remove allocations from ObjectCache](https://github.com/dotnet/runtime/pull/45229)
- [X] [Reduce allocations in OptionsManager at startup](https://github.com/dotnet/runtime/pull/45231)
- [X] [Remove closure/delegate allocations from CreateLogger](https://github.com/dotnet/runtime/pull/45236)
- [X] [Improve OidLookup.ToLookup perf](https://github.com/dotnet/runtime/pull/46819)
- [X] [Reduce allocation in BigInteger used to process certificates](https://github.com/dotnet/runtime/pull/46895)
- [X] [Improve EventSource attribute lookup during ctor](https://github.com/dotnet/runtime/pull/45621)
- [X] [Remove more LINQ from dependency injection](https://github.com/dotnet/runtime/pull/47496)
- [X] [Remove boxing from configuration loading](https://github.com/dotnet/runtime/pull/47453)

**Comment by CatalinAdlerDF** [comment]
Consider the serverless functions scenarios as well; people still use cold startup perf to chose a particular language over the other.

**Comment by iSazonov** [comment]
I measured PowerShell startup. It seems there are delays in hostpolicy on realpath() and GetFileAttributesExW(). 
I hope performance improvements could be made there. (Is it really necessary to check for the existence of files?)
PerfView trace https://ru.files.fm/u/n2hqqsr7z
![image](https://user-images.githubusercontent.com/22290914/100316689-de128b80-2fdc-11eb-9454-0a05d842a0ab.png)
![image](https://user-images.githubusercontent.com/22290914/100316930-42cde600-2fdd-11eb-86e4-8ab580a415fe.png)

**Comment by jkotas** [comment]
@iSazonov This is tracked by #44545

**Comment by stephentoub** [comment]
All planned work for .NET 6 has been done here, with some nice improvements on startup.  I'm going to close this; there can still be further opportunistic work for the release.
