### ISSUE TITLE
System.Reflection work planned for .NET 7

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#44655]
This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.

### Features / User stories
- ~~[ ] [Developers using reflection invoke should be able to use ref struct](https://github.com/dotnet/runtime/issues/44327)~~
- ~~[ ] [Developers using Reflection should be able to use pointers and function pointers](https://github.com/dotnet/runtime/issues/44327)~~

The following are higher priority reflection issues that are affecting the community and for the most part, do not include features or bugs that have reasonable workarounds.

### MetadataLoadContext
- [x] [PathAssemblyResolver System.Reflection.MetadataLoadContext should be sealed or allow overrides](https://github.com/dotnet/runtime/issues/36753)

### General cleanup and bugs
- [x] [Assembly.CodeBase obsoletion is incomplete](https://github.com/dotnet/runtime/issues/42857)
- [x] [PseudoCustomAttribute.GetStructLayoutCustomAttribute returns incorrect data](https://github.com/dotnet/runtime/issues/12480)
- [x] [Type.IsPublic returns wrong answer for pointer and byref types](https://github.com/dotnet/runtime/issues/12355)
- [x] [Inconsistent GetRuntimeProperties() Behavior](https://github.com/dotnet/runtime/issues/28056)
- [x] [Allow GetProperties to order results by declaration order](https://github.com/dotnet/runtime/issues/46272)
- [x] [Attribute.GetCustomAttributes returns null when passed an unbound generic type](https://github.com/dotnet/runtime/issues/64335)
- [x] [Get info about generic attributes for open generic](https://github.com/dotnet/runtime/issues/64169)
- [x] [System.Reflection.Metadata doesn't handle generic attributes](https://github.com/dotnet/runtime/issues/58073) 
- [x] [Method binding by name with Type.DefaultBinder.BindToMethod fails with specific condition](https://github.com/dotnet/runtime/issues/66237)

### Reflection Emit
- [x] [TypeBuilder::CreateTypeInfo() should not throw COMException](https://github.com/dotnet/runtime/issues/43282)
- [x] [ModuleBuilder.GetType does not work with ignore case with certain unicode chars on Unix](https://github.com/dotnet/runtime/issues/18231)

### Backlog
- ~~[ ] [Support equivalent of AssemblyBuilder.Save to save in-memory IL to an assembly](https://github.com/dotnet/runtime/issues/62956)~~

**Comment by stephentoub** [comment]
@steveharter, I don't see https://github.com/dotnet/runtime/issues/15704 on the list.  Are we considering that at all?

**Comment by ThadHouse** [comment]
https://github.com/dotnet/runtime/issues/11354

This should probably be in here too

**Comment by steveharter** [comment]
>  I don't see #15704 on the list. Are we considering that at all?

`AssemblyBuilder.Save` in 5.0 was seriously discussed but didn't make the cut. I haven't heard any new blocking-status changes yet that would cause this to be a must-have.

@AArnott since you requested this feature in 5.0, what is the status now?

Some have been using https://github.com/Lokad/ILPack as an alternative.

**Comment by stephentoub** [comment]
> I haven't heard any new blocking-status changes yet that would cause this to be a must-have.

I called it out simply because it's got the second most upvotes of any issue in System.Reflection*.

**Comment by AArnott** [comment]
We still need it, @steveharter. Cutting it from 5.0 was reasonable from my POV because my team didn't need it before 6.0 anyway. But we do need a good story. You mention an alternative (ILPack) but I'll avoid responding to that because this and other workarounds are already discussed on the existing issue. If you'd like to pursue that further, we might pick up the conversation there, if that's ok with you.

**Comment by steveharter** [comment]
@ThadHouse 
>#11354
This should probably be in here too. There's no workaround for emitting functions with function pointers in their signatures.

That issue is linked in the "function pointer" section in https://github.com/dotnet/runtime/issues/44327

**Comment by buyaa-n** [comment]
[Triage:] moving to 8.0 for now

**Comment by steveharter** [comment]
Closing; issues not implemented moved to 8.0 or future

**Comment by steveharter** [comment]
8.0 epic: https://github.com/dotnet/runtime/issues/75358
