### ISSUE TITLE
Tracking runtime test failures on Android

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#44661]
Runtime test failures on Android:
- [ ] #44642 [Mono Android] Runtime tests couldn't pass build for Android target
- [ ] #44643 [Mono Android] Runtime tests used more memory than Android simulator allowed
- [ ] #44648 [Mono Android] Runtime tests failed due to Android app crashing

**Comment by SamMonoRT** [comment]
The Android x64 lane is Green. All failing tests are disabled. If you hit any failures in your PRs, please check for any actual regression. Thanks

**Comment by fanyang-mono** [comment]
Moving to milestone 8.0.0.

**Comment by fanyang-mono** [comment]
Test related issue. Moving to 9.0.0
