### ISSUE TITLE
Developers can target macOS UI with .NET 6 

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/runtime#44736]
This work is the evolution of existing Xamarin.Mac solution but built on CoreCLR VM foundations. The goal is to expose macOS APIs to allow developers to leverage macOS APIs such us Cocoa, Catalyst system and other native macOS APIS in the way they can build applications which run locally or are distributed via Mac App Store.

# Work Items
- [x] Low-level API support for Objective-C scenarios #44659
- [x] Thread and ThreadPool support for reference-counted resources #44213 https://github.com/dotnet/runtime/pull/52023
- [x] Enhance CoreCLR GC to support reference-counted interop
- [x] Support for Catalyst TFM #44882 https://github.com/dotnet/runtime/pull/47823
- [x] Enable Catalyst Runtime Packs #47517
- [x] Apple Silicon Support #43313
- [ ] Signal manipulation for existing scenarios where users have custom crash reporting mechanisms.
  - Mono semantics: https://www.mono-project.com/docs/advanced/signals/
 - [x] https://github.com/xamarin/xamarin-macios/issues/10818
 - [x] https://github.com/xamarin/xamarin-macios/issues/10312
 - [x] https://github.com/xamarin/xamarin-macios/issues/10413
 - [x] https://github.com/xamarin/xamarin-macios/issues/11392
 - [x] https://github.com/xamarin/xamarin-macios/issues/10215
 - [x] https://github.com/xamarin/xamarin-macios/issues/10216
 - [x] https://github.com/xamarin/xamarin-macios/issues/10700
 - [x] https://github.com/xamarin/xamarin-macios/issues/11724
 - [x] https://github.com/xamarin/xamarin-macios/issues/10452
 - [x] https://github.com/xamarin/xamarin-macios/issues/10508
 - [x] https://github.com/xamarin/xamarin-macios/issues/9835
 - [x] https://github.com/xamarin/xamarin-macios/issues/10646
 - [x] https://github.com/xamarin/xamarin-macios/issues/11667
 - [x] https://github.com/xamarin/xamarin-macios/issues/10504
 - [x] https://github.com/xamarin/xamarin-macios/issues/10170
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10470
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10405
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10254
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10251
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10249
 - [x] https://github.com/xamarin/xamarin-macios/issues/10210
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10051
 - [ ] https://github.com/xamarin/xamarin-macios/issues/9727
 - [ ] https://github.com/xamarin/xamarin-macios/issues/10659
 - [x] https://github.com/xamarin/xamarin-macios/issues/10679

**Comment by jkotas** [comment]
If we need compatibility for the existing bindings, we may also need to add "Special handling of nint/nuint/nfloat" in CoreCLR

**Comment by AaronRobinsonMSFT** [comment]
@rolfbjarne and @janvorli I have added a checkbox above for validating the signally logistics as they relate to customer crash collection mechanisms. I need to defer for how to validate these scenarios.

/cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
This is also an area where coreclr and mono provide different experiences.  For mono providing a hook so that textual traces would be produced was at the tip of possible.  coreclr provides an x-plat post mortem diagnostic experience (out of proc).  So this is likely an area where we can provide an enhanced experience in addition to the signal approach, but perhaps instead of that one as well.

**Comment by rolfbjarne** [comment]
@jeffschwMSFT my main concern is that we don't _prevent_ people from using custom crash-reporting mechanisms, and in that regard it's important to know if CoreCLR are using signals in any way right now (for instance: are NullReferenceExceptions implemented by handling SIGSEGVS like they are on Mono? And what out floating point exceptions such as division by zero / SIGFPE?) 

Also on some platforms it's not possible to do anything out of proc (this is the case on iOS - which is currently not a target platform for CoreCLR, but may be in the future).

**Comment by janvorli** [comment]
@rolfbjarne we use signals for handling hardware exceptions like SIGSEGV and SIGFPE on Linux, but not on MacOS where we use exception ports (I was planning to migrate to signals on macOS too soon). But we only handle them when they occur in our code (managed code for both and SIGSEGV also in a few related JIT helpers). When they happen at other places, we call the previously registered handler to give a chance to handle it e.g. in a custom host. 
If a native shared library loaded after the runtime registers such handler, we currently rely on it behaving the same way - handling the signals only when they know the signal belongs to their component and calling the previous handler if they don't.  
One important thing to note is that we register the SIGSEGV handler as using an alternate stack so that we can handle stack overflow and print full managed stack trace when it occurs. That might be something that the previously registered handlers may have a problem with. Our handler is able to run on both alternate stack and regular stack though in case some other component registers a SIGSEGV handler running on a regular stack and calls back to us.

**Comment by rolfbjarne** [comment]
@janvorli I think we'll have to come up with some solution then, because that will interfere with third-party crash reporters.

> If a native shared library loaded after the runtime registers such handler, we currently rely on it behaving the same way - handling the signals only when they know the signal belongs to their component and calling the previous handler if they don't.

The purpose of a crash reporter is to detect and report crashes _anywhere_ in an app, and they all assume that SIGSEGV/SIGFPE are bad and should be treated as a crash (rightfully so IMHO). They have no way of knowing that SIGSEGVs/SIGFPEs in certain parts of the app shouldn't be fatal.

The way we solved this with Xamarin was to let mono handle any signals first, and then chain to the previous handler (like CoreCLR doing) + add API to have third-party code (re)install mono's signal handlers, so that third-party code doesn't have to be initialized before mono (which might not be possible).

This is described here: https://www.mono-project.com/docs/advanced/signals/

This use case is narrow enough that I don't think we have to provide an identical API in CoreCLR, but we should at least find a solution to the problem.

**Comment by jkotas** [comment]
What are the third-party crash reporters that this is important to solve for?

**Comment by rolfbjarne** [comment]
@jkotas 

> What are the third-party crash reporters that this is important to solve for?

Crashlytics is one example of a third party crash reporter some of our customers use.

**Comment by bruno-garcia** [comment]
[Sentry](https://sentry.io/) has customers on multiple versions of Mono, .NET Core and .NET Framework. Obviously .NET 5 too.

**Comment by danmoseley** [comment]
@steveisok @marek-safar can we close this now? are any tasks remaining for the 6.0 release?

**Comment by joperezr** [comment]
@steveisok @marek-safar friendly ping 😄

**Comment by marek-safar** [comment]
We can close it if it's bothering you but this will be fully completed after GA

**Comment by joperezr** [comment]
Not bothering for sure 😄 just doing bookkeeping on issues marked as 6.0 for our areas. If this will be completed post 6.0 but it's not finished yet, I'll just swith the milestone.

**Comment by mairaw** [comment]
This issue title seems to be targeted at .NET 6 and I'm trying to clean up the .NET 6 project. Do we need to update the issue or create a new one?

**Comment by jeffhandley** [comment]
> This issue title seems to be targeted at .NET 6 and I'm trying to clean up the .NET 6 project. Do we need to update the issue or create a new one?

I defer to @marek-safar on this
