### ISSUE TITLE
QUIC API mega-issue

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#44786]
This is a mega-issue for tracking all issues related to QUIC API definition and semantics.

- [ ] Should QuicStream require Flush? https://github.com/dotnet/runtime/issues/44782
- [x] Define QuicConnection stream limit handling: https://github.com/dotnet/runtime/issues/32079
- [ ] Shutdown/Abort/Dispose handling for QuicStream: https://github.com/dotnet/runtime/issues/756, https://github.com/dotnet/runtime/issues/32075
- [ ] Dispose behavior for QuicConnection and QuicListener: https://github.com/dotnet/runtime/issues/32142
- [x] Issues with QuicListener.Start and QuicListener.LocalEndPoint: https://github.com/dotnet/runtime/issues/2262
- [ ] QuicConnection.RemoteEndPoint should be IPEndPoint: https://github.com/dotnet/runtime/issues/43000

If I've missed anything, or new issues are added, please comment. 

If you have thoughts on particular API issues, please add them to the linked issues above. 

cc @scalablecory @stephentoub @jkotalik @Tratcher @halter73 @davidfowl @rzikm

**Comment by wegylexy** [comment]
Please see https://github.com/wegylexy/runtime/pull/1 for datagram support, thanks.

**Comment by wegylexy** [comment]
created #53533 for datagram API suggestion just now

**Comment by ManickaP** [comment]
Closing as this is covered by https://github.com/dotnet/runtime/issues/69675 https://github.com/dotnet/runtime/issues/68902 and https://github.com/dotnet/runtime/issues/67560
