### ISSUE TITLE
Reducing Managed Libraries Testing Infrastructure Size

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#45126]
We need to optimize libraries testing infrastructure to work better with testing scenarios which involve AOT. Per our previous findings, we are right now around over 20 MB for most of them.

Approximate libraries size per single test suite/file
Android        ~22.6MB (12.5MB compressed)
iOS            ~22.6MB
Wasm           ~15.6MB

We would like to get to about 2MB per test suite to make the whole testing faster and less demanding of resources. It takes at least 30 min now to compile a single 15 MB trimmed Wasm test suite.

## Work Items

- [ ] Resolve testing framework to be trimming safe
- [ ] Enable aggressive trimming for all dependencies
- [ ] Consider removing legacy non-netcoreapp dependencies

## Update
We were able to significantly reduce the infrastructure by aggressively trimming out assemblies not being used. Our primary use case for this was to help build AOT for wasm to reduce the time it took to build the `.wasm` file.

Similarly, we had reduced the size for Android, but we had not investigated significantly for iOS yet.

I think the rest of this work should be pushed to 7.0.0

**Comment by jkotas** [comment]
cc @ViktorHofer

**Comment by mdh1418** [comment]
We were able to significantly reduce the infrastructure by aggressively trimming out assemblies not being used. Our primary use case for this was to help build AOT for wasm to reduce the time it took to build the `.wasm` file.

Similarly, we had reduced the size for Android, but we had not investigated significantly for iOS yet.

I think the rest of this work should be pushed to 7.0.0
