### ISSUE TITLE
Developers can convert between JSON data and C# `dynamic`, and also use a mutable JSON DOM type

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#45188]
## Work

- [x] `dynamic` https://github.com/dotnet/runtime/issues/29690
- [x] Mutable JSON DOM https://github.com/dotnet/runtime/issues/30436
- [x] We should be able serialize and deserialize from DOM https://github.com/dotnet/runtime/issues/31274
- [x] Add JsonElement.ToObject<T>() https://github.com/dotnet/runtime/issues/40393
- [x] Create primitives rather than `JsonElement` when deserializing `System.Object` https://github.com/dotnet/runtime/issues/29960

**Comment by danmosemsft** [comment]
@layomia this "user story" needs to be assigned to an engineering owner -- I'm guessing you? need not be the person who will actually do it, but the person that is responsible at the moment.

**Comment by layomia** [comment]
Yup I'll assign myself and work with @steveharter to get these in.

**Comment by danmoseley** [comment]
@layomia can we move this to "complete" (on the project board) and close it now?

For those observing: the although the "dynamic" keyword part here was done, we have removed it for 6.0: https://github.com/dotnet/docs/issues/25105

**Comment by layomia** [comment]
@danmoseley yes we can.
