### ISSUE TITLE
Developers using JsonSerializer have support for polymorphic types

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#45189]
### Work

- [x] `JsonConverterAttribute` cannot be applied to an interface https://github.com/dotnet/runtime/issues/33112
- [x] Allow custom `JsonConverter`s for base classes https://github.com/dotnet/runtime/issues/30427
- [ ] Serialization https://github.com/dotnet/runtime/issues/29937
- [ ] Deserialization https://github.com/dotnet/runtime/issues/30083
- [ ] Serialization of properties from inherited interfaces vs abstract base classes https://github.com/dotnet/runtime/issues/41749

**Comment by StingyJack** [comment]
System.Text.Json is not going to be usable until it can handle serialization of objects. Even then, if including all of the properties is not made the default behavior I'm still going to have to avoid using it. 

Why would an entire product team think that any data loss would be acceptable? Especially by default.

**Comment by layomia** [comment]
@StingyJack

Extending polymorphic support has always been on the roadmap for System.Text.Json. We do not consider this feature an edge case. We just couldn't get to it in previous releases due to product scoping and time constraints. As this issue indicates, it is being planned for .NET 6.0.

Polymorphic (de)serialization cannot be made the default behavior because that would be a breaking change from previous versions of System.Text.Json. Polymorphic serialization can also lead to accidental information disclosure when a object is treated as a different type than declared to the serializer. Such behavior needs to be opt-in only.

Not having built-in support for polymorphic is not a ship-blocker as many applications do not need this feature. Following up on https://github.com/dotnet/runtime/issues/45764: System.Text.Json was not designed to be a drop-in replacement for Newtonsoft.Json. You are free to continue using it if it satisfies your use cases. Please see our [migration guide](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0) for some clarity about the relationship between the two libraries:

> System.Text.Json focuses primarily on performance, security, and standards compliance. It has some key differences in default behavior and doesn't aim to have feature parity with Newtonsoft.Json. For some scenarios, System.Text.Json has no built-in functionality, but there are recommended workarounds. For other scenarios, workarounds are impractical. If your application depends on a missing feature, consider filing an issue to find out if support for your scenario can be added.

**Comment by StingyJack** [comment]
@layomia - A Breaking Change means just incrementing the Major Version number I thought. You can say that this is not intended to be a drop in replacement for newtonsoft's package, but being able to serialize an object completely is one of those things that is expected to work in a package like this. What good is the performance going to be to me if its not able to do the primary job? Is getting it to do the complete job going to net worse performance than the existing package?

If you asked 100 random .net developers (that are not already familiar with this shortfall of S.T.J) what Polymorphic Serialization is, you would get maybe one that could correctly answer what it meant, but I would bet $1 that this affects more than 75% of them.  The doc page should say "Can serialize base class members? Not supported"

**Comment by dmikov** [comment]
Please, please keep deserializing the shape of the declared type by default. This unintended information disclosure was the thing I hated about Json.Net the most. It is imperative that if your array of type User, it doesn't show Parent instead. It has to be opt-in. Thank you for making it for us.

**Comment by StingyJack** [comment]
Anyone concerned about information disclosure should be using DTOs for the exposed API that don't have the unwanted properties on them. 

Asking to have a tool crippled for everyone else because some people are unwilling to model their API data is a request that should not be taken seriously.

**Comment by qsdfplkj** [comment]
> Polymorphic serialization can also lead to accidental information disclosure when a object is treated as a different type than declared to the serializer. Such behavior needs to be opt-in only.

this is only valid when the declared property type is object.  If you deserialize to an interface or naar type you know exactly what to expect. include type information only when the runtime type isn’t the same as the declared type and you will be safe.

**Comment by StingyJack** [comment]
> naar type 

@qsdfplkj Is this a typo or an actual thing?

**Comment by qsdfplkj** [comment]
Isn’t it just that JavaScript is not really polymorphic but a dynamic language.

**Comment by eiriktsarpalis** [comment]
Closing this, since it is specifically tracking polymorphism-related work for .NET 6. Individual pending work items have been reassigned to different milestones.

**Comment by StingyJack** [comment]
@eiriktsarpalis - are those other work items something that non-msft users can see?

**Comment by eiriktsarpalis** [comment]
All planning and issue tracking happens publicly on github: I was referring to the open issues that are linked in the original post.
