### ISSUE TITLE
Trimming provides similar Xamarin experience in .NET 6

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#45714]
Mono and CoreCLR continue to increase code sharing and Xamarin is moving to consume more of the .NET Core surface area.

# Goals

- [ ] Trimmed Xamarin apps using .NET 6 produce similar behavior as before
- [ ] Trimmed Xamarin apps with .NET 6 are roughly the same size
- [ ] Xamarin apps produce minimal linker warnings and only for linker-unsafe constructs

# Work
- [ ] Investigate representative Xamarin app with trimming enabled
  - [ ] App still works
  - [ ] Catalog and remove warnings
  - [ ] Investigate with custom trim steps disabled

**Comment by marek-safar** [comment]
@jeffschwMSFT please don't tag user stories which have nothing to do with assembly loader with that area it's very confusing on the planning

**Comment by jeffschwMSFT** [comment]
would you prefer meta?  I am fine either way.

**Comment by marek-safar** [comment]
yep, certainly meta

**Comment by marek-safar** [comment]
I think we should close this issue, it duplicates existing users stories #44654 and #43078

**Comment by jeffschwMSFT** [comment]
It feels distinct to me.  This is an engineering tracking list of work.  I agree these should be linked together in a coherent way.  I see these items as a balance between engineering efficiency and tracking.  If it is more efficient to have them separate, I am ok with that.

**Comment by marek-safar** [comment]
Yes, this is engineering tracking and not user-story and we already track elsewhere in more details

**Comment by agocke** [comment]
@marek-safar Can you point me to those issues? I'm trying to build up a list of all Pri:0 linker items for Xamarin in .NET 6

**Comment by agocke** [comment]
https://github.com/dotnet/runtime/issues/43078 and https://github.com/dotnet/runtime/issues/44317 seem sufficient -- they cover the user experience for trimming, and size in the second one. Closing in favor of those issues
