### ISSUE TITLE
Perform simple https request with System.Security.Cryptography.Native.Android PAL

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#45739]
In order to support a simple https request, we need the following pinvokes to directly integrate with Android api's:

```
await new HttpClient().GetStringAsync("https://mail.google.com/mail/");
```

- [ ] `CryptoNative_BioCtrlPending`
- [ ] `CryptoNative_BioDestroy`
- [ ] `CryptoNative_BioNewFile`
- [ ] `CryptoNative_BioRead`
- [ ] `CryptoNative_BioWrite`
- [ ] `CryptoNative_CheckX509Hostname`
- [ ] `CryptoNative_CreateMemoryBio`
- [ ] `CryptoNative_EncodeAsn1Integer`
- [ ] `CryptoNative_EnsureLibSslInitialized`
- [ ] `CryptoNative_EnsureOpenSslI`nitialized`
- [ ] `CryptoNative_ErrClearError`
- [ ] `CryptoNative_ErrPeekError`
- [ ] `CryptoNative_ErrPeekLastError`
- [ ] `CryptoNative_GetAsn1IntegerDerSize`
- [ ] `CryptoNative_GetAsn1StringBytes`
- [ ] `CryptoNative_GetObjectDefinitionByName`
- [ ] `CryptoNative_GetX509NameRawBytes`
- [ ] `CryptoNative_GetX509RootStoreFile`
- [ ] `CryptoNative_GetX509RootStorePath`
- [ ] `CryptoNative_GetX509StackField`
- [ ] `CryptoNative_GetX509StackFieldCount`
- [ ] `CryptoNative_GetX509Thumbprint`
- [ ] `CryptoNative_IsSslRenegotiatePending`
- [ ] `CryptoNative_IsSslStateOK`
- [ ] `CryptoNative_LookupFriendlyNameByOid`
- [ ] `CryptoNative_NewX509Stack`
- [ ] `CryptoNative_ObjObj2Txt`
- [ ] `CryptoNative_PemReadX509FromBio`
- [ ] `CryptoNative_PushX509StackField`
- [ ] `CryptoNative_ReadX509AsDerFromBio`
- [ ] `CryptoNative_RecursiveFreeX509Stack`
- [ ] `CryptoNative_SetCiphers`
- [ ] `CryptoNative_SetEncryptionPolicy`
- [ ] `CryptoNative_SetProtocolOptions`
- [ ] `CryptoNative_SslCreate`
- [ ] `CryptoNative_SslCtxCreate`
- [ ] `CryptoNative_SslCtxDestroy`
- [ ] `CryptoNative_SslCtxSetQuietShutdown`
- [ ] `CryptoNative_SslDoHandshake`
- [ ] `CryptoNative_SslGet0AlpnSelected`
- [ ] `CryptoNative_SslGetCurrentCipherId`
- [ ] `CryptoNative_SslGetError`
- [ ] `CryptoNative_SslGetPeerCertChain`
- [ ] `CryptoNative_SslGetPeerCertificate`
- [ ] `CryptoNative_SslGetVersion`
- [ ] `CryptoNative_SslRead`
- [ ] `CryptoNative_SslSetBio`
- [ ] `CryptoNative_SslSetConnectState`
- [ ] `CryptoNative_SslSetTlsExtHostName`
- [ ] `CryptoNative_SslV2_3Method`
- [ ] `CryptoNative_SslWrite`
- [ ] `CryptoNative_Tls13Supported`
- [ ] `CryptoNative_X509ChainNew`
- [ ] `CryptoNative_X509CheckPurpose`
- [ ] `CryptoNative_X509Destroy`
- [ ] `CryptoNative_X509ExtensionGetData`
- [ ] `CryptoNative_X509ExtensionGetOid`
- [ ] `CryptoNative_X509GetExt`
- [ ] `CryptoNative_X509GetExtCount`
- [ ] `CryptoNative_X509GetIssuerName`
- [ ] `CryptoNative_X509GetSerialNumber`
- [ ] `CryptoNative_X509GetSubjectName`
- [ ] `CryptoNative_X509StackAddDirectoryStore`
- [ ] `CryptoNative_X509StackAddMultiple`
- [ ] `CryptoNative_X509StoreCtxCreate`
- [ ] `CryptoNative_X509StoreCtxDestroy`
- [ ] `CryptoNative_X509StoreCtxGetChain`
- [ ] `CryptoNative_X509StoreCtxGetError`
- [ ] `CryptoNative_X509StoreCtxInit`
- [ ] `CryptoNative_X509StoreCtxRebuildChain`
- [ ] `CryptoNative_X509StoreDestory`
- [ ] `CryptoNative_X509StoreSetVerifyTime`
- [ ] `CryptoNative_X509UpRef`
- [ ] `CryptoNative_X509VerifyCert`
