### ISSUE TITLE
Ensure Tests Pass Using System.Security.Cryptography.Native.Android PAL

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#45740]
The following test suites are impacted by Android PAL and should pass.

## System.Security.Cryptography

- [x] System.Security.Cryptography.Algorithms.Tests
  <details><summary>Status - Total: 2581 | Passed: 2568 | Failed: 0 | Skipped: 13</summary>

  - [x] System.Security.Cryptography.Algorithms.Tests.AesCcmTests
  - [x] System.Security.Cryptography.Algorithms.Tests.AesGcmTests
  - [x] System.Security.Cryptography.Algorithms.Tests.AesTests
  - [x] System.Security.Cryptography.Algorithms.Tests.DSACreateTests
  - [x] System.Security.Cryptography.Algorithms.Tests.DSATests
  - [x] System.Security.Cryptography.Algorithms.Tests.ECDsaTests
  - [x] System.Security.Cryptography.Algorithms.Tests.HKDFTests+HkdfByteArrayTests
  - [x] System.Security.Cryptography.Algorithms.Tests.HKDFTests+HkdfSpanTests
  - [x] System.Security.Cryptography.Algorithms.Tests.IncrementalHashTests
  - [x] System.Security.Cryptography.Algorithms.Tests.PKCS1MaskGenerationMethodTest
  - [x] System.Security.Cryptography.Algorithms.Tests.RSACreateTests
  - [x] System.Security.Cryptography.Algorithms.Tests.RSATests
  - [x] System.Security.Cryptography.Algorithms.Tests.SignatureDescriptionTests
  - [x] System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests
  - [x] System.Security.Cryptography.DeriveBytesTests.Rfc2898OneShotTests
  - [x] System.Security.Cryptography.DeriveBytesTests.Rfc2898Tests
  - [x] System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests
  - [x] System.Security.Cryptography.Dsa.Tests.DsaArraySignatureFormatTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSAImportExport
  - [x] System.Security.Cryptography.Dsa.Tests.DSAKeyFileTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration
  - [x] System.Security.Cryptography.Dsa.Tests.DSAKeyPemTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignatureFormatterTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignVerify_Array
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignVerify_Span
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream
  - [x] System.Security.Cryptography.Dsa.Tests.DsaSpanSignatureFormatTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSAXml
  - [x] System.Security.Cryptography.EcDiffieHellman.Tests.ECDhKeyFileTests
  - [x] System.Security.Cryptography.EcDiffieHellman.Tests.ECDiffieHellmanPublicKeyTests
  - [x] System.Security.Cryptography.EcDiffieHellman.Tests.ECDiffieHellmanTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDiffieHellmanKeyPemTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaArrayOffsetSignatureFormatTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaArraySignatureFormatTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaImportExportTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaKeyFileTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaKeyPemTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaSpanSignatureFormatTests
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaTests_Array
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaTests_Span
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaTests_Stream
  - [x] System.Security.Cryptography.EcDsa.Tests.ECDsaXml
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.AesCipherTests
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.AesCornerTests
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.AesManagedTests
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.AesModeTests
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.DecryptorReusabilty
  - [x] System.Security.Cryptography.Encryption.Des.Tests.DesCipherTests
  - [x] System.Security.Cryptography.Encryption.Des.Tests.DesContractTests
  - [x] System.Security.Cryptography.Encryption.Des.Tests.DesTests
  - [x] System.Security.Cryptography.Encryption.RC2.Tests.RC2ContractTests
  - [x] System.Security.Cryptography.Encryption.RC2.Tests.RC2Tests
  - [x] System.Security.Cryptography.Encryption.Rijndael.Tests.RijndaelTests
  - [x] System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests
  - [x] System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESContractTests
  - [x] System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESReusabilityTests
  - [x] System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.BlockSizeValueTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.HashDerivedTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.HmacMD5Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.HmacSha1Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.HmacSha256Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.HmacSha384Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.HmacSha512Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.InvalidUsageTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.MD5Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.ReusabilityTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha1ManagedTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha1Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha256ManagedTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha256Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha384ManagedTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha384Tests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha512ManagedTests
  - [x] System.Security.Cryptography.Hashing.Algorithms.Tests.Sha512Tests
  - [x] System.Security.Cryptography.RNG.Tests.RandomNumberGeneratorTests
  - [x] System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array
  - [x] System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span
  - [x] System.Security.Cryptography.Rsa.Tests.ImportExport
  - [x] System.Security.Cryptography.Rsa.Tests.KeyGeneration
  - [x] System.Security.Cryptography.Rsa.Tests.RSAKeyExchangeFormatterTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAKeyPemTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSASignatureFormatterTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAXml
  - [x] System.Security.Cryptography.Rsa.Tests.SignVerify_Array
  - [x] System.Security.Cryptography.Rsa.Tests.SignVerify_Span
  - [x] System.Security.Cryptography.Tests.PaddingModeTests
  </details>

- [x] System.Security.Cryptography.Csp.Tests
  <details><summary>Status - Total: 648 | Passed: 598 | Failed: 0 | Skipped: 50</summary>

  - [x] System.Security.Cryptography.Csp.Tests.CreateTransformCompat
  - [x] System.Security.Cryptography.Csp.Tests.CspParametersTests
  - [x] System.Security.Cryptography.Csp.Tests.DSACryptoServiceProviderTests
  - [x] System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderBackCompat
  - [x] System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderTests
  - [x] System.Security.Cryptography.DeriveBytesTests.PasswordDeriveBytesTests
  - [x] System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests
  - [x] System.Security.Cryptography.Dsa.Tests.DsaArraySignatureFormatTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSAImportExport
  - [x] System.Security.Cryptography.Dsa.Tests.DSAKeyFileTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration
  - [x] System.Security.Cryptography.Dsa.Tests.DSAKeyPemTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignatureFormatterTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignVerify_Array
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignVerify_Span
  - [x] System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream
  - [x] System.Security.Cryptography.Dsa.Tests.DsaSpanSignatureFormatTests
  - [x] System.Security.Cryptography.Dsa.Tests.DSAXml
  - [x] System.Security.Cryptography.Encryption.Aes.Tests.AesCryptoServiceProviderTests
  - [x] System.Security.Cryptography.Encryption.Des.Tests.DesCipherTests
  - [x] System.Security.Cryptography.Encryption.Des.Tests.DESCryptoServiceProviderTests
  - [x] System.Security.Cryptography.Encryption.Des.Tests.DesTests
  - [x] System.Security.Cryptography.Encryption.MD5.Tests.MD5CryptoServiceProviderTests
  - [x] System.Security.Cryptography.Encryption.RC2.Tests.RC2CryptoServiceProviderTests
  - [x] System.Security.Cryptography.Encryption.RC2.Tests.RC2Tests
  - [x] System.Security.Cryptography.Encryption.SHA1.Tests.SHAxCryptoServiceProviderTests
  - [x] System.Security.Cryptography.Encryption.TripleDES.Tests.TripleDESCryptoServiceProviderTests
  - [x] System.Security.Cryptography.RNG.Tests.RNGCryptoServiceProviderTests
  - [x] System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array
  - [x] System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span
  - [x] System.Security.Cryptography.Rsa.Tests.ImportExport
  - [x] System.Security.Cryptography.Rsa.Tests.KeyGeneration
  - [x] System.Security.Cryptography.Rsa.Tests.RSAImportExportCspBlobTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAKeyExchangeFormatterTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAKeyPemTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSASignatureFormatterTests
  - [x] System.Security.Cryptography.Rsa.Tests.RSAXml
  - [x] System.Security.Cryptography.Rsa.Tests.SignVerify_Array
  - [x] System.Security.Cryptography.Rsa.Tests.SignVerify_Span
  </details>

- [x] System.Security.Cryptography.Encoding.Tests:
  <details><summary>Status - Total: 273 | Passed: 273 | Failed: 0 | Skipped: 0</summary>

  - [x] System.Security.Cryptography.Encoding.Tests.AsnEncodedDataCollectionTests
  - [x] System.Security.Cryptography.Encoding.Tests.AsnEncodedDataTests
  - [x] System.Security.Cryptography.Encoding.Tests.Base64TransformsTests
  - [x] System.Security.Cryptography.Encoding.Tests.OidCollectionTests
  - [x] System.Security.Cryptography.Encoding.Tests.OidTests
  - [x] System.Security.Cryptography.Encoding.Tests.PemEncodingFindThrowingTests
  - [x] System.Security.Cryptography.Encoding.Tests.PemEncodingFindTryTests
  - [x] System.Security.Cryptography.Encoding.Tests.PemEncodingTests
  </details>

- [x] System.Security.Cryptography.Pkcs.Tests
  <details><summary>Status - Total: 823 | Passed: 803 | Failed: 0 | Skipped: 20</summary>

  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.CertificateTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.ContentEncryptionAlgorithmTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsRsaPaddingMode
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsUsingCertWithPrivateKey
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsUsingExplicitPrivateKey
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.GeneralTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoRsaOaepCertTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoRsaPaddingModeTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.StateTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.SubjectIdentifierTests
  - [x] System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.UnprotectedAttributeTests
  - [x] System.Security.Cryptography.Pkcs.Tests.AlgorithmIdentifierTest
  - [x] System.Security.Cryptography.Pkcs.Tests.CmsRecipientCollectionTests
  - [x] System.Security.Cryptography.Pkcs.Tests.CmsSignerTests
  - [x] System.Security.Cryptography.Pkcs.Tests.CounterSigningDerOrder
  - [x] System.Security.Cryptography.Pkcs.Tests.CryptographicAttributeObjectCollectionTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.CertBagTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.CustomBagTypeTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12BuilderTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12SafeBagTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12SafeContentsTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs9LocalKeyIdTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.SafeContentsBagTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.SecretBagTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.ShroudedKeyBagTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs12.SimpleRead
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs8PrivateKeyInfoTests
  - [x] System.Security.Cryptography.Pkcs.Tests.Pkcs9AttributeTests
  - [x] System.Security.Cryptography.Pkcs.Tests.RecipientInfoCollectionTests
  - [x] System.Security.Cryptography.Pkcs.Tests.SignedCmsTests
  - [x] System.Security.Cryptography.Pkcs.Tests.SignedCmsWholeDocumentTests
  - [x] System.Security.Cryptography.Pkcs.Tests.SignerInfoTests
  - [x] System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests
  - [x] System.Security.Cryptography.Pkcs.Tests.TimestampTokenInfoTests
  - [x] System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests
  </details>

- [x] System.Security.Cryptography.Primitives.Tests
  <details><summary>Status - Total: 527 | Passed: 527 | Failed: 0 | Skipped: 0</summary>
  - [x] System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests
  - [x] System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptographicExceptionTests
  - [x] System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptoStreamTests
  - [x] System.Security.Cryptography.Encryption.Tests.Asymmetric.TrivialTests
  - [x] System.Security.Cryptography.Encryption.Tests.Symmetric.MinimalTests
  - [x] System.Security.Cryptography.Encryption.Tests.Symmetric.TrivialTests
  - [x] System.Security.Cryptography.Hashing.Tests.HashAlgorithmTest
  - [x] System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest
  - [x] System.Security.Cryptography.Hashing.Tests.KeyedHashAlgorithmTest
  - [x] System.Security.Cryptography.Hashing.Tests.SimpleHashAlgorithmTest
  - [x] System.Security.Cryptography.Primitives.Tests.FixedTimeEqualsTests
  - [x] System.Security.Cryptography.Primitives.Tests.HashAlgorithmNameTests
  - [x] System.Security.Cryptography.Primitives.Tests.PbeParametersTests
  - [x] System.Security.Cryptography.Primitives.Tests.SymmetricAlgorithmTests
  - [x] System.Security.Cryptography.Primitives.Tests.ZeroMemoryTests
  </details>

- [x] System.Security.Cryptography.X509Certificates.Tests
  <details><summary>Status - Total: 1057 | Passed: 1055 | Failed: 0 | Skipped: 2</summary>

  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestApiTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestChainTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestUsageTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.ECDsaX509SignatureGeneratorTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.PrivateKeyAssociationTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.RSAPkcs1X509SignatureGeneratorTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.RSAPssX509SignatureGeneratorTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.SubjectAlternativeNameBuilderTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CertTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.ChainTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CollectionImportTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CollectionTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.ContentTypeTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.CtorTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.ExportTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.ExtensionsTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.FindTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.ImportTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.NameTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_Collection
  - [x] System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_SingleCert
  - [x] System.Security.Cryptography.X509Certificates.Tests.PfxTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.PropsTests
  - [ ] System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests (out of 43 tests, 42 passed, 0 skipped)
  - [x] System.Security.Cryptography.X509Certificates.Tests.X500DistinguishedNameEncodingTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.X500DistinguishedNameTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.X509Certificate2PemTests
  - [x] System.Security.Cryptography.X509Certificates.Tests.X509StoreTests
  </details>

- [x] System.Security.Cryptography.Xml.Tests
  <details><summary>Status - Total: 585 | Passed: 585 | Failed: 0 | Skipped: 0</summary>

  - [x] System.Security.Cryptography.Xml.Tests.CipherDataTests
  - [x] System.Security.Cryptography.Xml.Tests.DataObjectTest
  - [x] System.Security.Cryptography.Xml.Tests.DataObjectTests
  - [x] System.Security.Cryptography.Xml.Tests.DataReferenceTest
  - [x] System.Security.Cryptography.Xml.Tests.DSAKeyValueTest
  - [x] System.Security.Cryptography.Xml.Tests.EncryptedXmlTest
  - [x] System.Security.Cryptography.Xml.Tests.EncryptedXmlTests
  - [x] System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric
  - [x] System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingSymmetric
  - [x] System.Security.Cryptography.Xml.Tests.EncryptingDecryptingSymmetricKeyWrap
  - [x] System.Security.Cryptography.Xml.Tests.EncryptionMethodTests
  - [x] System.Security.Cryptography.Xml.Tests.EncryptionPropertyCollectionTest
  - [x] System.Security.Cryptography.Xml.Tests.EncryptionPropertyTest
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfo_ArbitraryElements
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfoNameTest
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfoNodeTest
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfoRetrievalMethodTest
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfoTest
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfoTests
  - [x] System.Security.Cryptography.Xml.Tests.KeyInfoX509DataTest
  - [x] System.Security.Cryptography.Xml.Tests.Reference_ArbitraryElements
  - [x] System.Security.Cryptography.Xml.Tests.ReferenceTest
  - [x] System.Security.Cryptography.Xml.Tests.RSAKeyValueTest
  - [x] System.Security.Cryptography.Xml.Tests.Signature_ArbitraryElements
  - [x] System.Security.Cryptography.Xml.Tests.SignatureTest
  - [x] System.Security.Cryptography.Xml.Tests.SignedInfo_ArbitraryElements
  - [x] System.Security.Cryptography.Xml.Tests.SignedInfoTest
  - [x] System.Security.Cryptography.Xml.Tests.SignedXml_Limits
  - [x] System.Security.Cryptography.Xml.Tests.SignedXml_SignatureMethodAlgorithm
  - [x] System.Security.Cryptography.Xml.Tests.SignedXmlTest
  - [x] System.Security.Cryptography.Xml.Tests.SignedXmlTests
  - [x] System.Security.Cryptography.Xml.Tests.SigningAndVerifying
  - [x] System.Security.Cryptography.Xml.Tests.SigningAndVerifyingWithCustomSignatureMethod
  - [x] System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert
  - [x] System.Security.Cryptography.Xml.Tests.TransformChainTest
  - [x] System.Security.Cryptography.Xml.Tests.TransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigBase64TransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigC14NTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigEnvelopedSignatureTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigExcC14NTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigExcC14NWithCommentsTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigXPathTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlDsigXsltTransformTest
  - [x] System.Security.Cryptography.Xml.Tests.XmlLicenseEncryptedRef
  - [x] System.Security.Cryptography.Xml.Tests.XmlLicenseTransformTest
  </details>

## System.Net

- [ ] System.Net.Http.Functional.Tests
  - Uses non-system-default certificate validation
- [x] System.Net.Http.Unit.Tests
- [ ] System.Net.HttpListener.Tests
  - Currently skipped on Mono
- [x] System.Net.NameResolution.Functional.Tests
- [x] System.Net.Quic.Functional.Tests
- [ ] System.Net.Requests.Tests
  - Uses non-system-default certificate validation
- [ ] System.Net.Security.Tests
  - Uses non-system-default certificate validation
- [x] System.Net.Security.Unit.Tests
- [x] System.Net.WebSockets.Tests
- [x] System.Net.WebSockets.Client.Tests

## Other

- [x] Common.Tests
- [x] Microsoft.Extensions.Configuration.Xml.Tests
- [x] Microsoft.Extensions.DependencyModel.Tests
- [x] Microsoft.Extensions.FileProviders.Physical.Tests
- [x] System.Formats.Asn1.Tests
- [x] System.Formats.Cbor.Tests
- [x] System.IO.Tests
- [x] System.IO.Compression.Brotli.Tests
- [x] System.IO.MemoryMappedFiles.Tests
- [x] System.IO.Pipelines.Tests
- [x] System.IO.UnmanagedMemoryStream.Tests
- [x] System.Reflection.Metadata.Tests

**Comment by jkoritzinsky** [comment]
Here's a tool for generating a list of test collections based on the XUnit test results from an assembly:
https://gist.github.com/jkoritzinsky/0f67aee654cc53997fdcf53e127d1c07
