### ISSUE TITLE
Android developers can produce smaller apps when targeting .NET6

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#45831]
This is a tracking issue for all cross teamwork to deliver the same or better app size for Xamarin Android workloads which migrate to .NET6

## Goals
- [ ] Same or smaller size [SingleActivity](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc) app targetting arm64 (less than 4.78 MB)
- [ ] Same or smaller size default Xamarin.Forms [app](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc) (less than 10.0 MB)

## Work Items
- [x] Core Managed libraries size reduction on top of #44530
- [ ] Android-specific size reduction work https://github.com/xamarin/xamarin-android/projects/15
- [ ] MAUI-specific size reduction work
- [ ] Enable size tracking testing infrastructure for netcore
  - [x] Add size tracking for Android functional tests
  - [ ] Add size tracking for Xamarin-Android sample
  - [ ] Add size tracking for MAUI Android sample

**Comment by danmoseley** [comment]
@marek-safar can we close this now?

**Comment by steveisok** [comment]
@SamMonoRT I think we're good here.  OK to close?

**Comment by SamMonoRT** [comment]
This work is completed. Closing the issue.
