### ISSUE TITLE
iOS developers can produce smaller apps when targeting .NET6

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#45832]
This is a tracking issue for all cross teamwork to deliver the same or better app size for Xamarin iOS/tvOS Xamarin apps migrating to .NET6

## Goals
- [ ] Same or smaller size [SingleView](https://github.com/xamarin/xamarin-macios/issues/10249) app for release arm64 output (less than 4.35 MB)
- [ ] Same or smaller size default MAUI app template for iOS than Xamarin.Forms (TBD)

## Work Items
- [x] Core Managed libraries size reduction on top of #44530
	- [x] #46915
- [x] iOS-specific size reduction work https://github.com/xamarin/xamarin-macios/issues/10249
- [x] MAUI-specific size reduction work
- [x] Enable size tracking testing infrastructure for netcore
  - [x] Add size tracking for iOS functional tests
  - [x] Add size tracking for Xamarin iOS sample
  - [x] Add size tracking for MAUI iOS sample
 - [ ] https://github.com/dotnet/runtime/issues/61815

**Comment by SamMonoRT** [comment]
Further work tracked in https://github.com/dotnet/runtime/issues/61815
