### ISSUE TITLE
Improve low level struct performance 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#46104]
This is a "User Story" to track the proposed improvements to low level struct performance improvements. 

C# Language Features
- [ ] [Allow `ref` fields in `ref struct` types](https://github.com/dotnet/csharplang/issues/1147)
- [ ] [Allow safe fixed sized buffers of any type](https://github.com/dotnet/csharplang/issues/1314)

The feature proposal for both C# features is captured [here](https://github.com/dotnet/csharplang/blob/master/proposals/low-level-struct-improvements.md)

Related Runtime Requests: 
- [ ] [Allow `ref` fields in `ref struct`](https://github.com/dotnet/runtime/issues/32060)
- [ ] [`FixedSizBufferAttribute` proposal](https://github.com/dotnet/runtime/issues/12320)

**Comment by benaadams** [comment]
What about...?

`Span<object> span = stackalloc object[5];` 

Which is sorta
```csharp
struct Obj5
{
    object o0;
    object o1;
    object o2;
    object o3;
    object o4;
}

Obj5 objs = default;
Span<object> span = CreateSpan(ref objs.o0, 5);
```

**Comment by jaredpar** [comment]
The `stackalloc` primitive doesn't support reference types.

**Comment by benaadams** [comment]
`localloc` returning a `byte*` pointer is obv problematic for a reference type; however if it was limited to a `Span<ref type>` receiver and a fixed size rather than variable size then t could be translated to something closer to the safe fixed sized buffer proposal? e.g.
```csharp
struct <Buffer>e__FixedBuffer_1024<T>
{
    private T _e0;
    private T _e1;
    // _e2 ... _e1023
    private T _e1024;

    public ref T this[int index] => ref (uint)index <= 1024u ?
                                         ref RefAdd<T>(ref _e0, index):
}
```
Not sure what the GC would make of referring only to an internal element of a stack struct (if it was sliced)

**Comment by jkotas** [comment]
I think https://github.com/dotnet/runtime/issues/25423 is the proposal we should follow to improve stackalloc.

**Comment by mangod9** [comment]
@jaredpar this is unlikely for 6 due to statics in interfaces work. Ok to move out?

**Comment by sgf** [comment]
[provide-unscoped](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/low-level-struct-improvements.md#provide-unscoped)
I've been waiting a long time for this feature , when  will be available.
