### ISSUE TITLE
Developers can run diagnostics tooling on their iOS and Android devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#46371]
As an Android/IOS application developer I want to build a configuration of my application using dotnet CLI that includes Diagnostics Classes/EventPipe/Diagnostic Server, so that I can use existing dotnet-* tooling and PerfView for on device debugging and profiling.

**Description**
To use diagnostic tooling, application needs to include custom implemented EventListeners, EventSources, managed diagnostic classes, native EventPipe library and native Diagnostic Server library. Since all that could make a significant impact on application size (very important for Android/IOS developers), we should exclude all those components in retail builds that will be pass for certification and published in app stores (at least the EventPipe/Diagnostic Server). Since a lot of the diagnostic tasks related to EventPipe handles performance, it still make sense to include all of the above in a configuration that will be as close to the retail build as possible, full optimization (full AOT build on platforms demanding it) and full IL linking. It also needs to be clear to developers that this configuration is not intended for certification, just for profiling and performance testing. Regular debug builds should also include all needed components to be able to run dotnet-* tooling against running application on device.

**Tasks**
- [x] Add support for a "profile" build configuration. As part of component architecture, this is now pushed down to SDK's when linking binary. It is possible to include/exclude tracing in final binary, meaning it is possible to define custom build configurations including/excluding native tracing support independent of SKD build. AppBuilder has also been extended to accept a msbuild property where caller can decide what components to include/exclude.
- [x] EventPipe implemented on devices 
- [x] TCP/IP support either in the Diagnostics Server itself or a distributable proxy 
- [x] CLI is able to launch a profiling application in debug mode
- [x] Validate diagnostic tooling can be used against a iOS simulator and Android emulator.
- [x] Validate diagnostic tooling can be used against a running device.
- [x] Validate EventSource support for AOT.
- [x] Add support for RuntimeEventSource counters.
- [x] Add support for selected NativeRuntimeEventSource events.

**Comment by danmosemsft** [comment]
@steveisok do you plan to parent all these User Stories under some Epic? So the universe is in harmony.

**Comment by lateralusX** [comment]
Have run some validation using full AOT on iOS simulator and looks like mono reflections support is handling EventSource needs and didn't hit any other code constructs that seems to be problematic for full AOT targets. Run SampleProfiler, RuntimeEventSource, custom EventSource using counters and custom EventSource using regular event.
