### ISSUE TITLE
Create Workload Packs for Mono AOT Compilers & AOT Compiler MSBuild Task

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#46429]
The AOT compilers in Mono are host specific, so we need to create multiple workload packs for the host + target architecture combos we support.  Additionally, we should create a single workload pack for the [MonoAOTCompiler](https://github.com/dotnet/runtime/tree/master/src/tasks/AotCompilerTask) MSBuild task that can be used to trigger AOT compilation.  

The names of the AOT compiler workload packs should take the form of:

`Microsoft.NetCore.App.Runtime.AOT.{host-rid}.Cross.{target-rid}.{version}.nupkg`

And the name of the MSBuild task should be:

`Microsoft.NET.Runtime.MonoAOTCompiler.Task.{version}.nupkg`

### Android

**Windows x64**
- [x] x64
- [x] x86
- [x] arm
- [x] arm64

**MacOS**
- [x] x64 https://github.com/dotnet/runtime/pull/43535
- [x] x86 https://github.com/dotnet/runtime/pull/43535
- [x] arm https://github.com/dotnet/runtime/pull/43535
- [x] arm64 https://github.com/dotnet/runtime/pull/43535

### iOS / tvOS

**MacOS**
- [x] arm64 https://github.com/dotnet/runtime/pull/47184
- [x] x64 (simulator) https://github.com/dotnet/runtime/pull/47184

### Wasm

**MacOS**
- [x] Wasm https://github.com/dotnet/runtime/pull/47011

**Linux**
- [x] Wasm https://github.com/dotnet/runtime/pull/47011

_Windows is a "nice to have"_

### MSBuild Task
- [x] MonoAOTCompiler Task https://github.com/dotnet/runtime/pull/46537

**Comment by lambdageek** [comment]
Is the naming general enough for our needs?
Should we also specify AOT flavor? (ie LLVM vs mini)
