### ISSUE TITLE
Developers should be guided away from more obsolete APIs in .NET 6

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#46767]
With #39269, we marked many APIs as `[Obsolete]` in .NET 5. Some follow-up infrastructure work was identified during and after that PR, and some other obsoletions have been proposed. With this story, we will:

1. Complete that follow-up infrastructure work
2. Consider additional APIs that could be marked as `[Obsolete]` (optionally with custom diagnostic Ids)
3. Document those obsoletions
4. Consider if there are places where a Roslyn Code Fixer should be provided for obsolete APIs

## .NET 6 Work Items

* [x] Consider marking net5.0 obsoleted APIs obsolete in downlevel targets for OOB packages #43484
* [x] For .NET 5 Obsoletions - use partial ref source classes instead of ifdefs #39687
* [x] ImageAnimator.StopAnimate (on Unix) could throw PNSE #39405
* [x] Obsolete warnings on clean build #39976
* [x] Add SYSLIB0013 into obsoletion list #44203 (this just needs documentation)
* [x] API proposal: obsolete DisablePrivateReflectionAttribute #43247
* [x] Obsolete SuppressILDasmAttribute #40622 (PR #50951)
* [x] WebRequest/ServicePoint/WebClient Obsoletion Follow-Up #41759
* [x] API proposal: Obsolete RNGCryptoServiceProvider #40169 (PR: #52373)
* [x] Consider marking HandleProcessCorruptedStateExceptionsAttribute as obsolete/hidden #31157
* [x] Obsolete the Rijndael and RijndaelManaged classes #46930 (PR: #52366)
* [x] Obsolete unnecessary cryptographic derived types #46934 (PR: #52303)
* [x] 32 bit memory getters on Process should not wrap #46901
* [x] Developers are directed to helpful documentation for existing obsoletions #47255

## Moved to Future

* Mark StringDictionary as obsolete #889
* Proposed code fixer for obsoleted CAS APIs #39235
* Assembly.CodeBase obsoletion is incomplete #42857
* [Meta] List of APIs considered for "Better Obsoletion" #33360

## Definition of Done

Each obsoletion needs to have the following Definition of Done applied.

* Pre-announce the upcoming breaking change to partner teams using our breaking change DL at least 2 weeks before merge
* Use the [Obsoletions.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Obsoletions.cs) file to define the message and diagnostic ID
* Add the obsoletion to the [list of diagnostics](https://github.com/dotnet/runtime/blob/master/docs/project/list-of-diagnostics.md)
* Announce the breaking change to our partner teams using our breaking change DL upon merge
* Create the breaking change document issue
* Register the aka.ms link for SYSLIBxxxx obsoletions (see @jeffhandley)

**Comment by jeffhandley** [comment]
Closing this issue for .NET 6 as we have completed the obsoletions for that release. #57207 was filed for obsoletions to consider in .NET 7.
