### ISSUE TITLE
Create workload pack for Emscripten

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#46831]
In order to support AOT as part of the Wasm workload, we need to produce an Emscripten workload pack.  

The workload pack nuget should be: 

`microsoft.net.runtime.emscripten.<host-rid>.<runtime-version>.<emscripten-version>`

- [x] Build scripts for windows, osx, and linux.  This should basically pull and activate the version of emscripten in use.
- [ ] Resolve LLVM versioning https://github.com/dotnet/runtime/issues/49644
- [x] Packages for windows, osx, and linux

**Comment by steveisok** [comment]
@lewing Does `microsoft.net.runtime.emscripten.<host-rid>.<runtime-version>.<emscripten-version>` work for you naming wise?
