### ISSUE TITLE
Developers can observe notable performance improvements in MemoryCache

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#46970]
With a collection of changes that were identified through profiling, we can gain as much as +15% RPS for the TechEmpower [Cached Queries](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=cached-query) benchmark.

## Product improvements

* [x] dotnet/runtime#44797 (low hanging fruits)
* [x] dotnet/runtime#45280 (more improvements)
* [x] dotnet/runtime#45281 (DateTimeOffset.UtcNow +10%)
* [x] dotnet/runtime#45410 (reduce CacheEntry size)
* [x] dotnet/runtime#45563 (reduce allocations)
* [x] dotnet/runtime#45962 (reduce CacheEntry size even further)

## Benchmark improvements

* [x] https://github.com/aspnet/Benchmarks/pull/1603
* [x] https://github.com/aspnet/Benchmarks/pull/1607
* [x] https://github.com/dotnet/performance/pull/1598
* [x] https://github.com/dotnet/performance/pull/1606
* [x] https://github.com/dotnet/performance/pull/1618

## Proof of concept

* [x] dotnet/runtime#45842 (use Timer)

## Bugs Introduced

* [x] dotnet/runtime#46807

## Microbenchmark results

[Source](https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/Microsoft.Extensions.Caching.Memory/MemoryCacheTests.cs)

|                           Method |  Runtime |         Mean | Ratio | Allocated |
|--------------------------------- |--------- |-------------:|------:|----------:|
|                           GetHit | .NET 5.0 |    167.73 ns |  1.00 |         - |
|                           GetHit | .NET 6.0 |    112.15 ns |  0.67 |         - |
|                                  |          |              |       |           |
|                   TryGetValueHit | .NET 5.0 |    163.23 ns |  1.00 |         - |
|                   TryGetValueHit | .NET 6.0 |    103.77 ns |  0.64 |         - |
|                                  |          |              |       |           |
|                          GetMiss | .NET 5.0 |    115.63 ns |  1.00 |         - |
|                          GetMiss | .NET 6.0 |     90.21 ns |  0.78 |         - |
|                                  |          |              |       |           |
|                  TryGetValueMiss | .NET 5.0 |    116.12 ns |  1.00 |         - |
|                  TryGetValueMiss | .NET 6.0 |     92.80 ns |  0.80 |         - |
|                                  |          |              |       |           |
|                      SetOverride | .NET 5.0 |    394.62 ns |  1.00 |     424 B |
|                      SetOverride | .NET 6.0 |    286.34 ns |  0.73 |     224 B |
|                                  |          |              |       |           |
|                      CreateEntry | .NET 5.0 |    390.19 ns |  1.00 |     424 B |
|                      CreateEntry | .NET 6.0 |     76.73 ns |  0.20 |     224 B |
|                                  |          |              |       |           |
|       AddThenRemove_NoExpiration | .NET 5.0 | 61,943.36 ns |  1.00 |  60,546 B |
|       AddThenRemove_NoExpiration | .NET 6.0 | 53,270.07 ns |  0.86 |  54,674 B |
|                                  |          |              |       |           |
| AddThenRemove_AbsoluteExpiration | .NET 5.0 | 70,461.50 ns |  1.00 |  73,331 B |
| AddThenRemove_AbsoluteExpiration | .NET 6.0 | 55,862.63 ns |  0.79 |  54,290 B |
|                                  |          |              |       |           |
| AddThenRemove_RelativeExpiration | .NET 5.0 | 66,384.71 ns |  1.00 |  61,026 B |
| AddThenRemove_RelativeExpiration | .NET 6.0 | 49,905.29 ns |  0.75 |  33,889 B |
|                                  |          |              |       |           |
|  AddThenRemove_SlidingExpiration | .NET 5.0 | 70,597.44 ns |  1.00 |  74,099 B |
|  AddThenRemove_SlidingExpiration | .NET 6.0 | 49,301.41 ns |  0.70 |  40,017 B |
|                                  |          |              |       |           |
|   AddThenRemove_ExpirationTokens | .NET 5.0 | 72,186.78 ns |  1.00 |  71,771 B |
|   AddThenRemove_ExpirationTokens | .NET 6.0 | 65,962.42 ns |  0.91 |  66,490 B |

**Comment by ygra** [comment]
> #45962 (use Timer, most probably will get rejected)

This seems to reference the wrong pull request; it's the same one as the one before, and doesn't seem to have anything to do with a timer. Perhaps #45842 was intended to be linked here?

**Comment by jeffhandley** [comment]
Thanks, @ygra!

**Comment by adamsitnik** [comment]
@sebastienros is there any chance that you could add the Caching benchmark to the first page of the PowerBI report?

**Comment by adamsitnik** [comment]
@jeffhandley I've updated the issue description and closed the proof of concept PR, so our work here is done. I am closing the issue.
