### ISSUE TITLE
Add workload for embeddable MonoVM

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#46994]
We'd like to add a new workload for everyone that could be used by developers to build libraries and apps which would like to use Mono embedding API to embed .NET runtime. The end goal is to allow developers to install all bits required to use embeddable .NET VM.

### Work Items
- [ ] Build MonoVM runtime packs for all interesting targets (they should be shared with other workloads)
- [ ] Build EmbeddingMonoVM workload pack
	- [ ] Determine what kind of workload that should be
	- [ ] Determine if there is a need to split the static and dynamic aspect of libraries
- [ ] Create a custom tool which could be used by native build to (like simple pkg-config) get a reference to workload pack folder with C headers and native libs.

@lambdageek @steveisok @SamMonoRT

**Comment by CoffeeFlux** [comment]
Would my proposed header modernization for netcore go under this issue or a separate one?

**Comment by marek-safar** [comment]
That'd be a separate issue, this is primarily about building and packaging

**Comment by lambdageek** [comment]
I have an example of how we might do this today - https://github.com/lambdageek/monovm-embed-sample - it's not pretty. There are three steps:
   1. Build and publish the managed code that will be invoked by the embedder.  I use `dotnet publish --self-contained` for this step, with `<TrimMode>copyused</TrimMode>` to get a subset of the BCL.
   2. Publish a fake managed project just to get nuget to download the runtime pack and hook onto the `ResolveFrameworkReferences` target to find where the native library and the embedding headers are located.
   3. Use the info from step 2 to compile a native C/C++ project to embed the runtime.

Step 1 is fine. Steps 2 and 3 should be streamlined.  (Also note that in Step 2 right now there's no headers because of https://github.com/dotnet/runtime/issues/46461

**Comment by steveisok** [comment]
Does it make sense to move the headers out of the runtime pack and into the embedded workload pack?

**Comment by srxqds** [comment]
hope this move to .net6 milestone

**Comment by jayrulez** [comment]
> I have an example of how we might do this today - https://github.com/lambdageek/monovm-embed-sample - it's not pretty. There are four steps:
> 
> 1. Build and publish the managed code that will be invoked by the embedder.  I use `dotnet publish --self-contained` for this step, with `<TrimMode>copyused</TrimMode>` to get a subset of the BCL.
> 2. Publish a fake managed project just to get nuget to download the runtime pack and hook onto the `ResolveFrameworkReferences` target to find where the native library and the embedding headers are located.
> 3. Use the info from step 2 to compile a native C/C++ project to embed the runtime.  You also need to build a `TRUSTED_PLATFORM_ASSEMBLY` list in the C code based on the contents of Step 1.
> 4. To deploy, you copy the published managed code from Step 1, together with the native libraries from Step 2 and System.Private.CoreLib from Step 2 into the right place so that the native code from Step 3 can find them.
> 
> Step 1 is fine. Steps 2 and 3 should be streamlined. (Also note that in Step 2 right now there's no headers because of #46461). Step 4 needs to be simpler too - it's unclear which native and managed artifacts from the runtime pack you need to distribute with the embedder.
> 
> Also if you are building for multiple target architectures/OSes, you have to do step 2 per-RID. Our headers are the same on all architectures, so it's a bit unfortunate that you need to different include paths. (Of course when linking I don't think there's a way to avoid having per-arch library paths)

This would be a very welcome change.
Currently, I'm guessing picking artifacts like here: https://github.com/jayrulez/ezEngine/tree/monodotnet/Code/ThirdParty/mono/windows.x64.Release

It would be great to have this packaged nicely where the includes are placed independent of the arch dir (since it should be the same).

I'm not sure about the order there though. I figure most people embedding mono would be building it themselves.
I didn't need to create a fake project or anything. I just compiled mono+libs and copied the relevant bits and copied it to somewhere convenient for linking.

**Comment by lambdageek** [comment]
Found another issue on Linux (well, any non-OSX, I think).  We set the SONAME to libmonosgen.so.1 in the runtime pack, but name the file `libcoreclr.so`.  As a result, any app linking against "libcoreclr" will end up with a dynamic linker reference to libmonosgen.so.1 and then fail at runtime.

A heavyhanded solution is to use `patchelf --set-soname libcoreclr.so libcoreclr.so` but a better solution would be to update the runtime pack.

Filed a bug about it https://github.com/dotnet/runtime/issues/49661
