### ISSUE TITLE
Developers have their top System.Linq feature requests implemented

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#47231]
Creating this issue to keep track of System.Linq community feature requests that we are considering for .NET 6.

## Done

 - [x] [Support more arities for Enumerable.Zip](https://github.com/dotnet/runtime/issues/43702). ([implementation PR](https://github.com/dotnet/runtime/pull/47147))
 - [x] [Add an Enumerable.ChunkBy method](https://github.com/dotnet/runtime/issues/27449). ([Implementation PR](https://github.com/dotnet/runtime/pull/47965))
 - [x] [Add a non-enumerating Count method](https://github.com/dotnet/runtime/issues/27183). ([Implementation PR](https://github.com/dotnet/runtime/pull/48239))
 - [x] [Add SingleOrDefault/FirstOrDefault/LastOrDefault overloads that allow specifying a default](https://github.com/dotnet/runtime/issues/20064). ([implementation PR](https://github.com/dotnet/runtime/pull/48886))
 - [x] [LINQ APIs to enable C# 8.0 index and range for IEnumerable<T>](https://github.com/dotnet/runtime/issues/28776). ([Implementation PR](https://github.com/dotnet/runtime/pull/47950))
 - [x] [Add Enumerable.*By operators (DistinctBy, ExceptBy, IntersectBy, UnionBy, MinBy, MaxBy)](https://github.com/dotnet/runtime/issues/27687). ([implementation PR](https://github.com/dotnet/runtime/pull/50335))

## Notes on Potential Breaking Changes

The changes add new method overloads to the `System.Linq.Queryable` APIs. This is known to break query provider implementations whose reflection code isn't sufficiently strong when looking up methods (cf. https://github.com/dotnet/efcore/issues/24002, https://github.com/dotnet/runtime/issues/49683). Query provider library authors are advised to ensure that their reflection code is tolerant of future method overload additions, e.g. by using a [`Type.GetMethod()` ](https://docs.microsoft.com/en-us/dotnet/api/system.type.getmethod?view=net-5.0) overload that explicitly accepts the method's parameter types.

**Comment by MgSam** [comment]
Finally! After 14 years LINQ will finally get some attention again!

**Comment by GSPP** [comment]
This is very important work. The introduction of LINQ was such a boon to productivity on .NET. We were leading the entire industry. Now, some additional innovation is desirable to convert the experiences of a decade into widely useful data-processing methods.

**Comment by eiriktsarpalis** [comment]
All implementation are now complete. Note that some of the new APIs are pending xml documentation, which I'll be introducing in tandem with work for https://github.com/dotnet/runtime/issues/48986. cc @carlossanlop

**Comment by Thaina** [comment]
Sadly this not include #28650

**Comment by davidfowl** [comment]
@eiriktsarpalis we need to make sure these go into the blog
