### ISSUE TITLE
Developers will be unblocked for unsupported  tracing and OpenTelemetry scenarios

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#47313]
This issue is tracking the System.Diagnostics tracing work in the 6.0 release. It tracks all tracing feature requests and the fixes we need to do.

# Features #

- [x] [Add ability to update Activity.Baggage](https://github.com/dotnet/runtime/issues/42706)
- [x] [Add Status field to Activity API](https://github.com/dotnet/runtime/issues/46689)
- [x] [Add Activity.GetTagItem](https://github.com/dotnet/runtime/issues/39866)
- [x] [Provide default activity name value from [CallerMemberName] in ActivitySource.StartActivity](https://github.com/dotnet/runtime/issues/43483)
- [x] [Support customized Activity trace id generation](https://github.com/dotnet/runtime/issues/46704)
- [x] [Allow setting the Activity properties after Activity creation and before starting it when using ActivitySource](https://github.com/dotnet/runtime/issues/42784)
- [x] [Impossible to set Activity.IdFormat when using ActivitySource](https://github.com/dotnet/runtime/issues/43853)

# Fixes

- [x] [ActivitySource started activities aren't using an accurate utcnow on framework](https://github.com/dotnet/runtime/issues/45111)
- [x] [Faster Diagnostics Activity ID generation from random bytes ](https://github.com/dotnet/runtime/issues/46818)
- [X] [Ending an activity will not restore the previously active one for explicit parents](https://github.com/dotnet/runtime/issues/46721)

# Docs

- [x] [Distributed Tracing Doc](https://github.com/dotnet/docs/pull/22617)

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by marek-safar** [comment]
Note, every user story should be attached to a theme

@danmosemsft

**Comment by danmosemsft** [comment]
I parented this one under https://github.com/dotnet/core/issues/5490 like the other Open Telemetry one  dotnet/runtime#44445

**Comment by tarekgh** [comment]
All items here are already addressed and completed.
