### ISSUE TITLE
Enable Catalyst Runtime Packs

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#47517]
Catalyst is a software-development tool that allows developers to write self-contained apps that can run on both macOS and iPadOS. To support that we need to build, test, and ship Catalyst runtime packs.

### Work Items
- [x] Introduce Catalyst RIDs #47518
- [x] Build Catalyst mono runtime packs for x64 and arm64 (like iOS)
~~Produce coreclr based Catalyst runtime packs for x64 and arm64~~
- [x] Run all libraries tests with Catalyst runtime packs
- [x] Add functional/integration tests for Catalyst
- [x] Ensure new runtime packs are trimmable

**Oldest supported version: Mac Catalyst 13**

**Comment by directhex** [comment]
A step is also needed for API review, as adding IsMacCatalyst() and IsMacCatalystVersionAtLeast() entries to src/libraries/System.Runtime/ref/System.Runtime.cs is subject to mandatory API change review.

**Comment by steveisok** [comment]
We're waiting on https://github.com/dotnet/xharness/issues/435 in order to run tests.

**Comment by krwq** [comment]
@steveisok @directhex is this still planned for 6.0? Seems the other issue is fixed
