### ISSUE TITLE
Developers using the Mono embedding API can upgrade to modern .NET

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#47763]
Developers using framework Mono should be able to upgrade to the modern .NET stack with as little pain as possible.

### Work Items
- [ ] Publish runtime/workload packs for relevant targets: https://github.com/dotnet/runtime/issues/46994
- [ ] Run survey to better understand embedder needs and concerns
- [ ] Document embedding API deprecation and stability policy: https://github.com/dotnet/runtime/pull/47715
- [ ] Audit embedding API for correctness: https://github.com/dotnet/runtime/issues/33557
    - [ ] Remove and/or deprecate outdated APIs
    - [ ] Add new ALC-aware APIs where necessary
- [ ] Remove the unstable headers and migrate functions from them elsewhere
- [ ] Add new embedding samples for relevant targets
- [ ] Update documentation
    - [ ] Try to encourage migration to new managed APIs where appropriate

cc: @marek-safar @SamMonoRT

**Comment by BrUnOXaVIeRLeiTE** [comment]
I've embedded Mono into Unreal Engine, but can only migrate to NET5 / NET6 if I give up the ability to compile C# from within Unreal Editor.

This could provide a solution to my dilemma, so I will watch how things unfold ;)
