### ISSUE TITLE
MacOS arm64 mono build issues

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#47833]
This issue will track build problems on the M1 for mono:

**-os osx -arch arm64**
- [x]  No ICU arm64 package -> unicode/uclean.h not found in `pal_calendarData` and `pal_casing` https://github.com/dotnet/runtime/issues/47831
- [x]  [Platform version is not present](https://github.com/dotnet/runtime/pull/47245) when bumping to 6.0 SDK

**-os iOS -arch arm64**
- [x] Missing LLVM arm64 package https://github.com/dotnet/runtime/issues/47830

**Comment by steveisok** [comment]
No longer an issue
