### ISSUE TITLE
[Wasm] Tracking AOT wasm library test failures

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#48079]
To see where the wasm library tests stand with AOT compilation with respect to how many pass/fail, what the failures are, how many hang, the 268 test suites were ran locally.

Dropbox [paper](https://www.dropbox.com/scl/fi/ui5z7xvew34z6bkdg7swo/Running-AOT-wasm-tests-locally.paper?dl=0&rlkey=3dzmlw797jqgumxufc3grbuxd) with findings

[All CI Results](https://helix.dot.net/api/jobs/763c687c-e148-4b1a-bbaf-26e248918da3/workitems?api-version=2019-06-17)

## Among all the test suites failing on CI, the following are the main unique test failures observed.
____
### **Unique Test Failures based on [CI logs](https://dev.azure.com/dnceng/public/_build/results?buildId=1019456&view=logs&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=9df76bd4-3041-5537-002b-9e29a53263b9)**
- [ ] a) `Assert.True() Failure` https://github.com/dotnet/runtime/issues/49246
- [ ] b) `System.ExecutionEngineException : AOT Compilation failed for method` https://github.com/dotnet/runtime/issues/49219
- [ ] c) `System.ExecutionEngineException : Attempting to JIT compile method` https://github.com/dotnet/runtime/issues/46708
- [ ] d) `console.error: RuntimeError: memory access out of bounds` https://github.com/dotnet/runtime/issues/46700
- [x] e) `System.NotImplementedException : The method or operation is not implemented.` https://github.com/dotnet/runtime/issues/49229
- [ ] f) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Threading.CancellationTokenSource:ExecuteCallbackHandlers (bool)'.` https://github.com/dotnet/runtime/issues/49219
- [ ] g) `System.ExecutionEngineException : AOT Compilation failed for method 'bool Microsoft.Extensions.Internal.ParameterDefaultValue:TryGetDefaultValue (System.Reflection.ParameterInfo,object&)'.` https://github.com/dotnet/runtime/issues/49219
- [ ] h) `System.ExecutionEngineException : Attempting to JIT compile method '(wrapper dynamic-method) object Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder:ResolveService (Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder/ILEmitResolverBuilderRuntimeContext,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.` https://github.com/dotnet/runtime/issues/46708
- [ ] i) `System.ExecutionEngineException : Attempting to JIT compile method '(wrapper dynamic-method) object object:lambda_method` https://github.com/dotnet/runtime/issues/46708
- [ ] j) `AOT Compilation failed for method 'object Microsoft.Extensions.DependencyInjection.ActivatorUtilities/ConstructorMatcher:CreateInstance (System.IServiceProvider)'.` https://github.com/dotnet/runtime/issues/49219
- [ ] k) `System.ExecutionEngineException : AOT Compilation failed for method 'System.Threading.Tasks.Task System.Net.Http.HttpContent:LoadIntoBufferAsync (long,System.Threading.CancellationToken)'.` https://github.com/dotnet/runtime/issues/49219
- [ ] l) `EventName and ExceptionJson is supposed to be null but it isn't.` https://github.com/dotnet/runtime/issues/49240
- [ ] m) `LoggerName is supposed to be null but it isn't.` https://github.com/dotnet/runtime/issues/49240
- [ ] n) `console.error: RuntimeError: invalid index into function table` https://github.com/dotnet/runtime/issues/46731
- [ ] p) `System.Composition.Hosting.CompositionFailedException : No export was found for the contract` https://github.com/dotnet/runtime/issues/49230
- [ ] q) `System.Composition.Hosting.CompositionFailedException : No importing constructor was found on type` https://github.com/dotnet/runtime/issues/49230
- [ ] u) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Data.DataColumnCollection:BaseAdd (System.Data.DataColumn)'.` https://github.com/dotnet/runtime/issues/49219
- [ ] v) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Data.DataRow:set_Item (System.Data.DataColumn,object)'` https://github.com/dotnet/runtime/issues/49219
- [ ] w) `System.IO.DirectoryNotFoundException : Could not find a part of the path` or `System.IO.FileNotFoundException : Could not find file` https://github.com/dotnet/runtime/issues/49232  (@fanyang-mono working on this)
- [ ] x) `Assert.NotEmpty() Failure` https://github.com/dotnet/runtime/issues/49241
- [ ] y) `Assert.Contains() Failure` https://github.com/dotnet/runtime/issues/49241
- [ ] z) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile` https://github.com/dotnet/runtime/issues/49219
- [ ] ab) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Net.Http.HttpContent:CopyTo (System.IO.Stream,System.Net.TransportContext,System.Threading.CancellationToken)'.` https://github.com/dotnet/runtime/issues/49219
Special case (Invariant.Tests)
- [ ] ac) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Net.Mime.ContentType:ParseValue ()'.` https://github.com/dotnet/runtime/issues/49219
- [ ] ad) `[byte difference]` https://github.com/dotnet/runtime/issues/49245
- [ ] ae) `System.InvalidOperationException : Failed to compare two elements in the array.` https://github.com/dotnet/runtime/issues/46759 
- [ ] ag) `Assert.Throws() Failure` https://github.com/dotnet/runtime/issues/49242
- [ ] aj) `console.error: RuntimeError: function signature mismatch` https://github.com/dotnet/runtime/issues/46761 [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.ValueTuple.Tests/console.4942e000.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
- [ ] ak) `System.NullReferenceException : Object reference not set to an instance of an object.` https://github.com/dotnet/runtime/issues/49234
- [ ] al) `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Numerics.Tests.divremTest:VerifyDivRemString (string)'.` https://github.com/dotnet/runtime/issues/49219
- [x] am) `Assertion at /__w/1/s/src/mono/mono/metadata/class-init.c:2746, condition '<disabled>' not met` https://github.com/dotnet/runtime/issues/46698 [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.VisualBasic.Core.Tests/console.47751287.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
- [ ] an) `Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/class-accessors.c:86` https://github.com/dotnet/runtime/issues/45304
- [x] ao) `Assertion at /__w/1/s/src/mono/mono/mini/mini-generic-sharing.c:2168, condition '<disabled>' not met` https://github.com/dotnet/runtime/issues/46698 [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Private.Runtime.InteropServices.JavaScript.Tests/console.6857b294.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
- [ ] ap) `Process 24507 didn't exit within 00:15:00 and will be killed` https://github.com/dotnet/runtime/issues/49243
- [x] aq) `Assertion at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:3965, condition '<disabled>' not met` https://github.com/dotnet/runtime/issues/46698 [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.Linq.xNodeBuilder.Tests/console.43fd44dd.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
- [ ] as) `console.error: Unhandled exception in _finalize_startup Error: FS error` https://github.com/dotnet/runtime/issues/49244
- [ ] au) `Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-object.h:91` https://github.com/dotnet/runtime/issues/49225

EnableAggressiveTrimming related failures
r) `System.ArgumentException : Type Moq.Internals.InterfaceProxy is not valid base type for interface proxy, because it does not have accessible parameterless constructor. Only a non-sealed class with non-private default constructor can be used as base type for interface proxy. Please use some other valid type.` https://github.com/dotnet/runtime/issues/46760 [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.Extensions.Configuration.FileExtensions.Tests/console.13d17004.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
s) `System.InvalidOperationException : Sequence contains no matching element` https://github.com/dotnet/runtime/issues/46759
t) `System.ArgumentNullException : Value cannot be null. (Parameter 'method')` https://github.com/dotnet/runtime/issues/46758 (@naricc working on this)
af) `System.NotSupportedException : Use of ResourceManager for custom types is disabled. Set the MSBuild Property CustomResourceTypesSupport to true in order to enable it.`
ah) `console.error: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.`
ai) `Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.ComponentModel.Composition.Tests/console.ab648589.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

---

### **Suites that did not produce test results**
---
Error: Failed to load method 0x6000001
- [ ] System.ComponentModel.Composition.Tests -- ai
- [ ] System.Diagnostics.Tracing.Tests -- ai
- [ ] System.Runtime.Loader.DefaultContext.Tests -- ai
- [ ] System.Runtime.Loader.RefEmitLoadContext.Tests -- ai
- [ ] System.Runtime.Tests -- Precompiling failed for [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Runtime.Tests/console.18668218.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

____
### **Suites that failed with 1 or more test failures**
- [ ] System.Data.Common.Tests -- u
- [ ] System.Security.Cryptography.Algorithms.Tests -- aj
- [ ] System.Numerics.Vectors.Tests -- c 
- [ ] System.Linq.Queryable.Tests -- i, d
- [ ] System.IO.FileSystem.Tests -- as 
- [ ] System.Linq.Expressions.Tests -- an
- [ ] System.Runtime.Serialization.Xml.Tests -- an
- [ ] Microsoft.Extensions.DependencyInjection.Tests -- g, h, i, j, k
- [ ] System.Runtime.Serialization.Json.Tests -- c
- [ ] System.Composition.Tests -- i, p, q
- [ ] System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests -- w
- [ ] System.ComponentModel.TypeConverter.Tests -- i, d, t
- [ ] System.Threading.Channels.Tests -- c, f
- [ ] System.IO.Pipelines.Tests -- f, y
- [ ] System.Data.DataSetExtensions.Tests -- u, v, w, missing 33 tests
- [ ] System.Runtime.Numerics.Tests -- ak, al
- [ ] System.ServiceModel.Syndication.Tests -- c, w
- [ ] System.Collections.Immutable.Tests -- d
- [ ] System.ComponentModel.Composition.Registration.Tests -- i
- [ ] System.Reflection.DispatchProxy.Tests -- c
- [ ] System.Net.Http.Json.Functional.Tests -- c, f
- [ ] Microsoft.Extensions.Configuration.Json.Tests -- a, f
- [ ] Microsoft.Extensions.Logging.EventSource.Tests -- g, l, m
- [ ] Microsoft.Extensions.Configuration.Functional.Tests -- f
- [ ] System.IO.Compression.Tests -- w
- [ ] Common.Tests -- a, b
- [ ] System.Collections.Concurrent.Tests -- e, f
- [ ] System.IO.MemoryMappedFiles.Tests -- z
- [ ] System.Composition.Convention.Tests -- i
- [ ] System.Threading.Tests -- f 
- [ ] System.Xml.XmlSchemaSet.Tests -- a, w
- [ ] Microsoft.Extensions.Primitives.Tests -- f, r
- [ ] System.Composition.TypedParts.Tests -- i
- [ ] Microsoft.Extensions.Http.Tests -- i, k, t
- [ ] System.Reflection.Emit.Lightweight.Tests -- c
- [ ] Microsoft.Extensions.Configuration.Ini.Tests -- a, f
- [ ] System.IO.Tests -- Random text `KÃ¦ï¿¿	 $@#'ã†ìŽ A5` not AOT related
- [ ] Microsoft.Extensions.Configuration.Xml.Tests -- a, f
- [ ] System.Collections.Tests -- e, killed
- [ ] System.Text.RegularExpressions.Tests -- au 
- [ ] System.CodeDom.Tests -- d
- [ ] System.Drawing.Primitives.Tests -- c
- [ ] System.Memory.Tests -- c
- [ ] System.ObjectModel.Tests -- d
- [ ] Microsoft.Extensions.Options.Tests -- f
- [ ] Microsoft.Extensions.Configuration.Tests -- f
- [ ] Microsoft.Extensions.Configuration.UserSecrets.Tests -- f
- [ ] Microsoft.Extensions.Logging.Testing.Tests -- g
- [ ] System.IO.Packaging.Tests -- w
- [ ] System.Memory.Data.Tests -- f, c
- [ ] System.Net.Primitives.Functional.Tests -- e 
- [ ] Microsoft.Extensions.FileProviders.Composite.Tests -- a, r
- [ ] System.Diagnostics.TraceSource.Tests -- x, y
- [ ] Microsoft.Extensions.Configuration.Binder.Tests -- e
- [ ] Microsoft.Extensions.Configuration.FileExtensions.Tests -- r
- [ ] System.Composition.Hosting.Tests -- i 
- [ ] System.Globalization.Tests -- e
- [ ] System.Net.WebSockets.Tests -- c 
- [ ] System.Reflection.CoreCLR.Tests -- EnableAggressiveTrimming failure
- [ ] System.Transactions.Local.Tests -- ak
- [ ] System.Diagnostics.DiagnosticSource.Tests -- t
- [ ] System.Net.Http.Json.Unit.Tests -- c 
- [ ] System.Net.Http.Unit.Tests -- k, ab
- [ ] System.Resources.Reader.Tests -- af
- [ ] System.Runtime.CompilerServices.Unsafe.Tests -- ag
- [ ] System.Threading.Tasks.Extensions.Tests -- s
- [ ] System.Reflection.MetadataLoadContext.Tests -- 360 failures -- missing 78 tests -- w
- [ ] System.Diagnostics.StackTrace.Tests -- 22 failures -- a
- [ ] System.Reflection.Tests -- missing ~1100 tests -- d
- [ ] Microsoft.CSharp.Tests -- c, d
- [ ] Microsoft.Extensions.Logging.Tests -- n
- [ ] Microsoft.VisualBasic.Core.Tests -- am
- [ ] System.Dynamic.Runtime.Tests -- an
- [ ] System.Linq.Tests -- i
- [ ] System.Net.Mail.Functional.Tests -- ac
- [ ] System.Private.Runtime.InteropServices.JavaScript.Tests -- ao
- [ ] System.Reflection.Context.Tests -- am
- [ ] System.Reflection.Emit.ILGeneration.Tests -- c
- [ ] System.Reflection.Emit.Tests -- c 
- [ ] System.Reflection.Metadata.Tests -- c, w, ad, ae
- [ ] System.Runtime.Extensions.Tests -- d
- [ ] System.Runtime.InteropServices.Tests -- c, ah
- [ ] System.Runtime.Loader.Tests -- am
- [ ] System.Runtime.Serialization.Json.ReflectionOnly.Tests -- ao
- [ ] System.Runtime.Serialization.Xml.ReflectionOnly.Tests -- ao
- [ ] System.Text.Json.Tests -- b, c, d
- [ ] System.Threading.Tasks.Dataflow.Tests -- ap
- [ ] System.Threading.Tasks.Parallel.Tests -- f
- [ ] System.Threading.Tasks.Tests -- d
- [ ] System.ValueTuple.Tests -- aj
- [ ] System.Xml.Linq.xNodeBuilder.Tests -- aq 
- [ ] System.Xml.XmlSerializer.ReflectionOnly.Tests -- i
- [ ] System.Xml.XmlSerializer.Tests -- ao
- [ ] System.Xml.Xsl.XslCompiledTransformApi.Tests -- w
- [ ] System.Xml.Xsl.XslTransformApi.Tests -- w 

Tests failing in CI
- [ ] System.Collections.Specialized.Tests -- d
- [ ] System.IO.Compression.ZipFile.Tests -- w
- [ ] System.Private.Uri.Functional.Tests -- n
- [ ] System.Xml.RW.XmlWriterApi.Tests -- aj
- [ ] System.Xml.XPath.XmlDocument.Tests -- aj
- [ ] System.Xml.XmlDocument.Tests -- w
- [ ] System.Xml.XmlResolver.Tests -- w
- [ ] System.Xml.RW.XmlSystemPathResolver.Tests -- w

**Comment by CoffeeFlux** [comment]
It would be nice to compare this with currently known failures with the interpreter, so we can tell what is AOT-specific.

**Comment by mdh1418** [comment]
I ran all the libraries for Browser wasm [here](https://www.dropbox.com/scl/fi/ui5z7xvew34z6bkdg7swo/Untitled.paper?dl=0&rlkey=3dzmlw797jqgumxufc3grbuxd#:uid=453026499705371826979118&h2=Non-AOT-wasm-Tests). There were only 5 test failures overall, belonging to two different test suites. However, there were a number of suites that had 0 tests run most likely due to skips.

To compare the failures found from running tests in AOT mode, the test names themselves were compared and out of the tests ran (Not skipped) in interp mode (non AOT), 5275 of the 10974 tests failing in AOT Mode were ran on interp mode. The rest (5699) are likely tests that are skipped on interp mode.

The 5275 tests that failed on AOT yet passing on Interp overall belong to 79 different test suites under `sameTests.log` in this [section](https://www.dropbox.com/scl/fi/ui5z7xvew34z6bkdg7swo/Untitled.paper?dl=0&rlkey=3dzmlw797jqgumxufc3grbuxd#:uid=309733732032306492125843&h2=Test-Suites-Summary)

**Comment by vargaz** [comment]
Can the changes be merged, even if turned off by default, so these failures are easier to debug ?

**Comment by steveisok** [comment]
@vargaz You should be able to run each of these suites now locally.  The only thing https://github.com/dotnet/runtime/pull/48226 does is it shifts the AOT / final link step to helix so that we can spread the work beyond 1 build machine.

**Comment by mdh1418** [comment]
@vargaz There are a couple of changes on that branch that help run more tests. 
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.

**Comment by naricc** [comment]
I (@naricc) am working on  System.ComponentModel.TypeConverter.Tests.

**Comment by fanyang-mono** [comment]
I (@fanyang-mono ) am working on the issue `w) System.IO.DirectoryNotFoundException : Could not find a part of the path or System.IO.FileNotFoundException : Could not find file #49232`

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
