### ISSUE TITLE
Continue evolving System.Data and the database providers

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#48253]
- [x] https://github.com/dotnet/runtime/issues/28633
- [ ] https://github.com/dotnet/runtime/issues/22336
- [ ] [Support the new date-only and time-only types across database providers](https://github.com/dotnet/runtime/issues/49036#issuecomment-806444260)
- [x] https://github.com/dotnet/efcore/issues/13837
- [ ] https://github.com/dotnet/efcore/issues/14044
- [ ] https://github.com/dotnet/datalab/issues/6
