### ISSUE TITLE
Mobile developers will experience improved app startup time when targeting .NET 6

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/runtime#48761]
Mobile developers will experience improved app startup time when migrating their apps to .NET6 runtime.

## Work Items
- [ ] Setup testing infrastructure for tracking start-up metrics
	- [ ] iOS Devices
	- [ ] Android Devices
- [ ] Establish base-line for tests apps by manually running the tests on latest Xamarin version
- [ ] Setup tracking environment for
	- [ ] iOS default template app (https://github.com/xamarin/xamarin-macios/tree/main/dotnet/Microsoft.iOS.Templates)
	- [ ] Android default template app (https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates)
	- [ ] Empty MAUI app on iOS (https://aka.ms/maui-templates)
	- [ ] Empty MAUI app on Android (https://aka.ms/maui-templates)
- [x] https://github.com/dotnet/maui/issues/229

**Comment by CoffeeFlux** [comment]
@Redth: Is there a public link available for the proper MAUI templates to use? Do we want the same ones for startup and size tracking?

**Comment by SamMonoRT** [comment]
We can close this issue as we achieved the target goals when we released .NET6 MAUI release earlier this year and are on track to get better with the 7.0 release in coming months.
