### ISSUE TITLE
[mono][debugger] To do list to implement iCorDebug on Mono

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#49239]
## Functionalities:
- [ ] Support transition between managed and unmanaged code;
- [x] Pause on Exception;
- [ ] Validate memory address that is being accessed by ReadMemory;
- [x] Get value of static attributes;
- [x] Evaluate expressions using object value (and this value);
- [ ] Support view generics objects (`List<object>`);
- [x] Implement WriteMemory;
## Architecture:
- [ ] Review data structure used to cache `CordbType`;
- [ ] Review data structure used to save protocol replies;
- [ ] Review data structure used to save protocol messages;
- [x] Encode using_icordbg in the protocol version;
- [ ] Use something like mono_metadata_type_hash as a method in CordbType and CordbClass.
## Questions:
- [ ] Continue using `CordbChainEnum` or use `CreateStackWalk()`? (Is Vs team ready to move?);
- [x] When `CordbRegisterSet` is used?;
- [ ] Will we need to implement correclty `GetStackRange()`?;
- [ ] When it's used `GetNativeCode()` and `GetILCode()`? Should we implement both?;
## General:
- [x] Run debugger tests using Mono runtime;
- [ ] Extract MDBGPROT_VALUE_TYPE_ID_NULL to a helper function;
- [ ] Break up CordbReferenceValue::GetExactType into some helper functions and use else if instead of goto
- [ ] Use EX_TRY/CATCH everywhere which allocs memory
- [ ] Rename booleanValue to byteValue
- [x] Compile on ARM64

**Comment by srxqds** [comment]
will these supported with .net6?

**Comment by lambdageek** [comment]
Let's add the crash protection for ReadMemory to this list.  I don't think it's needed in the initial PR, but we should figure out if there is some way to tell the difference between a user poking at random memory and when the debugger is doing in of some normal operation.

**Comment by lambdageek** [comment]
@thaystg I think this can be updated now, right?
