### ISSUE TITLE
Mobile runtimeconfig.json support

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#49237]
The goal here is to offer a fast, runtime-controlled mechanic for supporting arbitrary AppContext properties on mobile devices and potentially single file scenarios.

.NET6 :
- [x] #37240 - [mono] Propagate hosting properties through AppContext
- [x] #49235 - Create msbuild task that generates binary runtimeconfig format
- [x] #49236 - Add new Mono embedding API to consume binary runtimeconfig format
- [x] Document new embedding API and MSBuild task
- [x] #51236 - Create a Nuget package for RuntimeConfigParserTask
- [x] #50906 - Add RuntimeConfigParserTask to the Mono workload pack
- [x] Adopt in the Xamarin products (requires the nuget/workload pack)
  - [x] Android
  - [x] iOS
- [x] #38433
- [x] #50908 - Add a runtimeconfig.json test for WASM
- [x] #51232 - Replace ArgumentException with LogError for RuntimeConfigParser to be more user friendly

Future milestone : 
- [x] #50905 - Create a new test, instead of adding runtimeconfig.json to the existing Android functional test

**Comment by fanyang-mono** [comment]
Android has adopted this feature via https://github.com/xamarin/xamarin-android/pull/6009. It landed in Preview 6.

**Comment by fanyang-mono** [comment]
Apple has adopted this feature via https://github.com/xamarin/xamarin-macios/issues/11745.

**Comment by fanyang-mono** [comment]
All sub issues have been resolved. Closing the tracking issue as well.
