### ISSUE TITLE
Remove src/installer (core-setup) umbrella in favor of distinct components

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#49428]
Today, src/installer consists of various assets which are planned to either be removed or moved out of the installer directory:
- [ ] Host including end-to-end tests: https://github.com/dotnet/runtime/issues/49233
- [ ] Snaps: https://github.com/dotnet/runtime/issues/49374
- [ ] Shared Framework packages: https://github.com/dotnet/runtime/issues/49426
- [ ] Publishing: https://github.com/dotnet/core-eng/issues/12289

This issue tracks the completion of the sub-tasks and the final removal of the src/installer directory and its custom infrastructure.
