### ISSUE TITLE
[Mono] implement static methods in interfaces support

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#49904]
Implement support for [static interface methods](https://github.com/dotnet/runtime/pull/49558) (csharp design: https://github.com/dotnet/csharplang/issues/4436)

Work items:
- [ ] unconditionally enable JIT support (can borrow from partydonk prototype)
- [ ] unconditionally enable interpreter support
- [ ] support for the `RuntimeFeature` flag to check for [experimental features](https://github.com/dotnet/designs/pull/185) - will be used to tag BCL additions.

**Comment by lambdageek** [comment]
@vargaz I think we're probably going to need static vtables.  The ecma spec addendum says the static interface methods are going to be in the methodimpl table.  The partydonk prototype completely ignores that and does matching by name.  But we should just add a `PROP_STATIC_VTABLE` to `InfrequentDataKind` and just write down the impls from the MethodImpl in there when setting up the class.  It can be completely separate from instance vtable layout.  What do you think?

**Comment by davidwrighton** [comment]
There is now a working implmentation of all of this for CoreCLR checked in. Tests are disabled for mono, but otherwise it should be ready for implementation work to begin in Mono.

**Comment by lambdageek** [comment]
Zoltan implemented the initial version in #53465 

Notably generic sharing does not work correctly, so the AOT support isn't quite there yet.

**Comment by lambdageek** [comment]
Remaining work pushed back to .net 7

**Comment by lambdageek** [comment]
@tannergooding @stephentoub I think in general Mono is in good shape to use static virtual methods in libraries.  There may be bugs, but the only remaining completely unimplemented functionality that I'm aware of is the `constrained . ldftn` opcode - ie `&T.StaticMethod`  and creation of delegates from static virtual methods from inside another generic method.

**Comment by SamMonoRT** [comment]
@lambdageek @BrzVlad - There are a couple unchecked ones. Are these required for 7.0 or can this be moved to 8.0.0 ?

**Comment by BrzVlad** [comment]
Moving to 8.0 since only corner cases from runtime tests are left implementing
