### ISSUE TITLE
[wasm] Tracking issue for options for build improvements

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50287]
Ideas that we can try:

For build time:
- [x] Compile bitcode files, and use the .o files for the linking step (https://github.com/dotnet/runtime/issues/50285) (assigned: @radical)
- [x] `WasmDedup=true`
- [x] `DisableParallelAot=false`
- [x] Incremental builds, correctly handle dependencies (https://github.com/dotnet/runtime/issues/51013)

General build improvements:

- [x] lewing: emcc-flags.txt should be line based and emcc-flags.rsp
- [ ] #89482

/cc @vargaz @steveisok @lewing

**Comment by radical** [comment]
Closing this as there is only one issue left - https://github.com/dotnet/runtime/issues/89482 , and marking that for 8.0 .
