### ISSUE TITLE
PGO: Enable PGO Pipeline for Framework assemblies

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#50517]
This is a tracking issue for PGO related work in the runtime repo:

- [x]  PGO training data is flowing from optimization scenarios
- [x]  PGO training data is embedded within assemblies from runtime repo
- [x] Flow PGO data into checked runtime build to enable better testing (PR #50536)
- [x]  PGO training data is embedded within assemblies from aspnet repo
- [x] Update SDK to allow specification of training data at publish time
- [x] Publish training data from standard scenarios for internal consumption
- [x]  Codegen is able to consume the profile data to influence optimizations for measure performance gains.
- [ ] PGO training data influences file layout
- [ ]  Validate the filesize increases are expected and within 1% with PGO data embedded.
- [ ] Enable crossgen2 testing of pgo data generation/consumption
  - [x] Use training data for composite framework generation in outerloop testing (PR #50536)
  - [ ] Enable test pipeline with pgo data collection and consumption
- [x] R2RDump dumps embedded pgo data
- [ ] PGO training data is associated exact IL so that degradation from non-matching data is reduced
- [ ] Validate PGO training data provides meaningful boost in runtime performance
- [x] Publish training data from standard scenarios for public consumption
  - [ ] Consider making it easy/automatic to consume when building a standalone application and recompiling the core framework assemblies
 
@davidwrighton @AndyAyersMS @JulieLeeMSFT to add/update items.

**Comment by AndyAyersMS** [comment]
See also some of the items in #50432. If there's consensus I will add some of them to the list above.

Would really like to see PGO data flow into Checked SPC builds. Because everything is keyed to IL, and the IL in a checked SPC diverges from the IL in a release SPC, this requires a separate collection and package.

Or perhaps some level of CI testing with release runtime + SPC and a checked jit.

**Comment by mangod9** [comment]
@AndyAyersMS yeah would make sense to capture relevant tasks as part of this list.

**Comment by davidwrighton** [comment]
@AndyAyersMS  I've put together #50536 which will address the checked build with pgo data concern as well as adding pgo to our outerloop testing path

**Comment by mangod9** [comment]
@davidwrighton assume this is ok to close and remaining work can be tracked as separate items for .net 7?

**Comment by mangod9** [comment]
Closing per discussion we can move the remaining work to .net 7
