### ISSUE TITLE
[wasm][tests][eat] Multiple test failures with EnableAggressiveTrimming

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50724]
- [ ] https://github.com/dotnet/runtime/issues/50874
- [ ] https://github.com/dotnet/runtime/issues/56845
- [ ] [System.Dynamic.Runtime.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-d7050d97e17f4af48c/System.Dynamic.Runtime.Tests/console.f65216d1.log?sv=2019-07-07&se=2021-05-14T10%3A12%3A51Z&sr=c&sp=rl&sig=joFjNEgxpTnETLo%2BQpy0GG9W3JRhjUYwDz51sJW1Qcs%3D)
- [ ] [System.Net.Primitives.Functional.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-d7050d97e17f4af48c/System.Net.Primitives.Functional.Tests/console.baa9a70c.log?sv=2019-07-07&se=2021-05-14T10%3A12%3A51Z&sr=c&sp=rl&sig=joFjNEgxpTnETLo%2BQpy0GG9W3JRhjUYwDz51sJW1Qcs%3D)
- [ ] https://github.com/dotnet/runtime/issues/50711
- [x] https://github.com/dotnet/runtime/issues/56846
- [ ] [System.Diagnostics.Tracing.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-d7050d97e17f4af48c/System.Diagnostics.Tracing.Tests/console.f043451f.log?sv=2019-07-07&se=2021-05-14T10%3A12%3A51Z&sr=c&sp=rl&sig=joFjNEgxpTnETLo%2BQpy0GG9W3JRhjUYwDz51sJW1Qcs%3D)

Fixing in https://github.com/dotnet/runtime/pull/50885

**Comment by radical** [comment]
Closing this. Failures are being tracked by most individual issues now.
