### ISSUE TITLE
Mono Componentization

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#50862]
This is a project about delivering optional features with the Mono runtime as pieces that can be included or omitted by the workload for particular scenarios.

## Tasks ##

Initial lift
- [x] [Design document](https://github.com/dotnet/runtime/blob/main/docs/design/mono/components.md) - code organization #49913
- [x] Initial implementation #50837 - static components only
- [x] Dynamic components
- [x] Design an MSBuild protocol between runtime pack and workloads https://github.com/dotnet/runtime/issues/54417 
   - [x] Generate a .props file describing the components into the runtime pack
   - [x] Default targets for describing which native libs to link given the selected components
- [x] Runtime functional tests

Components
- [x] Diagnostic Server & EventPipe
- [x] Hot Reload - PR #52866 

Followup work
- [x] (moved to vNext #57131) ~Route eglib stateful functions (logging, allocators) from the components to the runtime~

Bonus
- [x] Move debugger to a component
- [x] (moved to vNext #57131) ~Move the interpreter to a component (leverage existing libmono-ee-interp.a support)~

End to end supported workloads:
- [x] Browser #54565
- [x] Android
- [x] iOS Simulator
- [x] iOS Device
- [x] MacCatalyst

**Comment by lateralusX** [comment]
EventPipe/DiagnosticsServer need this support for .net6 on platforms where we use TCP transport in DiagnosticsServer (iOS/Android).

**Comment by lambdageek** [comment]
We need some uniform mechanism to update src/installer/pkg/sfx/Microsoft.NETCore.App/Directory.Build.props for the installer packaging of components.  Adding individual manifest entries doesn't seem sustainable.

**Comment by lateralusX** [comment]
Initial implementation and use of static components on all platforms, done.

**Comment by CoffeeFlux** [comment]
We should estimate the size savings when compiling out the debugger to try and prioritize componentizing it.

**Comment by lateralusX** [comment]
Support for dynamic components done, currently Android runtime is configured to use dynamic instead of static components.

**Comment by steveisok** [comment]
@lambdageek Do you think we're good for what you wanted to get out of 6.0?

**Comment by lewing** [comment]
good for 6 from my side

**Comment by lambdageek** [comment]
Yea I think we're good for .net6.  Moved the remaining work to a new issue #57131
