### ISSUE TITLE
[Mono] Upgrade LLVM to 11.0

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#51312]
Tracking issue to upgrade LLVM from 9.x to 11.0 to consume newer features

- [x] Forward-port mono-specific patches to LLVM 11
- [x] Ensure dotnet/runtime builds against a local copy of patched LLVM 11
- [x] Enable running dotnet/runtime against a custom build of LLVM 11 on CI
- [x] Switch to using LLVM 11 in production

Not strictly needed
- [ ] Verify that Apple bitcode submission works with bitcode generated by patched LLVM 11

**Comment by SamMonoRT** [comment]
Local branch for upgrade to LLVM 11: https://github.com/imhameed/llvm-project/tree/ih-llvm11-test

**Comment by imhameed** [comment]
Now LLVM 11 fails to build with:
```
[...]
Scanning dependencies of target benchmark_main
make[2]: *** No rule to make target `utils/llvm-locstats/llvm-dwarfdump', needed by `bin/llvm-locstats'.  Stop.
make[1]: *** [utils/llvm-locstats/CMakeFiles/llvm-locstats.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by imhameed** [comment]
The work-in-progress runtime-side changes can be found here: https://github.com/imhameed/runtime/tree/mono-llvm11

**Comment by imhameed** [comment]
https://github.com/dotnet/runtime/pull/51993

**Comment by imhameed** [comment]
The CI test suite is being run against LLVM 11 here: https://github.com/dotnet/runtime/pull/52984

There are some genuine failures on the LLVM AOT lanes for arm64 and amd64. I don't have access to my usual Linux work setup right now, and I can't reproduce these failures on amd64 Catalina, so I'm setting up a little Linux VM to debug this further.

**Comment by SamMonoRT** [comment]
@imhameed  - please verify that all required updates are reflected in main and we can close this issue.

**Comment by imhameed** [comment]
This should be done.
