### ISSUE TITLE
Developers using filesystem APIs find them to work well with symbolic links

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#51605]
Proposed priorities for the issues we currently have open in the [symlinks project](https://github.com/dotnet/runtime/projects/41).

## P0

- [x] https://github.com/dotnet/runtime/issues/36091 ReloadOnChange of AddJsonFile is invalid in kubernetes [AB#1282969](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1282969).
- [x] https://github.com/dotnet/runtime/issues/25078 Linux: FileSystemWatcher does not raise events when target directory is symlink - [PR merged](https://github.com/dotnet/runtime/pull/52679)
- [x] https://github.com/dotnet/runtime/issues/37301 Unix: FileSystemEntry.Attributes property is not correct on Unix - [PR merged](https://github.com/dotnet/runtime/pull/52235)
- [x] https://github.com/dotnet/runtime/issues/24271 APIs for symbolic links - [PR](https://github.com/dotnet/runtime/pull/54253/)

For items moved to .NET 7 please refer to #57205

**Comment by iSazonov** [comment]
@carlossanlop In PowerShell an symlink functionality was already added but we catch a lot of bugs, some (not all) ones was fixed. So your team could look  and use the experience to make the work better in .Net.

**Comment by adamsitnik** [comment]
@Jozkee @carlossanlop @jeffhandley should we move the things that are not done yet to a new issue and close this one? Or just move this to 7.0.0 milestone?

**Comment by jeffhandley** [comment]
I'd prefer to update this one to reflect what was completed in 6.0.0 and file a new issue for 7.0.0 (that links to this one).

**Comment by adamsitnik** [comment]
@jeffhandley done: #57205
