### ISSUE TITLE
[wasm] Tracking issue for testing on Windows

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#52143]
- [x] [Helix/windows image changes needed for running tests](https://github.com/dotnet/runtime/issues/51631)
- [ ] [helix/windows tests issues](https://github.com/dotnet/runtime/issues/52138)
- [ ] Functional tests (`src/tests/FunctionalTests/WebAssembly/`)
- [ ] Library tests
- [ ] Wasm.Build tests
- [ ] Runtime tests
- [ ] Debugger tests
- [ ] AOT tests (v8+chrome)
    - [ ] System.Buffers
    - [ ] Enable other tests
- [ ] Integration tests
    - [ ] blazor
    - [ ] blazor+aot, with workloads
    - [ ] blazor+debugger, with page interaction
    - [ ] build these with `dotnet`, and `msbuild`

**Comment by radical** [comment]
cc @steveisok @radekdoulik

**Comment by radical** [comment]
Mostly superseded by https://github.com/dotnet/runtime/issues/52138 .
