### ISSUE TITLE
Tracking issue for threading work items

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#52701]
- [ ] Increase starvation heuristic for blocking due to sync-over-async (https://github.com/dotnet/runtime/issues/52558)
- [ ] Improve starvation heuristic in general - increase the rate of thread injection
- [ ] Reduce the overhead of hill climbing - it seems to do more noticeable harm than good in perf tests
- [ ] The overhead of work stealing is too high, fix
- [ ] Lot more to add here

**Comment by davidfowl** [comment]
@kouvel do you want to link some of the other work items.

**Comment by kouvel** [comment]
Yes there are some links I can add, I'm not there yet

**Comment by kouvel** [comment]
Well there are links to issues I can add in some cases, not for work items

**Comment by mangod9** [comment]
Thanks for listing these. Couple of questions: 
1. Are these in priority order? 
2. Would be good to determine which will make it into .net 6 preview 7 timeframe
3. First and last items are basically the same?

**Comment by kouvel** [comment]
> Are these in priority order?

These are not in any particular order, I believe they are all worth doing.

> Would be good to determine which will make it into .net 6 preview 7 timeframe

Other than the checked item, "Increase rate of thread injection for blocking due to sync-over-async" and "Fix spin-waiting to not depend on values measured at startup" are the currently scheduled items.

> First and last items are basically the same?

The last one is specific to sync-over-async and works a bit differently. There is some overlap between them.

**Comment by davidfowl** [comment]
This list is awesome. There are only 2 open work items. Great work all. We made lots of progress on the thread pool over the years.

**Comment by jeremysimmons** [comment]
I was interested in the event for ThreadPool mentioned in #11008, does this exist?
I don't see an item tracking this
 https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool?view=net-8.0 doesn't have any events listed.

**Comment by kouvel** [comment]
> I was interested in the event for ThreadPool mentioned in https://github.com/dotnet/runtime/issues/11008, does this exist?

This event indicates when starvation is detected (when `Reason` is `Starvation`): https://learn.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-thread-events#threadpoolworkerthreadadjustmentadjustment-event

**Comment by WeihanLi** [comment]
Currently, we already have some threadpool metrics in the runtime metrics, could we also add metrics for thread starvation?
