### ISSUE TITLE
Improve JIT loop optimizations (.NET 7)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#55235]
This issue describes which loop optimization opportunities we intend to work on for .NET 7. A full summary of RyuJIT loop optimization opportunities is given in https://github.com/dotnet/runtime/issues/65342.

## Work in .NET 7

- [x] Generalize loop cloning to be more flexible w.r.t. the loop initialization condition. This helps OSR. https://github.com/dotnet/runtime/pull/66257
- [x] Address multi-dimensional array deficiencies, since they are often used in loops, as described by https://github.com/dotnet/runtime/issues/60785
- [ ] (Andy WIP) Improve loop cloning: https://github.com/dotnet/runtime/issues/65206

## Cut

- [ ] Address loop recognition weaknesses described by https://github.com/dotnet/runtime/issues/43713, https://github.com/dotnet/runtime/issues/58941
- [ ] Consider loop cloning improvements to aid OSR, as described here: https://github.com/dotnet/runtime/issues/33658#issuecomment-1055894673

category:planning
theme:loop-opt
skill-level:expert
cost:large

**Comment by BruceForstall** [comment]
The time for feature work in .NET 7 has passed, so closing this.
