### ISSUE TITLE
[Arm64] Peephole optimization opportunities

### ISSUE THREAD

**Issue by echesakov** [dotnet/runtime#55365]
- [x] #35141 : Optimize redundant memory loads with mov
  - [x] #35071 : Redundant load/stores for methods that operates/returns structs
  - [x] #35136 : Optimize pair of "str wzr, [reg]" to "str xzr"
  - [x]  #35134 : Optimize pair of "str reg, [fp]" to stp (**Done**: https://github.com/dotnet/runtime/pull/77540)
  - [x] #35133 : Optimize pair of "str reg, [reg]" to stp  (**WIP**: PR77540)
  - [x] #35132 : Optimize pair of "ldr reg, [reg]" to ldp (**WIP**: PR77540)
  - [x] #35130 : Optimize pair of "ldr reg, [fp]" to ldp  (**WIP**: PR77540)
  - [x] #35254 : Redundant movs done for zero extend the register

category:cq
theme:optimization
skill-level:expert
cost:medium
impact:medium

**Comment by kunalspathak** [comment]
Moving this to Future. 
cc: @a74nh

**Comment by kunalspathak** [comment]
https://github.com/dotnet/runtime/issues/81278 should fix #35130, #35132, #35133

**Comment by kunalspathak** [comment]
All the identified work items are done.
