### ISSUE TITLE
Additional diagnostics for .NET 6

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#56072]
The goal is to help customers better understand how their applications are running by adding events and counters that can give more insights and will help them debug potential performance issues. It'll also help us debug customer applications and write tools that would be able to glean insights from traces.

## Runtime
- [ ] What is the thread pool configuration? Many of our customers set a high number of minimum thread pool threads to “fix” starvation. Knowing what this is relative to machine setting (working set and core count) would be useful. (tracked in https://github.com/dotnet/runtime/issues/57247)
- [x] What app context switches are used, and what are they set to? This will tell customers what quirks are enabled (binary formatter etc.) This can be a huge aid when debugging applications. (tracked in #56142)
- [ ] What are the GC settings? Today it's sometimes difficult to tell how the GC was configured without a dump. The goal is to have an event that emits the current GC settings so customers can see what was applied. (part of PR #55888)
- [ ] What was the value of Environment.ProcessorCount should be emitted in an event. I'm not sure which event is most appropriate for this (if we have an existing one) but we need a way to get the runtime settings. (tracked in #56143)

## Networking

- [x] How much time is spent in DNS resolution? This is a blocking operation, and we added a mitigation for this in .NET 6. We would like customers to be able to determine the time spent here using something high level like a counter or an event (Do we already have an event for this?)
    - dns-lookups-duration counter + we have the events
- [ ] How many unique DNS addresses are resolved in an application’s lifetime? In .NET 6 we added some special logic to queue DNS requests to a single host name (to avoid thread pool starvation). We assume there is a handful of these in the process. Can we add a counters so customers can get a sense of what total and unique DNS resolutions look like in their applications? (tracked in #48885)

## Threading
- [ ] How many timers are one-shot, vs periodic? The Timer implementation optimizes for timers firing rarely, customers can figure out how their timer queue is behaving. Today we only collect the number of timers, but not the types of timers.
- [ ] We added a thread pool starvation mitigation feature in .NET 6 and have added events that kick in when this mechanism is being used. We should make sure we have the appropriate events here so that customers can observe how this is behaving in their systems.

## ArrayPool
- [x] How many arrays are discarded when returning to the pool? This is a measure of pooling efficiency that we’d like to help customers understand better. We have an event but we need to make sure it's efficient enough to turn on in a production environment.

## Dependency Injection
- [x] We would like to help customers better understand some statistics about registered services:
 - How many singleton services?
 - How many scoped services?
 - How many transient services?
 - How many container instances are in the processes?
 - (tracked in #56313)

similar issue in aspnetcore repo: https://github.com/dotnet/aspnetcore/issues/34578

cc @danmoseley @jeffschwMSFT @jkotas @geoffkizer @stephentoub @eerhardt @kouvel @mangod9 @Maoni0

**Comment by danmoseley** [comment]
@ericstj @karelz @jeffhandley

**Comment by stephentoub** [comment]
> How much time is spent in DNS resolution? This is a blocking operation, and we added a mitigation for this in .NET 6. We would like customers to be able to determine the time spent here using something high level like a counter or an event (Do we already have an event for this?)

The existing dns-lookups-duration counter provides this.

> How many unique DNS addresses are resolved in an application’s lifetime?

What is a developer going to do with this information? Doing this "perfectly" would be a leak, as it would require the application to maintain a set of every address it saw; that's not viable. Events are already emitted for that information, so a dev can post-process that information from traces if needed.  https://github.com/dotnet/runtime/issues/48885 proposes one for the number of unique addresses _currently_ being resolved; from my perspective, that's more reasonable, though I'm not sure how actionable it actually is, either.

> How many arrays are discarded when returning to the pool? This is a measure of pooling efficiency that we’d like to help customers understand better. We have an event but we need to make sure it's efficient enough to turn on in a production environment.

What is "efficient enough"? Just adding one (uncontended) interlocked operation increases the cost of renting/returning by 10%:
```C#
private long _counter;

[Benchmark(Baseline = true)]
public void RentReturn()
{
    ArrayPool<byte>.Shared.Return(ArrayPool<byte>.Shared.Rent(16));
}

[Benchmark]
public void RentReturnInterlocked()
{
    ArrayPool<byte>.Shared.Return(ArrayPool<byte>.Shared.Rent(16));
    Interlocked.Increment(ref _counter);
}
```
|                Method |     Mean |    Error |   StdDev | Ratio |
|---------------------- |---------:|---------:|---------:|------:|
|            RentReturn | 16.54 ns | 0.051 ns | 0.047 ns |  1.00 |
| RentReturnInterlocked | 18.40 ns | 0.132 ns | 0.117 ns |  1.11 |

and if it's contended, the difference skyrockets:
```C#
private long _counter;

[Benchmark(Baseline = true)]
public void RentReturn()
{
    Parallel.For(0, 1_000_000, i =>
    {
        ArrayPool<byte>.Shared.Return(ArrayPool<byte>.Shared.Rent(16));
    });
}

[Benchmark]
public void RentReturnInterlocked()
{
    Parallel.For(0, 1_000_000, i =>
    {
        ArrayPool<byte>.Shared.Return(ArrayPool<byte>.Shared.Rent(16));
        Interlocked.Increment(ref _counter);
    });
}
```
|                Method |      Mean |     Error |    StdDev | Ratio |
|---------------------- |----------:|----------:|----------:|------:|
|            RentReturn |  3.437 ms | 0.0373 ms | 0.0349 ms |  1.00 |
| RentReturnInterlocked | 19.153 ms | 0.0407 ms | 0.0381 ms |  5.57 |

Even for the uncontended case, the difference is more pronounced if you just look at such an interlocked in comparison to an allocation (since for dropped arrays, that's basically what we're talking about):
```C#
private long _counter;

[Benchmark(Baseline = true)]
public void Allocate()
{
    _ = new byte[16];
}

[Benchmark]
public void AllocateInterlocked()
{
    _ = new byte[16];
    Interlocked.Increment(ref _counter);
}
```
|              Method |     Mean |     Error |    StdDev | Ratio |
|-------------------- |---------:|----------:|----------:|------:|
|            Allocate | 2.697 ns | 0.0289 ns | 0.0270 ns |  1.00 |
| AllocateInterlocked | 6.811 ns | 0.0745 ns | 0.0696 ns |  2.53 |

I added the event for dropped arrays in .NET 6 with the idea that someone can either measure it in development, or they can temporarily turn on the event for a minute in production to get a sampling of what their app is doing.

> How many timers are one-shot, vs periodic? The Timer implementation optimizes for timers firing rarely, customers can figure out how their timer queue is behaving. Today we only collect the number of timers, but not the types of timers.

(It's more that it optimizes for adds/removes happening much more frequently than firings.)

What is someone going to do with information about periodic vs non-periodic?

**Comment by karelz** [comment]
@davidfowl 

> How many unique DNS addresses are resolved in an application’s lifetime?

I agree with @stephentoub here. Let's move the final discussion into #48885 and let's decide there if we want current vs. all-lifetime, how useful it is and if it needs to land in 6.0 vs. Future.

BTW: I updated the first Networking item with answer inline in the top post for easier tracking.

**Comment by jeffschwMSFT** [comment]
@mangod9

**Comment by jeffschwMSFT** [comment]
> What app context switches are used, and what are they set to? This will tell customers what quirks are enabled (binary formatter etc.) This can be a huge aid when debugging applications.

There are more than just app context switches and should consider most configuration of NetCoreApp which also include environment and runtimeconfig.json.  My hypothesis is that these are raw.

> What are the GC settings? Today it's sometimes difficult to tell how the GC was configured without a dump. The goal is to have an event that emits the current GC settings so customers can see what was applied.

I presume this is referring to the various dynamically tuned configuration within the gc - budget, etc.  As traces already capture the gc configuration - svr vs wks.  Capturing the current set of configuration we would gather the remaining configuration details.  

> Runtime

I believe that all these would need to be rundown events as they are configuration and would likely fire at startup.

>  How many timers are one-shot, vs periodic? The Timer implementation optimizes for timers firing rarely, customers can figure out how their timer queue is behaving. Today we only collect the number of timers, but not the types of timers.

This feels like a perf counter/metric.  Do we have something analogous already?

**Comment by stephentoub** [comment]
> This feels like a perf counter/metric. Do we have something analogous already?

We have active-timer-count, which polls Timer.ActiveCount.  That's inclusive of all timers, both periodic and non-periodic.  David is suggesting splitting that to know how many are periodic and how many are non-periodic.  I'd like to understand how such knowledge would be used :)

**Comment by stephentoub** [comment]
>> Runtime

> I believe that all these would need to be rundown events as they are configuration and would likely fire at startup.

If the goal is simply to report configuration so that it's in a trace log, could we have one event / rundown component that's just a text string that includes every bit of configuration information we can muster?

**Comment by davidfowl** [comment]
> There are more than just app context switches and should consider most configuration of NetCoreApp which also include environment and runtimeconfig.json. My hypothesis is that these are rare.

I'm not sure I want to group environment variables as part of the other runtime payload since it might contain PII and secrets and you may not want that to be it the same events as the other configuration.

**Comment by jeffschwMSFT** [comment]
>> There are more than just app context switches and should consider most configuration of NetCoreApp which also include environment and runtimeconfig.json. My hypothesis is that these are rare.

> I'm not sure I want to group environment variables as part of the other runtime payload since it might contain PII and secrets and you may not want that to be it the same events as the other configuration.

Certainly not recommending the peb, but rather we have configuration that is unique to complus_/dotnet_ env variables.  There are a few config systems that we could query for configuration information.  App context is only 1.

**Comment by davidfowl** [comment]
> Certainly not recommending the peb, but rather we have configuration that is unique to complus_/dotnet_ env variables. There are a few config systems that we could query for configuration information. App context is only 1.

I agree, lets add that to the list.

**Comment by noahfalk** [comment]
> What was the value of Environment.ProcessorCount should be emitted in an event

Do you care about the number of processors on the machine, or specifically this value (which I believe might differ when apps run with restricted processor groups)? For the machine level info ETW emits that into every trace with the Windows Kernel/EventTrace event.

> What are the GC settings?

Maoni has a PR open that is adding that info: https://github.com/dotnet/runtime/pull/55888

> How many unique DNS addresses are resolved in an application’s lifetime?

Agreed with @stephentoub that metrics that involve distinct counts are expensive to maintain. The description sounded like we had added a caching or bucketing scheme and we wanted to understand whether it was operating effectively. Standard measures are often total cache requests, cache hits, cache misses, and max cache size if it is dynamically sized. 

> How many arrays are discarded when returning to the pool? This is a measure of pooling efficiency that we’d like to help customers understand better. We have an event but we need to make sure it's efficient enough to turn on in a production environment.

The events that are present now could be very noisy because they fire every time a buffer is dropped. You probably want a new counter that summarizes how many buffers are being dropped per second.


Overall, given that these asks span different areas/teams, each of which will need to independently triage and track the request it probably makes sense for area owners to open new issues for any of the above items that can't be immediately marked done (as Karel did with #48885). I added several for the runtime area that I am guessing would fall upon Tom's team, but I also immediately postponed them to 7.0 as we need the remaining 6.0 time to finish addressing bugs. Of course if someone else not on Tom's team can get to them right away we can gladly reassign them.

**Comment by stephentoub** [comment]
> The description sounded like we had added a caching or bucketing scheme and we wanted to understand whether it was operating effectively.

Sort of.  When there's no OS-based asynchronous mechanism for doing asynchronous DNS resolution, as there is on newer Windows releases, we fall back to implementing Dns.XxAsync via async-over-sync, meaning we queue a work item to the thread pool that will do the operation synchronously.  That, however, can be an issue if you get a burst of requests that all try to resolve the same address at the same time and satisfying those requests can take some time because the OS doesn't have the information cached and needs to go off-box to get it.  In such a case, you can end up tying up all threads in the pool effectively performing the same operation.  For .NET 6, for such cases, we've add a serialization mechanism, where we maintain a static dictionary of all such requests currently in flight, ensuring that if there's an in-flight request for address A, another request for address A doesn't actually get queued to the thread pool until the first request finishes.
https://github.com/dotnet/runtime/blob/14d6532f388903f425f0a3b9dea697c5a28293d3/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs#L660-L722

**Comment by davidfowl** [comment]
Environment.ProcessorCount is separate because we can change it based on an environment variable now. I'd want that to be a part of the runtime settings blob we emit

**Comment by noahfalk** [comment]
Thanks @stephentoub. Perhaps the desirable metrics would be the maximum size of the dictionary ever observed and the maximum size of the task queue for any single key? You might also want to measure maximum latency for a single request or a batch of requests, a lot of this depends on what we want to learn about the implementation.

Thanks @davidfowl - I captured your response over on #56143 so we don't lose it.

**Comment by danmoseley** [comment]
@davidfowl  can we close on ArrayPool specifically - given we cannot add an event by default due to cost, is the existing opt-in event sufficient?  If so we can scratch that one out. Or, we can tune it in servicing if needed.

**Comment by danmoseley** [comment]
@eerhardt could you (or someone) evaluate the value and cost of the asks here for DI? We should boil any that make sense into a separate issue. 

Anything that is worthwhile but also costly could potentially hold off until eg 6.0.1

**Comment by danmoseley** [comment]
@davidfowl can you respond to questions by Stephen/Jeff above about your Timers ask?

**Comment by danmoseley** [comment]
ping @davidfowl ...

**Comment by davidfowl** [comment]
My thought was it was to help people understand how many periodic vs short lived timers they had. Ina typical application, id expect a handful of periodic timers and lots of short lived ones. As a potential signal for problems (maybe people are spinning up a crapload of http clients vs a crapload of cancellation tokens).

**Comment by danmoseley** [comment]
@stephentoub thoughts about that?

@davidfowl what about arraypool question above?

I want to drive open issues here so we can rapidly get to a firm list of what we're doing for 6.0.

**Comment by stephentoub** [comment]
I'm not convinced it'd be particularly helpful; at the point where we see "oh my goodness there's a ton of timers", the next step is usually "where are all of these coming from", and knowing the periodic/one-shot split doesn't help with that. And it'd be yet another thing to track. But I don't feel strongly about it.

**Comment by davidfowl** [comment]
> I'm not convinced it'd be particularly helpful; at the point where we see "oh my goodness there's a ton of timers", the next step is usually "where are all of these coming from", and knowing the periodic/one-shot split doesn't help with that. And it'd be yet another thing to track. But I don't feel strongly about it.

Lets punt it then! 

> @davidfowl what about arraypool question above?

I have another one about array pool. I think we need more detailed usage statics about the shared array pool.

**Comment by danmoseley** [comment]
@davidfowl can you please give more detail on what you're hoping to learn from ArrayPool data. There's a perf concern about the discard rate. Help us get asap to an agreed list if any.

**Comment by eerhardt** [comment]
Just following up here that the Dependency Injection work was completed with https://github.com/dotnet/runtime/pull/56809.

**Comment by danmoseley** [comment]
thanks. @davidfowl I don't see any remaining 6.0 work here. Do you agree? If so I would like to close this.

**Comment by joperezr** [comment]
Moving this to 7.0.0 for now from the discussion above. If you guys prefer to either move back to 6.0 (if there is anything we still want to do for 6.0) or close, feel free to do so.

**Comment by danmoseley** [comment]
@mangod9 @davidfowl can we close this now?

**Comment by davidfowl** [comment]
Yes
