### ISSUE TITLE
[HTTP/3] Developers can build libraries for HTTP/3 to meet their client/server needs (.NET 7)

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#57600]
Continuing where #43546 left off. For .NET 6, HTTP/3 was in preview, in .NET7 we need to make sure its ready for end to end usage.
---
HTTP3 is the next major version of HTTP and the successor to HTTP2. It is in the final stages of standardization in the IETF. Some browsers (notably Chrome) already support draft versions of HTTP3. HTTP3 runs over QUIC, which replaces TCP as the underlying transport. QUIC is also in the final stages of standardization in the IETF. It provides secure, multiplexed streams over UDP. QUIC is a general-purpose, extensible transport protocol and we expect it to be used by other application protocols aside from HTTP3.

## Work Items
- [x] A set of public classes for using the QUIC protocol on either client or server. This is System.Net.Quic. It is the equivalent of System.Net.Sockets for the QUIC protocol. #57601
- [x] HTTP3 client support in HttpClient/SocketsHttpHandler.
- [x] Linux support
- [ ] MacOS support

### P0
- [x] #2262 - Improve QuicListener API to not have non-functional properties
- [x] #31695 - Use GCHandles
- [x] #32050 - Fix stream read returning 0 on connection abort
- [x] #32066 - Improve error messages and move to resources
- [x] #32071 - TLS server options
- [ ] #32072 - Handle exceptions within MsQuic callbacks
- [x] #32073 - Fix QuicListener disposal leaking MsQuic handles
- [x] #32075 - Finalize "abortive dispose" model
- [x] #32079 - Implement stream availability events
- [x] #32142 - Finalize dispose model
- [x] #44580 - Update MsQuic
- [x] #756 - Finalize shutdown behavior
- [x] Add tests
- [x] #32069 - TLS client options
- [x] #32077 - Implement Write cancellation support
- [x] #43000 - Make RemoteEndPoint an IPEndPoint

### P1
- [x] #32575 - Implement platform compatibility detection
- [x] #42651 - Optimized stream reads
- [x] #32068 - Remove duplicate SOCKADDR code
- [x] #32076 - Optimize synchronous QuicStream APIs
- [ ] #43792 - (Decide if needed and) Implement sync APIs
- [ ] #42642 - (Decide if needed and) Split out configuration APIs
- [x] #44782 - Implement flush capability

### P2
- [ ] #43061 - (Decide if needed and) Participate in QUIC interop testing

We intend to share as much HTTP3 code as is reasonably possible between the client and server implementation.

**Comment by wegylexy** [comment]
Will the QPack helpers be `public` too?

**Comment by karelz** [comment]
The 7.0 work for HTTP/3 is finished.
