### ISSUE TITLE
Tracking issue for Core Runtime HouseKeeping Items

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#58120]
- [ ]	Rename test entrypoints
- [x]	Cg2 pipeline cleanup
- [ ]	Cg2 + libraries CI enablement
- [ ]	Test repo consolidation / merge
- [ ]	GC + containers e2e validation (including K8s)
- [ ]	GC codebase #define cleanup
- [ ]	GC improved test validation support 
- [ ]	How can we ship clrgc so it can be consumed easily
- [ ]	E2E Perfview Validation to ensure tracing is working 
- [x]	Documentation for threading / CET
  - Added doc describing CET and how to enable it - https://github.com/dotnet/runtime/pull/58891
  - Clarified/fixed some threading docs, documented new config settings for blocking in the thread pool due to sync-over-async - https://github.com/dotnet/dotnet-api-docs/pull/7137, https://github.com/dotnet/docs/pull/26041
- [x]	Threading Test removal
  - Removed some redundant/unnecessary threading tests from runtime tests, moved/added some missing cases to libraries tests - https://github.com/dotnet/runtime/pull/59073
- [ ]	Review SDK support for crossgen1 removal -- still need to targeting 5.0 (VS UX validation for R2R configuration)
- [ ]	Investigate Crossgen2 Composite app perf -- Fx composite mode is slower than standalone R2R [Perf investigations]
- [ ]	Regions -- GCPerfSim targets .net 5 (natively target .net 6)?
- [ ]	GC -- Validate whether piecemeal #define settings work 
- [ ]  GC -- Tuning code simulator
- [x]  GC -- Porting StressLogAnalyzer to Linux
- [ ]  GC -- Automated testing generational aware analysis 
- [x] dotnet/docs#25780
  - [ ] dotnet/sdk#20481
- Reduce size of crossgen2 distribution and cost of building
  - [ ] #58279 
- Clean up test build scripts by moving most of their functionality to MSBuild
   - [ ] #58762
- Minor R2RTest improvements (perfmap support, multiple test iterations)
   - [x] #58144
- Tooling for Jellyfin perf analysis
   - [x] https://github.com/richlander/jellyfin/pull/3

**Comment by danmoseley** [comment]
@mangod9 can you move this into the .NET 8 milestone now?

**Comment by ericstj** [comment]
@mangod9 are you still using this?  If not maybe it can be closed?

**Comment by mangod9** [comment]
Yeah closing for now since this has been superseded by other issues. Weird that it doesnt show up in my queries.
