### ISSUE TITLE
Crossgen2 perfmap format version support

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#58468]
As of

https://github.com/dotnet/runtime/pull/53792

Crossgen2 newly supports a new command-line option <code>--perfmap-format-version</code> that currently has two legal values, 0 and 1, where 0 corresponds to the "old style Crossgen1" perfmap naming format and 1 is the "new style Crossgen2" naming format. In particular, historically Crossgen1 used to name perfmap files like this:

<code>&lt;assembly-name&gt;.ni.{&lt;MVID of the MSIL file&gt;}.map</code>

This is insufficient and cumbersome in Crossgen2 composite mode where multiple assemblies get compiled into a single native executable; moreover the pre-existing scheme was insufficient anyway as symbol indexation needs to take targeting OS and architecture into consideration and that wasn't reflected in the <code>MVID</code>. The new naming in version 1 is like this:

<code>&lt;assembly-name&gt;.ni.r2rmap</code>

The current POR is that we drop the <code>{MVID}</code> bit and change <code>.map</code> to <code>.r2rmap</code> to avoid clashes with traditional .map files; this will need adjusting the following SDK source files:

https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs

We also need to adjust the script calling them:

https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets

These changes should let SDK make Crossgen2 produce the new perfmap format version 1 and ultimately switch over installer build in the runtime repo to produce the new perfmap style files. According to my understanding the bulk of the follow-up work will involve consuming the metadata in the perfmap file for the purpose of symbol indexation; I believe that should be tracked by a separate work item.

This change may need a counterpart perfview change and possibly additional downstream changes I'm not yet aware of; these will probably merit creating additional specific work items as we discover them.

Thanks

Tomas

/cc @dotnet/crossgen-contrib
@dotnet/dotnet-diag 
@tommcdon 
@brianrob 
@hoyosjs 
@mikem8361 

# Work Needed

- Consume the changes in R2R map generation.
  - [x] SDK needs to consume the flag for new perf format. dotnet/sdk#19132
  - [x] Runtime needs to also consume them in their copy of the tasks. dotnet/runtime#57195
  - [x] ASP needs to consume this in their own custom CrossGen2 runner. dotnet/aspnetcore#35288
- Packaging and indexing.
  - [x] Shared framework SDK needs to glob the new map files so they get properly packaged in symbol transport.  dotnet/arcade#7738
  - [ ] Symbol indexing needs to be updated to get an update in the spec and in the publishing/download tools.

**Comment by tommcdon** [comment]
@mangod we are transferring this issue to crossgen2 as we discovered there is work left on it.  Juan will be updating the checklist with the remaining work

**Comment by mangod9** [comment]
so this still requires work in 6?

**Comment by tommcdon** [comment]
@mangod yes this is net6 bug fix work. @hoyosjs is authoring a pr

**Comment by mangod9** [comment]
@hoyosjs assume this can now be closed based on your PR?

**Comment by mangod9** [comment]
Closing this issue for now.
