### ISSUE TITLE
[mono] Tracking: iOS - Size reduction

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#61815]
This tracks runtime-specific issues and work items in support of reducing the size of the iOS apps we generate.

**Achieved in 7.0.0**
- [x] https://github.com/dotnet/runtime/issues/54849
- [x] https://github.com/dotnet/runtime/issues/54850
- [x] https://github.com/dotnet/runtime/issues/70679

**Future work (8.0.0)**
- [x] https://github.com/dotnet/runtime/issues/56385

Size breakdown:
- Sizes by file included in the app bundle: https://github.com/xamarin/xamarin-macios/issues/10249#issuecomment-948993047
- Sizes by symbols included in the app binary: https://github.com/xamarin/xamarin-macios/issues/10249#issuecomment-896166472

How to build MySingleView:
1. Clone https://github.com/xamarin/xamarin-macios
2. Build xamarin-macios. Instructions: https://github.com/xamarin/xamarin-macios/wiki/Build-&-Run
3. `cd tests/dotnet/size-comparison/MySingleView; make compare`: https://github.com/xamarin/xamarin-macios/blob/61e43f8486451c6f1844c77df73f914e140b9f4d/tests/dotnet/Makefile#L41

[Bloaty](https://github.com/google/bloaty) can be used to view Mach-O arm64 symbol and section sizes.

**End Goals** 

- [ ] Same or smaller size https://github.com/xamarin/xamarin-macios/issues/10249 app for release arm64 output (less than 4.35 MB)
- [ ]  Same or smaller size default MAUI app template for iOS than Xamarin.Forms (TBD)

**Comment by ivanpovazan** [comment]
Closing this issue as all subtasks have been completed and reported size reduction is outdated.
/cc: @SamMonoRT
