### ISSUE TITLE
Remove Spaces from GitHub Labels

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#62032]
There have been several offline conversations recently about the spaces in use within labels in this repo. Common comments include:

1. Spaces in labels are annoying because it requires quotes around the label when searching/filtering
2. We are inconsistent between our use of spaces and dashes, but dashes are used far more often

I propose that we standardize on dashes and update existing labels with spaces to conform to dashes instead. Here is what would be affected if we adopted that approach:

- [ ]  `Bottom Up Work` ➡️ `bottom-up-work` (requires themesof.net change)
- [ ]  `Continuous Improvement`: Unused; could be deleted or changed to `continuous-improvement` (requires themesof.net change)
- [x] `Design Discussion` ➡️ `design-discussion`
- [x] `diagnostic global tooling`: Only used by 7 closed issues; could be deleted or changed to `diagnostic-global-tooling`
- [x] `feature request` ➡️ `feature` (for symmetry with `bug`) or `feature-request`
- [x] `FollowingUp` ➡️ Very low usage with only 1 (stale) open issue; could be deleted, changed to `following-up`, or merged with `needs-further-triage`
- [x] `hard problem` ➡️ `hard-problem` (or consider `difficulty:hard` with `easy` ➡️ `difficulty:easy`)
- [x] `in pr` ➡️ `in-pr` (impacts automation)
- [x] `needs further triage` ➡️ `needs-further-triage` (impacts automation)
- [x] `needs more info` ➡️ `needs-more-info` (impacts automation)
- [x] `* NO MERGE *` ➡️ `-NO-MERGE-` or `NO-MERGE`
- [x] `* NO SQUASH *` ➡️ `-NO-SQUASH-` or `NO-SQUASH`
- [x] `NO REVIEW` ➡️ `-NO-REVIEW-` or `NO-REVIEW`
- [x] `no recent activity` ➡️ `no-recent-activity` (impacts automation)
- [x] `release notes` ➡️ `release-notes`
- [x] `test bug` ➡️ `test-bug`
- [x] `test enhancement` ➡️ `test-enhancement`
- [ ] `User Story` ➡️ `User-Story` (requires themesof.net change)

/cc @terrajobst, @jeffschwMSFT, @danmoseley, @marek-safar

**Comment by terrajobst** [comment]
> * `* NO MERGE *` ➡️ `-NO-MERGE-` or `NO-MERGE`
> * `* NO SQUASH *` ➡️ `-NO-SQUASH-` or `NO-SQUASH`
> * `NO REVIEW` ➡️ `-NO-REVIEW-` or `NO-REVIEW`

I'd opt for no surrounding dashes. Color + ALL-CAPS should be enough to make those pop.

**Comment by danmoseley** [comment]
changes are fine with me, when we've changed label strings in the past there was little fallout: it seems that not many people bookmark queries.

**Comment by danmoseley** [comment]
BTW, I wonder whether there are any emerging standards across other dotnet repos, or repos in general? 

It looks like https://up-for-grabs.net/ is fairly agnostic.

It looks like https://github.com/microsoft/vscode/labels standardized on lower case kebab.

**Comment by danmoseley** [comment]
cc @eiriktsarpalis

**Comment by jeffhandley** [comment]
Thanks for the notes there, @danmoseley. I'm going to wait a couple days into next week before taking any action to make sure folks get to see this after the long US holiday weekend.

**Comment by karelz** [comment]
Given that we plan to rename "**feature request**" ... why do we even have this label? It is duplicate of '**enhancement**' label. Instead of renaming, should we just merge it? (happy to take it separately if needed / desired)

**Comment by eiriktsarpalis** [comment]
By the way -- with FabricBot configuration being moved to Config-As-Code (#62297) it should be fairly straightforward to bulk rename labels that are touched by automation.

**Comment by danmoseley** [comment]
My 2c I have no objection to any of the changes proposed.

**Comment by eiriktsarpalis** [comment]
I just merged #64048 which completed conversion of all labels impacted by FB automation.

**Comment by teo-tsirpanis** [comment]
Copying [a discussion item from the `dotnet-runtime-triage` team](https://github.com/orgs/dotnet/teams/dotnet-runtime-triage/discussions/1), I noticed that some labels in `dotnet/runtime` actually came from issues transferred from other repositories (like Roslyn or ASP.NET Core), and are effectively unused. They can be noticed by their incompleteness (e.g. there is "4 - In Review" but not the other three), inconsistent coloring or casing, irrelevant name or low issue population. These labels are:

* [`4 - In Review`](https://github.com/dotnet/runtime/labels/4%20-%20In%20Review)
* [`area-blazor`](https://github.com/dotnet/runtime/labels/area-blazor)
* [`Area-Compilers`](https://github.com/dotnet/runtime/labels/Area-Compilers)
* [`Area-NetSDK`](https://github.com/dotnet/runtime/labels/Area-NetSDK)
* [`area-runtime`](https://github.com/dotnet/runtime/labels/area-runtime)
* [`area-web-frameworks`](https://github.com/dotnet/runtime/labels/area-web-frameworks)
* [`blazor-wasm`](https://github.com/dotnet/runtime/labels/blazor-wasm)
* [`feature-httpclient-extensions`](https://github.com/dotnet/runtime/labels/feature-httpclient-extensions)
* [`New Feature - Warning Waves`](https://github.com/dotnet/runtime/labels/New%20Feature%20-%20Warning%20Waves)

Somebody with the necessary permissions could evaluate each label and delete it from `dotnet/runtime` if so decided.

---

The `dotnet/perf-autofiling-issues` repository is also introducing some labels that have a more plentiful `dotnet/runtime` equivalent but are named differently:

* [`arm64`](https://github.com/dotnet/runtime/labels/arm64) clashes with [`arch-arm64`](https://github.com/dotnet/runtime/labels/arch-arm64). I changed the only issue with this label (#64751).
* [`CoreClr`](https://github.com/dotnet/runtime/labels/CoreClr) clashes with [`runtime-coreclr`](https://github.com/dotnet/runtime/labels/runtime-coreclr).
* [`x64`](https://github.com/dotnet/runtime/labels/x64) clashes with [`arch-x64`](https://github.com/dotnet/runtime/labels/arch-x64).

Also the [`Regression`](https://github.com/dotnet/runtime/labels/Regression) label's name is misleading; it is applied on issues that represent _performance_ regressions, while the term "regression" means something broader.

Somebody with the necessary permissions could evaluate each label and synchronize its naming on `dotnet/perf-autifiling-issues` and the performanceautofiler bot if so decided.

**Comment by jeffhandley** [comment]
I've made all of the changes (including the cleanup identified by @teo-tsirpanis) except for those that require changes to themesof.net. That will need to be coordinated with @terrajobst and it potentially affects other repos as well.

**Comment by jeffhandley** [comment]
Since https://github.com/dotnet/runtime/labels/Bottom%20Up%20Work and https://github.com/dotnet/runtime/labels/Continuous%20Improvement are waning in usage, we won't worry about renaming those. This leaves only https://github.com/dotnet/runtime/labels/User%20Story with a space; the disruption from that is not justifiable.
