### ISSUE TITLE
Add support for reading, validating, creating, and encrypting COSE messages

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#62600]
### Minimum viable product (MVP) :

0. [ ] Add support for ns2.0 to System.Formats.CBOR.
1.  [ ] https://github.com/dotnet/runtime/issues/32121.
    - Proceed adding the code normally as any other new project.
    - Namespace will be System.Security.Cryptography.Cose.
    -  Scenarios that need support:
        - Tag/Untagged (Assume COSE_Sign1 in untagged case).
        - Embedded/detached content.
2. [ ] We need an sponsor for adding the feature without going through API review (@bartonjs nominated @jeffhandley as sponsor).
3. [ ] Show API to @blowdart for UX validation.
4. [ ] Add write support of COSE_Sign1.

### Additional scope after MVP:

5. [ ] https://github.com/dotnet/runtime/issues/62599
6. [ ] https://github.com/dotnet/runtime/issues/32123
