### ISSUE TITLE
System.IO.Compression work planned for .NET 7

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#62658]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Planned for .NET 7

- [x] #1547
- [x] #57197
- [x] #65951

## Backlog (roughly in priority order)

- [ ] Explore if we should consume the zlib-ng native cross-platform implementation to benefit ARM64.
  - [ ] PR testing this: #61883
- [ ] Improve the way our Zip APIs load entries in memory.
  - [ ] #1543
  - [ ] #1544
  - [ ] #49149
  - [ ] #59027
- [ ] #24149
- [ ] Explore if we should implement LZMA/7z or recommend an existing 3rd party package and contribute to it.
  - [ ] #1542
- [ ] Allow opening (raw) compressed archive entries in ZipArchiveEntry
    - [ ] #63155
- [ ] Add async compression APIs.
  - [ ] #1541
- [ ] Add stream-less compression APIs
  - [ ] #44793
- [ ] Ensure we provide full support for zip64 (reading, creating, updating).
  - [ ] #31825
- [ ] #1545
- [ ] Explore if we should implement ZStandard or recommend an existing 3rd party package and contribute to it.
  - [ ] #59591
- [ ] Clarify documentation ambiguity between some of our compression types: `DeflateStream`, `GZipStream`, `ZLibStream`.
- [ ] Explore if we should implement other algorithms or file formats, or recommend an existing 3rd party package and contribute to it.
- [ ] Continuous performance improvements.
- [ ] Improve documentation and add more examples.

**Comment by danmoseley** [comment]
Thanks @carlossanlop . Are there opportunities for community contributions here?

**Comment by carlossanlop** [comment]
Yes, I think I can mark a couple of issues as up-for-grabs, but I first need to add a comment with some context first.

**Comment by AraHaan** [comment]
More things I would like done for .NET 7 (Zlib):
- https://github.com/dotnet/runtime/issues/62113
  - prerec: https://github.com/dotnet/runtime/issues/42820#issuecomment-980830626

**Comment by Genbox** [comment]
Finally, System.IO.Compression gets some much-needed attention!

Ask 1:
Can we revert this rather [crazy input validation](https://github.com/dotnet/runtime/pull/57561)? It completely destroys any ability to provide an alternative value, even though the [related issue](https://github.com/dotnet/runtime/issues/46595) describes it as "a range check between 0 and 11" which out make much more sense.

Every sine encoder/decoder that currently exists and all future ones should have sane input validation on the compression level to ensure there is no unexpected behavior.

**Comment by Genbox** [comment]
Ask 2:
Can we change CompressionLevel to something a lot more user-friendly?

[Current values are](https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression/src/System/IO/Compression/CompressionLevel.cs):
- Optimal
- Fastest
- NoCompression
- SmallestSize

I propose we change it to:
- Store
- Fast
- Normal (or Default)
- High
- Maximum

If that is not possible for whatever reason, can we at least change "Optimal" to "Default"?

The main reason is that .NET devs and users alike seem to not understand what "optimal" means. I've had this [discussion in 2018](https://github.com/dotnet/runtime/issues/26097) and about 15 times since.

**Comment by Genbox** [comment]
Ask 4:

Zlib is great, but the implementation is dated.

There are several highly optimized versions out there:
- Intel ([whitepaper ](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/zlib-compression-whitepaper-copy.pdf) and [source](https://github.com/jtkukunas/zlib))
- Cloudflare ([source](https://github.com/cloudflare/zlib) and [AWS's patches](https://aws.amazon.com/blogs/opensource/improving-zlib-cloudflare-and-comparing-performance-with-other-zlib-forks/))
- Chromium ([source](https://source.chromium.org/chromium/chromium/src/+/main:third_party/zlib/))
- Zlib-ng ([source](https://github.com/zlib-ng/zlib-ng) and [bechmark](https://github.com/zlib-ng/zlib-ng/discussions/871))

Zlib-ng seems like a good next step:
- It has the optimizations from intel and Cloudflare
- It has a Zlib compatible API
- It has the same Zlib license
- It is 2x faster than Zlib out of the box

**Comment by AraHaan** [comment]
I been working on a span based zlib that calls into the same native version under the hood that provides more config. However it will need to be marked as ready for review so it can have a PR be created.

As for the PR I would have to place 2 related proposals into the same PR as well they depend on eachother on changes (new types would be added to expose all compression levels for all of the currently implemented compressors in the runtime for better configuration).

I would have made the options classes structs in that proposal but sadly C# does not allow structs to inherit from other structs.

**Comment by jeffhandley** [comment]
This list in this issue has been edited to reflect changes from our ongoing planning and discussions. The headings have been updated to reflect what is still planned for .NET 7 and what is in the backlog. The list is still expected to change throughout the release cycle with periodic reviews of our plans.

**Comment by AraHaan** [comment]
@jeffhandley any updates for what I proposed here for zlib (all linked here): https://github.com/dotnet/runtime/issues/62658#issuecomment-1032942626 ?

I really need them in .NET 7 at least if possible because span based compression apis should be a priority as well (I think) for those of us who hate stream based due to perf from loading a files as bytes, then create a stream, use that stream with compression apis to compress/decompress, do other stuff that expects spans, and then save the compressed/decompressed output. The stream part becomes a pain as with span based compression apis they can be avoided entirely.

**Comment by jeffhandley** [comment]
> @jeffhandley any updates for what I proposed here for zlib (all linked here): [#62658 (comment)](https://github.com/dotnet/runtime/issues/62658#issuecomment-1032942626) ?

@AraHaan I'm sorry I overlooked that question months back and didn't notice until now. The proposals you made for zlib are valuable, but did not make it into .NET 7.0. We will consider them while we do our .NET 8 planning. Thank you.
