### ISSUE TITLE
[mono][llvm] Fully support .NET exceptions with LLVM on x64, x86, arm64, arm32

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#63404]
- [ ] Create a Mono-specific EH personality, to support associating outlined filter functions with individual `catchpad` or `landingpad` instructions (by scanning their IR parameter lists for constant function pointers)
- [ ] Use `llvm.localescape` to mark filter-captured values
- [ ] Translate exception filters into outlined filter functions
- [ ] Support nested clauses either by: 
    - [ ] Using a scheme to encode nested filters using `landingpad`, or
    - [ ] Using `catchswitch`, `catchpad`, and `cleanuppad`, and removing Windows-specific assumptions associated with these IR ops found during testing
- [ ] Update the Mono unwinder to support all of the above

Also see:
- [ ] https://github.com/dotnet/runtime/issues/54185
- [ ] https://github.com/dotnet/runtime/issues/54176

**Comment by SamMonoRT** [comment]
cc @vargaz

**Comment by jandupej** [comment]
Simulations show that the performance and binary size benefits would be minimal. Closing.
