### ISSUE TITLE
Consider adding "no new features" note to low churn libraries

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#63401]
Most of the libraries in this repo are actively developed, but there are several that exist primarily for compatibility and for that reason we don't expect to accept PR's into them that include major refactorings or new features.

These include System.Linq.Expressions, System.Dynamic.Runtime, Microsoft.CSharp, and Microsoft.VisualBasic and they each have a README.md ([example](https://github.com/dotnet/runtime/blob/6616a49e494f13baab9e6f69cdf30b5a6a428428/src/libraries/System.Linq.Expressions/README.md#L8)) that indicates this, and a note in [area-owners.md](https://github.com/dotnet/runtime/blob/6616a49e494f13baab9e6f69cdf30b5a6a428428/docs/area-owners.md#L1-L0).

There are several other libraries that could use such notes. These likely include System.Management, System.Speech, MEF and others. In some cases the note could indicate the preferred replacement technologies.

cc @ericstj

**Comment by jeffhandley** [comment]
I've been thinking about this topic recently too. Beyond notes like the example shown, we also need an easily discoverable, easily maintainable, and consistent approach for documenting roadmaps by area. I've been starting to imagine this as creating an issue per area with a "roadmap" label. We could then illustrate the current state of the area and what level of investment we're making into it, describe how open we are to new APIs in the area, etc.

With the issue approach, the note wouldn't be within the source tree where its placement isn't necessarily discoverable or consistent. And we could just keep editing the issue description whenever the roadmap changes and use comments on the issue to garner feedback on the area roadmap. We could then have the area-owners.md file link to each of the roadmap issues too, to boost the discoverability even more.

@danmoseley, @ericstj, @karelz -- what do you think?

**Comment by danmoseley** [comment]
Re roadmaps, perhaps that's an outcome of us spending time creating them for a particular library? It would have to avoid duplication with user stories/themes.

Re files in the source tree, I agree that they should be for documenting enduring principles.

**Comment by eerhardt** [comment]
> Re files in the source tree

I think I would prefer files in the repo - specifically `README.md` files at the root of each library. That way it is easy to see the changes, who made the change, why, PR discussion, what did we think the roadmap was in `release/5.0`, etc. Yes issues have an "Edited" drop down, but once it gets past a few changes, it becomes unmanageable and doesn't allow for review.

**Comment by jeffhandley** [comment]
(nodding) Seeing the history is interesting. I suppose we need some acceptance criteria for these publications.

* [ ] Discoverable
* [ ] Consistent across areas
* [ ] Easily editable
* [ ] Single location for comments
* [ ] Versioned
* [ ] Snapshotted with each release

What else?

**Comment by danmoseley** [comment]
that works if it's a high level discussion about direction, but if it starts eg linking to user stories, marking off progress, it's turning into what we already do in epics/user stories, but without the benefit of the tooling github and themesof.net provides for linking, tracking progress that we have in those. Perhaps the pivot is -- how often would this change? if it's 2-3 times a year, it seems reasonable to me to store in the repo.

cc @stephentoub 

I believe @eiriktsarpalis was working on a S.T.JSON roadmap so that might provide an example to think about.

**Comment by eerhardt** [comment]
Maybe we have a different model for tracking where an active library is going vs. saying "this library is effectively archived". If every library had a `README.md` file, we could have:

1. Libraries whose roadmaps are changing can track it in an issue that is linked from its `README.md` file. That issue can link to epics/user stories/etc.

2. "Effectively archived" libraries don't have a roadmap issue, and their `README.md` file says they are effectively archived and not accepting new features / refactorings.

The consistent place to go would be the library's `README.md` file. That would be the root of all the important info.

**Comment by jeffhandley** [comment]
@danmoseley is right that these won't be edited often. @eerhardt's suggestion sounds like a good balance to me. It meets the criteria of:

1. **Discoverable**. The README docs would be discoverable in GitHub when browsing the source, and the area-owners doc would link to them.
2. **Consistent across areas**.
3. **Easily editable**. The README docs are editable easily enough for the frequency of editing; the volatile ones would have issues to capture the intra-release updates.
4. **Single location for comments**. For the areas with active roadmaps, the issues would collect the comments. For inactive areas, we don't expect much commentary, but folks would just file issues regularly.
5. **Versioned**.
6. **Snapshotted with each release**.

For each README, I'd still like us to prescribe some guidance for the vocabulary we use to indicate the level of investment going into the area. Thoughts on these descriptions?

### Area Investment Levels

1. **Legacy**
    - Not under development; maintained for compatibility
    - PRs are unlikely to be accepted
    - Issues are likely to be closed without fix
2. **Inactive**
    - Under minimal development; quality is maintained
    - PRs for both features and fixes will be considered
    - Issues will be considered for fix or addition to the backlog
3. **Active**
    - Under active development by the team, but not a strategic focus
    - PRs for both features and fixes will be considered and championed
    - Issues will be considered for fix or addition to the backlog
4. **Strategic**
    - Under heavy development by the team, as a strategic focus
    - PRs for both features and fixes will be considered and championed
    - Issues will be considered for fix or addition to the backlog

**Comment by eerhardt** [comment]
> For each README, I'd still like us to prescribe some guidance for the vocabulary we use to indicate the level of investment going into the area. Thoughts on these descriptions?

I agreed that have a consistent vocabulary across the areas is important. I think those descriptions sound good.

One quick question though: what is the effective difference between `Active` and `Strategic`? Is the intention that `Strategic` areas will have more changes in their roadmap / more user stories/features per release?

**Comment by jeffhandley** [comment]
> What is the effective difference between `Active` and `Strategic`? Is the intention that `Strategic` areas will have more changes in their roadmap / more user stories/features per release?

That's what I was thinking. But the notes on them are only subtly different. Perhaps we can omit 'Strategic' and just have **Legacy**, **Inactive**, and **Active**. Simpler is probably better; right?

**Comment by stephentoub** [comment]
> Simpler is probably better; right?

Yes ;-)

**Comment by jeffhandley** [comment]
This is done. Early in .NET 8, we added [README docs across the libraries](https://github.com/search?q=repo%3Adotnet%2Fruntime+path%3Asrc%2Flibraries%2F*%2Freadme.md&type=code) and we defined contribution bars where we declare whether or not we will consider new features.
