### ISSUE TITLE
Developers can use Generic Math without enabling preview features

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#63548]
In .NET 7, we will stabilize the API surface area and implementations for Generic Math features.

### Prerequisites

- [x] Ensure the C++/CLI compatibility issue with static abstracts in interfaces has been addressed
  - [x] Partner with the WPF team to ensure that fix has been integrated and validated
- [x] Confirm Native AOT scenarios work with static abstract interface members on primitive types
- [x] Confirm Mono AOT scenarios work with static abstract interface members on primitive types

### Work Items

- [ ] #49904 Ensure mono is compatible with static abstracts in interfaces
   - [x] #60447
   - [x] #61920
   - [ ] #67540
- [ ] #54063
- [ ] #58162
- [x] #58607
- [x] #60365
- [x] #60536
- [x] #62296
- [x] #64717

### Language Features

- [x] dotnet/csharplang#4665
- [ ] dotnet/csharplang#4666
- [x] dotnet/csharplang#4682
- [ ] dotnet/csharplang#5783
- [x] Default Interface Methods support
  - [x] Runtime (@davidwrighton)
    - [x] Mainline scenarios
    - [x] Allowing overrides within the interfaces (not required for Preview 4)
  - [x] Compiler (@AlekseyTs)
- [x] nint vs IntPtr differences (@tannergooding)
- self constraint (this language feature is not approved at this time)

### Acceptance Criteria

- [x] Present the feature set at the MVP summit to solicit feedback (@MadsTorgersen)
- [x] Consider moving the advanced interfaces into a namespace other than `System`
- [x] Consider making interface implementations implicit
- [x] Reference APIs are integrated into System.Runtime without the need for the System.Runtime.Experimental package installation
- [x] The `[RequiresPreviewFeatures]` attribute is removed from all Generic Math APIs
- [ ] Propose and implement a Roslyn Analyzer for spotting IntPtr vs. nint behavioral differences to highlight the altered behavior
- [ ] Partner with ecosystem package authors to garner feedback on the APIs
- [ ] Validate usability in F#
- [ ] Author a blog post / demo

### Community Validation

The following community members and products will be contacted for validation of compatibility with this feature set. We will aim for validation from them before Preview 4 ships.

- [ ] ILSpy
- [ ] Unity
- [ ] Profilers

**Comment by tannergooding** [comment]
This has been resolved since .NET 7 Preview 4.
