### ISSUE TITLE
System.IO work planned for .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#64596]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
We invested heavily in System.IO during .NET 6. During .NET 7, we will continue to make improvements to this area. We will address issues with the FileStream rewrite (#40359) and Symbolic Links, and we will make improvements to System.IO.Stream. At the top of the backlog after .NET 7 are investments such more enhancements to the Symbolic Links introduced in .NET 6, stabilizing more tests, and possibly introducing new APIs related to globbing.

## Planned for .NET 7

- Symbolic Links
  - [x] #29940
  - [x] #38824
- FileStream
  - [x] #55196
  - [x] #62851
  - [x] dotnet/dotnet-api-docs#7455
- [x] #16598
- [x] #58359
- [x] #58383
- [x] #62602
- [x] #58376
- [x] #20824
- [x] #62606
- [x] #63287
- [x] #12339
- [x] #56165
- [x] #58707
- [x] #25375
- [x] #62975

## Backlog (roughly in priority order)

- Canonical paths / real file casing / real path:
  - [ ] #23871
  - [ ] #14321
  - [ ] #17873
- Symbolic Links
  - [ ] #53577
  - [ ] #52666
  - [ ] #58612
  - [ ] #52908
  - [ ] #1908
  - [ ] #34363
  - [ ] #20874
- Test Stabilization
  - [ ] #60427
  - [ ] #53366
  - [ ] #48717
  - [ ] #32955
  - [ ] #60586
  - [ ] #45954
  - [ ] #56681
- FileStream
  - [ ] #51048
  - [ ] dotnet/dotnet-api-docs#1041
  - [ ] dotnet/dotnet-api-docs#1124
  - [ ] dotnet/dotnet-api-docs#4141
- [ ] #44543
- [ ] #48793
- [ ] #21362
- [ ] #2162
- [ ] #64288 
- [ ] #22428
- [ ] #62061
- [ ] #2379
- [ ] #45089
- [ ] #58381
- [x] #58211

**Comment by jeffhandley** [comment]
This list in this issue has been edited to reflect changes from our ongoing planning and discussions. The headings have been updated to reflect what is still planned for .NET 7 and what is in the backlog. The list is still expected to change throughout the release cycle with periodic reviews of our plans.

Additionally, the items from [System.IO Symbolic Link work planned for .NET 7 · Issue #57205 · dotnet/runtime](https://github.com/dotnet/runtime/issues/57205) have been merged into this issue.

**Comment by iSazonov** [comment]
Can we include #1953 too?
