### ISSUE TITLE
System.Runtime work planned for .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#64603]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
The System.Runtime area represents our primitive types and other fundamental APIs. During .NET 7, we will address high-impact issues in this area, invest in more performance and trimming optimizations, resolve test issues, and consider other enhancements.

## Planned for .NET 7

- [x] #64292
- [x] #63687
- [x] #60864
- [x] #57993
- [x] #51700
- [x] #36901
- [x] #58440
- [x] #60469
- [x] #36839
- [x] #56020
- [x] #59414
- [x] #59149
- [x] #59152
- [x] #59253

####  Globalization
- [x] https://github.com/dotnet/runtime/issues/23799
- [x] https://github.com/dotnet/runtime/issues/62329
- [x] https://github.com/dotnet/runtime/issues/66815

## Backlog (roughly in priority order)

- [ ] #31853
- [ ] #60562
- [ ] #63426
- [ ] #58575
- [ ] #58642
- [ ] #45812
- [ ] #14386
- [ ] #48849
- [ ] #37739
- [ ] #47861
- [ ] #26227
