### ISSUE TITLE
Improving ARM64 Performance in .NET 7.0

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#64820]
In .NET 7.0, we will continue our efforts to improve the Arm64 code quality and closing the performance gap with x64. Similar to how we did this in .NET 5 in #35853 , we will continue the trend of tracking all the Arm64 issues in a top level issue.

- [x] Arm64: Better addressing mode for float/double array access #64819
- [x] (kunalspathak) Hoisting the invariant out of multi-level nested loops #61420
- [x] ARM64: Optimize a % b operation #34937
- [x] Arm64: Add support for loop alignment
   - [x] Arm64: Align methods containing loops to 32B #59828
   - [x] Loop Alignment support for Arm64 #60135
   - [x] Hide 'align' instruction behind jmp #60787
- [x] https://github.com/dotnet/runtime/pull/68085
- [x] https://github.com/dotnet/runtime/issues/67326 @a74nh 
- [x] Tooling support for Arm64 performance investigation
  - [x] jitdump output not accepted by ARM streamline #62456
- [x] (@kunalspathak) https://github.com/dotnet/runtime/issues/67824
- [ ] (@mangod9) https://github.com/dotnet/runtime/issues/67266 - Revisit after concurrent queue fix 
- [ ] (@EgorBo, @Kunalspathak) x64 vs ARM64 Microbenchmarks Performance Study Report https://github.com/dotnet/runtime/issues/67339
- [ ] (@EgorBo) https://github.com/dotnet/runtime/issues/67981
- [ ] (@a74nh) Conditional comparison and selection instructions https://github.com/dotnet/runtime/issues/55364, https://github.com/dotnet/runtime/pull/67894
- [x] Intrinsify some .NET libraries with Arm64 intrinsics
  - [x] (@a74nh) https://github.com/dotnet/runtime/issues/41292
  - [x] https://github.com/dotnet/runtime/issues/35033

## Moved to Future Work
- [ ] Arm64: Evaluate if it is possible to combine subsequent field loads in a single load #64815 
- [ ] [Arm64] Peephole optimization opportunities #55365
- [ ] https://github.com/dotnet/runtime/issues/12735
- [x] https://github.com/dotnet/runtime/issues/58954
- [ ] https://github.com/dotnet/runtime/issues/64921
- [ ] https://github.com/dotnet/runtime/issues/39457
- [ ] https://github.com/dotnet/runtime/issues/67244
- [ ] https://github.com/dotnet/runtime/issues/67180, Closed https://github.com/dotnet/runtime/pull/68639 to try a different approach (AntonLapounov)
- [ ] https://github.com/dotnet/runtime/issues/41699
- [ ] https://github.com/dotnet/runtime/issues/1277
- [ ] (TiHan) Arm64: In mod operation happening inside the loop, if divisor is an invariant, hoist the divisor checks #64795
- [ ] (@EgorBo) https://github.com/dotnet/runtime/issues/62302
- [ ] (@TiHan) Double constants usage in a loop can be CSEed #35257

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by adamsitnik** [comment]
Based on #67339 I think it would be good to add #62302 to this list.

**Comment by kunalspathak** [comment]
> Based on #67339 I think it would be good to add #62302 to this list.

Done. Thanks for preparing the report.

**Comment by kunalspathak** [comment]
**.NET 7 items:**

| Issue                                                                                                          | Owner                     | ETA      |
|----------------------------------------------------------------------------------------------------------------|---------------------------|----------|
| Arm64: Align methods containing loops to 32B #59828                                                            | @kpathak                  | DONE     |
| Loop Alignment support for Arm64 #60135                                                                        | @kpathak                  | DONE     |
| Hide 'align' instruction behind jmp #60787                                                                     | @kpathak                  | DONE     |
| Arm64: Better addressing mode for float/double array access #64819                                             | @EgorBo                   | DONE     |
| Correctly get the last level cache size used by GC #60166                                                      | @mangod9                  | June' 22 |
| Threadpool scalability issue with higher number of cores                                                       | @mangod9                  | June' 22 |
| Arm64: Environment.ProcessorCount returns wrong value on higher core machine #67180                            | @mangod9                  | June' 22 |
| Arm64: Revisit the heuristics for IO completion poller threads #67266                                          | @mangod9                  | June' 22 |
| ARM64: Optimize a % b operation #34937 (WIP)                                                                   | @TiHan                    | June' 22 |
| Double constants usage in a loop can be CSEed #35257 (WIP)                                                     | @TiHan                    | June' 22 |
| x64 vs ARM64 Microbenchmarks Performance Study Report #67339                                                   | @EgorBo, @kpathak         | June' 22 |
| Arm64: Forward memset/memcpy to CRT implementation #67326                                                      | @kpathak                  | June' 22 |
| Hoisting the invariant out of multi-level nested loops #61420                                                  | @kpathak,  @BruceForstall | June' 22 |
| Arm64: In mod operation happening inside the loop, if divisor is an invariant, hoist the divisor checks #64795 | @TiHan                    | June' 22 |
| Arm64: Evaluate if it is possible to combine subsequent field loads in a single load #64815 (lower priority)   | TBD                       | TBD      |
| [Arm64] Peephole optimization opportunities #55365                                                             | @a74nh                    | TBD      |
| Arm64: Generate conditional comparison and selection instructions #55364                                       | @a74nh                    | TBD      |
| Optimize System.Text.ASCIIUtility for arm64 using cross-platform intrinsics #41292                             | @a74nh                    | TBD      |
| Optimize System.Buffers for arm64 using cross-platform intrinsics #35033                                       | @a74nh                    | TBD      |
| [ARM64] Performance regression: Utf8Encoding #41699                                                            | @a74nh                    | TBD      |
| [ARM64/Linux] Inefficient conditionals branching #12735                                                        | @a74nh                    | TBD      |
| JIT: Redundant fmov's on arm64 for a simple function #58954                                                    | @a74nh                    | TBD     |
| Arm64: Consider using "DC ZVA" instruction #67244                                                              | @kpathak, @a74nh          | TBD      |

**Stretch goals:**

| Issue                                                                                                          | Owner                     | ETA      |
|----------------------------------------------------------------------------------------------------------------|---------------------------|----------|
| [LSRA] Add support for allocating consecutive registers #39457                                                 | @kpathak                  | Future   |
| Enable multi-register intrinsics support for Arm64 #64921                                                      | @BruceForstall            | Future   |
| API Proposal : Arm TableVectorLookup and TableVectorExtension intrinsics #1277                                 | @a74nh                    | Future   |
| jitdump output not accepted by ARM streamline #62456                                                           | @RobertHenry6bev          | Future   |
| Optimize set_brick code in GC                                                                                  | @Maoni0                   | TBD      |
|                                                                                                                |                           |          |
|                                                                                                                |                           |          |

**Comment by JulieLeeMSFT** [comment]
https://github.com/dotnet/runtime/issues/68028

**Comment by kunalspathak** [comment]
> #68028

Included in the table above.

**Comment by a74nh** [comment]
**Optimize System.Text.ASCIIUtility for arm64 using cross-platform intrinsics**
**Issue**: https://github.com/dotnet/runtime/issues/41292
**PR**: https://github.com/dotnet/runtime/pull/70080 and https://github.com/dotnet/runtime/pull/71637
**Approach taken:**
The existing Sse2/Sse41 implementation was moved to use the Vector128 API.
Arm64 was switched to use the Vector128 implementation instead of the vector generic version.
Where required for performance, the Sse2/Sse41/AdvSimd APIs were used.
**Impact:**
Small improvement in the relevant microbenchmarks on Arm64.
These changes were not significant enough to be picked up by the Performanceautofiler post merge.
Performance gain was small due to the vector generic version being good/simple.
Use of the Vector128 API helps to reduce code debt.
**Follow on work:**
None.
 
**Optimize System.Buffers for arm64 using cross-platform intrinsics**
**Issue**: https://github.com/dotnet/runtime/issues/35033
**PR**: https://github.com/dotnet/runtime/pull/70654 and https://github.com/dotnet/performance/pull/2479
**Approach taken:**
Fixed issue with the microbenchmarks using invalid data.
The existing Ssse3 implementation was moved to use the Vector128 API.
Arm64 was switched to use the Vector128 implementation instead of non-vectorised version.
Where required for performance, the Sse3/AdvSimd APIs were used.
**Impact:**
Large improvement in the relevant microbenchmarks on Arm64.
Performance improvements detected by the Performanceautofiler:
                        https://github.com/dotnet/perf-autofiling-issues/issues/6346
                        https://github.com/dotnet/perf-autofiling-issues/issues/6334
                        https://github.com/dotnet/perf-autofiling-issues/issues/6340
                        https://github.com/dotnet/perf-autofiling-issues/issues/6328
                        https://github.com/dotnet/perf-autofiling-issues/issues/6327
                        https://github.com/dotnet/perf-autofiling-issues/issues/6326
                        https://github.com/dotnet/perf-autofiling-issues/issues/6321
Use of the Vector128 API helps to reduce code debt.
**Follow on Work:**
Once multiple register instructions (such as LD4) have been implemented in Vector128, then further improvements may be possible switching to an implementation based on the NEON version of the Aklomp base64 algorithm.

**Comment by kunalspathak** [comment]
The only thing remaining from the list is https://github.com/dotnet/runtime/issues/55364 and it is already set for .NET 7. I will move this to .NET 8 to track remaining work.

**Comment by kunalspathak** [comment]
Replaced with https://github.com/dotnet/runtime/issues/77010
