### ISSUE TITLE
.NET 7.0 Preview 1 Microbenchmarks Performance Study Report

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#65200]
## Data

This time we have covered following configs:

* architectures: x64, x86, arm64, arm
* Unix: Alpine 3.13, CentOS 7, Ubuntu 18.04, Ubuntu 20.04, macOS 11.4, macOS 11.6.3
* Windows: 10 & 11

ARM64 results are not 100% complete because we have hit two ARM bugs: https://github.com/dotnet/runtime/issues/64657 (AV) and https://github.com/dotnet/runtime/issues/64980 (hang).

| Operating System     | Bit   | Processor Name                                  |
| -------------------- | ----- | ----------------------------------------------- |
| Windows 11           | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Windows 11           | X64   | AMD Ryzen 9 5900X                               |
| Windows 10           | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Windows 11           | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       |
| Windows 10           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Windows 11           | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Windows 11           | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
| Windows 11           | X64   | Unknown processor                               |
| ubuntu 20.04         | X64   | AMD Ryzen 9 5900X                               |
| ubuntu 18.04         | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| centos 7             | X64   | Intel Xeon CPU E5530 2.40GHz                    |
| ubuntu 18.04         | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| alpine 3.13          | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| ubuntu 18.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| ubuntu 20.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| ubuntu 20.04         | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| ubuntu 20.04         | Arm64 | Unknown processor                               |
| Windows 10           | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Windows 11           | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Windows 10           | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Windows 10           | Arm   | Microsoft SQ1 3.0 GHz                           |
| macOS Big Sur 11.6.3 | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       |
| macOS Big Sur 11.4   | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |

Most of the benchmarks were run on bare-metal machines, some were executed via WSL.

This would not be possible without the help from: @AndyAyersMS @carlossanlop @danmoseley @jeffhandley and @janvorli who contributed their results and time.

The full report generated by the tool is available [here](https://github.com/adamsitnik/performance/blob/compareRuntimes/src/tools/ResultsComparer/net60_vs_net70p1_10p_2ns.md). The full report contains also improvements, so if you read it from the end you can see the biggest perf improvements. There are plenty of them!

Again, the [full historical data](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/TestHistoryIndexIndex.html) turned out to be **extremely useful**. For details about methodology please read https://github.com/dotnet/runtime/issues/41871.

### By design

* [x] `System.IO.Tests.StringReaderReadLineTests.ReadLine(LineLengthRange: [   0,    0])`, `System.IO.Tests.StringReaderReadLineTests.ReadLine(LineLengthRange: [   1,    1])`, `System.IO.Tests.StringReaderReadLineTests.ReadLineAsync(LineLengthRange: [   1,    1])`:
    * reading 0-1 char long lines: https://github.com/dotnet/runtime/pull/60463
* [x] `System.Numerics.Tests.Perf_BigInteger.Subtract(arguments: 65536,65536 bits)`:
    * acceptable trade-off https://github.com/dotnet/runtime/issues/60293#issuecomment-941568196
* [ ] `System.Numerics.Tests.Perf_VectorConvert.Convert_double_long`:
    * seems to be missed by the bot
    * opened: https://github.com/dotnet/runtime/issues/65189
    * explained: https://github.com/dotnet/runtime/issues/65189#issuecomment-1036388904
* [ ] Multiple `System.Text.RegularExpressions*` regressions: https://github.com/dotnet/runtime/issues/65187
    * not detected by the bot, as it seems that benchmarks were added after the regression happened
    * opened: https://github.com/dotnet/runtime/issues/65187
    * trade-offs explained: https://github.com/dotnet/runtime/issues/65187#issuecomment-1036287653

### Investigation in progress

* [ ] `System.Numerics.Tests.Perf_Matrix4x4.NegationOperatorBenchmark`, `System.Collections.Sort<BigStruct>.Array_Comparison(Size: 512)`, `System.Collections.Sort<BigStruct>.Array_ComparerClass(Size: 512)`, `System.Collections.Sort<BigStruct>.LinqOrderByExtension(Size: 512)`, `System.Collections.Sort<BigStruct>.Array_ComparerStruct(Size: 512)`
    * detected by the bot: https://github.com/dotnet/runtime/issues/59415
    * added a comment: https://github.com/dotnet/runtime/issues/59415#issuecomment-1036158901
* [ ] `System.Collections.IterateForEach<String>.SortedSet`
    * it's not visible in the Reporting System, but I can reproduce it locally.
    * opened: https://github.com/dotnet/runtime/issues/65190
* [ ] `System.Numerics.Tests.Perf_Matrix4x4.MultiplyByScalarOperatorBenchmark`, `System.Numerics.Tests.Perf_Matrix4x4.Transpose`, `System.Numerics.Tests.Perf_Matrix4x4.NegateBenchmark`, `System.Numerics.Tests.Perf_Matrix4x4.MultiplyByScalarBenchmark`
    * seems to be missed by the bot
    * opened https://github.com/dotnet/runtime/issues/65191
* [ ] `PerfLabTests.GetMember.GetMethod*`, `PerfLabTests.GetMember.GetField`
    * seems to be missed by the bot
    * opened: https://github.com/dotnet/runtime/issues/65192
* [ ] `System.Collections.TryGetValueFalse<Int32, Int32>.Dictionary(Size: 512)`
    * detected by the bot: https://github.com/dotnet/runtime/issues/63745
    * added a comment: https://github.com/dotnet/runtime/issues/63745#issuecomment-1036203930
* [ ] `System.Tests.Perf_Version.Parse2`
    * seems to be missed by the bot
    * opened: https://github.com/dotnet/runtime/issues/65193
    * Unix specific
    * most likely caused by a PGO data update
* [ ] `System.Tests.Perf_GC<Char>.AllocateUninitializedArray(length: 10000, pinned: False)`
    * not reported by the bot because we don't have macOS machines in our perf lab (yet)
    * opened: https://github.com/dotnet/runtime/issues/65198
    * macOS-specific
    
### Fixed in the meantime

* [x] `System.Text.Json.Tests.Perf_Ctor.Ctor(Formatted: False, SkipValidation: False)`
    * was there when we started the manual runs, bot got [fixed](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fSystem.Text.Json.Tests.Perf_Ctor.Ctor(Formatted%3a%20False%2c%20SkipValidation%3a%20False).html) very recently
* [x] `System.Text.Json.Tests.Perf_Base64.WriteByteArrayAsBase64_NoEscaping(NumberOfBytes: 100)`
    * was there when we started the manual runs, bot got [fixed](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Text.Json.Tests.Perf_Base64.WriteByteArrayAsBase64_NoEscaping(NumberOfBytes%3a%20100).html) recently

### Noise, flaky or multimodal

The following benchmarks showed up in the report generated by the tool, but were not actual regressions:

* `System.Threading.Tests.Perf_Interlocked.Decrement_long`, `System.Threading.Tests.Perf_Interlocked.Increment_long` on x86: https://github.com/dotnet/performance/issues/1497#issuecomment-717510508
* `System.Diagnostics.Perf_Process.GetProcessesByName` I was unable to reproduce it despite my machine reported it previously
* `System.Memory.Span<Char>.Fill(Size: 512)` - memory alignment
* `PerfLabTests.CastingPerf.CheckArrayIsInterfaceNo` - very noisy

 **Big thanks to everyone involved!**

**Comment by EgorBo** [comment]
Is there a report with improvements? 😄

**Comment by adamsitnik** [comment]
> Is there a report with improvements?

You can read the [full report](https://github.com/adamsitnik/performance/blob/compareRuntimes/src/tools/ResultsComparer/net60_vs_net70p1_10p_2ns.md ) from the end ;)

**Comment by EgorBo** [comment]
> > Is there a report with improvements?
> 
> You can read the [full report](https://github.com/adamsitnik/performance/blob/compareRuntimes/src/tools/ResultsComparer/net60_vs_net70p1_10p_2ns.md) from the end ;)

Yeah, I removed the comment because I've realized that 🙂. I think we've made a lot of progress for ARM so I'd be curious to see that, I hope we'll be able to do it for P2

**Comment by danmoseley** [comment]
Great - thanks for doing this @adamsitnik . @kunalspathak @DrewScoggins and other perf v-team folks -- I assume we'll look into why some of these were apparently missed by the regular system?
