### ISSUE TITLE
Libraries Infrastructure and Tools work planned for .NET 7

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#65260]
Collecting the work in Infrastructure and Tools that we aspire to complete in .NET 7

- [ ] https://github.com/dotnet/sdk/issues/17364
- [x] https://github.com/dotnet/sdk/issues/18677
- [x] https://github.com/dotnet/runtime/issues/65741
