### ISSUE TITLE
[wasm] Tracking issue for issues caused by the emscripten bump to 2.0.34

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65464]
This is the list of tests that we have seen after the bump, so most should be because of the bump itself.
The bump was merged in https://github.com/dotnet/runtime/pull/64447 .

- [ ] https://github.com/dotnet/runtime/issues/64725 (not disabled)
- [ ] https://github.com/dotnet/runtime/issues/64774

## `System.Text.RegularExpressions.Tests`:
- [ ] https://github.com/dotnet/runtime/issues/64769
- [ ] https://github.com/dotnet/runtime/issues/64916
- [ ] https://github.com/dotnet/runtime/issues/64917

## `System.Collections.Immutable.Tests`:
- [ ] https://github.com/dotnet/runtime/issues/65242
- [ ] https://github.com/dotnet/runtime/issues/65335

## `System.Text.Json.Tests`:
- [ ] https://github.com/dotnet/runtime/issues/64775
- [ ] https://github.com/dotnet/runtime/issues/65243
- [ ] https://github.com/dotnet/runtime/issues/65336

## `System.Threading.Channels.Tests`:
- [ ] https://github.com/dotnet/runtime/issues/65012
- [ ] https://github.com/dotnet/runtime/issues/65245
- [ ] https://github.com/dotnet/runtime/issues/65337

cc @radekdoulik @lewing

**Comment by radical** [comment]
`2.0.34` has been [rolled back](https://github.com/dotnet/runtime/pull/65517) now.
