### ISSUE TITLE
[wasm][debugger] Todo in expression evaluation

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65864]
- [ ] incorrect argument types in method calls
- [ ] surface exceptions thrown from property getters, and method calls
- [ ] surface a NRE for `foo.NullObject.Prop`
- [ ] Calling methods with `params`
- [ ] methods with named arguments
- [ ] Extension methods
- [ ] Go through [SyntaxKind](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntaxkind) and cover unsupported cases of arguments passed to methods.

**Comment by thaystg** [comment]
This is fixed by the new debugger.
