### ISSUE TITLE
Add support for Android Bionic runtime

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#66027]
In .NET 7, we will add a new configuration that targets Android without using the Dalvik VM. 

### Work Items

- [ ] Determine if we need a new RID and if so, add to the list (e.g. linux-bionic, android-bionic)
- [ ] Modify the runtime build to produce runtime packs for the configurations we support (x86, x64, arm, arm64)
- [ ] Add leg to CI and run tests

### Notes

- The runtime being used is Mono
- We should try to use as much of the existing Android build as we can
- We are viewing this configuration more like linux desktop. It is assumed ICU and OpenSSL are provided externally.

**Comment by juepiezhongren** [comment]
> 

current clr lacks a lot of capabilities as to mono, aot-jit-interp modes is one example.

**Comment by directhex** [comment]
> > * The runtime being used is Mono
> 
> I'm wondering is there any plan to replace mono with coreclr as runtime on mobile devices? Generally mono runs much slower than coreclr (both GC and JIT) and doesn't perform well from performance perspective.

That's not within the scope of this issue.
