### ISSUE TITLE
SDL signoff requirements - please enable additional C/C++ compiler warnings

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#66154]
> __Please prioritize this work.__ Depending on the size of the code base, there could be hundreds or thousands of warnings which require addressing.
> 
> __This work must be completed before RC1 snap.__

Recent SDL changes require that we enable additional compiler warnings across our C/C++ projects. The requirements are:

- [x] Compile with warning level 3 or higher. These warnings do not have to be fixed, but they must at least be triaged.

Enable the following additional warnings, which __must__ be fixed if they occur:
- [x] __C4018__ - 'expression' : signed/unsigned mismatch
- [x] __C4055__ - 'conversion' : from data pointer 'type1' to function pointer 'type2'
- [x] __C4146__ - unary minus operator applied to unsigned type, result still unsigned
- [x] __C4242__ - 'identifier' : conversion from 'type1' to 'type2', possible loss of data
- [x] __C4244__ - 'conversion' conversion from 'type1' to 'type2', possible loss of data
- [x] __C4267__ - 'var' : conversion from 'size_t' to 'type', possible loss of data
- [x] __C4302__ - 'conversion' : truncation from 'type 1' to 'type 2'
- [x] __C4308__ - negative integral constant converted to unsigned type
- [x] __C4509__ - nonstandard extension used: 'function' uses SEH and 'object' has destructor
- [x] __C4510__ - 'class' : default constructor could not be generated
- [x] __C4532__ - 'continue' : jump out of __finally/finally block has undefined behavior during termination handling
- [x] __C4533__ - initialization of 'variable' is skipped by 'instruction'
- [x] __C4610__ - object 'class' can never be instantiated - user-defined constructor required
- [x] __C4611__ - interaction between 'function' and C++ object destruction is non-portable
- [x] __C4700__ - uninitialized local variable 'name' used
- [x] __C4701__ - Potentially uninitialized local variable 'name' used
- [x] __C4703__ - Potentially uninitialized local pointer variable 'name' used
- [x] __C4789__ - destination of memory copy is too small
- [x] __C4995__ - 'function': name was marked as #pragma deprecated
- [x] __C4996__ - 'function': was declared deprecated also 'std::': Function call with parameters that are potentially unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'

See [the SDL guidelines](https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.SystemsADM.10086) (MSFT internal only) for further information.

To make auditing code easier prior to signoff and release, **please include the string _Microsoft.Security.SystemsADM.10086_** somewhere in the vcxproj / cmake / whatever file which is responsible for C/C++ compilation where all of these flags are defined. That gives the code auditors a target string to search against and validate that the proper warnings are enabled. See below an example of how to do this in a cmake file.

```cmake
# [[! Microsoft.Security.SystemsADM.10086 !]] - SQL required warnings
add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:/W3>) # warning level 3
add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:/WX>) # treat warnings as errors
add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:/we4018>) # 'expression' : signed/unsigned mismatch
add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:/we4055>) # 'conversion' : from data pointer 'type1' to function pointer 'type2'
# ... and so on ...
```

Once the work is finished, or if there is no work to perform, please feel free to close this issue.

Thanks for your assistance!

## Quick FAQ

__What code is bound to this requirement?__

This affects only _production_ code. Production code is generally defined as code which ships as part of the product and which runs on customer machines or which manages infrastructure, such as our build labs. Unit and functional test projects are not considered production code.

__Does this need to be backported?__

No backporting plans at this time. If actual bugs are found during this process, individual product teams have discretion to selectively backport into the next downlevel servicing vehicle.

__What about forked third-party code?__

This requirement applies to all code that MSFT builds from source, regardless of its provenance. Ideally any changes that we make to local forked copies can be submitted upstream as a PR so that the wider ecosystem can enjoy their benefits.

If this is impractical, exceptions to this requirement can be sought on an as-needed basis. However, exceptions are: (a) not guaranteed to be granted; and (b) time-constrained. The exception process is not intended to provide a permanent deferral of this work. Please contact the _fxsecurity_ alias if an exception is needed.

__What about C# and other languages?__

This requirement only affects C/C++ code. Requirements for other languages will be filed as separate issues.

**Comment by danmoseley** [comment]
Added checkboxes...

**Comment by AaronRobinsonMSFT** [comment]
@GrabYourPitchforks Is this for the repo all up or only for coreclr and native code in libraries?

**Comment by AaronRobinsonMSFT** [comment]
Relevant occurrences under `src/coreclr`

We are already building with at least `/W3` on I believe. The `jit/` subdirectory is set for `/W4`.

## 4146
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/inc/safemath.h#L526

## 4244
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/debug/daccess/gcdump_dac.cpp#L11
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/utilcode/stgpooli.cpp#L313
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/ceeload.cpp#L69
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/common.h#L42
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/method.cpp#L41
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/typehash.cpp#L21

## 4267
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/debug/daccess/daccess.cpp#L215
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/codeman.cpp#L5474
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/eehash.cpp#L40

## 4302
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/gc/env/volatile.h#L155
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/gc/env/volatile.h#L236
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/inc/volatile.h#L162
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/inc/volatile.h#L248

## 4510
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/common.h#L29

## 4610
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/common.h#L32

## 4611
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/pal/inc/pal.h#L5041
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/fcall.h#L248

## 4701
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/jit/eeinterface.cpp#L25
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/jit/optimizer.cpp#L16
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/vm/common.h#L61

## 4996
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/pal/src/safecrt/internal.h#L1039-L1041
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/pal/src/safecrt/input.inl#L698
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/pal/src/safecrt/input.inl#L705
https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/coreclr/tools/superpmi/superpmi-shared/standardpch.h#L27

**Comment by GrabYourPitchforks** [comment]
> @GrabYourPitchforks Levi Broderick FTE Is this for the repo all up or only for coreclr and native code in libraries?

Only for production code, so I'd think coreclr / mono (if compiled via MSVC++) / libs. Test code is excluded.

**Comment by danmoseley** [comment]
@AaronRobinsonMSFT in case anyone would like to help with this one, could you give a pointer to the necessary cmake changes?

I am not familiar with cmake and I only found this:
https://github.com/dotnet/runtime/blob/7db092a6ed68a5fbf47962c45bb0c1bb965d02c6/src/mono/CMakeLists.txt#L266

**Comment by AaronRobinsonMSFT** [comment]
> in case anyone would like to help with this one, could you give a pointer to the necessary cmake changes?

@danmoseley Sure. The way this issue is framed it is confusing. I believe the entire repo already has `/W3` set by default. The set up for this is

https://github.com/dotnet/runtime/blob/b463b1630dbf1be5b013208a9fa73e1ecd6c774c/eng/native/configurecompiler.cmake#L551-L555

Note the removal of the default flag and then the conditional for CMake is added. If `TARGET_PROPERTY:MSVC_WARNING_LEVEL` isn't set, `/W3` is added back - at least that is how I understand that line. I've confirmed this by looking a the generated ninja files for coreclr. The coreclr JIT sets `/W4` as using the above properly and mono is explicit (see your link above). I believe this means the repo is properly targeted for ``/W3`. Which means we need to see where any of the above warnings are disabled.

In https://github.com/dotnet/runtime/issues/66154#issuecomment-1059236871, I went through coreclr and found all the places we disabled one of the target warnings. In https://github.com/dotnet/runtime/pull/66234 I removing many of them for both mono and coreclr. However, even with the above PR some still remain. I've not checked the `native/` or `libraries/` directories at all.

**4146** - Still exists in both mono and coreclr.
**4244** - Still exists in both mono and coreclr.
**4267** - Still exists in mono.

Once https://github.com/dotnet/runtime/pull/66234 is in, all others in the list have been handled in mono and coreclr.

**Comment by lambdageek** [comment]
For mono, we need to pay attention to:
- AOT cross compilers running on Windows targeting Android and WebAssembly, including our LLVM fork /cc @steveisok 
- Windows desktop builds of Mono, if we productize is @lateralusX 
- the mono mscordbi, if we productize it @lewing @thaystg 

one complications - mono doesn't use eng/native/configurecompiler.cmake and sets its own compiler flags.  So we need to verify all these warnings are on.

**Comment by am11** [comment]
> one complication - mono doesn't use eng/native/configurecompiler.cmake and sets its own compiler flags. So we need to verify all these warnings are on.

Note that we have [slowly adapted](https://grep.app/search?q=CLR_ENG_NATIVE_DIR&filter[repo.pattern][0]=dotnet/runtime&filter[path.pattern][0]=src/mono) eng/native infra in mono; so it is semi-true these days. :)

>  4267 - Still exists in mono.

Looking at @AaronRobinsonMSFT's fixes for coreclr, it should be easy to fix. I can take a stab at it (if nobody else is working on it).

**Comment by AaronRobinsonMSFT** [comment]
@am11 if you could handle 4267 in mono that would be great. I'll be working on 4146 and 4244 shortly.

**Comment by danmoseley** [comment]
If anyone is willing to take a first scan of `/native` that would be great.

**Comment by elinor-fung** [comment]
For the hosting components, a number of these are disabled - **4018**, **4244**, **4267**, **4996**:

https://github.com/dotnet/runtime/blob/853e494abd1c1e12d28a76829b4680af7f694afa/src/native/corehost/CMakeLists.txt#L13-L17

https://github.com/dotnet/runtime/blob/853e494abd1c1e12d28a76829b4680af7f694afa/src/native/corehost/apphost/static/CMakeLists.txt#L48-L52

**Comment by elinor-fung** [comment]
A few pragma suppressions in the host too:

https://github.com/dotnet/runtime/blob/853e494abd1c1e12d28a76829b4680af7f694afa/src/native/corehost/hostmisc/pal.h#L161
https://github.com/dotnet/runtime/blob/853e494abd1c1e12d28a76829b4680af7f694afa/src/native/corehost/hostmisc/pal.h#L169
https://github.com/dotnet/runtime/blob/853e494abd1c1e12d28a76829b4680af7f694afa/src/native/corehost/hostmisc/pal.h#L174

**Comment by AaronRobinsonMSFT** [comment]
Ugh. I forgot the src/native directory.

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Can you provide a PR for the 4996 issues in `src/native`?

**Comment by elinor-fung** [comment]
Yep, I will do that.

**Comment by AaronRobinsonMSFT** [comment]
@am11, @lambdageek, @elinor-fung Once https://github.com/dotnet/runtime/pull/66427 is merged, I believe that `coreclr/` is clean according to this issue. How can I help with `native/` or `mono/`?

**Comment by elinor-fung** [comment]
A number of the additional warnings listed that must be fixed wouldn't be under /W3 - are those already explicitly enabled for `coreclr/`? 
- C4244 (level 3 and 4)
- C4610 (level 4)
- C4611 (level 4)
- C4701 (level 4)
- C4703 (level 4)

I know they are not enabled for the host.

C4700 is level 1 and 4, but it is explicitly enabled by configurecompiler.cmake.

**Comment by AaronRobinsonMSFT** [comment]
> A number of the additional warnings listed that must be fixed wouldn't be under /W3 - are those already explicitly enabled for coreclr/?

@elinor-fung Well shoot. I read the following as they are on by default for `/W3`

> Enable the following additional warnings, which must be fixed if they occur

Your investigation though does seem to confirm they aren't. Well, looks like I need to reconsider that. Some are definitely on for `/W3` but agreed not all.

**Comment by AaronRobinsonMSFT** [comment]
@danmoseley Perhaps. Let me see how noisy that becomes.

**Comment by AaronRobinsonMSFT** [comment]
@danmoseley I think this was an excellent suggestion. I've updated the default to `/W4` and added disabling for all failures. Now we can work in parallel and simply reenable them - See https://github.com/dotnet/runtime/pull/66474.

**Comment by AaronRobinsonMSFT** [comment]
@GrabYourPitchforks I believe the SDL requirements are now all met in dotnet/runtime, except for issues under `src/mono`. 
@lateralusX is working on https://github.com/dotnet/runtime/pull/66710 to move mono up to `/W4`, which once that is done we can do another pass.

Thanks to @am11 @jkotas and @elinor-fung for all their help so far!

**Comment by AaronRobinsonMSFT** [comment]
The following needs to be updated in mono once on `/W4`.

https://github.com/dotnet/runtime/blob/0d4b279ba79f0b68b5a722868d04c51c10346387/src/mono/cmake/config.h.in#L6-L10

**Comment by AaronRobinsonMSFT** [comment]
> I just tried out 4244 and it issued around 2000 warnings, some in macros, but still a bunch to go through, guess that 4018 will generate a bunch as well.

@lateralusX Yes, there is going to be substantial changes to mitigate these. I tried going down this path but got a bit overwhelmed and took a step back to work on other tasks. I am not sure of the preferred strategy for Mono to mitigate these to be honest. There are so many and as someone who primarily works in CoreCLR I'm likely not the correct person to make a call on how to proceed.

I am more than willing to help in any way that I can but I can't make the call myself and would prefer to hear from you, @lambdageek, or @vargaz on how you would like to mitigate them.

**Comment by AaronRobinsonMSFT** [comment]
@lateralusX That is a fine solution. I agree using this task feasible. I, along with @elinor-fung and likely @am11, would be willing to help with tasks if they could be clearly defined - perhaps down to compilation unit?

**Comment by lateralusX** [comment]
> @lateralusX That is a fine solution. I agree using this task feasible. I, along with @elinor-fung and likely @am11, would be willing to help with tasks if they could be clearly defined - perhaps down to compilation unit?

I can probably work through component libraries first to get a feeling as well as the total amount of outstanding issues. Once that is done, we could divide on compile unit or sub area, like utils/metadata/mini (different folders), but they will probably need to come in dependency order, since fixing in one might also fix in others (due to shared headers).

**Comment by AaronRobinsonMSFT** [comment]
@lateralusX Have you had a chance to discuss with the rest of the mono team on this one? No pressure, just want to avoid a mad rush on this kind of issue prior to RC.

**Comment by AaronRobinsonMSFT** [comment]
I stand corrected. It looks like 4244 is still present under `src/coreclr` and `src/native/external`.

**Comment by lateralusX** [comment]
> @lateralusX Have you had a chance to discuss with the rest of the mono team on this one? No pressure, just want to avoid a mad rush on this kind of issue prior to RC.

Finishing of another work item and then I will do a triage on the remaining ones and add them to this issue (probably fix a set of them during the triage), we could then distribute it withing the teams if needed. Hopefully I will have something done beginning of next week.

**Comment by lateralusX** [comment]
Got some quick stats:

Enabling 4018 on Mono Windows build generate **1170** warnings:

File | Count
-- | --
C:\git\runtime\src\mono\mono\mini\aot-compiler.c | 140
C:\git\runtime\src\mono\mono\mini\method-to-ir.c | 116
C:\git\runtime\src\mono\mono\mini\ssa.c | 72
C:\git\runtime\src\mono\mono\mini\liveness.c | 56
C:\git\runtime\src\mono\mono\metadata\metadata.c | 54
C:\git\runtime\src\mono\mono\mini\interp\transform.c | 52
C:\git\runtime\src\mono\mono\mini\interp\interp.c | 50
C:\git\runtime\src\mono\mono\mini\mini.c | 48
C:\git\runtime\src\mono\mono\mini\mini-generic-sharing.c | 38
C:\git\runtime\src\mono\mono\mini\mini-amd64.c | 34
C:\git\runtime\src\mono\mono\mini\decompose.c | 30
C:\git\runtime\src\mono\mono\component\debugger-agent.c | 27
C:\git\runtime\src\mono\mono\mini\dwarfwriter.c | 26
C:\git\runtime\src\mono\mono\mini\debug-mini.c | 24
C:\git\runtime\src\mono\mono\mini\dominators.c | 22
C:\git\runtime\src\mono\mono\metadata\class-setup-vtable.c | 22
C:\git\runtime\src\mono\mono\mini\mini-exceptions.c | 20
C:\git\runtime\src\mono\mono\mini\aot-runtime.c | 20
C:\git\runtime\src\mono\mono\metadata\icall.c | 18
C:\git\runtime\src\mono\mono\metadata\class.c | 18
C:\git\runtime\src\mono\mono\metadata\sre.c | 16
C:\git\runtime\src\mono\mono\mini\local-propagation.c | 16
C:\git\runtime\src\mono\mono\component\debugger-engine.c | 14
C:\git\runtime\src\mono\mono\metadata\class-init.c | 14
C:\git\runtime\src\mono\mono\metadata\reflection.c | 12
C:\git\runtime\src\mono\mono\metadata\mono-hash.c | 12
C:\git\runtime\src\mono\mono\metadata\object.c | 12
C:\git\runtime\src\mono\mono\metadata\marshal.c | 10
C:\git\runtime\src\mono\mono\metadata\mono-basic-block.c | 10
C:\git\runtime\src\mono\mono\metadata\threads.c | 10
C:\git\runtime\src\mono\mono\metadata\loader.c | 8
C:\git\runtime\src\mono\mono\component\hot_reload.c | 8
C:\git\runtime\src\mono\mono\metadata\memory-manager.c | 8
C:\git\runtime\src\mono\mono\mini\abcremoval.c | 8
C:\git\runtime\src\mono\mono\metadata\image.c | 8
C:\git\runtime\src\mono\mono\metadata\custom-attrs.c | 8
C:\git\runtime\src\mono\mono\mini\mini-profiler.c | 6
C:\git\runtime\src\mono\mono\mini\seq-points.c | 6
C:\git\runtime\src\mono\mono\mini\mini-runtime.c | 6
C:\git\runtime\src\mono\mono\mini\driver.c | 6
C:\git\runtime\src\mono\mono\metadata\debug-helpers.c | 6
C:\git\runtime\src\mono\mono\utils\mono-flight-recorder.c | 6
C:\git\runtime\src\mono\mono\mini\mini-codegen.c | 4
C:\git\runtime\src\mono\mono\mini\exceptions-amd64.c | 4
C:\git\runtime\src\mono\mono\mini\linear-scan.c | 4
C:\git\runtime\src\mono\mono\profiler\aot.c | 4
C:\git\runtime\src\mono\mono\mini\simd-intrinsics.c | 4
C:\git\runtime\src\mono\mono\mini\memory-access.c | 4
C:\git\runtime\src\mono\mono\metadata\debug-mono-ppdb.c | 4
C:\git\runtime\src\mono\mono\metadata\dynamic-stream.c | 4
C:\git\runtime\src\mono\mono\utils\mono-poll.c | 4
C:\git\runtime\src\mono\mono\metadata\exception.c | 2
C:\git\runtime\src\mono\mono\mini\unwind.c | 2
C:\git\runtime\src\mono\mono\mini\helpers.c | 2
C:\git\runtime\src\mono\mono\mini\alias-analysis.c | 2
C:\git\runtime\src\mono\mono\utils\lock-free-alloc.c | 2
C:\git\runtime\src\mono\mono\metadata\dynamic-image.c | 2
C:\git\runtime\src\mono\mono\mini\graph.c | 2
C:\git\runtime\src\mono\mono\metadata\assembly.c | 2
C:\git\runtime\src\mono\mono\mini\type-checking.c | 2
C:\git\runtime\src\mono\mono\mini\lldb.c | 2
C:\git\runtime\src\mono\mono\metadata\assembly-load-context.c | 2
C:\git\runtime\src\mono\mono\metadata\sre-encode.c | 2
C:\git\runtime\src\mono\mono\mini\mini-amd64-gsharedvt.c | 2
C:\git\runtime\src\mono\mono\mini\monovm.c | 2
C:\git\runtime\src\mono\mono\mini\calls.c | 2
C:\git\runtime\src\mono\mono\mini\branch-opts.c | 2
C:\git\runtime\src\mono\mono\eglib\gfile.c | 1
C:\git\runtime\src\mono\mono\eventpipe\ep-rt-mono.h | 1
C:\git\runtime\src\mono\mono\eglib\gptrarray.c | 1
C:\git\runtime\src\mono\mono\component\debugger-state-machine.c | 1
C:\git\runtime\src\mono\mono\eglib\garray.c | 1
Grand Total | 1170

Enabling 4244 on Mono Windows build generate **2615** warnings:

File | Count
-- | --
C:\git\runtime\src\mono\mono\mini\interp\transform.c | 644
C:\git\runtime\src\mono\mono\mini\mini-amd64.c | 386
C:\git\runtime\src\mono\mono\mini\method-to-ir.c | 204
C:\git\runtime\src\mono\mono\mini\mini.h | 123
C:\git\runtime\src\mono\mono\mini\tramp-amd64.c | 118
C:\git\runtime\src\mono\mono\mini\aot-compiler.c | 102
C:\git\runtime\src\mono\mono\mini\intrinsics.c | 68
C:\git\runtime\src\mono\mono\metadata\sre.c | 60
C:\git\runtime\src\mono\mono\metadata\metadata.c | 58
C:\git\runtime\src\mono\mono\metadata\icall.c | 58
C:\git\runtime\src\mono\mono\mini\aot-runtime.c | 42
C:\git\runtime\src\mono\mono\mini\mini.c | 38
C:\git\runtime\src\mono\mono\mini\dwarfwriter.c | 38
C:\git\runtime\src\mono\mono\mini\interp\interp.c | 32
C:\git\runtime\src\mono\mono\component\debugger-agent.c | 31
C:\git\runtime\src\mono\mono\mini\exceptions-amd64.c | 28
C:\git\runtime\src\mono\mono\metadata\class.c | 26
C:\git\runtime\src\mono\mono\mini\tramp-amd64-gsharedvt.c | 26
C:\git\runtime\src\mono\mono\metadata\image.c | 26
C:\git\runtime\src\mono\mono\mini\ir-emit.h | 26
C:\git\runtime\src\mono\mono\mini\ssa.c | 24
C:\git\runtime\src\mono\mono\metadata\assembly.c | 22
C:\git\runtime\src\mono\mono\metadata\class-init.c | 22
C:\git\runtime\src\mono\mono\metadata\sre-encode.c | 20
C:\git\runtime\src\mono\mono\mini\unwind.c | 20
C:\git\runtime\src\mono\mono\mini\debug-mini.c | 18
C:\git\runtime\src\mono\mono\mini\mini-exceptions.c | 18
C:\git\runtime\src\mono\mono\mini\local-propagation.c | 18
C:\git\runtime\src\mono\mono\mini\mini-runtime.c | 18
C:\git\runtime\src\mono\mono\mini\decompose.c | 18
C:\git\runtime\src\mono\mono\metadata\reflection.c | 16
C:\git\runtime\src\mono\mono\mini\mini-generic-sharing.c | 16
C:\git\runtime\src\mono\mono\mini\liveness.c | 16
C:\git\runtime\src\mono\mono\mini\memory-access.c | 14
C:\git\runtime\src\mono\mono\metadata\marshal.c | 14
C:\git\runtime\src\mono\mono\mini\branch-opts.c | 12
C:\git\runtime\src\mono\mono\eglib\giconv.c | 12
C:\git\runtime\src\mono\mono\metadata\mono-basic-block.c | 12
C:\git\runtime\src\mono\mono\mini\abcremoval.c | 10
C:\git\runtime\src\mono\mono\eventpipe\ep-rt-mono.c | 9
C:\git\runtime\src\mono\mono\mini\mini-codegen.c | 8
C:\git\runtime\src\mono\mono\metadata\custom-attrs.c | 8
C:\git\runtime\src\mono\mono\utils\networking.c | 8
C:\git\runtime\src\mono\mono\mini\lldb.c | 8
C:\git\runtime\src\mono\mono\mini\mini-profiler.c | 8
C:\git\runtime\src\mono\mono\metadata\debug-helpers.c | 6
C:\git\runtime\src\mono\mono\mini\alias-analysis.c | 6
C:\git\runtime\src\mono\mono\mini\calls.c | 6
C:\git\runtime\src\mono\mono\metadata\loader.c | 6
C:\git\runtime\src\mono\mono\metadata\memory-manager.c | 6
C:\git\runtime\src\mono\mono\utils\mono-codeman.c | 4
C:\git\runtime\src\mono\mono\metadata\class-setup-vtable.c | 4
C:\git\runtime\src\mono\mono\metadata\profiler.c | 4
C:\git\runtime\src\mono\mono\utils\mono-dl.c | 4
C:\git\runtime\src\mono\mono\mini\type-checking.c | 4
C:\git\runtime\src\mono\mono\utils\mono-threads.c | 4
C:\git\runtime\src\mono\mono\mini\seq-points.c | 4
C:\git\runtime\src\mono\mono\utils\mono-error.c | 4
C:\git\runtime\src\mono\mono\metadata\mempool.c | 4
C:\git\runtime\src\mono\mono\mini\mini-trampolines.c | 4
C:\git\runtime\src\mono\mono\mini\simd-intrinsics.c | 4
C:\git\runtime\src\mono\mono\component\debugger-engine.c | 3
C:\git\runtime\src\mono\mono\metadata\threads.c | 2
C:\git\runtime\src\mono\mono\metadata\jit-info.c | 2
C:\git\runtime\src\mono\mono\metadata\handle.c | 2
C:\git\runtime\src\mono\mono\metadata\native-library.c | 2
C:\git\runtime\src\mono\mono\utils\mono-threads-coop.c | 2
C:\git\runtime\src\mono\mono\mini\driver.c | 2
C:\git\runtime\src\mono\mono\metadata\mono-debug.c | 2
C:\git\runtime\src\mono\mono\metadata\debug-mono-ppdb.c | 2
C:\git\runtime\src\mono\mono\mini\cfold.c | 2
C:\git\runtime\src\mono\mono\utils\mono-math-c.c | 2
C:\git\runtime\src\mono\mono\utils\mono-path.c | 2
C:\git\runtime\src\mono\mono\metadata\mono-hash.c | 2
C:\git\runtime\src\mono\mono\profiler\aot.c | 2
C:\git\runtime\src\mono\mono\utils\mono-time.c | 2
C:\git\runtime\src\mono\mono\profiler\helper.c | 2
C:\git\runtime\src\mono\mono\utils\lock-free-alloc.c | 2
C:\git\runtime\src\mono\mono\component\event_pipe.c | 1
C:\git\runtime\src\mono\mono\eglib\gstr.c | 1
C:\git\runtime\src\mono\mono\eglib\gutf8.c | 1
Grand Total | 2615

Some of the warnings could come from shared headers and macros so hopefully the real count is less than above, but still a big chunk of work to go through.

I can do a race next week to reduce the number of items in the list, since that would touch headers and macros (if they are) and we see how many we are left. I will probably not touch top file source files, since they cover around 50% of the warnings.

Once that is done I believe we would need to distribute the top 5 files around a couple of people.

//CC @lambdageek @vargaz

**Comment by danmoseley** [comment]
@AaronRobinsonMSFT is CoreCLR work here now all done?
@lateralusX @fanyang-mono is Mono work still in progress, but on track for RC1 snap?

**Comment by fanyang-mono** [comment]
@danmoseley The final piece of work should be merged no later than tmr. (https://github.com/dotnet/runtime/pull/71269)

**Comment by fanyang-mono** [comment]
> @danmoseley The final piece of work should be merged no later than tmr. (#71269)
Merged.

**Comment by AaronRobinsonMSFT** [comment]
> > @danmoseley The final piece of work should be merged no later than tmr. (#71269)
> > Merged.

W00t! Thank you @fanyang-mono @lambdageek @lateralusX @elinor-fung @am11 and anyone else who helped make this happen.

@GrabYourPitchforks Do we have an audit plan from SDL. Just to make sure we didn't miss anything.

**Comment by danmoseley** [comment]
@GrabYourPitchforks ? what remains to close this..

**Comment by GrabYourPitchforks** [comment]
I think we're good here! Will reopen it if new things crop up. Thanks again for the efforts. :)
