### ISSUE TITLE
[wasm] Tracking issue for wasm/performance runs

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#67319]
These should be added to catch build breakages:

- [ ] Add a wasm run to `dotnet/performance` ci
- [ ] Add a wasm/perf (sanity-check) run to `dotnet/runtime` that runs one benchmark, essentially to catch build, and running issues
- [ ] Run the wasm/perf sanity-check as part of `runtime-wasm`
- [ ] Run the wasm/perf sanity-check as part of `runtime-wasm`, with rolling builds 

Others:
- [ ] explore picking `performance`, and `bdn` branch/commits for manual runs via azdo UI
- [ ] Can the bdn nuget publishing to internal feed be automated?

**Comment by adamsitnik** [comment]
I love the idea of adding the sanity checks! We have faced too many issues in the past, it would be great if we could prevent them.

**Comment by radical** [comment]
> On the automated publishing of BDN, I am not sure. @mmitche is this something that we could setup, or do we have to keep this as a manual process since we are crossing from a public feed thing to an internal feed thing?

Maybe something can check for new packages periodically, and publish when new ones become available? And this can run on the internal side of things.
