### ISSUE TITLE
[wasm] .NET WebAssembly profiling and memory diagnostics

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#69268]
Moved remaining goals to https://github.com/dotnet/runtime/issues/76316

**Comment by pavelsavara** [comment]
# Previous goals

- [x] #69158
   This adds support for using the JS console to create an EventPipe session with the default providers and to collect a trace in-memory to the Emscripten VFS and to egress it to a JavaScript Blob object (which can then be downloaded).
- [x] https://github.com/dotnet/runtime/pull/69567
   - Add support for specifying the providers for a session.
   - Allow the EventSource counter polling thread to start. 

- [x] ~~Save runtime artifacts from the EventPIpe build in an `ep` subfolder in the runtime pack (in addition to `mt` and plain) (variant of https://github.com/dotnet/runtime/issues/68506)~~ we ended up with separate runtime packs selected using `MonoWasmBuildVariant=perftrace` or `MonoWasmBuildVariant=multithread` in https://github.com/dotnet/runtime/pull/71054
- [ ] SDK property to build the app with profiling enabled using the `ep` variant of the runtime artifacts #72872 

The goal is to make it possible to add "something" to a webassembly project in order to cause it to collect a nettrace file that can be fed to the `dotnet-pgo` tool to produce an `.mibc` file which can be consumed by the Mono AOT compiler.

- [x] #68571
- [x] #69674
- [x] #72482
- [x] #72481
- [x]  Diagnostic server support #72482
   The goal is to make it possible to start and stop EventPipe sessions using a `dotnet-dsrouter` and `dotnet-counters`/`dotnet-trace`/etc combo when running a dev server.
- [x] https://github.com/dotnet/diagnostics/issues/3422 (prototype `dotnet-dsrouter server-websocket` is https://github.com/lambdageek/diagnostics/tree/wasm-server)
- [x] #73011
- [x] #69568
- [ ] https://github.com/dotnet/runtime/issues/76316

**Comment by pavelsavara** [comment]
unified with https://github.com/dotnet/runtime/issues/76316
