### ISSUE TITLE
[mono] Profiled AOT - PGO tracking 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#69512]
This issue tracks the move to use `dotnet-trace` in conjunction with `dotnet-pgo` to produce a `.mibc` file that can be used as input to our AOT compiler.  

- [x] [Emit MethodDetails and BulkType events from mono](https://github.com/dotnet/runtime/pull/68571) ✅ 
- [x] [Parse .mibc file within Mono AOT compiler](https://github.com/dotnet/runtime/pull/70194) ✅ 
- [x] [Modify AOT compiler msbuild task to take .mibc file as input](https://github.com/dotnet/runtime/pull/70194) ✅ 
- [x] Modify AOT compiler msbuild task to run dotnet-pgo and modify mono-sgen to take .nettrace file as input (https://github.com/dotnet/runtime/pull/70851) 🚧 
- [ ] Add option to `dotnet-trace` to spawn `dotnet-ds-router` and control lifetime
- [ ] <s>Bundle `dotnet-pgo` tooling</s> See whether or not dotnet-pgo is shipped
