### ISSUE TITLE
Native AOT in .NET 8

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#69739]
- [x] https://github.com/dotnet/runtime/issues/79003
- [x] https://github.com/dotnet/runtime/issues/79241
- [ ] https://github.com/dotnet/runtime/issues/79316
- [x] https://github.com/dotnet/runtime/issues/79570
- [x] https://github.com/dotnet/runtime/issues/78671
- [x] https://github.com/dotnet/linker/issues/3034

**Comment by filipnavara** [comment]
> Mac x64/ARM64

Done

**Comment by am11** [comment]
> Musl compatibility

This works with .NET 7. We even have docs listing Alpine Linux prerequisites: https://github.com/dotnet/docs/blob/main/docs/core/deploying/native-aot/index.md#prerequisites.

note: in reality, we only need `apk add build-base zlib-dev` in addition to `icu-libs` in a fresh VM / container to `PublishAot` a fully loaded mvc app.. `lld` is _especially_ not a prerequisite.

**Comment by jkotas** [comment]
> note: in reality, we only need apk add build-base zlib-dev 

Fixed in https://github.com/dotnet/docs/pull/31535

**Comment by ygoe** [comment]
Are there plans to support the arm32 (armhf) architecture? This is relevant for most Raspberry Pi environments that are not using the newest 64-bit OS or older hardware (before RPi 3). Armbian also does not seem to offer 64-bit images yet (for other devices like NanoPi, Orange Pi etc.).

**Comment by MichalPetryka** [comment]
> Are there plans to support the arm32 (armhf) architecture? This is relevant for most Raspberry Pi environments that are not using the newest 64-bit OS or older hardware (before RPi 3). Armbian also does not seem to offer 64-bit images yet (for other devices like NanoPi, Orange Pi etc.).

[It is planned](https://github.com/dotnet/runtime/discussions/71042) to remove ARM32 support from CoreCLR in .Net 9 (and NativeAOT uses that for codegen).

**Comment by MichalStrehovsky** [comment]
> > Are there plans to support the arm32 (armhf) architecture? This is relevant for most Raspberry Pi environments that are not using the newest 64-bit OS or older hardware (before RPi 3). Armbian also does not seem to offer 64-bit images yet (for other devices like NanoPi, Orange Pi etc.).
> 
> [There are plans to remove ARM32 support from CoreCLR](https://github.com/dotnet/runtime/discussions/71042) in .Net 9 (and NativeAOT uses that for codegen).

That said, we would still accept community contributions towards ARM32-Linux. It used to work at some point and it's probably not too far from working. No matter the resolution of the ARM32 .NET 9 discussion, for .NET 8 we'll still have all the infrastructure for Linux-ARM32 release and testing in place and we can run the port in the CI.

**Comment by agocke** [comment]
Also, as that issue mentions, that would be dropping Microsoft-maintained support. If community members would be willing to maintain support, that is up for discussion.

**Comment by ziaulhasanhamim** [comment]
I think till now the biggest performance problem with Native AOT is for reflection because ASP.NET CORE and EF Core-like frameworks are based on reflection. A nice way to solve many of these problems (not all) would be adding Rust-like macros in C#. Macros can do most of the important things that reflection does in compile time. In rust, all dynamic frameworks rely on it.

**Comment by DeafMan1983** [comment]
I should use `musl-g++` with **native aot** if yes then I can continue with musl-libc for Alpine and Void-Linux.

**Comment by fishkapro** [comment]
Will com\wmi be added? Are there any ways to work with wmi now?

**Comment by agocke** [comment]
.NET 8 is closing out, we'll pick new things up in .NET 9.
