### ISSUE TITLE
[wasm] Tracking issue for failures due to stack overflow

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#69810]
- [x] https://github.com/dotnet/runtime/issues/68798
- [x] https://github.com/dotnet/runtime/issues/69517
   - `JIT/Directed/tailcall/tailcall/tailcall.sh` test disabled in https://github.com/dotnet/runtime/pull/69863
- [ ] https://github.com/dotnet/runtime/issues/66118
- [ ] https://github.com/dotnet/runtime/issues/61756
