### ISSUE TITLE
[wasm] Improve the UX for using codespaces to run library tests, and debug

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#70122]
- [x] make it easier to install the deps like chrome, chromedriver
- [x] install the deps automatically
- [x] setup the paths accordingly
- [x] Pass `--no-sandbox` for the library tests too
- [x] Update instructions
- [x] Add instructions for debugging (`workflow/testing/libraries/debugging-wasm.md`)

**Comment by radical** [comment]
First 4 items should be complete now. @ilonatommy would you please be able to confirm that? Essentially, on a fresh codespace, with a wasm build run:
`
./dotnet.sh build /bl src/libraries/System.Net.Http/tests/FunctionalTests/System.Net.Http.Functional.Tests.csproj /p:Configuration=Release /p:TargetOS=Browser /p:TargetArchitecture=wasm /t:Test -p:RunAOTCompilation=true -p:EnableAggressiveTrimming=true -p:Scenario=WasmTestOnBrowser -bl
`

**Comment by ilonatommy** [comment]
Confirmed. But I have to admit that only when testing this I realized how new Codespaces configuration should be done. We need an info about setting `Dev cofiguration` 
![image](https://user-images.githubusercontent.com/32700855/199180997-57f96fba-4200-4603-a936-2a5821e2fce8.png)
because after the change that introduced configs I did not see this step and kept building manually. I'm not sure about the docs location though. Can we e.g. add a new column `Codespaces` to `Build requirements` section here: https://github.com/ilonatommy/runtime/blob/main/docs/workflow/README.md with a link to `Codespaces-requirements.md`?

**Comment by radical** [comment]
Isn't there another file about Codespaces setup?

**Comment by ilonatommy** [comment]
We do, did not see it. https://github.com/dotnet/runtime/blob/6811cc4dcb4aaabbfa471c0bff101ee70b237fc0/docs/workflow/Codespaces.md

**Comment by radical** [comment]
This is already completed.
