### ISSUE TITLE
Arm64 profile tooling support for performance analysis

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#70529]
# Overview
We can measure performance and analyze which areas show performance gap. However, in order to drill into code that needs improvement, we need tooling support for such as pcs-source mapping. We evaluated MAP and Streamline tools from Arm Holdings. However, both of them are not working for .NET for the basic CPU profiling. This is preventing us from doing the most basic kind of perf analysis. This requires work from both Arm Holding and us. 

## Work Items
- [x] Arm Holdings
  - [x] Provide vTune like profiling tool that works for .NET performance analysis (received a private fix)
  - [x] https://github.com/dotnet/runtime/issues/62456
    - They made a fix. It will be released in Streamline 8.0. Checking the timeline for 8.0.
- [x] MSFT .NET team
  - [x] Provided needed support to enable profiling on Arm Streamline
  - [x] Evaluate C++ IR Explorer tool if we can add .NET profiling in case Streamline is not enabled in time    
    - IRExplorer now supports R2R profiling on Arm64 (02/23/2022)

**Comment by adamsitnik** [comment]
@JulieLeeMSFT are there any plans to record some demos and share them online?

**Comment by JulieLeeMSFT** [comment]
@adamsitnik there will be internal presentation on IRExplorer in July. Will forward it to you. We are planning some documentation on Streamline tool. cc @RobertHenry6bev.
