### ISSUE TITLE
Enable platform agnostic SIMD support for vector

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#70532]
# Overview
Part of the library side work here is ensuring that users looking to support ARM64 can do so trivially even when they aren't familiar with the platform and to reduce overall cost of needing to support multiple platforms with SIMD acceleration (x86, x64, and ARM64 today; potentially other platforms like WASM in the future).

That work is being tracked by: dotnet/runtime#49397 which tracks us exposing a common cross-platform API surface that allows users to utilize "write-once" algorithms and successfully support multiple architectures.

## Work Items
- [ ] Enable platform agnostics SIMD  
  - [x]  https://github.com/dotnet/runtime/issues/49397
  - [x] **monoVM support:** https://github.com/dotnet/runtime/issues/64072
  - [ ] **JIT support:** https://github.com/dotnet/runtime/issues/63331
  
## Benchmarks to use
- Microbenchmarks

## What Success Looks Like
- The new API does not degrade the performance of the platform specific SIMD.
- Advertise the feature to the community, e.g., through blog posts or twitter.

**Comment by dakersnar** [comment]
Everything planned here for 7.0 has been completed, with the exception of the details in https://github.com/dotnet/runtime/issues/63331 that were moved out to 8.0.
