### ISSUE TITLE
Throughput for Server workloads on ARM64 is comparable to x64

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#70530]
# Summary
The server workload is both the most stressful and the most economically important. We want .NET Arm64 to be competitive with .NET x64, there should be no significant penalty for teams to use .NET Arm64. 

## What does success look like (include a metric if possible) 
0.8x or better performance on key metrics, as compared to x64 baselines. 

## User Stories under this Epic
- [ ] https://github.com/dotnet/runtime/issues/70527
- [x] https://github.com/dotnet/runtime/issues/70528
- [x] https://github.com/dotnet/runtime/issues/70529
