### ISSUE TITLE
[Mono-Arm64] Improved application throughput performance implementing hardware specific optimizations

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#70562]
**Work items::**

- [x]  Implement missing arm64 intrinsics
- [x]  Correct SIMD calling conventions (for P/Invoke, FFI, etc)

Research items not completed in 7.0. Will be done as part of 8.0
- [x]  Possibly consider implementing a basic set of cross-platform intrinsics to aid Mono Interpreter fall back scenarios in case of iOS/Apple products
- [ ]  Research Scalable Vector Extension (SVE) and possible implementation details
- [ ]  Research if it makes sense to support undocumented Apple M1 instructions (as used in the Apple "accelerate" library)

**Validation work items needed:**

- [x]  Enhance CI validation Mono runtime coverage on Arm64 Android/iOS/Apple devices
- [x]  Ensure reliable microbenchmarks runs on AOT/JIT on ARM64
- [x]  Ensure adequate comparisons on microbenchmarks runs for Arm64 v/s x64, also compare to CoreCLR
- [x]  Ensure startup/size metric automation on Arm64 devices in performance labs

**What success looks like:**

- [x]  Slowest 100 Microbenchmarks improve 30% compared to .NET6
- [x]  MAUI apps on Arm64 devices should show improved performance
- [ ]  80% total tests running/passing via CI coverage for Arm64 device runs  (We have good coverage on Android, but iOS remains, which will be covered in 8.0)
- [x] Improvements in AOT-LLVM and JIT-LLVM lanes on internal runs for TechEmpower benchmarks

**Comment by SamMonoRT** [comment]
We have accomplished significant gains in microbenchmarks, MAUI startup, and the remaining items in the list will be tackled as part of 8.0. I'll make separations and move to 8.0.

**Comment by SamMonoRT** [comment]
Closing this issue, but @matouskozak and @jandupej will investigate  Research Scalable Vector Extension (SVE) and possible implementation details for 9.0 release.
