### ISSUE TITLE
[Mono-Arm64] Create smaller mobile applications by refactoring code

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#70561]
**Work items:**

- [ ]  Code sharing for SIMD fallbacks leading to size improvements for arm64 offerings
- [x]  General code inspection and cleanup
- [x]  Targeted bypassing of large chunks of code not supported on arm64 like adding checks for Platform.IsSupported -- this was covered by second item above. Marking this as completed.

**Validation work items needed:**

- [x]  Enhance CI validation Mono runtime coverage on Arm64 Android/iOS/Apple devices
- [x]  Ensure reliable microbenchmarks runs on AOT/JIT on ARM64
- [x]  Ensure adequate comparisons on microbenchmarks runs for Arm64 v/s x64, also compare to CoreCLR
- [x]  Ensure startup/size metric automation on Arm64 devices in performance labs

**What success looks like:**

- [x]  No functional regressions in mobile apps
- [x]  Overall measurable app size reduction

**Comment by SamMonoRT** [comment]
This can be closed. MAUI apps have shown significant size reductions, and hello world samples as well. Closing the issue.
