### ISSUE TITLE
[ICU] Tracking issue for all culture, language and translation problems

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#70781]
- [x] culture not loaded and not present in [`AllGlobalizationData`](https://github.com/dotnet/icu/blob/8ea608427e5988d3dd25130400947aad0a917bba/icu-filters/icudt_browser.json#L7): https://github.com/dotnet/runtime/issues/43398, https://github.com/dotnet/runtime/issues/53239, https://github.com/dotnet/runtime/issues/67115
"nb_NO", "nb" - got fixed between https://github.com/dotnet/icu/commit/ae1ada7f6e6b1bd2e4d8c91e5959606fd16c1ea8 and https://github.com/dotnet/icu/commit/913f9944b83a9365106bf8a0ec5b56662f6b93d5 - using new version of icu data file helps here, tested on Blazor's sample HEAD: https://github.com/dotnet/aspnetcore/commit/c94c3b1995aef88008ba52063f8c5fb8b776e890 and WASM's sample HEAD: https://github.com/dotnet/runtime/commit/f0c4347ff0eb8852dd8c39a45f7d2c4da6cf0892.
- [x] Missing locales that are considered canonical - https://github.com/dotnet/runtime/issues/79816
- [x] Aliases for Norwegian locale do not work - https://github.com/dotnet/runtime/issues/79815
- [x] culture not resolved using short name: https://github.com/dotnet/runtime/issues/52388
- [x] shortened native name: https://github.com/dotnet/runtime/issues/44739, https://github.com/dotnet/runtime/issues/55348, https://github.com/dotnet/runtime/issues/53880, https://github.com/dotnet/runtime/issues/45951.
- [x] currency symbols: https://github.com/dotnet/runtime/issues/45262, https://github.com/dotnet/runtime/issues/79235
- [x] pseudo locales: https://github.com/dotnet/aspnetcore/issues/42258
- [x] string sorting: https://github.com/dotnet/runtime/issues/66899
- [x] EFIGS does not support all English currencies, users have to load full data for them: https://github.com/dotnet/runtime/issues/79740
- [x] Arabic DateTimeFormat.GetMonthName https://github.com/dotnet/runtime/issues/57723

**Comment by andrerom** [comment]
Unsure where to report this, but potential ICU and .Net related issues:
- In ICU v69 ["no" `Norwegian` became parent of "nb" `Norwegian Bokmål` AND for "nn" `Norwegian Nynorsk`](https://icu.unicode.org/design/norwegian-locales-changes-in-v39), earlier `no` was alias of `nb` 

This effectively means the following hierarchy per ICU as far as I understand it:
- `nb-NO` => `nb` => `no`
- `nn-NO` => `nn` => `no`

Right now this does not seem to work: If I add translation files in `*.no.resx` they are **not** picked up if I have `nb-NO` and/or `nb` as supported languages in Asp.Net.

And documentation ([1](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/provide-resources?view=aspnetcore-8.0#culture-fallback-behavior), [2](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.parent?view=net-8.0#remarks), [3](https://learn.microsoft.com/en-us/globalization/locale/fallback)) seems to imply such hierarchy is currently not supported.

Is this something that should be tracked as an issues?
Or is this due to me testing on MacOS with potentially older ICU versions[^note]?
 
[^note]: Additional Info:
  [Documentation](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#macos-behavior) on upgrading ICU on Mac seems to imply you'll need to build icu and dotnet yourself, installing updated ICU from homebrew does not seems like it's picked up and used, and I haven't found a way to detect which ICU version is used by .Net.
  `CultureInfo.InvariantCulture.CompareInfo.Version` only gives me:
  `{"FullVersion":31129,"SortId":"00007999-0000-0000-0000-00000000007f"}`
  `icuinfo` gave med `58.1` before I installed updated version via brew.

**Comment by ilonatommy** [comment]
@andrerom, behavior of .net depends directly on ICU, unless you use `HybridGlobalization`. Net8 is relying on ICU 72, earlier we were shipping ICU bundles built with ICU 69. If ICU standard changes we assume it's by design and do not intend to keep the older behavior.

**Comment by ilonatommy** [comment]
Closing, all the linked issues are resolved.
