### ISSUE TITLE
[wasm] Ensure subtleCrypto is usable from Blazor app

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#72810]
There are potentially several things blocking it from working

- [ ] Blazor uses their own runtime initialization path and the crypto initialization call is not included in that path (or public)
    - [ ] https://github.com/dotnet/aspnetcore/pull/43049
    - [x] https://github.com/dotnet/runtime/pull/73484
- [ ] Blazor's publish targets limit what files end up in the publish output [history](https://github.com/dotnet/runtime/issues/48016) 
    - [x] https://github.com/dotnet/sdk/pull/26966
    - [x] https://github.com/dotnet/runtime/pull/73073
- [x] https://github.com/dotnet/aspnetcore/issues/42114
- [x] https://github.com/dotnet/runtime/issues/73386
- [x] https://github.com/dotnet/runtime/pull/73537
- [x] https://github.com/dotnet/runtime/pull/73702

**Comment by lewing** [comment]
also related to https://github.com/dotnet/runtime/issues/69741

**Comment by pavelsavara** [comment]
After [this](https://github.com/dotnet/runtime/pull/72275) arrives to Blazor via SDK, we will attempt to load the `dotnet-crypto-worker.js`

![image](https://user-images.githubusercontent.com/271576/181018042-a49ad1ee-4f05-4845-b36b-adb64da2115e.png)

We need to add `dotnet-crypto-worker.js` into SDK and into list of files hosted by Blazor.

**Comment by pavelsavara** [comment]
The current runtime code is using `new Worker("dotnet-crypto-worker.js")` which means that the file is relative to `baseURL` is that what we want for Blazor?

**Comment by pavelsavara** [comment]
It seems we also need `Cross-Origin-Embedder-Policy: require-corp` for it.
![image](https://user-images.githubusercontent.com/271576/182125132-90f4d0d4-2bdb-4ff3-a126-0344ea0dd6d8.png)

**Comment by pavelsavara** [comment]
Also, the file as is doesn't have any hash or cache policy.

**Comment by javiercn** [comment]
@pavelsavara @radical and I talked about this.

It would be ideal if the runtime does not hardcode any path and receives this data as part of the initialization process. We likely want to add a version hash to the file in the same way we do for dotnet.js, and in general, we want control over anything that loads over a fetch request. (In other words, the runtime should not hardcode the logic related to how things work, as we might want to change it in the future or needs to be tweaked depending on the scenario.

**Comment by pavelsavara** [comment]
Yes, but your custom startup sequence is already nightmare for us. So it would be better if we don't make it worse by handling modules of the runtime in separate way as well. 

My draft https://github.com/dotnet/aspnetcore/pull/42770 doesn't deal with JS assets, but passing us the list of assets with hashes is the right way how to do it.

**Comment by javiercn** [comment]
@pavelsavara cool, that's very much inline with what @radical and myself discussed.

We mostly care about what @SteveSandersonMS commented on the relevant issue. As long as we maintain the current functionality, we should be good, for example, we wouldn't want to start imposing a concrete file layout on the deployed apps.

**Comment by pavelsavara** [comment]
![image](https://user-images.githubusercontent.com/271576/182936906-4f536092-fa46-4207-b4d5-d9d177afe06b.png)

**Comment by radical** [comment]
This needs a test in Wasm.Build.Tests . It can use playwright to click on some button to trigger a crypto call. An existing blazor test - https://github.com/dotnet/runtime/blob/main/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs#L250-L278 :

https://github.com/dotnet/runtime/blob/bf56a7c7e876ba12bddcc1df1c024deb86ab4ff8/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs#L268-L277

**Comment by eerhardt** [comment]
cc @jeffhandley - FYI

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/73858 . Please re-open if needed for some reason.
