### ISSUE TITLE
.NET 7.0 Preview 7 Microbenchmarks Performance Study Report

### ISSUE THREAD

**Issue by mrsharm** [dotnet/runtime#73866]
## Data

This time we have covered following configurations comparing .NET 7.0 Preview 7 vs. .NET 7.0 Preview 5:

* architectures: arm64, x64, x86
* Unix: ubuntu 18.04, ubuntu 20.04, macOS Monterey 12.3, macOS Monterey 12.3.1, macOS Monterey 12.4, macOS Big Sur 11.6.8
* Windows: 10 & 11

<details>   
 
 Operating System      | Bit   | Processor 
 --------------------- | ----- | ----------------------------------------------- |
 Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           
 Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           
 macOS Monterey 12.3   | Arm64 | Apple M1 Max                                    
 Windows 10            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               
 Windows 10            | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        
 Windows 10            | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        
 Windows 10            | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   
 Windows 10            | X64   | Intel Core i9-10900K CPU 3.70GHz                
 Windows 11            | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      
 Windows 11            | X64   | AMD Ryzen 9 3950X                               
 Windows 11            | X64   | AMD Ryzen 9 5900X                               
 Windows 11            | X64   | AMD Ryzen 9 5950X                               
 Windows 11            | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    
 Windows 11            | X64   | Intel Core i9-10900K CPU 3.70GHz                
 Windows 11            | X64   | 11th Gen Intel Core i9-11900H 2.50GHz           
 ubuntu 18.04          | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               
 ubuntu 18.04          | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) 
 ubuntu 18.04          | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    
 ubuntu 20.04          | X64   | AMD Ryzen 9 5900X                               
 ubuntu 20.04          | X64   | Intel Core i9-10900K CPU 3.70GHz                
 Windows 10            | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               
 Windows 10            | X86   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        
 Windows 11            | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      
 macOS Big Sur 11.6.8  | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       
 macOS Monterey 12.3.1 | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     
 macOS Monterey 12.4   | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       

</details>

Most of the benchmarks were run on bare-metal machines, some were executed via WSL.

This would not be possible without the help from: @adamsitnik , @AndyAyersMS, @brianrob, @Jozkee , @ivanpovazan, @kunalspathak, @jeffhandley, @GrabYourPitchforks, @tannergooding who contributed their results and time. An addtional thank you to @dakersnar for shadowing the creation of this report and helping with the vetting of the results!

The full report generated by the tool is available [here](https://gist.github.com/mrsharm/2627093b1fb55cae5417f4a9a547de97). You will have to click "Raw" to see the entire file. The report is sorted from most regressed to most improved, so scroll to the bottom in the full report to see improvements. There are plenty of them! 

Again, the [full historical data](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/TestHistoryIndexIndex.html) turned out to be **extremely useful**. For details about methodology please read https://github.com/dotnet/runtime/issues/41871. Preview 5 report can be found [here](https://github.com/dotnet/runtime/issues/70590).

## Notable Improvements

* [x] `System.Perf_Convert.ToBase64String(formattingOptions: None)`
  * Detected and reported here: https://github.com/dotnet/perf-autofiling-issues/issues/6731 
  * Solved by: https://github.com/dotnet/runtime/pull/71795
* [x] `System.Numerics.Tests.Perf_Quaternion.NormalizeBenchmark`
  * Detected and reported here: https://github.com/dotnet/perf-autofiling-issues/issues/6256
  * Solved by: https://github.com/dotnet/runtime/pull/70777
* [x] `Benchstone.MDBenchF.MDInvMt.Test`
  * Detected and reported here: https://github.com/dotnet/perf-autofiling-issues/issues/6721
  * Solved by: https://github.com/dotnet/runtime/pull/70271
* [x] ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: ".*", Options: NonBacktracking)``
  * Detected and reported here: https://github.com/dotnet/perf-autofiling-issues/issues/5970 
  * Solved by: https://github.com/dotnet/runtime/pull/70217
* [x] `System.Numerics.Tests.Perf_VectorConvert.Convert_ulong_double`
  * Detected and reported here: https://github.com/dotnet/perf-autofiling-issues/issues/5841
  * Solved by: https://github.com/dotnet/runtime/pull/68874
* [x] `System.Tests.Perf_Environment.GetLogicalDrives` 
  *  Detected and reported here: https://github.com/dotnet/perf-autofiling-issues/issues/5773
  * Solved by: https://github.com/dotnet/runtime/pull/72923

### By Design

* [x] `Benchstone.BenchI.Array2.Test`
  * Detected by: https://github.com/dotnet/runtime/issues/71059 
  * Explained: https://github.com/dotnet/runtime/issues/71059#issuecomment-1203196867
  * Added comment: https://github.com/dotnet/runtime/issues/71059#issuecomment-1208535442
* [x] `System.Buffers.Text.Tests.Base64Tests.Base64Decode(NumberOfBytes: 1000)`
  * Unit Test Changed. Discussion here: https://github.com/dotnet/perf-autofiling-issues/issues/6271
* [x] ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "\p{Ll}", Options: NonBacktracking)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "aei", Options: Compiled)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "aqj", Options: Compiled)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "aqj", Options: NonBacktracking)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "aqj", Options: None)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "zqj", Options: Compiled)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "zqj", Options: NonBacktracking)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern: "zqj", Options: None)``, ``System.Collections.IterateForEach<Int32>.HashSet(Size: 512)``, `System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options: (en-US, Ordinal, False))`, `System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options: (, IgnoreCase, False))`, `System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options: (enUS, IgnoreCase, False))`, `System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (enUS, IgnoreCase, False))`, `System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (, IgnoreCase, False))`, `System.Globalization.Tests.StringSearch.IsSuffix_DifferentLastChar(Options: (en-US, Ordinal, False))`, `System.IO.Tests.Perf_Path.GetDirectoryName`, `System.Linq.Tests.Perf_Enumerable.Count(input: IEnumerable)`, ``System.Tests.Perf_Double.Parse(value: "1.7976931348623157e+308")``, ``System.Tests.Perf_Double.Parse(value: "-1.7976931348623157e+308")``, ``System.Tests.Perf_Double.Parse(value: "12345")``, ``System.Tests.Perf_Double.TryParse(value: "-1.7976931348623157e+308")``, ``System.Tests.Perf_Double.TryParse(value: "1.7976931348623157e+308")``, ``System.Tests.Perf_UInt64.TryParse(value: "18446744073709551615")``, ``System.Tests.Perf_UInt16.TryParse(value: "12345")``, ``System.Tests.Perf_Double.TryParse(value: "12345")``, ``System.Tests.Perf_Double.TryParse(value: "1.7976931348623157e+308")``, `System.IO.Tests.Perf_Path.GetDirectoryName`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/5818
  * Explained: https://github.com/dotnet/runtime/pull/69878
  * Added comment: https://github.com/dotnet/runtime/pull/69878#issuecomment-1211150243
* [x] ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_BoostDocs_Simple.IsMatch(Id: 11, Options: NonBacktracking)``, ``System.Text.RegularExpressions.Tests.Perf_Regex_Industry_BoostDocs_Simple.IsMatch(Id: 0, Options: NonBacktracking)``
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/5760
  * Explained: https://github.com/dotnet/runtime/pull/69839
  * Added comment: https://github.com/dotnet/runtime/pull/69839#issuecomment-1211319995
* [x] `System.Security.Cryptography.X509Certificates.Tests.X509ChainTests.BuildX509ChainContoso`, `System.Text.RegularExpressions.Tests.Perf_Regex_Common.CtorInvoke(Options: IgnoreCase, Compiled)`, `System.Text.RegularExpressions.Tests.Perf_Regex_Common.CtorInvoke(Options: Compiled)`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/5638, https://github.com/dotnet/perf-autofiling-issues/issues/5602
  * Explained: https://github.com/dotnet/runtime/pull/69672 
  * Added comment: https://github.com/dotnet/runtime/pull/69672#issuecomment-1212535787
* [x] `System.Tests.Perf_UInt64.ParseSpan(value: "18446744073709551615")`
  * Detected by: https://github.com/dotnet/runtime/issues/71771 
  * Added comment: 

### Investigation In Progress

* [ ] `Benchstone.MDBenchI.MDMulMatrix.Test`
  * Detected by: https://github.com/dotnet/runtime/issues/72030
  * Added comment: https://github.com/dotnet/runtime/issues/72030#issuecomment-1208557384
* [ ] `System.Threading.Channels.Tests.SpscUnboundedChannelPerfTests.PingPong`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/6018, https://github.com/dotnet/perf-autofiling-issues/issues/6027, https://github.com/dotnet/perf-autofiling-issues/issues/6009
  * Added comment: https://github.com/dotnet/perf-autofiling-issues/issues/6009 
* [ ] `System.Collections.IndexerSet<String>.Array(Size: 512)`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/6746
  * Added comment: https://github.com/dotnet/runtime/pull/71659#issuecomment-1211352430 
  * Tracked by: https://github.com/dotnet/core/issues/7455 
* [ ] `System.Numerics.Tests.Perf_BigInteger.Parse(numberString: 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890)`
  * Detected by: https://github.com/dotnet/runtime/issues/74158, https://github.com/dotnet/perf-autofiling-issues/issues/6936, https://github.com/dotnet/perf-autofiling-issues/issues/6968
  * Added comment: https://github.com/dotnet/runtime/pull/71968#issuecomment-1211367995
* [ ] `System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.ProducerConsumer(RentalSize: 4096, ManipulateArray: False, Async: True, UseSharedPool: True)`, `System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.SingleSerial(RentalSize: 4096, ManipulateArray: False, Async: True, UseSharedPool: False)`, `System.Buffers.Tests.RentReturnArrayPoolTests<Object>.MultipleSerial(RentalSize: 4096, ManipulateArray: False, Async: True, UseSharedPool: False)`, `System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.SingleSerial(RentalSize: 4096, ManipulateArray: False, Async: True, UseSharedPool: False)`, `System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.ProducerConsumer(RentalSize: 4096, ManipulateArray: False, Async: False, UseSharedPool: False)` 
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/6106 
  * Added comment: https://github.com/dotnet/runtime/issues/72194#issuecomment-1213429501
* [ ] `System.Numerics.Tests.Perf_Matrix4x4.CreateShadowBenchmark`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/5830
  * Explained: https://github.com/dotnet/runtime/pull/68874#issuecomment-1212487089
  * Added comment: https://github.com/dotnet/runtime/pull/68874#issuecomment-1212475772
* [ ] `System.Threading.Tasks.ValueTaskPerfTest.CreateAndAwait_FromYieldingAsyncMethod`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/6105
  * Added comment: https://github.com/dotnet/perf-autofiling-issues/issues/6105#issuecomment-1213388916
* [ ] `System.Globalization.Tests.StringEquality.Compare_Same_Upper(Count: 1024, Options: (en-US, OrdinalIgnoreCase))`
  * Detected by: https://github.com/dotnet/perf-autofiling-issues/issues/6523
  * Added comment: https://github.com/dotnet/perf-autofiling-issues/issues/6523#issuecomment-1213401079
* [ ] `System.IO.Tests.Perf_File.Delete`
  * Detected by: https://github.com/dotnet/runtime/issues/73861

### Already Solved
* [x] `System.Text.Json.Serialization.Tests.ColdStartSerialization<SimpleStructWithProperties>.NewCustomConverter`
  * Detected and Reported here: https://github.com/dotnet/runtime/issues/73388
  * Solved by: https://github.com/dotnet/runtime/pull/73497
* [x] `System.Tests.Perf_UInt64.Parse(value: "12345")`, `System.Tests.Perf_UInt16.TryParse(value: "12345")`
  * Detected and Reported here: https://github.com/dotnet/perf-autofiling-issues/issues/6587 
  * Solved by: https://github.com/dotnet/runtime/pull/71673 
* [x] `Microsoft.Extensions.Logging.FormattingOverhead.FourArguments_EnumerableArgument`
  * Detected and Reported here: https://github.com/dotnet/perf-autofiling-issues/issues/7149 
  * Noise caused the jump and now the trend is back to normal. 

### Noise, Flaky or Multimodal

The following benchmarks showed up in the report generated by the tool, but were not actual regressions:

* `CscBench.CompileTest`
* `Microsoft.Extensions.Primitives.Performance.StringValuesBenchmark.Indexer_FirstElement_String`
* `System.Numerics.Tests.Perf_VectorOf<Int32>.ConditionalSelectBenchmark`
* `System.Buffers.Tests.RentReturnArrayPoolTests<Object>.ProducerConsumer(RentalSize: 4096, ManipulateArray: False, Async: True, UseSharedPool: True)`
* `System.Numerics.Tests.Perf_Vector4.MultiplyOperatorBenchmark`
* `System.Numerics.Tests.Perf_Vector4.LengthSquaredBenchmark`
* `System.Numerics.Tests.Perf_Vector4.SquareRootBenchmark`
* `System.Numerics.Tests.Perf_Vector4.SubtractFunctionBenchmark`
* `System.Numerics.Tests.Perf_VectorOf<*>.*`
* `System.Memory.Span<Int32>.StartsWith(Size: 512)`
* `PerfLabTests.CastingPerf.CheckArrayIsArrayByVariance`
* `System.Text.Tests.Perf_StringBuilder.ctor_capacity(length: 100000)`
* `System.Collections.TryGetValueFalse<Int32, Int32>.Dictionary(Size: 512)`
* `PerfLabTests.StackWalk.Walk`
* `System.Memory.MemoryMarshal<Byte>.CastToByte`
* `System.Memory.MemoryMarshal<Byte>.CastToInt`
* `System.Memory.MemoryMarshal<Byte>.Read`
* `System.Memory.MemoryMarshal<Int32>.Read`
* `System.Numerics.Tests.Constructor.ConstructorBenchmark_Single`
* `System.Buffers.Tests.ReadOnlySequenceTests<Byte>.IterateTryGetTenSegments`
* `System.Diagnostics.Perf_Process.GetProcessesByName`
* `System.Diagnostics.Perf_Process.GetProcesses`

## Statistics

Total:   119052
Same:    77.32 %
Slower:  4.81 %
Faster:  8.99 %
Noise:   8.83 %
Unknown: 0.04 %

## Statistics per Architecture

| Architecture | Same    | Slower  | Faster  | Noise  | Unknown|
| ------------ | ------- | ------- | ------- | ------ | ------- |
| Arm64        | 70.13 % | 10.87 % | 13.28 % | 5.67 % | 0.04 % |
| X64          | 77.89 % | 3.89 %  | 8.77 %  | 9.40 % | 0.05 % |
| X86          | 80.69 % | 4.93 %  | 6.16 %  | 8.20 % | 0.02 % |

## Statistics per Operating System

| Operating System      | Same    | Slower  | Faster  | Noise   | Unknown|
| --------------------- | ------- | ------- | ------- | ------- | ------- |
| macOS Monterey 12.3   | 56.65 % | 12.80 % | 22.04 % | 8.38 %  | 0.13 % |
| Windows 11            | 77.72 % | 6.52 %  | 6.74 %  | 8.99 %  | 0.03 % |
| macOS Big Sur 11.6.8  | 86.57 % | 3.12 %  | 5.64 %  | 4.61 %  | 0.07 % |
| macOS Monterey 12.3.1 | 87.38 % | 3.20 %  | 4.41 %  | 4.87 %  | 0.13 % |
| macOS Monterey 12.4   | 85.71 % | 2.35 %  | 4.48 %  | 7.40 %  | 0.07 % |
| ubuntu 18.04          | 64.02 % | 2.04 %  | 23.69 % | 10.18 % | 0.07 % |
| ubuntu 20.04          | 80.80 % | 4.70 %  | 5.62 %  | 8.85 %  | 0.04 % |
| Windows 10            | 80.44 % | 3.28 %  | 6.81 %  | 9.46 %  | 0.02 % |

## Statistics per Namespace

<details>

| Namespace                                                 | Same    | Slower  | Faster  | Noise   | Unknown|
| --------------------------------------------------------- | ------- | ------- | ------- | ------- | ------- |
| BenchmarksGame                                            | 85.16 % | 5.31 %  | 9.52 %  | 0.00 %  | 0.00 % |
| Benchstone.BenchF                                         | 92.31 % | 4.04 %  | 3.65 %  | 0.00 %  | 0.00 % |
| Benchstone.BenchI                                         | 86.06 % | 5.13 %  | 8.81 %  | 0.00 %  | 0.00 % |
| Benchstone.MDBenchF                                       | 36.92 % | 0.77 %  | 62.31 % | 0.00 %  | 0.00 % |
| Benchstone.MDBenchI                                       | 32.31 % | 9.23 %  | 58.46 % | 0.00 %  | 0.00 % |
| Devirtualization                                          | 82.31 % | 0.77 %  | 2.31 %  | 14.62 % | 0.00 % |
| Exceptions                                                | 83.23 % | 8.55 %  | 8.23 %  | 0.00 %  | 0.00 % |
| FractalPerf                                               | 96.15 % | 0.00 %  | 3.85 %  | 0.00 %  | 0.00 % |
| GuardedDevirtualization                                   | 81.59 % | 0.00 %  | 0.09 %  | 18.32 % | 0.00 % |
| Inlining                                                  | 51.28 % | 1.28 %  | 0.00 %  | 47.44 % | 0.00 % |
| Interop                                                   | 79.49 % | 11.54 % | 8.97 %  | 0.00 %  | 0.00 % |
| JetStream                                                 | 90.38 % | 3.85 %  | 5.77 %  | 0.00 %  | 0.00 % |
| Layout                                                    | 94.23 % | 0.00 %  | 5.77 %  | 0.00 %  | 0.00 % |
| Lowering                                                  | 88.46 % | 0.00 %  | 0.00 %  | 11.54 % | 0.00 % |
| MicroBenchmarks.Serializers                               | 82.35 % | 3.83 %  | 13.81 % | 0.00 %  | 0.00 % |
| Microsoft.AspNetCore.Server.Kestrel.Performance           | 80.29 % | 7.69 %  | 12.02 % | 0.00 %  | 0.00 % |
| Microsoft.Extensions.Caching.Memory.Tests                 | 77.62 % | 10.49 % | 11.89 % | 0.00 %  | 0.00 % |
| Microsoft.Extensions.Configuration.Xml                    | 86.54 % | 6.73 %  | 6.73 %  | 0.00 %  | 0.00 % |
| Microsoft.Extensions.DependencyInjection                  | 66.50 % | 5.21 %  | 27.05 % | 1.24 %  | 0.00 % |
| Microsoft.Extensions.Logging                              | 81.98 % | 5.93 %  | 9.78 %  | 2.31 %  | 0.00 % |
| Microsoft.Extensions.Primitives.Performance               | 70.67 % | 3.37 %  | 0.00 %  | 25.96 % | 0.00 % |
| Microsoft.Extensions.Primitives                           | 73.50 % | 2.56 %  | 2.99 %  | 20.94 % | 0.00 % |
| PerfLabTests                                              | 68.75 % | 7.74 %  | 18.32 % | 5.19 %  | 0.00 % |
| PerfLabTests.CastingPerf2                                 | 69.23 % | 4.36 %  | 26.41 % | 0.00 %  | 0.00 % |
| SciMark2                                                  | 89.23 % | 3.85 %  | 6.92 %  | 0.00 %  | 0.00 % |
| SIMD                                                      | 95.73 % | 2.56 %  | 1.71 %  | 0.00 %  | 0.00 % |
| Span                                                      | 90.46 % | 2.00 %  | 7.54 %  | 0.00 %  | 0.00 % |
| StoreBlock                                                | 78.72 % | 0.13 %  | 0.13 %  | 21.03 % | 0.00 % |
| System.Buffers.Binary.Tests                               | 75.96 % | 2.40 %  | 11.54 % | 10.10 % | 0.00 % |
| System.Buffers.Tests                                      | 82.36 % | 6.03 %  | 7.59 %  | 4.01 %  | 0.00 % |
| System.Buffers.Text.Tests                                 | 79.14 % | 3.58 %  | 5.12 %  | 12.17 % | 0.00 % |
| System.Collections                                        | 83.03 % | 6.26 %  | 10.07 % | 0.64 %  | 0.00 % |
| System.Collections.Concurrent                             | 78.21 % | 5.19 %  | 6.82 %  | 9.78 %  | 0.00 % |
| System.Collections.Tests                                  | 78.58 % | 3.88 %  | 11.68 % | 5.86 %  | 0.00 % |
| System.ComponentModel.Tests                               | 92.31 % | 2.45 %  | 5.24 %  | 0.00 %  | 0.00 % |
| System.ConsoleTests                                       | 87.18 % | 11.54 % | 1.28 %  | 0.00 %  | 0.00 % |
| System.Diagnostics                                        | 78.65 % | 12.50 % | 8.85 %  | 0.00 %  | 0.00 % |
| System.Diagnostics.Tracing                                | 90.38 % | 3.85 %  | 5.77 %  | 0.00 %  | 0.00 % |
| System.Formats.Cbor.Tests                                 | 88.17 % | 6.21 %  | 5.62 %  | 0.00 %  | 0.00 % |
| System.Formats.Tar.Tests                                  | 71.15 % | 11.54 % | 17.31 % | 0.00 %  | 0.00 % |
| System.Globalization.Tests                                | 82.30 % | 5.70 %  | 10.72 % | 1.29 %  | 0.00 % |
| System                                                    | 87.82 % | 1.28 %  | 10.04 % | 0.85 %  | 0.00 % |
| System.IO.Compression                                     | 92.95 % | 1.87 %  | 5.18 %  | 0.00 %  | 0.00 % |
| System.IO.MemoryMappedFiles.Tests                         | 89.10 % | 6.41 %  | 4.49 %  | 0.00 %  | 0.00 % |
| System.IO.Pipelines.Tests                                 | 79.81 % | 0.96 %  | 19.23 % | 0.00 %  | 0.00 % |
| System.IO.Pipes.Tests                                     | 87.82 % | 5.77 %  | 6.41 %  | 0.00 %  | 0.00 % |
| System.IO.Tests                                           | 84.12 % | 8.03 %  | 6.08 %  | 1.78 %  | 0.00 % |
| System.Linq.Tests                                         | 88.31 % | 3.69 %  | 7.43 %  | 0.57 %  | 0.00 % |
| System.MathBenchmarks                                     | 89.45 % | 1.30 %  | 8.31 %  | 0.93 %  | 0.00 % |
| System.Memory                                             | 75.22 % | 3.95 %  | 6.98 %  | 13.85 % | 0.00 % |
| System.Net.Http.Tests                                     | 78.37 % | 11.22 % | 10.42 % | 0.00 %  | 0.00 % |
| System.Net.NetworkInformation.Tests                       | 78.85 % | 14.42 % | 6.73 %  | 0.00 %  | 0.00 % |
| System.Net.Primitives.Tests                               | 85.66 % | 2.97 %  | 4.02 %  | 7.34 %  | 0.00 % |
| System.Net.Security.Tests                                 | 84.50 % | 7.24 %  | 8.27 %  | 0.00 %  | 0.00 % |
| System.Net.Sockets.Tests                                  | 75.59 % | 15.75 % | 8.66 %  | 0.00 %  | 0.00 % |
| System.Net.Tests                                          | 83.97 % | 12.18 % | 3.85 %  | 0.00 %  | 0.00 % |
| System.Net.WebSockets.Tests                               | 69.23 % | 19.23 % | 11.54 % | 0.00 %  | 0.00 % |
| System.Numerics.Tests                                     | 59.29 % | 4.34 %  | 2.53 %  | 33.84 % | 0.00 % |
| System.Reflection                                         | 85.13 % | 3.08 %  | 9.23 %  | 2.56 %  | 0.00 % |
| System.Runtime.InteropServices.Tests                      | 88.46 % | 1.92 %  | 9.62 %  | 0.00 %  | 0.00 % |
| System.Runtime.Serialization.Formatters.Tests             | 84.62 % | 0.00 %  | 15.38 % | 0.00 %  | 0.00 % |
| System.Security.Cryptography.Primitives.Tests.Performance | 84.62 % | 6.73 %  | 8.65 %  | 0.00 %  | 0.00 % |
| System.Security.Cryptography.Tests                        | 69.23 % | 2.99 %  | 27.78 % | 0.00 %  | 0.00 % |
| System.Security.Cryptography.X509Certificates.Tests       | 87.18 % | 10.26 % | 2.56 %  | 0.00 %  | 0.00 % |
| System.Tests                                              | 82.18 % | 5.06 %  | 5.57 %  | 7.20 %  | 0.00 % |
| System.Text.Encodings.Web.Tests                           | 80.93 % | 8.97 %  | 10.10 % | 0.00 %  | 0.00 % |
| System.Text.Json.Document.Tests                           | 78.23 % | 0.46 %  | 21.31 % | 0.00 %  | 0.00 % |
| System.Text.Json.Reader.Tests                             | 66.35 % | 8.65 %  | 25.00 % | 0.00 %  | 0.00 % |
| System.Text.Json.Serialization.Tests                      | 89.41 % | 2.33 %  | 8.27 %  | 0.00 %  | 0.00 % |
| System.Text.Json.Tests                                    | 92.53 % | 1.95 %  | 5.30 %  | 0.22 %  | 0.00 % |
| System.Text                                               | 70.51 % | 3.33 %  | 26.15 % | 0.00 %  | 0.00 % |
| System.Text.RegularExpressions.Tests                      | 63.41 % | 5.17 %  | 30.69 % | 0.00 %  | 0.73 % |
| System.Text.Tests                                         | 85.90 % | 3.75 %  | 7.51 %  | 2.84 %  | 0.00 % |
| System.Threading.Channels.Tests                           | 87.18 % | 7.37 %  | 5.45 %  | 0.00 %  | 0.00 % |
| System.Threading.Tasks.Tests                              | 76.92 % | 10.26 % | 11.54 % | 1.28 %  | 0.00 % |
| System.Threading.Tasks                                    | 83.24 % | 3.02 %  | 12.36 % | 1.37 %  | 0.00 % |
| System.Threading.Tests                                    | 83.21 % | 2.46 %  | 8.19 %  | 6.14 %  | 0.00 % |
| System.Xml.Linq                                           | 84.62 % | 3.44 %  | 5.67 %  | 6.28 %  | 0.00 % |
| System.Xml.Tests                                          | 93.08 % | 2.31 %  | 4.62 %  | 0.00 %  | 0.00 % |
| V8.Crypto                                                 | 84.62 % | 3.85 %  | 11.54 % | 0.00 %  | 0.00 % |
| V8.Richards                                               | 84.62 % | 3.85 %  | 11.54 % | 0.00 %  | 0.00 % |
| XmlDocumentTests.XmlDocumentTests                         | 82.05 % | 5.13 %  | 6.41 %  | 6.41 %  | 0.00 % |
| XmlDocumentTests.XmlNodeListTests                         | 90.38 % | 1.92 %  | 5.77 %  | 1.92 %  | 0.00 % |
| XmlDocumentTests.XmlNodeTests                             | 55.77 % | 0.00 %  | 0.00 %  | 44.23 % | 0.00 % |
| System.Drawing.Tests                                      | 90.59 % | 3.24 %  | 2.65 %  | 3.53 %  | 0.00 % |
| HardwareIntrinsics.RayTracer                              | 78.26 % | 8.70 %  | 8.70 %  | 4.35 %  | 0.00 % |

</details>

 **Big thanks to everyone involved!**

**Comment by danmoseley** [comment]
setting milestone 7, but if all the "investigating" issues have something tracking them (for 7 or later) or are determined not worth tracking, presumably we can close this.

**Comment by dakersnar** [comment]
Usually we close these once the next report gets released (which should be in the next couple days). Feel free to close it now if it makes things easier.

**Comment by danmoseley** [comment]
@dakersnar iff it tracks work necessary to ship .NET 7, it should stay open and in 7.0.0 milestone. If not, something else (eg Future or closed)

My assumption is that any work would already be tracked by individual issues linked above but that wasn't entirely clear.

**Comment by dakersnar** [comment]
Your assumption is correct. I think I'll move this to "Future" for now. Any individual issues within this report that *are* targeting 7.0 should already be individually marked as such.
