### ISSUE TITLE
Update msquic to 2.1.1

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75262]
New servicing release for msquic 2.1.1 - https://github.com/microsoft/msquic/releases/tag/v2.1.1
Contains:
- arm64 / arm32 Linux packaging support
- Creation of threads without affinization on error (https://github.com/microsoft/msquic/pull/3041) to unblock #74629

We need to:
- [ ] Update Docker images for testing (TODO: List all Docker images we need to change and the PRs)
    - [x] Debian 10 & 11 - x64 & arm64
        - [x] Docker images update - PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/685
        - [x] Helix consumption of updated Docker images - PR #75291
        - [x] Backport to 7.0 - PR #75479
    - [ ] Debian 10 & 11 - arm32
        - [x] Docker images update - PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/689
        - [ ] Helix consumption of updated Docker images
            - [ ] Test failures blocking - issue #75493 and #75471
        - [ ] Backport to 7.0 - TODO PR
    - [x] Ubuntu 18.04 & 22.04 - arm64 -- note: 22.04 does not support msquic (missing OpenSSL 1.1)
        - [x] Docker images update - PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/687
        - [x] Helix consumption of updated Docker images -  PR #75380
        - [x] Backport to 7.0 - PR #75479
    - [x] Fedora 34 & 36 - x64
        - [x] Docker images update - PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/688
        - [x] Helix consumption of updated Docker images - PR #75380
        - [x] Backport to 7.0 - PR #75479
     - [x] OpenSUSE 15 - x64
        - [x] Docker images update - PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/690
        - [x] Helix consumption of updated Docker images - PR #75534
        - [x] Backport to 7.0 - PR #75479
- [ ] Update Helix queues for testing
- [x] Update sources used for Windows runtime build
    - [x] PR #75287
    - [x] Backport to 7.0 - PR #75479

@wfurt is that all? I would like to document complete list of things that have to happen to consume new msquic release for future usage.

**Comment by wfurt** [comment]
Update for Windows
https://github.com/dotnet/runtime/pull/75287

**Comment by wfurt** [comment]
Ubuntu 18.04 and 22.04
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/687
(22 builds from sources as there is no OpenSSL 1.1)
Fedora
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/688

Debian Arm32
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/689

**Comment by rzikm** [comment]
Docker images currently in use on main (taken from https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/helix-queues-setup.yml). Checked items are tracked in the post above.

Arm32v7:
- [x] (Debian.10.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-20210304164340-6616c63
- [x] (Debian.11.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm32v7-20210304164347-5a7c380

Arm32v6:
- [ ] (Raspbian.10.Armv6.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:raspbian-10-helix-arm32v6-20211215185610-60748cc

Arm64v8:
- [x] (Debian.10.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm64v8-20220908131935-59ee6b3
- [x] (Debian.11.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm64v8-20220908131932-59ee6b3
- [x] (Ubuntu.1804.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220909180906-777c06f
- [x] (Ubuntu.2204.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-helix-arm64v8-20220909180915-6c91216

x64 musl:
- [ ] (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20220803180115-99b3286
  - missing MsQuic
- [ ] (Alpine.313.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-helix-amd64-20210910135845-8a6f4f3
  - missing MsQuic

x64:
- [ ] (Centos.7.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20220601183719-dde38af
  - incompatible OpenSSL (< 1.1)
- [x] (Debian.10.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20220908132009-59ee6b3
- [x] (Debian.11.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64-20220908132354-59ee6b3
- [x] (Fedora.34.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20220908220224-98605e8
- [ ] (Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620
- [x] (openSUSE.15.2.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-15.2-helix-amd64-20211018152525-9cc02fe
- [x] (Ubuntu.2204.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-helix-amd64-20220909180913-1b9461f

**Comment by rzikm** [comment]
@wfurt I noticed you updated the image for Fedora 36, but that image is not used (at least on main), should we add it?

**Comment by wfurt** [comment]
We will need to switch to msquic/main at some point during 8.0 development. One good way how to do that is do that on upgraded OS e.g. keep 34+2.1.1 as legacy and move `runtime/main` to `36+msquic/main`. That would give us most of the coverage IMHO.

**Comment by karelz** [comment]
Thanks @rzikm for the Docker image list!
Comments on missing images:

Image | Notes
-- |--
Raspbian.10.Armv6.Open | No officially supported by .NET 7.0, ok to skip for now
Alpine.314.Amd64.Open | Blocked on official msquic release for Alpine
Alpine.313.Amd64.Open | Blocked on official msquic release for Alpine
Centos.7.Amd64.Open | Not supported - the image does not have minimal OpenSSL 1.1.1 required for msquic
Mariner.1.0.Amd64.Open | Not officially supported by .NET 7.0, ok to skip for now

**Comment by wfurt** [comment]
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/692 for the Alpine. We can run 2.1.1 binaries we can build our ourselves. 
3.13 is end of support in November, we should kick it out and perhaps test on 3.16 as current latest stable release.

**Comment by karelz** [comment]
We are done here for 7.0 in dotnet/runtime repo. The 2 remaining work items for 7.0:
- Debian 10 & 11 - arm32 - Docker images need update (test-only change) - blocked by test failures - tracked by #75493 and #75471
- Update Helix queues - infra change, does not need PR in dotnet/runtime repo

**Comment by karelz** [comment]
Fixed in main (8.0) in PRs #75287, #75291, #75380 and #75534.
Fixed in 7.0 (RC2) in PR #75479
