### ISSUE TITLE
System.Reflection work planned for .NET 8

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#75358]
This issue captures the planned work for .NET 8. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.

### Function Pointers
- [x] [original issue]: [Representation of function pointer types in the reflection stack](https://github.com/dotnet/runtime/issues/11354)
- [x] [[API Proposal]: Reflection introspection support for FunctionPointer](https://github.com/dotnet/runtime/issues/69273)
- [ ] [[API Proposal]: Reflection invoke support for FunctionPointer](https://github.com/dotnet/runtime/issues/75347)
- [ ] [[API Proposal]: IL Emit support for FunctionPointer](https://github.com/dotnet/runtime/issues/75348)

### Invoke
- [prototype created] [User Story]: [Developers using reflection invoke should be able to use ref struct 
](https://github.com/dotnet/runtime/issues/45152)
- [prototype created] [[API Proposal]: byref parameter collection for invoke](https://github.com/dotnet/runtime/issues/75349)
- [prototype created] Support byref invoke for return parameter and target (plumbing; no public API changes)
- [prototype created] [[API Proposal] Add reflection support to byref-like types](https://github.com/dotnet/runtime/issues/10057)
- [ ] [Change IL Emit invoke path to use function pointers and OpCodes.Calli](https://github.com/dotnet/runtime/issues/75357)
- [ ] Support fast field get\set.

### Activator
- [ ] [API proposal: Activator.CreateFactory and ConstructorInfo.CreateDelegate](https://github.com/dotnet/runtime/issues/36194)
- [ ] [Have `ConstructorInfo` use `Activator.CreateInstance()` instead of emit for default constructors](https://github.com/dotnet/runtime/issues/78917)

## Misc backlog
The following are higher priority issues that are affecting the community and for the most part, do not include features or bugs that have reasonable workarounds.

- [ ] [Runtime: Support for reflection-invoking methods that take pointers by reference](https://github.com/dotnet/runtime/issues/10842)
- [ ] [FileNotFoundException resource files is slowing things down ridiculously](https://github.com/dotnet/runtime/issues/36053)

## Emit
- [partial implementation] [Support equivalent of AssemblyBuilder.Save to save in-memory IL to an assembly](https://github.com/dotnet/runtime/issues/62956)
- [x] [Add InstructionEncoder.Switch to enable emitting switch instructions with LabelHandles](https://github.com/dotnet/runtime/issues/40546)

**Comment by BreyerW** [comment]
Some links are broken like Support for generating IL Emit for field get\set and Support byref invoke for return parameter and target.

**Comment by steveharter** [comment]
Closing for v8; several were partially implemented or prototyped and the description was updated to reflection that.

A new issue will be created for v9,
