### ISSUE TITLE
[x86/Linux] CI support for build using docker

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/runtime#7538]
I hope to build x86/Linux in CI machine using docker. 

- build native code using x86 ubuntu docker container
- build managed code in x64 environment (cannot use dotnetcli in x86/linux)
- test using x86 ubuntu docker container

I succeeded building x86/Linux coreclr using this steps. (not test yet) If we use x86 docker images, the rootfs for x86 is needless.

To do this, we need x86 ubuntu docker image including packages to build and test. (maybe same packages for ubuntu-arm build). 

related issue: dotnet/runtime#7424 

CoreCLR
- [x] CI support: CoreCLR build (#10079)
- [ ] CI support: CoreCLR test 
- [ ] Use official docker image for CoreCLR build & test

CoreFX
- [x] CI support: CoreFX build (dotnet/corefx#17182)
- [ ] CI support: CoreFX test 
- [ ] Use official docker image for CoreFX build & test (dotnet/corefx#17601)
