### ISSUE TITLE
Performance profiling for WebAssembly

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#76316]
## Net 10 goals - single threaded Event Pipe and Diagnostic server
- [x] gc heap dump, counters, CPU sampling
- [x] implement single-threaded DS native code
    - [x] https://github.com/dotnet/runtime/pull/111910
- [x] single threaded managed `AggregationManager` and `EventPipeEventDispatcher`
    - [x] https://github.com/dotnet/runtime/pull/113524
- [x] implement single-threaded sample profiler (interp, AOT, jiterp)
    - [x] for browser dev tools https://github.com/dotnet/runtime/pull/112352
    - [x] for EP https://github.com/dotnet/runtime/pull/113758
- [x] implement JavaScript API for triggering trace
    - [x] https://github.com/dotnet/runtime/pull/112787
    - [x] https://github.com/dotnet/runtime/pull/110818
- [x] implement WebSocket transport for EP
- [x] Documentation https://github.com/dotnet/AspNetCore.Docs/issues/35230
- [x] trigger re-build with `<WasmPerfTracing />` change
- [x] fix timeouts in `ds-router` for WebSockets https://github.com/dotnet/diagnostics/pull/5121
- [ ] WBT and manual tests https://github.com/dotnet/runtime/issues/114232

## Net 10 nice to have
- [ ] include ds-router in the dev-server, so that the IPC channel is visible on the local machine
- [ ] explore how .nettrace output could be used for PGO AOT in Mono 
     - [x] https://github.com/dotnet/runtime/issues/69512
- [x] click thru symbols in the trace to C# code in VS
- [ ] [optimize](https://github.com/dotnet/runtime/pull/112352#discussion_r1969797447) sampling profiler
- [x] simplify browser `<WasmProfilers>browser</WasmProfilers>` and `config.browserProfilerOptions`
- [ ] `Timing-Allow-Origin` in the devtools

## Future goals
 - [ ] propagate from the WASM client to the server side open telemetry
 - [ ] integration with VS or VS code
 - [ ] make multi-threaded event pipe also work
 - [ ] annotate Mono AOT with event pipe events
     - [ ]  `FRAME_TYPE_IL_STATE`
 - [ ] annotate AOT/Interp transitions
 - [ ] annotate JS interop with event pipe events
 - [ ] use stats about Interp of runtime libraries to bring more intrinsic methods to Interp
 - [ ] propagate event pipe events as [performance.mark()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark) and [performance.measure()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure)
     - [ ] optional, configurable
     - [ ] [HTTP header Timing-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin)
 - [ ] propagate browser events as event pipe events
- [ ] Add a way for JavaScript to push events to EventSources.
- [ ] VS integration
- [ ] Refactor runtime startup to allow the diagnostic server to async pause the browser thread.

## Non-goals
- (debugging of) full memory dump - the layout of WASM linear memory is significantly different from other OSs. Also it doesn't capture WASM stack trace, just shadow stack. 
- DS/EP and Mono profilers at the same time
- Anything based on `DiagnosticCounter` like `RuntimeEventSource` and `CounterGroup`, keep `UnsupportedOSPlatform("browser")`

**Comment by mkArtakMSFT** [comment]
@lewing let's include this in an agenda for our weekly sync meetings. We'd like to have something for customers here in .NET 8.

**Comment by pavelsavara** [comment]
@SteveSandersonMS where do I find the old prototype ?

**Comment by SteveSandersonMS** [comment]
@pavelsavara I dug up some info in an old email thread and am forwarding it to you.

**Comment by pavelsavara** [comment]
Notes to self
https://github.com/dotnet/runtime/pull/70851

`dotnet-trace collect --providers Microsoft-Windows-DotNETRuntime:0x1F000080018:5`

https://github.com/dotnet/runtime/blob/fb104e374d89f3e005e6d67fc7766e824f88dd11/src/coreclr/vm/ClrEtwAll.man#L14-L92

**Comment by jjzhang12** [comment]
@pavelsavara : How can I enable the browserProfilerOptions of https://github.com/dotnet/runtime/pull/77449 in Blazor WebAssembly?

**Comment by jjzhang12** [comment]
@pavelsavara Thanks, I installed the latest .net 8 preview 7 and implemented the above change to the template sample app, I still see "wasm-functions[]" in performance profile. I tried debug, release, published and published with AOT, all same result.
I saw you are using rc version (8.0.0-rc.1.23402.3), how can I get that wasm-tools?

**Comment by pavelsavara** [comment]
>I still see "wasm-functions[]" in performance profile. 

Those are C symbols of the mono VM. You can enable them by 
`<WasmNativeDebugSymbols>true</WasmNativeDebugSymbols><WasmNativeStrip>false</WasmNativeStrip>`

Note that is being improved right now https://github.com/dotnet/runtime/pull/89754

> I saw you are using rc version (8.0.0-rc.1.23402.3), how can I get that wasm-tools?

Wait for next preview to be released or use nightly build https://aka.ms/dotnet/8.0.1xx/daily/dotnet-sdk-win-x64.zip

**Comment by ts-indikaf** [comment]
> @jjzhang12 with latest previews you can use new API `configureRuntime` which allows you to configure runtime. I tested with `8.0.0-rc.1.23402.3` wasm-tools workload installed.
> 
> In your project file `<WasmProfilers>browser;</WasmProfilers><WasmBuildNative>true</WasmBuildNative> ` And in your index.html
> 
> ```
> <script src="_framework/blazor.webassembly.js" autostart="false"></script>
> <script>
> Blazor.start({
>     configureRuntime: function (builder) {
>         builder.withConfig({
>             browserProfilerOptions: {}
>         });
>     }
> });
> </script>
> ```

@pavelsavara do we have a solution for pure WebAssembly projects?

**Comment by pavelsavara** [comment]
`<WasmProfilers>browser;</WasmProfilers><WasmBuildNative>true</WasmBuildNative> `

```js
import { dotnet } from './dotnet.js'
const runtime  = dotnet
        .withConfig({
            browserProfilerOptions: {}
        })
        .create()
;
```

**Comment by ts-indikaf** [comment]
@pavelsavara thanks - it works.

**Comment by jjzhang12** [comment]
@pavelsavara : I can profile my app in Preview 7. But for the same Blazor app in rc2, if I turn on those flags, the page goes out of memory quickly. I did look at the task bar and saw the Edge used more than 4GB memory before the page crashes. Without the profile flags, the memory is about 350MB.

I still can profile a simple app though.

Do we have option to reduce the memory consumption of this profile feature?

**Comment by pavelsavara** [comment]
This is logging, not sampling profiler and so it collects everything. (besides memory it also consumes CPU and affects timing).
I'm not aware of any recent changes to profiler which would cause more calls to be reported. 

Maybe some you have some build flags which make this to generate more methods or more calls in the profiled code ?

**Comment by ts-indikaf** [comment]
> @pavelsavara thanks - it works.

@pavelsavara Unfortunately, this only works with the sample DotNet project not with my real Wasm app. Chrome Profile loading goes forever with the real app. I'm using .DotNet8 RC1.

**Comment by MattParkerDev** [comment]
@pavelsavara How much effort is involved in adding method filtering to #77449?

**Comment by pavelsavara** [comment]
> @pavelsavara How much effort is involved in adding method filtering to #77449?

It would be good to filter in early on Mono side, probably here
https://github.com/dotnet/runtime/blob/f39dae85e28de85f87bb921a9e6a6581d531d293/src/mono/mono/profiler/browser.c#L70

Similar to https://github.com/dotnet/runtime/blob/f39dae85e28de85f87bb921a9e6a6581d531d293/src/mono/mono/profiler/log.c#L1974-L1976

And you need to pass the configuration flags
this is how other mono profilers do it
https://github.com/dotnet/runtime/blob/f39dae85e28de85f87bb921a9e6a6581d531d293/src/mono/mono/profiler/coverage.c#L1053

I'm not sure this is best way how to do it together with JavaScript. I would prefer to make it work with `browserProfilerOptions`

**Comment by ocoka** [comment]
Hello for community !

I am interested in profiling my project and have read the whole discussion, but I still don't understand clearly:
1. What exactly are the minimum parameters I need in a .csproj file ?
2. Can this be used with 'dotnet run' ?
3. Does there have to be a 'Release' configuration ?
4. and what is the purpose of the expression: " Blazor.start({
            configureRuntime: function (builder) {
                builder.withConfig({
                    browserProfilerOptions: {}
                });
            }
        });"

I tested the solution on .NET8, and with the .csproj configuration:
    <RunAOTCompilation>true</RunAOTCompilation>.
    <RunAOTCompilationAfterBuild>true</RunAOTCompilationAfterBuild>
    <WasmNativeStrip>false</WasmNativeStrip>
    <WasmProfilers>browser;</WasmProfilers>
    <WasmBuildNative>true</WasmBuildNative>

This does crash in Google Chrome with a SIGILL signal, but Firefox survives and profiling works. Maybe I don't need the whole list of above parameters anymore since I have .NET8 ?

**Comment by tibuprophen** [comment]
Hi! I am also having some trouble enabling profiling on WASM. May someone clear it up how to set up profiling properly? I achived chrome profiling on a fresh web project with changes @ocoka posted. Is there any option without AOT complilation and publishing the project?

**Comment by MikiraSora** [comment]
> Any news about this? AOT needs to be a release build only, making debugging annoying. What are exactly the combination of flags and code that you need to use for it to work on NET 9?
> 
> Edit : I partially made it work without AOT as [@pavelsavara](https://github.com/pavelsavara) recommended. Sadly in my Web App, is unusable. Memory usage goes up like crazy for no good reason and chrome crashes. Firefox can go up indefinitely until the app becomes so slow that it cant be of any usage anymore. In an attempt to find the culprit I tried to deactivate different plugins to see what happens, Serilog seems to be doing something, and Fluxor as well. Still not sure what they are doing that makes the app behave like that.

Same problem in my Avalonia browser.
![Image](https://github.com/user-attachments/assets/d898ae84-6774-41c6-9d07-508932e22dd9)
![Image](https://github.com/user-attachments/assets/823b02a5-8833-476f-b16d-844131a9c8fb)

**Comment by coder-johnz** [comment]
> Any news about this? AOT needs to be a release build only, making debugging annoying. What are exactly the combination of flags and code that you need to use for it to work on NET 9?
> 
> Edit : I partially made it work without AOT as [@pavelsavara](https://github.com/pavelsavara) recommended. Sadly in my Web App, is unusable. Memory usage goes up like crazy for no good reason and chrome crashes. Firefox can go up indefinitely until the app becomes so slow that it cant be of any usage anymore. In an attempt to find the culprit I tried to deactivate different plugins to see what happens, Serilog seems to be doing something, and Fluxor as well. Still not sure what they are doing that makes the app behave like that.

I have a Blazor Webassembly App that need Keep running in browser for a long time.
When I upgrade the App from .net8 to .net9, the browser memory usage increases from 200MB to nearly 1GB in 1 day, and up to nearly 2GB in 2days. I don't know why. So I let user to refresh the browser window when the App become slow.
When I downgrade the App to .net8, the browser memory usage only increases from 200MB to 300MB in 1 day.

**Comment by pavelsavara** [comment]
> Any news about this? Memory usage goes up like crazy for no good reason and chrome crashes.

Yes :) https://github.com/dotnet/runtime/pull/112352
I'm working on making the sampling profiler to actually take samples, rather than every single method enter/leave event.

@MikiraSora @EliseoDiegoViola could you please create repro project with Avalonia for me to try with new runtime bits ? Thanks.

> When I upgrade the App from .net8 to .net9, the browser memory usage increases from 200MB to nearly 1GB in 1 day, and up to nearly 2GB in 2days. 
> I don't know why the Blazor Webassembly App memory usage goes up so quickly in .net9, maybe is memory leak. 

This could be problems related to bad memory ratio and address space fragmentation in Net9. 
I think I fixed it here for Net10. https://github.com/dotnet/runtime/pull/108512

@coder-johnz Net10 Preview 1 would be out any day now. Please test it and let me know.
