### ISSUE TITLE
System.Text.Json work planned for .NET 8

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#77020]
**This issue captures the planned work for .NET 8. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

For .NET 8 we are prioritizing System.Text.Json work according to the following high-level themes:

1. **Developers should be able to use System.Text.Json in NativeAOT seamlessly**
2. **Source generator improvements**: improve performance, close functionality gaps with reflection-based implementation, fixing known bugs.
3. **Reliability**: developers should have a consistent experience when using System.Text.Json; minimize the number of high-impact bugs in the codebase.
4. **Extend contract customization capabilities**: provide more extensibility points to help users achieve more
5. **Extend custom converter capabiliies**: provide more capability for users to directly control reading and writing

## Planned for .NET 8

- [x] https://github.com/dotnet/runtime/issues/79122
- [x] https://github.com/dotnet/runtime/issues/77019
- [x] https://github.com/dotnet/runtime/issues/71967
- [x] **Performance (Enhancements, new perf-focused APIs)**
    - [ ] #65396
    - [x] https://github.com/dotnet/runtime/pull/78646
    - [x] https://github.com/dotnet/runtime/issues/68223
    - [x] https://github.com/dotnet/runtime/issues/69716
- [x] **Misc (New APIs etc.)**
    - [x] #37483
    - [x] https://github.com/dotnet/runtime/issues/72103
    - [x] https://github.com/dotnet/runtime/issues/54482
    - [x] https://github.com/dotnet/runtime/issues/782

### Not Planned for .NET 8

- [x] #63918
- [x] https://github.com/dotnet/runtime/issues/77018
- [x] https://github.com/dotnet/runtime/issues/77666

### Work done in previous releases
- [.NET 7](https://github.com/dotnet/runtime/issues/63762)
- [.NET 6](https://github.com/dotnet/runtime/issues/43620)
- [.NET 5](https://github.com/dotnet/runtime/issues/41313)

**Comment by stefan-schweiger** [comment]
Just to clarify, https://github.com/dotnet/runtime/issues/31068 is not going to happen for .NET 8? The issue is currently tagged for 8.0.0 milestone

**Comment by layomia** [comment]
> The issue is currently tagged for 8.0.0 milestone

@stefan-schweiger the issue is labeled as "future" (Did you mean to link to that issue?)


The [latest thought](https://github.com/dotnet/runtime/issues/31068#issuecomment-1178088836) is that the spec is not finished (the latest [Internet-Draft appears to be expired](https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html)) and we should wait for that to settle first.

**Comment by gregsdennis** [comment]
Hello. Just making myself available for support for JSON Schema and JSON Path.  I'm co-author on both specs, and I support both in my `json-everything` suite of libraries (backed by STJ).

JSON Schema is on a path toward a stable spec (i.e. one that doesn't have `draft` in the version), and JSON Path is nearing completion with the features in place and only language to tidy up.

**Comment by eiriktsarpalis** [comment]
Closing as completed. The outstanding issue is an analyzer that will be implemented after RC is done.
