### ISSUE TITLE
Improve JIT loop optimizations (.NET 8)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#77032]
As we did for [.NET 6](https://github.com/dotnet/runtime/issues/43549) and [.NET 7](https://github.com/dotnet/runtime/issues/55235), we plan to continue improving JIT optimization capabilities for loop code. An overview of many JIT optimization possibilities is [here](https://github.com/dotnet/runtime/issues/65342); this issue will focus on issues we choose to address in .NET 8.

### Multi-dimensional array improvements
- [x] https://github.com/dotnet/runtime/issues/71678

### Loop recognition and canonicalization
- [x] https://github.com/dotnet/runtime/issues/77033 Always create pre-headers
- [x] https://github.com/dotnet/runtime/issues/62665 Change loop cloning to work with pre-header blocks

### Loop cloning
- [ ] https://github.com/dotnet/runtime/issues/82946 Support loop cloning for Span

### Multi-dimensional array improvements
- https://github.com/dotnet/runtime/issues/71674
- https://github.com/dotnet/runtime/issues/71676

### Loop recognition and canonicalization
- https://github.com/dotnet/runtime/issues/43713 Describes two cases where loops are missed due to various issues.
  - https://github.com/dotnet/runtime/issues/58941 F# loops not recognized

### Loop cloning
- https://github.com/dotnet/runtime/issues/77071 Clone arrays with class member arrays.
- https://github.com/dotnet/runtime/issues/62615

**Comment by jakobbotsch** [comment]
@BruceForstall #9977 is a benchmark for the span loop cloning, so it might be appropriate to put it in .NET 8 milestone too as part of #82946.

**Comment by BruceForstall** [comment]
No more work is planned here for .NET 8. A new issue will be created for .NET 9 as appropriate.
