### ISSUE TITLE
Implement AVX-512 support

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#77034]
This issue will track work being done to support the AVX-512 ISA extensions in .NET.

A GitHub project also exists to do this tracking: https://github.com/orgs/dotnet/projects/157

GitHub query for all issues and pull requests tagged `arch-avx512`: https://github.com/dotnet/runtime/labels/arch-avx512

We will alter how we track this work based on experience with both mechanisms.

The following work is all planned for .NET 8. If we determine work will not make .NET 8, it will be noted.

## RyuJIT feature work

- [x] Implement AVX-512 state support in VM. https://github.com/dotnet/runtime/pull/74113
- [x] Implement EVEX encoding. https://github.com/dotnet/runtime/pull/75934 and related.
- [x] Add support for new AVX-512 vector registers https://github.com/dotnet/runtime/pull/79544
- [x] Enable 512-bit SIMD types in .NET Runtime and JIT.  
- [x] https://github.com/dotnet/runtime/issues/81847
- [x] Implement light-weight K register ExtractMostSignificantBits for Vector512. https://github.com/dotnet/runtime/issues/80820
- [x] https://github.com/dotnet/runtime/issues/80810. https://github.com/dotnet/runtime/pull/80960
- [x] Implement minimal Vector512 hardware accelerated lowering in the JIT. https://github.com/dotnet/runtime/issues/80811
- [x] Implement Vector512<T> API surface for Vector512 hardware acceleration. https://github.com/dotnet/runtime/issues/80814
- [x] Add opmask (k) registers to the register allocator. https://github.com/dotnet/runtime/issues/80823
- [x] Enable EVEX embedded broadcasting support in xarch emitter. https://github.com/dotnet/runtime/issues/80825
- [x] Add optimization for vector conversion of uint/ulong to float/double https://github.com/dotnet/runtime/issues/89277
- [x] Implement System.Runtime.Intrinsics.X86.Avx512F lowerings in JIT. https://github.com/dotnet/runtime/issues/80865
- [x] Implement System.Runtime.Intrinsics.X86.Avx512F.VL lowerings in JIT. https://github.com/dotnet/runtime/issues/80867
- [x] Implement System.Runtime.Intrinsics.X86.Avx512BW lowerings in JIT. https://github.com/dotnet/runtime/issues/80868
- [x] Implement System.Runtime.Intrinsics.X86.Avx512CD lowerings in JIT. https://github.com/dotnet/runtime/issues/80869
- [x] Implement System.Runtime.Intrinsics.X86.Avx512DQ lowerings in JIT. https://github.com/dotnet/runtime/issues/80870
- [x] Implement permanent solution to integrate simd64 type to VecCon node. https://github.com/dotnet/runtime/issues/82312
- [x] https://github.com/dotnet/runtime/pull/87083

## RyuJIT optimization work

- [x] https://github.com/dotnet/runtime/issues/83798
- [x] https://github.com/dotnet/runtime/issues/83946
- [x] https://github.com/dotnet/runtime/pull/84348
- [x] https://github.com/dotnet/runtime/pull/84854
- [x] https://github.com/dotnet/runtime/pull/84885
- [x] https://github.com/dotnet/runtime/pull/84821
- [x] https://github.com/dotnet/runtime/pull/84384

## CI/testing work

- [x] Enable CI testing on AVX-512 machines on Windows. https://github.com/dotnet/runtime/pull/77930
- [x] Enable CI testing on AVX-512 machines on Linux. https://github.com/dotnet/runtime/pull/79417
- [x] Create AVX-512 AzDO pipeline for testing with AVX-512 stress modes. https://github.com/dotnet/runtime/pull/77930
- [x] Enable performance lab AVX-512 testing
- [ ] ~Test performance in ASP.NET performance lab~

## VM work

- [x] https://github.com/dotnet/runtime/issues/81846
- [x] https://github.com/dotnet/runtime/issues/84087

## Debugging / diagnostics work

- [ ] https://github.com/dotnet/runtime/issues/87843
- [x] Ensure debugging works with AVX-512 types and intrinsics.

## Libraries work

- [x] Light up Span with Vector512 code paths. https://github.com/dotnet/runtime/issues/80824, https://github.com/dotnet/runtime/pull/86655
- [ ] Light up Ascii.Utility methods with Vector512 code paths. https://github.com/dotnet/runtime/issues/89280

## API design work

- [x] https://github.com/dotnet/runtime/issues/73262
- [x] https://github.com/dotnet/runtime/issues/73604
- [x] https://github.com/dotnet/runtime/issues/74813
- [x] (Will not implement) https://github.com/dotnet/runtime/issues/74613
- [x] https://github.com/dotnet/runtime/issues/76579

Note: all API implementation work that has been planned for .NET 8 has been completed. There are a few remaining "esoteric" APIs that still need to be completed, and that work has been moved to .NET 9. The linked issues will not be closed until the entire API surface area is complete, due to API design issue tracking rules.

## Related work

- https://github.com/dotnet/runtime/issues/75724
- https://github.com/dotnet/designs/pull/268

# Future work

The following work items for work that did not get implemented for .NET 8 will be considered for .NET 9.

## RyuJIT feature work

- [ ] Add EVEX encoding opmask (k) register masking for per-instruction opmask to xarch emitter. https://github.com/dotnet/runtime/issues/80821
- [ ] Enable EVEX embedded rounding support in xarch emitter.
- [ ] Add optimization for scalar/vector conversion of uint32/uint64 to/from packed float/double. https://github.com/dotnet/runtime/issues/80829
- [ ] https://github.com/dotnet/runtime/issues/85207

## RyuJIT optimization work

- [ ] AVX512: Fold some bitwise operations to vpternlogq https://github.com/dotnet/runtime/issues/84534
- [ ] Add optimization for scalar conversion of float/double to ulong https://github.com/dotnet/runtime/issues/89279

## Debugging / diagnostics work

- [ ] https://github.com/dotnet/runtime/issues/87854
- [ ] Ensure ELT (enter/leave/tailcall hooks, for profiling) works.

## Libraries work

- [ ] Light up Utf8/Utf16 code with Vector512. https://github.com/dotnet/runtime/issues/86119

## API design work

- [ ] https://github.com/dotnet/runtime/issues/73604
- [x] https://github.com/dotnet/runtime/issues/74813
- [ ] (Reconsider implementing?) https://github.com/dotnet/runtime/issues/74613
- [ ] https://github.com/dotnet/runtime/issues/76579

**Comment by hopperpl** [comment]
I'm rather interested to know what the conceptual idea will be to use the mask registers. 

Will it be just an intrinsic-approach? Or will there also be some logic built around?

I'm asking this as the mask registers k0-k7 are directly set into EVEX and there is no way to provide a constant. This would either mean we specifically use a register, like k3, and apply this to AVX512 instructions. Or, we request a k-register which is encapsulated in a helper-class which we then provide to AVX512 instructions. How will JIT ensure integrity thru sub-function calls?

**Comment by jakobbotsch** [comment]
@hopperpl You may be interested in reading https://github.com/dotnet/designs/pull/268.

**Comment by DeepakRajendrakumaran** [comment]
FYI -  https://github.com/dotnet/runtime/issues/80811 is also covered under https://github.com/dotnet/runtime/pull/80960
