### ISSUE TITLE
System.Collections work planned for .NET 8

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#77391]
**This issue captures the planned work for .NET 8. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

For .NET 8 we are prioritizing System.Collections work according to the following high-level themes:

1. **Add new APIs**: add new APIs that have high-impact, are perf oriented, and increase convenience
2. **Reliability**: minimize the number of high-impact bugs in the codebase
3. **Analyzers**: add new analyzers helping developers write more performant code

#### Novel or high-impact functionality

- [x] https://github.com/dotnet/runtime/issues/77209
- [x] https://github.com/dotnet/runtime/issues/67209
- [x] https://github.com/dotnet/runtime/issues/77891

#### Perf oriented

- [x] https://github.com/dotnet/runtime/issues/72999
- [x] https://github.com/dotnet/runtime/issues/55217
- [x] https://github.com/dotnet/runtime/issues/76028
- [x] https://github.com/dotnet/runtime/issues/75936

#### Convenience APIs

- [x] https://github.com/dotnet/runtime/issues/72625
- [x] https://github.com/dotnet/runtime/issues/75070
- [x] https://github.com/dotnet/runtime/issues/66773
- [x] https://github.com/dotnet/runtime/issues/1530 

### Analyzers

- [x] https://github.com/dotnet/runtime/issues/75933

### Quality/reliability fixes

- [x] https://github.com/dotnet/runtime/issues/77212
- [x] https://github.com/dotnet/runtime/issues/76116

### Work done in previous releases

- [.NET 7](https://github.com/dotnet/runtime/issues/64599)

---

#### Moved to Future

- https://github.com/dotnet/runtime/issues/18087

**Comment by krwq** [comment]
Yes, we started closing some user stories issues during our triage meeting and since there are only few things left it's easier to track them individually

**Comment by jeffhandley** [comment]
I'd like to leave this open. @ericstj and I use these meta issues for tracking:

* What we planned for the release
* What the progress is against the list
* How that changed throughout the release

@krwq From your comment, I infer that you and the rest of the @dotnet/area-system-collections crew has finished refining the backlog of issues in the 8.0.0 milestone and that you folks plan to track progress based on what's still open within the milestone; is that correct?

**Comment by krwq** [comment]
@jeffhandley yes, we've went through all 8.0 issues in our areas and will be tracking with 8.0 issues and triage board. We generally left 8.0 milestones on things we're actively/potentially work on (including any regressions etc.). For some "maybe"/"unsure" issues given number of issues we currently have we also moved them to Future under assumption if there is strong enough feedback they will show up on our triage board and we can reconsider them again.

On the way we've closed couple of issues like this one which on their own didn't describe the problem (except maybe title) but were tracking other issues and are not helping with any active/potential work in this release (since they will be outdated in next release).

I don't think anyone will have any strong objections to to keep this one open but having said that it's not super useful from our perspective given we can find even more up to date list with `milestone:8.0.0 label:area-System.Collections`.

**Comment by Daniel-Svensson** [comment]
Any chance of having #31001 (Have mutable collection interfaces implement read only interfaces) for NET8 ?

While it would probably require some additional work in the runtime and type loader to make an (internal) solution for the typeloader (diamond dependency problem) so that any default interface implementations on the collection types have a lower priority than normal, it would make the built in readonly interfaces a lot more useful

**Comment by eiriktsarpalis** [comment]
Closing as completed.
