### ISSUE TITLE
Host work in .NET 8

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#77456]
In .NET 8, we want to improve the hosting space in three main areas:

## User experience
.NET hosting is the entry point for both the end-user experience of running an application and the developer experience of building one. There is often a fair amount of overlap with SDK work.
- [ ] https://github.com/dotnet/runtime/issues/3828
- [x] https://github.com/dotnet/runtime/issues/77614
- [x] https://github.com/dotnet/runtime/issues/71284
- [x] https://github.com/dotnet/runtime/issues/71288

## Developer building blocks
This is functionality related to hosting a .NET runtime that enable developers to better integrate with the runtime. Pain points with custom hosting often revolve around interactions with assembly load contexts - building out this capability will alleviate this and help users move away from older / Windows-only platforms like .NET Framework and C++/CLI.
- [x] https://github.com/dotnet/runtime/issues/77458
- [x] https://github.com/dotnet/runtime/issues/77696
- [x] https://github.com/dotnet/runtime/issues/66013

## Fundamentals
Test infrastructure (steps towards https://github.com/dotnet/runtime/issues/77800)
- [x] https://github.com/dotnet/runtime/issues/77805
- [ ] https://github.com/dotnet/runtime/issues/77807

Single-file testing strategy
- [ ] https://github.com/dotnet/runtime/issues/80369
