### ISSUE TITLE
[Merge-on-Red] - Accurately log catastrophic test failures and freezes in source-gened test infrastructure

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#77735]
# Merge-on-Red Subproject

Tests should have failures logged in a format that Build Analysis can easily reasoned about and surfaced to the check tab.

## Goals

* Be able to identify and record catastrophic failures to Build Analysis:
  * Native Crashes
  * Hangs and Timeouts

## Work Items

* [x] Look into the other format (other than _trx_) used by `dotnet test` and understand how it works.
* [x] ~~A Yaml version was decided, so it has to be implemented in the test source generators.~~ Helix compatibility with older OS's would be broken by adding new stuff, so this work item was changed to a XML log fixer.
* [ ] Implement accordingly so the _Helix script_ can easily understand and surface it.
* [ ] Implement a _watchdog_ to be able to easily identify when a test has taken too long and/or frozen. Suggested ideas:
  ~~* [ ] Add it as a new feature in _corerun_: Create a new flag like `--timeout`. Have _corerun_ exit and report the failure if this value is exceeded.~~
  * [ ] Add it as a new mini-app: This mini-app will receive the test's corerun command, and the timeout value as parameters. It will spawn a separate process to run the test in, and monitor it itself. If it exceeds the time limit, then i
t will kill the process and report the failure accordingly.
