### ISSUE TITLE
Libraries work to support Cloud Native effort for .NET 8

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#78518]
# Summary

This issue is tracking a miscellaneous work item in the following areas:
- Cloud Native Theme
- Microsoft Extensions
- System.Diagnostics.Metrics
- Date and Time82844
- Globalization

This issue contains some items which overlap with 
- dotnet/runtime#77390 

## Cloud Native Theme
- [x] https://github.com/dotnet/runtime/issues/77404 (Extensions.Options)
- [x] https://github.com/dotnet/runtime/issues/84347 (Extensions.Options)
- [x] https://github.com/dotnet/runtime/issues/85475 (Extensions.Options)
- [x] https://github.com/dotnet/runtime/issues/87254 (Extensions.Logging)
- [x] https://github.com/dotnet/runtime/issues/86075 (Extensions.DependencyInjection)
- [x] https://github.com/dotnet/runtime/issues/64427 (Extensions.DependencyInjection)
- [x] https://github.com/dotnet/runtime/issues/77514 (System.Diagnostics)
- [x] https://github.com/dotnet/runtime/issues/84321 (System.Diagnostics)
- [x] https://github.com/dotnet/runtime/issues/36617 (System Time)
- [x] https://github.com/dotnet/runtime/issues/84945 (System Time)
- [x] https://github.com/dotnet/runtime/issues/85080 (System Time)
- [x] https://github.com/dotnet/runtime/issues/77402 (Data annotation)
- [x] https://github.com/dotnet/runtime/issues/78606 (Analyzer) (System.Globalization)
- [x] https://github.com/dotnet/runtime/issues/78607 (Analyzer) (System.Globalization)
- [x]  https://github.com/dotnet/runtime/issues/78392 (Analyzer) (System.Globalization)
- [x] https://github.com/dotnet/runtime/issues/78608 (Analyzer) (System.Globalization)
- [x] https://github.com/dotnet/runtime/issues/76279 (system.IO.Hashing)
- [x] https://github.com/dotnet/runtime/issues/76028 (system. Collections)
- [x] https://github.com/dotnet/runtime/issues/75948 (system.IO.Hashing)
- [x] https://github.com/dotnet/runtime/issues/75936 (system. Collections)
- [x] https://github.com/dotnet/runtime/issues/67209 (system. Collections)
- [x] https://github.com/dotnet/runtime/pull/76726 (System.Runtime)
- [x] https://github.com/dotnet/runtime/pull/76043 (system. Collections)
- [x] https://github.com/dotnet/runtime/issues/1530 (system. Collections)
- [x] https://github.com/dotnet/runtime/issues/75933 (Analyzer) (system. Collections)
- [x] https://github.com/dotnet/runtime/issues/76020 (System.Memory)
- [x] https://github.com/dotnet/runtime/issues/76186 (System.Memory)
- [x] https://github.com/dotnet/runtime/issues/76888 (System.Runtime)
- [x] https://github.com/dotnet/runtime/issues/77955 (System.Runtime)
- [x] https://github.com/dotnet/runtime/issues/50330 (System.Runtime)
- [x] https://github.com/dotnet/runtime/issues/84978 (System.NET)
- [x] https://github.com/dotnet/runtime/issues/79946 (System.NET)
- [x] https://github.com/dotnet/runtime/issues/84075 (Extensions.HttpClientFactory)
- [x] https://github.com/dotnet/runtime/issues/85840 (System.NET)

### Post .NET 8.0 
- [ ] https://github.com/dotnet/runtime/issues/77516 (System.Diagnostics)
- [ ] https://github.com/dotnet/runtime/issues/82465 (Extensions.Logging)
- [ ] https://github.com/dotnet/runtime/issues/84902  (Microsoft.Extensions.Logging)
- [ ] https://github.com/dotnet/runtime/issues/87250 (Extensions.Logging)
- [ ] https://github.com/dotnet/runtime/issues/81730 (Extensions.Logging)
- [ ] https://github.com/dotnet/runtime/issues/87253 (Extensions.Logging)
- [ ] https://github.com/dotnet/runtime/issues/84903 (System.Diagnostics) 
- [ ] https://github.com/dotnet/runtime/issues/84905 (System.Diagnostics) 
- [ ] https://github.com/dotnet/runtime/issues/84728 (System.NET)
- [ ] https://github.com/dotnet/runtime/issues/88383 (System.NET)
- [ ] https://github.com/dotnet/runtime/issues/88384 (System.NET)
- [ ] https://github.com/dotnet/runtime/issues/88460 (System.NET)
- [ ] https://github.com/dotnet/runtime/issues/77679 (System.Runtime)
- [ ] https://github.com/dotnet/runtime/issues/82526 (Data annotation)
- [ ] https://github.com/dotnet/runtime/issues/85116
- [ ] https://github.com/dotnet/runtime/issues/82844
- [ ] https://github.com/dotnet/runtime/issues/85684 (System.Diagnostics)
- [ ] https://github.com/dotnet/runtime/issues/78406 (Analyzer) (Microsoft.Extensions.Logging)
- [ ] https://github.com/dotnet/runtime/issues/86814 (System.Security)
- [ ] https://github.com/dotnet/runtime/issues/78402 (Analyzer) (Microsoft.Extensions.Logging)

## AOT
- [x] https://github.com/dotnet/runtime/issues/44493
- [x] https://github.com/dotnet/runtime/issues/81931
- [x] https://github.com/dotnet/runtime/issues/85486

## System.Diagnostics
- [x] https://github.com/dotnet/runtime/issues/77621

## Date/Time 
- [x] https://github.com/dotnet/runtime/issues/52081
- [x] https://github.com/dotnet/runtime/issues/24601

## Globalization
- [x] https://github.com/dotnet/runtime/issues/75711

**Comment by teo-tsirpanis** [comment]
What is R9?

**Comment by iSazonov** [comment]
Please add https://github.com/dotnet/runtime/issues/77945 for System.Diagnostics.

**Comment by tarekgh** [comment]
> Please add https://github.com/dotnet/runtime/issues/77945 for System.Diagnostics.

This issue is tracking a subset of work for .NET 8.0 and not the whole features. https://github.com/dotnet/runtime/issues/77945 is not part of this category and that is why we are not tracking it here.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/79122

**Comment by danmoseley** [comment]
@teo-tsirpanis R9 is an internal team. I see they've edited to use a generic term as it doesn't have public meaning.
