### ISSUE TITLE
System.Runtime.Intrinsics work planned for .NET 8

### ISSUE THREAD

**Issue by dakersnar** [dotnet/runtime#79005]
**This is a work in progress as we develop our .NET 8 plans. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

During .NET 8, we will be focusing on AVX-512, an effort that includes the addition of a new intrinsic type `Vector512` as well as `Vector<T>` improvements. Beyond that major theme, we will invest in quality, enhancements and new APIs. This is an ambitious set of work, so it's likely that several of the items below will be pushed out beyond .NET 8. It is also likely additional items will be added throughout the year.

### AVX-512
- [ ] https://github.com/dotnet/runtime/issues/63331
- [x] https://github.com/dotnet/runtime/issues/73262
- [ ] https://github.com/dotnet/runtime/issues/73604
- [x] https://github.com/dotnet/runtime/issues/74613
- [x] https://github.com/dotnet/runtime/issues/74813
- [ ] https://github.com/dotnet/runtime/issues/76244
- [ ] https://github.com/dotnet/runtime/issues/76579
- [x] https://github.com/dotnet/runtime/issues/76593

### Quality
- [ ] https://github.com/dotnet/runtime/issues/64409
- [ ] https://github.com/dotnet/runtime/issues/64451

### Enhancements / New APIs
- [ ] https://github.com/dotnet/runtime/issues/28711
- [ ] https://github.com/dotnet/runtime/issues/53730
- [x] https://github.com/dotnet/runtime/issues/75084

**Comment by tannergooding** [comment]
Closing as this was a meta issue.

The core work got completed. Various non-critical bits were pushed out or not worked on.
