### ISSUE TITLE
System.Buffers work planned for .NET 8

### ISSUE THREAD

**Issue by dakersnar** [dotnet/runtime#79006]
**This is a work in progress as we develop our .NET 8 plans. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
We are not planning many notable investments into the System.Buffers area in .NET 8. This list may be added to as the year progresses.

## Planned for .NET 8
- [x] https://github.com/dotnet/runtime/issues/73842
- [X] https://github.com/dotnet/runtime/issues/71068
- [ ] https://github.com/dotnet/runtime/issues/853
- [ ] https://github.com/dotnet/runtime/issues/75866

**Comment by tannergooding** [comment]
Closing as this was a meta issue.

The core work got completed. Various non-critical bits were pushed out or not worked on.
