### ISSUE TITLE
System.Runtime work planned for .NET 8

### ISSUE THREAD

**Issue by dakersnar** [dotnet/runtime#79053]
**This is a work in progress as we develop our .NET 8 plans. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
The `System.Runtime` area represents our primitive types and other fundamental APIs. During .NET 8, we will tentatively consider the following tasks.

### Enhancements / New APIs
- [x] https://github.com/dotnet/runtime/issues/78389
- [x] https://github.com/dotnet/runtime/issues/77955
- [x] https://github.com/dotnet/runtime/issues/77749
- [ ] https://github.com/dotnet/runtime/issues/77679
- [ ] https://github.com/dotnet/runtime/issues/76478
- [x] https://github.com/dotnet/runtime/issues/76186
- [x] https://github.com/dotnet/runtime/issues/59466
- [x] https://github.com/dotnet/runtime/issues/57881
- [x] https://github.com/dotnet/runtime/issues/77644
- [X] https://github.com/dotnet/runtime/issues/73583
- [x] https://github.com/dotnet/runtime/issues/68770
- [X] https://github.com/dotnet/runtime/issues/24460

### Analyzers
- [ ] https://github.com/dotnet/runtime/issues/78398
- [ ] https://github.com/dotnet/runtime/issues/71698
- [ ] https://github.com/dotnet/runtime/issues/68946
- [ ] https://github.com/dotnet/runtime/issues/64545
- [ ] https://github.com/dotnet/runtime/issues/64009
- [ ] https://github.com/dotnet/runtime/issues/54794
- [ ] https://github.com/dotnet/runtime/issues/47927
- [ ] https://github.com/dotnet/runtime/issues/50389
- [x] https://github.com/dotnet/runtime/issues/34514
- [x] https://github.com/dotnet/runtime/issues/33794
- [ ] https://github.com/dotnet/runtime/issues/33780
- [ ] https://github.com/dotnet/runtime/issues/77625

### Quality/Performance

- [x] https://github.com/dotnet/runtime/issues/76888
- [ ] https://github.com/dotnet/runtime/issues/76830
- [ ] https://github.com/dotnet/runtime/issues/76285
- [x] https://github.com/dotnet/runtime/issues/76157
- [x] https://github.com/dotnet/runtime/issues/50330
- [x] https://github.com/dotnet/runtime/issues/73540
- [x] https://github.com/dotnet/runtime/issues/58642

**Comment by tannergooding** [comment]
Closing as this was a meta issue.

The core work got completed. Various non-critical bits were pushed out or not worked on.
