### ISSUE TITLE
Developers should be able to use System.Text.Json in Native AOT seamlessly

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#79122]
[WIP] User story to track improved Native AOT support in System.Text.Json for .NET 8.0

**Work items**
- [x] https://github.com/dotnet/runtime/issues/77051
- [x] https://github.com/dotnet/runtime/issues/71933
- [x] https://github.com/dotnet/runtime/issues/80527
- [x] https://github.com/dotnet/runtime/issues/58770
- [x] https://github.com/dotnet/runtime/issues/83095
- [x] https://github.com/dotnet/runtime/issues/83280
- [x] https://github.com/dotnet/runtime/issues/82457
- [x] https://github.com/dotnet/runtime/issues/83279
- [x] https://github.com/dotnet/runtime/issues/77532
- [x] https://github.com/dotnet/runtime/issues/81269
  - [x] https://github.com/dotnet/runtime/issues/84260
- [x] https://github.com/dotnet/runtime/issues/79311
- [x] https://github.com/dotnet/runtime/issues/73431
- [x] https://github.com/dotnet/runtime/issues/77897
- [x] https://github.com/dotnet/runtime/issues/84015

**TBD**
- [ ] https://github.com/dotnet/runtime/issues/73124
- [ ] https://github.com/dotnet/runtime/issues/74492
- [ ] https://github.com/dotnet/runtime/issues/78029
