### ISSUE TITLE
Developers should not encounter property visibility issues when using STJ source generation

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#79161]
[WIP] User story to track the above title.

**Work items**

- [x] https://github.com/dotnet/runtime/issues/76919
- [x] https://github.com/dotnet/runtime/issues/66679
- [x] https://github.com/dotnet/runtime/issues/66003
- [x] https://github.com/dotnet/runtime/issues/77675

**Comment by layomia** [comment]
Closing for 8.0 since all the child items are marked future.

**Comment by eiriktsarpalis** [comment]
Let's keep this open since the property visibility bug in the source generator is high impact. Keeping the individual bug reports in future is fine.
