### ISSUE TITLE
Native AOT Diagnostics in .NET 8

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#79241]
Goal: Full Diagnostic Capability in NativeAOT Applications
- Logging
  - EventSource
    - Runtime library EventSource need to work
    - EventSource events can be read from Windows and Linux platforms
    - Create a plan for general EventSource to work (cut from .NET8). New APIs added in .NET8 to enable primitive payloads to be AOT compliant
  - DiagnosticSource can be used for in-proc logging (no serialization) and as out-proc (with serialization) via the EventSource bridge for Runtime libraries
  - ETW Events
    - GC, Contention, Exception, Heap Snapshot (cut from .NET8), Rundown (cut from .NET8)
- Diagnostic tool support
    - Following dotnet-* tools need to work
      - dotnet-trace, dotnet-counter, dotnet-monitor
- Open telemetry Plan
- Debugging support

Work that is needed in .NET 8 to make the above happen
- [ ] Port EventPipe to NativeAot (and make it possible to be used as an optional feature)
  - [x] https://github.com/dotnet/runtime/issues/83051
  - [x] Will allow Linux to read EventSource events
  - [x] Will allow Diagnostic tools to work seamlessly
  - [x] Bring up plan
    - [x] Use a tracing sample application (A dotnet-trace like client from [here](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/diagnostics-client-library.md#6-live-parsing-events-for-a-specified-period-of-time) and a target process like [here](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventsource-getting-started#log-an-event)) to bring up EventPipe in NativeAOT. Specifically, enable CollectTracing2 on the [IPC protocol](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#eventpipe-commands).
    - [x] EventPipe in NativeAOT works in both Linux and Windows
    - [x] Enable tracing via [environment variables](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe#trace-using-environment-variables)
    - [x] Use common container code from the EventPipe library
    - [x] Dotnet-* tools (trace, monitor and counter) work with NativeAOT applications. Enable other relevant [CommandSet](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#commands)
  - [ ] Measure perf
- [ ] EventSource & DiagnosticSource
  - [x] Work with runtime library owners to ensure that trimming does not break
  - [ ] Work on a plan for EventSource source generator for the long-term solution (In .NET 8, compiler warnings will show problems)
- [ ] ETW Events
  - [ ] Contention events (Issues #76754 and #75108 track this)
- [x] Debugging support
  - [x] Produce correct symbols https://github.com/dotnet/runtime/issues/72552
  - [x] https://github.com/dotnet/runtime/issues/83037

Potential other improvements:
- [ ] https://github.com/dotnet/runtime/issues/81415

**Comment by agocke** [comment]
Closing out, as work is done for .NET 8

**Comment by filipnavara** [comment]
> Heap Snapshot (cut from .NET8), Rundown (cut from .NET8)

Is there a new issue to follow for these?
