### ISSUE TITLE
[wasm][globalization][icu] Tracking issue for HybridGlobalization: Web API + ICU

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#79989]
The task is to remove as much data from ICU files as possible and exchange ICU4C functions that are using this data with platform native functions - in the case of WASM with Web API. Because we are not able to get rid of ICU datafile completely (some functionalities are not easily replaceable) we will keep loading `icudt.dat` in a reduced form. This mode will be called `HybridGlobalization` and will be by default switched off. User can switch it on by setting MsBuild's `<HybridGlobalization>` to true.
PoC branch is here: https://github.com/dotnet/runtime/compare/main...ilonatommy:runtime:icu-platform-native.

1) Removing `collations` for WASM
- [x] Prepare icudt_wasm.dat and corresponding sharded datafiles without collations/standard, enable setting HybridGlobalization and write WBT checking if the new file got loaded instead of the old one. https://github.com/dotnet/icu/pull/300 [ILONA]
- [x] Loading reduced ICU files to Blazor - [this unified the startup for Blazor](https://github.com/dotnet/aspnetcore/pull/45628), so we could implement HG for it as well.
- [x] Finish implementing `GlobalizationNative_ChangeCase` + optimize memory usage - do not create a new string for returning the value but pass the address of buffer reserved on C# size that will hold the result. [ILONA]
public API: `TextInfo.ToLower`, `TextInfo.ToUpper`, TextInfo.ToTitleCase`
- [x] Implement `GlobalizationNative_IndexOf` and `GlobalizationNative_LastIndexOf` - will not work for letters that consist of more than one grapheme, issue: https://github.com/tc39/ecma402/issues/506 [ILONA]
public API: `CompareInfo.IndexOf`, `String.IndexOf`, `MemoryExtensions.IndexOf`, `CompareInfo.LastIndexOf`, `String.LastIndexOf`, `MemoryExtensions.LastIndexOf`.
- [x] Implement `GlobalizationNative_StartsWith` and `GlobalizationNative_EndsWith` [ILONA]
public API: `CompareInfo.IsSuffix`, `String.EndsWidth`, `MemoryExtensions.EndsWith`, `CompareInfo.IsPrefix`, `String.StartsWidth`, `MemoryExtensions.StartsWith`.
- [x] Implement `GlobalizationNative_CompareString` (without `Ordinal` and `OrdinalIgnoreCase`, `IgnoreKanaType`, `IgnoreWidth`) [ILONA]
public API: `CompareInfo.Compare`, `String.Compare`
- [x] ~~Implement `IgnoreKanaType` and `IgnoreWidth` basing on `pal_collation.c` code [ILONA]~~
- [x] Investigate `Ordinal` and `OrdinalIgnoreCase`. [ILONA]
- [x] Throw PNSE on `GlobalizationNative_GetSortKey`
- [x] How much do we gain removing SortVersion? 32kB on uncompressed. Not worth it. ~~If much, throw PNSE on `GlobalizationNative_GetSortVersion`.~~
- [x] Document how to use the flag and what to expect when switching it on.
- [x] Coordinate flow of `HybridGlobalization`from Blazor. Changes in dotnet/sdk might be needed.

2) Removing `normalization` for WASM:
Removed from planned Hybrid features. Savings from normalization removal on WASM are ~60kB. The removal breaks public APIs: string.Normalize, string.IsNormalized, IdnMapping.GetAsciii, IdnMapping.GetUnicode. Normalize/IsNormalized were succesfully replaced in https://github.com/dotnet/runtime/pull/85510.
For GetAscii/GetUnicode replacement, Invariant implementation enhanced by normalization step was used, see branch https://github.com/ilonatommy/runtime/tree/idn-mapping. The mapping still lacked detection of disallowed/ignored/mapped characters and would need access to [MappingTables](https://www.unicode.org/Public/idna/13.0.0/IdnaMappingTable.txt) of the current Unicode version to e.g. detect incorrect inputs to throw. One Unicode version mapping table in plain text weights ~900kB. Even if we compressed it, we still would need to maintain it with every Unicode version. Development time spent on correct implementation and chances of real size reduction, taking into cosideration the need to keep the mapping tables, are too small to remove normalization data from ICU.
- [ ] ~~Update `icudt_wasm.dat` and corresponding sharded datafiles.~~
- [ ] ~~Implement Punycode, ~~might be using [this algorithm](www.npmjs.com/package/punycode)~~ using InvariantGlobalization algorithm + normalization function.~~
- [x] ~~Use normalization from the PoC branch.~~
- [ ] ~~Update documentations.~~

3) Investigate implications of removing further data batches, e.g. check the effect of removing all collations, `coll_ucadata`, `locales_tree` etc.
- [ ] Fix `no exception thrown` for `CultureInfoAll.LcidTest`, `CultureInfoAll.GetCultureTest`, `CultureInfoConstructor.Ctor_String` (now we support wider range of locales so we should not expect some of them throw as it was with standard ICU)

4) (optional) Enhancement of collations by manual workarounds:
- [x] Assess risks connected with manual workarounds.
- [ ] ~~Consider fixing some `IgnoreSymbols` by adding static data on JS side.~~
- [ ] ~~Consider shifting katakana/hiragana and high/low symbols, based on `pal_collation.c` code~~
- [x] Check if we can implement invariant SortKey functionality for [this scenario](https://github.com/dotnet/runtime/pull/84621#issuecomment-1504931845).
- [x] Refactoring according to suggestions: https://github.com/dotnet/runtime/pull/86895/files#r1222395670, https://github.com/dotnet/runtime/pull/86895/files#r1222406677 ...

5) (optional) Consider failing a build when HybridGlobalization function is not supported
- [ ] we are throwing PNSE when unsupported globalization functionality is used. Consider this idea: https://github.com/dotnet/runtime/pull/84249#discussion_r1158449084 to catch them already during the build time.

## Tracking issues:

https://github.com/dotnet/runtime/issues/101912
https://github.com/dotnet/runtime/issues/102305
https://github.com/dotnet/runtime/issues/102373
https://github.com/dotnet/runtime/issues/95921
https://github.com/dotnet/runtime/issues/95795
https://github.com/dotnet/runtime/issues/95623

**Comment by ilonatommy** [comment]
Closing, the planned work for `HybridGlobalization` was completed.
