### ISSUE TITLE
[iOS][globalization][icu] Tracking issue for HybridGlobalization: Native API + ICU

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/runtime#80689]
The task is to remove as much data from ICU files as possible and exchange ICU4C functions that are using this data with iOS native functions.
1. Implement `Locale` functions.

    - [x] GlobalizationNative_GetLocaleInfoString
    Implemented by [#81470](https://github.com/dotnet/runtime/pull/81470)
    - [x]  GlobalizationNative_GetLocaleInfoInt
    Implemented by #84417 
    
    - [x] GlobalizationNative_GetLocaleInfoGroupingSizesNative
    Implemented by #84417 
    
    - [x]  GlobalizationNative_GetLocaleTimeFormat
    Implemented by #84417 
                       
2. Implement `Collation` functions.
            
    - [x]      GlobalizationNative_CompareString
    Implemented by https://github.com/dotnet/runtime/pull/85965
    
    - [x]      GlobalizationNative_IndexOf
    Implemented by https://github.com/dotnet/runtime/issues/86699
    
    - [x]      GlobalizationNative_LastIndexOf
    Implemented by https://github.com/dotnet/runtime/issues/86699
    
    - [x]    GlobalizationNative_StartsWith
    Implemented by https://github.com/dotnet/runtime/issues/86699
            
    - [x]    GlobalizationNative_EndsWith
    Implemented by https://github.com/dotnet/runtime/issues/86699
            
    - [x]      GlobalizationNative_ChangeCase
                 https://github.com/dotnet/runtime/pull/87919
                 https://github.com/dotnet/runtime/issues/88180
    - [x]      GlobalizationNative_ChangeCaseInvariant
                 https://github.com/dotnet/runtime/pull/87919
                 https://github.com/dotnet/runtime/issues/88180

3. Implement `Normalization` functions 

      - [x] IsNormalized
             Implemented by https://github.com/dotnet/runtime/pull/90582
      - [x] NormalizeString
             Implemented by https://github.com/dotnet/runtime/pull/90582

5. Implement `calendar` functions 
      - [x]  GlobalizationNative_GetCalendarInfo 
              Implemented by https://github.com/dotnet/runtime/pull/90004

6. Implement `timezoneinfo` functions
     - [x]  GetTimeZoneDisplayName 
              Implemented by https://github.com/dotnet/runtime/pull/91458

7. Create new icu file for mobile, filtering out features that are implemented by native functions

    - [x] Filter out Locale related resources
       Implemented by https://github.com/dotnet/icu/pull/349
       Implemented by https://github.com/dotnet/icu/pull/372
    
    - [x] Filter out Collation related resources
       Implemented by https://github.com/dotnet/icu/pull/363
8. Add HybridGlobalization flag to sdks and load icudt_hybrid.dat file when hybrid mode is on

    - [x] Add HybridGlobalization flag to dotnet/sdk https://github.com/dotnet/sdk/pull/33669
    - [x] Add HybridGlobalization flag to xamarin/macios sdk https://github.com/xamarin/xamarin-macios/pull/18498
    - [x] Load icudt_hybrid.dat file when hybrid mode is on https://github.com/dotnet/runtime/pull/88041

9. Tasks opened during feature implemetations

    - [x] https://github.com/dotnet/runtime/issues/86636
    - [x] https://github.com/dotnet/runtime/issues/83514
    - [x] https://github.com/dotnet/runtime/issues/87767

        
Details to be added.

cc @SamMonoRT

**Comment by steveisok** [comment]
@mkhamoyan @filipnavara put together a good mapping that will likely get us a ways there.  

https://github.com/dotnet/designs/pull/225#discussion_r647668983

**Comment by mkhamoyan** [comment]
Closing this as all tickets mentioned are already implemented.
