### ISSUE TITLE
NativeAOT on iOS as an experimental feature in .NET8 

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#80905]
## Overview 

Supporting NativeAOT on iOS platforms as an experimental feature in .NET8 would enable our customers to try the NativeAOT toolchain and runtime with their iOS applications, in order to benefit from advantages mostly concentrated around application size savings and start-up performance. 
In .NET8 the default toolchain and runtime when targeting iOS platforms will remain to be Mono, while NativeAOT would become available as an option.

This issues tracks progress on the identified work required for enabling NativeAOT on iOS platforms. The work will be organised and tracked with GitHub issues which are prioritised by their importance below. Some of the listed items can be considered as user stories and will require further break-down of work, while the others are plain tasks.

### Priority 0

- [ ] Investigate limitations and document findings of enabling NativeAOT for MAUI iOS application 
- [ ] Enable building NativeAOT for iOS platforms 
- [ ] Support targeting iOS platforms with ILCompiler 
- [ ] Enable dotnet SDK to support targeting iOS with NativeAOT
- [ ] Enable AppleAppBuilder to bundle applications compiled with NativeAOT 
- [ ] HelloiOS sample for NativeAOT
- [ ] Introduce symbol stripping build task for HelloiOS sample 
- [ ] Include measuring HelloiOS application size without debug symbols
- [ ] Static registrar with NativeAOT design – discussion 
- [ ] Static registrar with NativeAOT implementation
- [ ] Enable start-up hooks to wrap managed entry points: https://github.com/dotnet/runtime/issues/77957
- [ ] Objective-C marshalling and GC support: https://github.com/dotnet/runtime/issues/77472
- [ ] Enable building/running dotnet/runtime libraries tests on a simulator and device with NativeAOT
- [ ] Support NativeAOT as a third runtime variant with Xamarin (managed-to-native bridge and build system)

### Priority 1

- [ ] UnmanagedCallersOnly functions should be exposed from referenced libraries with NativeAOT
- [ ] Marshalled delegates vs function pointers support with NativeAOT
- [ ] Trimming and extensions compatibility design – discussion 
- [ ] Trimming and extensions compatibility implementation
- [ ] Enable dotnet/runtime functional tests for iOS platforms to run with NativeAOT 
- [ ] Enable Xamarin iOS testing to run with NativeAOT 

### Priority 2

- [ ] Investigate debugging support with NativeAOT 
- [ ] Improve methodology for start-up profiling and measuring SOD for iOS platforms 
- [ ] Completely move from marshalled delegates to function pointers throughout the Microsoft.iOS library 
- [ ] App size-regression tracking for NativeAOT iOS
- [ ] App startup time tracking for NativeAOT iOS
- [ ] App build time tracking for NativeAOT iOS

---
/cc: @marek-safar @SamMonoRT @steveisok @lambdageek @rolfbjarne @kotlarmilos @akoeplinger

**Comment by AaronRobinsonMSFT** [comment]
We should also have a note/item around diagnostics and document what the user experience will be on iOS. I believe it would be rather different and having a comprehensive list would help users make informed decisions about using NativeAOT and what to expect post deployment.

**Comment by tommcdon** [comment]
Adding @thaystg @lateralusX.   It is my understanding that Mono uses an in-proc debugger model due to mobile diagnostics restrictions.

**Comment by filipnavara** [comment]
> We should also have a note/item around diagnostics and document what the user experience will be on iOS. I believe it would be rather different and having a comprehensive list would help users make informed decisions about using NativeAOT and what to expect post deployment.

FWIW debugging with lldb on-device is possible, so in that sense it's comparable to the current model of debugging NativeAOT on Linux/macOS.

**Comment by ivanpovazan** [comment]
@AaronRobinsonMSFT thank you for the suggestion. I have added it to the list.

**Comment by curia-damiano** [comment]
Does this feature mean that it will be possible to export a .NET class library as a native iOS library?

**Comment by ivanpovazan** [comment]
> Does this feature mean that it will be possible to export a .NET class library as a native iOS library?

Thank you for the question @curia-damiano. In theory that would work as well, however, our current focus with NativeAOT is supporting full iOS applications. 

Would you mind sharing what would be the use case that you have in mind for native iOS libraries?

**Comment by filipnavara** [comment]
> Would you mind sharing what would be the use case that you have in mind for native iOS libraries?

https://github.com/dotnet/runtime/issues/79377#issuecomment-1556873513

**Comment by curia-damiano** [comment]
Sorry @ivanpovazan, I missed your request for comments. Thank you @filipnavara for the link!

**Comment by vitek-karas** [comment]
Moving to 10 since all the remaining 9 tasks are documentation and are tracked by separate issues.

**Comment by AlexeiNaabal** [comment]
> > Does this feature mean that it will be possible to export a .NET class library as a native iOS library?
> 
> Thank you for the question @curia-damiano. In theory that would work as well, however, our current focus with NativeAOT is supporting full iOS applications.
> 
> Would you mind sharing what would be the use case that you have in mind for native iOS libraries?

Could you please provide more information? We are now testing publish managed class to native library, only find out we have to enable self-contained. Maybe the after-procedural (like library builder) is ready, but the publish itself is not? when we set `<NativeLib>Shared</NativeLib>`, the compiler force us to enable self-contained.

Background: We already setup an embed mono runtime, thus self-contained is not suitable for our need :) Recently we are experimenting if we can extract certain managed class as native library for the native host to invoke, to see if it can improve performance.

**Comment by pavelsavara** [comment]
> We are now testing publish managed class to native library, only find out we have to enable self-contained. 
> when we set `<NativeLib>Shared</NativeLib>`, the compiler force us to enable self-contained.

This touches on our rooting/trimming WASM use-case https://github.com/dotnet/runtime/issues/101434

**Comment by curia-damiano** [comment]
As I see that this issue is not closed yet, I would like to ask this:

- the Swift SDK for Application Insights has been deprected less than a couple of years ago
- with perfect timing, we retire App Center
- the idea would be to use the .NET SDK for Application Insights in a native iOS library developed in Swift, compiling the SDK to a native library (eventually adding some entry point methods).

Do you think that this is possible with .NET 8? And if not, will it be possible in .NET 9?

**Comment by lemonmojo** [comment]
@curia-damiano Sounds like the perfect use case for [Beyond.NET](https://github.com/royalapplications/beyondnet). That being said, I would obviously very much appreciate if that was built in to .NET.

**Comment by curia-damiano** [comment]
I was not aware of it, thank you very much @lemonmojo for telling me!

**Comment by ivanpovazan** [comment]
@AlexeiNaabal 

> Could you please provide more information @ivanpovazan? We are now testing publish managed class to native library, only find out we have to enable self-contained. Maybe the after-procedural (like library builder) is ready, but the publish itself is not? when we set <NativeLib>Shared</NativeLib>, the compiler force us to enable self-contained.

This is by design. Building a managed library into a shared native one embeds the runtime with it. 

> Background: We already setup an embed mono runtime, thus self-contained is not suitable for our need :) Recently we are experimenting if we can extract certain managed class as native library for the native host to invoke, to see if it can improve performance.

If I understand your setup correctly, you would have mono and NativeAOT runtime running in the same process, which is not a setup that is supported. 

---
@curia-damiano 

> - the idea would be to use the .NET SDK for Application Insights in a native iOS library developed in Swift, compiling the SDK to a native library (eventually adding some entry point methods).

> Do you think that this is possible with .NET 8? And if not, will it be possible in .NET 9?

/cc: @kotlarmilos ^
