### ISSUE TITLE
Mono AOT size savings in .NET 8

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#80938]
## Overview 

This issue tracks progress on goals for Mono AOT size savings planned in .NET 8. Outcome of this effort is to reduce disk size in apps that use Mono AOT engine in full-LLVM mode. The work will be organised and tracked with GitHub issues. Some of the listed items can be considered as user stories and will require further break-down of work, while the others are plain tasks. 

## Tasks

- [ ] Trim inflated gshared methods in Vector/Scalar classes when SIMD is enabled
- [ ] Optimizing generics by using ILCompiler dependency graph and profile guided optimization
- [ ] Deduplication of symbols by using dedup/linkonce features
- [ ] Mono AOT full program analyses and interprocedural optimizations
- [ ] Enhance IL stripping in MAUI android apps

/cc: @fanyang-mono @jandupej @ivanpovazan @LeVladIonescu @lambdageek @vargaz @SamMonoRT @marek-safar

**Comment by ivanpovazan** [comment]
@kotlarmilos I have update the description and included the discussed sub tasks under the `Experimental optimizations`
