### ISSUE TITLE
Introduce symbol stripping build task for HelloiOS sample app

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#80977]
## Description

When building HelloiOS application the process uses dotnet SDK and local build tasks (mainly developed for testing purposes) which do not fully prepare the application for deployment. For example, when deploying an iOS application, debug symbols need to be extracted into a separate dSYM folder/file, then stripped away from the main binary, after which the binary needs to be resigned.

In the build process, the `-S` parameter only strips out debug information and not the symbol table. If `strip` is called without parameters, it further brings down the size on disk, but the app fails at the runtime. To fix this it is required to collect all the symbols needed during runtime and passing them to the strip tool via `-i -s <symbols_to_keep>`.

## Tasks

- [ ] Update build task in HelloiOS app to collect all symbols needed during runtime
- [ ] Update build task in HelloiOS app to strip symbols by using `-i -s <symbols_to_keep>`
- [ ] Preserve debug symbols by extracting them from the binary with dsymutil 
- [ ] Test and integrate the update into the perf dashboard

**Comment by kotlarmilos** [comment]
I tried to invoke `strip $(AppBundlePath)/$(AppName)` without any parameters and I am able to run the application on device and a simulator. I might be doing something wrong.

> Additionally, we might want to preserve debug symbols by extracting them from the binary with `dsymutil` to be made available for later resymbolication.

It make sense to have it aligned with Xamarin build. I will add it to the list of tasks.
