### ISSUE TITLE
[wasi] Tracking issue for test failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#82561]
Test PR: https://github.com/dotnet/runtime/pull/81649

## Issues in library tests found in #81649:

| Issue | Affected libraries| Log |
| --- | --- | -- |
| `System.IO.MemoryMappedFiles is not supported on this platform.` | System.Reflection.MetadataLoadContext.Tests | |
| `System.PlatformNotSupportedException : System.Security.Cryptography is not supported on this platform.` | ~~System.Formats.Asn1.Tests~~, System.Formats.Cbor.Tests |
| `cant resolve internal call to "System.Threading.ThreadPool::QueueCallback" (tested without signature also)`, and `System.Threading.TimerQueue::SetTimeout` | System.Linq.Tests, System.Text.Json.Tests, System.Transactions.Locals.Tests, System.IO.Tests  'n others |
| threading failures | * |
| Console pal not supported | System.Console.Tests |
| test data files not deployed (assigned: AJ) - https://github.com/dotnet/runtime/pull/82966 | System.Data.DataSetExtensions.Tests, System.IO.Packaging.Tests, System.IO.Packaging.Tests, System.Runtime.Serialization.Xml.Tests, System.Runtime.Serialization.Xml.ReflectionOnly.Tests |
| `mkstemp*`, `mkdtemp` missing | `Microsoft.Extensions.Configuration.Functional.Tests`,  |
| `DOTNET_USER_SECRETS_FALLBACK_DIR` not available, and cannot determine one of the special folders | Microsoft.Extensions.Configuration.UserSecrets.Tests | 

## Others

- [x] https://github.com/dotnet/runtime/issues/82515
- [x] https://github.com/dotnet/runtime/issues/81911
- [x] https://github.com/dotnet/runtime/issues/81736
- [x] https://github.com/dotnet/runtime/issues/82043
- [ ] Networking tests disabled
- [ ] Missing wasi-crypto (see https://github.com/WebAssembly/WASI-crypto)

## Fixes
- [ ] https://github.com/dotnet/runtime/pull/82966

cc @lewing @pavelsavara @maraf @ilonatommy @thaystg @vargaz @kg @lambdageek

**Comment by pavelsavara** [comment]
Thanks!
QueueCallback/SetTimeout is something we should solve soon.

**Comment by ilonatommy** [comment]
Closing, leaving `Enable wasi tests` opened to track the progress
