### ISSUE TITLE
Enable deduplication of generics in Xamarin.iOS build

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#83193]
## Description

This issue tracks progress on updating the `Xamarin.iOS` build to support deduplication of generics in the native code during AOT compilation. When Mono AOT compiler encounters a generic instance that is not handled by generic sharing, it will emit a code for the instance. If the same instance is encountered during AOT compilation in multiple assemblies, the code will be emitted multiple times, increasing code size.

## Tasks

 - [x] Generate an empty assembly prior `_AOTCompile` target
 - [x] Update `Xamarin.iOS` build to pass `dedup-skip` to AOT compiler
 - [x] Update `Xamarin.iOS` build to pass the generated assembly along with other assemblies with `dedup-include` to AOT compiler
 - [x] Test the update on MySingleView and MonoTouch tests

Related issues are https://github.com/dotnet/runtime/issues/80419 and https://github.com/mono/mono/issues/6965.
