### ISSUE TITLE
[mono][tests] Enhance iOS runtime tests coverage

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#84254]
## Description

This issue aims to expand the coverage of iOS runtime tests and improve the build process.

### Expand runtime tests coverage on iOS

Currently, only `tracing/eventpipe` is running on iOS/iOSSimulator using interpreter as a fallback. This issue aims to expand the coverage of iOS runtime tests by including other testing groups and enabling full AOT compilation.

### Parallel AOT compilation

To improve build time, the AOT compilation could be moved to Helix and executed simultaneously before the test execution. Additionally, unifying AOT compilation in one target would improve code maintenance as several targets use `MonoAOTCompiler` and `AppleAppBuilderTask` tasks.

### Split build and test execution

To mitigate various transient issues, build and test execution could be divided into separate steps. The test build should build the repository, create tests, and zip artifacts (as done in `build-test-job.yml`). The test execution should download the artifacts, unzip them, and send the tests to Helix for AOT compilation and execution (as done in `run-test-job.yml`).

## Tasks

- [ ] Identify other testing groups that could be executed on iOS/iOSSimulator and enable full AOT compilation for iOS/iOSSimulator tests
  - [ ] `baseservices`
  - [ ] `JIT`
  - [ ] `GC`
  - [ ] `ilverify`
  - [ ] `Interop`
  - [ ] `Loader`
  - [ ] `tracing`
- [ ] Move AOT compilation to Helix and execute it in parallel with test execution
- [ ] Unify AOT compilation to improve code maintenance
- [ ] Separate build and test execution into separate builds

**Comment by kotlarmilos** [comment]
> To mitigate various transient issues, build and test execution could be divided into separate steps. The test build should build the runtime and tests, and zip artifacts. The test execution should download the artifacts, unzip them, and send the tests to Helix for AOT compilation and execution. Additionally, a single build could be shared across runtime, library, and functional tests.

@steveisok I think you mentioned once this may not be a good approach. My assumption is that it may reduce costs and development time in cases when transient issues occur. What could be the potential downsides of such an approach? Are there some bottlenecks?
