### ISSUE TITLE
[API Proposal]: Introduce an intrinsic for more efficient lambda generation

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#85014]
### Background and motivation

Roslyn currently caches lambda delegates in static mutable fields in nested classes and initializes them lazily at the use site (guarded by a null check).
This pattern is inefficient for current runtimes, being hard to detect and optimize correctly, leading to dead code being left in generated assembly and making optimizations like delegate inlining more tricky.
Discussion [here](https://github.com/dotnet/csharplang/discussions/6746#discussioncomment-5567157) ended up with two possible solutions: creating a runtime intrinsic that'd create and cache the delegate for Roslyn or caching the delegates in `static readonly` fields which CoreCLR and Native AOT can analyze easily even today but that'd come with some metadata cost.

cc @jkotas @EgorBo @jaredpar @CyrusNajmabadi 

### API Proposal

From @jkotas in https://github.com/dotnet/csharplang/discussions/6746#discussioncomment-5587815:
```csharp
public class RuntimeHelpers
{
    [Intrinsic]
    // ldftn instruction must immediately precede call of this method. The target method must
    // match the delegate signature and it must be an instance method on the TScope reference. TScope should
    // have no instance fields. Given function pointer can be only mapped to one delegate type using this method.
    static TDelegate GetLambdaSingleton<TScope, TDelegate>(IntPtr ftn) where TScope: class, new(), TDelegate: delegate
    {
        // This is mock implementation. This method is always going to be expanded as JIT intrinsic.
        lock (s_table)
        {
            MethodInfo mi = MapEntryPointToMethodInfo(typeof(TScope), ftn);

            if (s_table.TryGetValue(mi, out Delegate del))
                return (TDelegate)del;

            Delegate ret = typeof(TScope).IsCollectible ? 
                 InternalCreateDelegate(typeof(TDelegate), new TScope(), ftn) :
                 InternalCreateFrozenDelegate(typeof(TDelegate), new-frozen TScope(), ftn);
            s_table.Add(mi, ret);
            return (TDelegate)ret;
        }
    }

    static readonly ConditionalWeakTable<MethodInfo, Delegate> s_table;
}
```

### API Usage

This would be used internally by Roslyn when emitting lambdas.

### Alternative Designs

Have Roslyn store delegates in `static readonly` fields - would work with CoreCLR and Native AOT, not require any runtime changes, but it'd introduce either more metadata bloat or more eager delegate object allocation (we'd either need a separate nested class per lambda or calling one lambda would then create delegates for all the lambdas in the nested class).

### Risks

All runtimes including Mono would need to have this implemented.

----

## Tasks:
- [ ] Refactor delegates to be immutable (see below)
- [ ] Build a functional-enough prototype
- [ ] Submit an API proposal for review, incorporating learnings from the prototype

**Comment by jaredpar** [comment]
> static TDelegate GetLambdaSingleton<TScope, TDelegate>(IntPtr ftn) where TScope: class,

Needs to include the `new()` constraint.

**Comment by jaredpar** [comment]
This will require a bit of refactoring on Roslyn's part. Today our emit strategy puts all lambdas for a given closure into the same type. That means it mixes capturing and non-capturing lambdas. In order to meet the constraints of this API we'll need to break up our closures such that non-capturing lambdas are never mixed with capturing ones. 

I _think_ this can be done by having a single closure per method for all of our non-capturing lambdas vs. having up to two per scope. Hopefully that is a bit cheaper given our implementation.

**Comment by EgorBo** [comment]
> Have Roslyn store delegates in static readonly fields - would work with CoreCLR and Native AOT, not require any runtime changes

The plan is to allocate them on a frozen (nongc) segment which is not support for `static readonly` in JIT today (but it can be done, just wanted to point out that there will be some runtime(jit) work any way).

**Comment by MichalPetryka** [comment]
> Today our emit strategy puts all lambdas for a given scope into the same closure type.

[It doesn't](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ6fYxjkuSqQCowDOALjgAUASlIBeAHykAYhAhDRE6awCcQgEQALGABtdEDSJEBuZg3Pk2Hbn35YlU2fMVinazQHdougCZHTRiYCIMtWdgxOOQVWLFIAQzB+AEsIADsRSzoQxgBfQlygA), it emits a type for all methods from the type.

**Comment by jaredpar** [comment]
> [It doesn't](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ6fYxjkuSqQCowDOALjgAUASlIBeAHykAYhAhDRE6awCcQgEQALGABtdEDSJEBuZg3Pk2Hbn35YlU2fMVinazQHdougCZHTRiYCIMtWdgxOOQVWLFIAQzB+AEsIADsRSzoQxgBfQlygA), it emits a type for all methods from the type.

My bad. It does look like we implemented that optimization already. I thought we had a number of cases where we still combined them with the capturing lambdas but does not appear so.

**Comment by MichalPetryka** [comment]
This should also be used for creation of delegates from method groups.

**Comment by MichalPetryka** [comment]
@jkotas @EgorBo While working on #85349, I've accidentally made delegate creation be regarded as slightly cheaper for the inliner, which triggers huge diffs for all the lambdas with the mostly dead initialization branch. This means that changing this will also trigger huge diffs due to removal of that branch.

**Comment by tannergooding** [comment]
I'll leave this open for the time being, but until I get the green light from Jan and Jared, this will remain an `api-suggestion`.

**Comment by jkotas** [comment]
In order to be able to allocate delegates as frozen heap, they must be immutable, or more precisely they cannot point to objects that are not allocated on frozen heap.

The delegates are not immutable in CoreCLR today. They contain cached MethodInfo that is initialized lazily: https://github.com/dotnet/runtime/blob/b2edecd5b2c521f2a098940efee324460a79057d/src/coreclr/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs#L159-L207 . So the first step is to figure out what to do about this cache. Is it possible to get rid of it and make delegate objects smaller? It should be fine to make Delegate.Method property slower if it makes Delegate objects smaller.

**Comment by MichalPetryka** [comment]
Could the cache maybe use `RuntimeMethodHandle.Value` instead?

**Comment by jkotas** [comment]
> Could the cache maybe use RuntimeMethodHandle.Value instead? Then the field will just be an IntPtr.

If we are not going to store MethodInfo directly in the delegate, there needs to be a lookup or mapping operation involved. If we are going to pay for a mapping or lookup operation, we can as well get rid of the field and use the existing fields or the delegate instance as the key for the lookup (notice that the existing implementation is able to compute the MethodInfo from existing fields). Some options:

- Cache it using the method pointer as the key. Skip caching for collectible assemblies.
- Cache it in `ConditionalWeakTable` using delegate instance as the key.
- Do not cache it at all. Declare `Delegate.Method` to be a slow operation.
 
None that the field is overloaded for other purposes, but those other purposes do not look that hard to refactor away.

**Comment by MichalPetryka** [comment]
> * Cache it in `ConditionalWeakTable` using delegate instance as the key.

Would the object that keeps the assembly alive for collectible assemblies also be moved there to keep them alive?

**Comment by EgorBo** [comment]
> > * Cache it in `ConditionalWeakTable` using delegate instance as the key.
> 
> Would the object that keeps the assembly alive for collectible assemblies also be moved there to keep them alive?

delegates from collectible assemblies won't be allocated on frozen segments anyway

**Comment by jkotas** [comment]
> Would the object that keeps the assembly alive for collectible assemblies also be moved there to keep them alive?

It should be possible to store the object reference that keeps collectible assemblies alive in `_invocationList` field.

**Comment by jkotas** [comment]
> Would something similar to [JEP 502: Stable Values (Preview)](https://openjdk.org/jeps/502) be the perfect candidate here

The existing beforefieldinit static constructors in .NET are very similar. Roslyn does not use beforefieldinit static constructors for lambdas today since it would require creating a type per lambda that is believed to have too expensive startup cost.

One challenge that this proposal needs to address is that the new scheme to represent the lambdas at runtime has lower (or at least same) startup cost compared to what we have today.

**Comment by aromaa** [comment]
> since it would require creating a type per lambda that is believed to have too expensive startup cost.

The `StableValue<T>` would solve this, right? It does not require locking, no tiered compilation and has no inherit type system requirements. You wouldn't need to define extra types and the cost is only paid after accessing each field.

> the new scheme to represent the lambdas at runtime has lower (or at least same) startup cost

Is there something that would make `StableValue<T>` more expensive than the proposed `GetLambdaSingleton` intrinsic?

**Comment by EgorBo** [comment]
> > The StableValue would solve this, right?
> 
> I am not able to tell from what your snippet how it would work. What's the IL and metadata generated by C# compiler for `public static readonly StableValue<Action> Action = new(() => Console.WriteLine("Hello World!"));`? What happens exactly when the runtime sees such IL and metadata?

@jkotas My understanding that Roslyn shouldn't generate its cache boilerplate for this specific lambda inside StableValue and just emit `new Action(anonymous_func)`.
JIT/Runtime should learn about StableValue that if some special field/sentinel object is set - the value (despite looking like it can be muted) is finalized.

I am not sure it's easier or not than an Intrinsic for Lambda, though. Feels fragile + overhead from the extra field (and CAS initialization)

**Comment by MichalPetryka** [comment]
> > Would there be a need for an instance at all? Since `TScope` is supposed to have no instance fields and no side effects from the constructor and the lambda should not (has no need to) access anything else through `this`, we could just leave `Delegate._target` as `null`. The method would still have to be an instance method, but would receive a null instance. Assuming `TScope` isn't needed for the method lookup, this API could be just:
> 
> We'll still need to access `this` if the ftn is on a generic type. The generic context for instance methods is acquired through `this` in shared generic code.
> 
> // This works
> typeof(Test).GetMethod(nameof(Test.SayHello)).CreateDelegate<Action<Test>>()(null);
> 
> // This throws. It will work if you remove the `typeof(T)` part
> typeof(Test<object>).GetMethod(nameof(Test<object>.SayHello)).CreateDelegate<Action<Test<object>>>()(null);
> 
> class Test
> {
>     public void SayHello() => Console.WriteLine("Hello");
> }
> 
> class Test<T>
> {
>     public void SayHello() => Console.WriteLine($"Hello {typeof(T)}");
> }


AFAIR we can just require Roslyn to not use those, since I'm not aware of any case where having the method generic instead wouldn't work.

**Comment by jkotas** [comment]
> For delegates to instance methods on generic types, the runtime would be required to create an instance instead. Such support would make the implementation relatively more complicated, as such it's not decided yet whether the API should work then or throw.

We should shoot for a design that works for generics too. We do not want generics to have a perf cliff.

> The API can't always return the same instance due to not being able to always expand as intrinsic for shared generics

Where is the problem with guaranteeing the same instance for generics? I do not see why it is hard to guarantee that.

**Comment by MichalPetryka** [comment]
> Where is the problem with guaranteeing the same instance for generics? I do not see why it is hard to guarantee that.

I've discussed it on the DNE discord with C# folks before, the issue is only hard to solve on NAOT cuz merging instances from compile and runtime paths is hard.
Code that hits this would for example be:
```cs
public static class C
{
  public static T A<T>(T t) => t;

  [MethodImpl(MethodImplOptions.AggressiveInlining)]
  public static Func<T, T> Create<T>() => A;

  [MethodImpl(MethodImplOptions.NoInlining)]
  public static Func<string, string> CompileTime() => Create<string>();
  [MethodImpl(MethodImplOptions.NoInlining)]
  public static Func<T, T> Runtime<T>() => Create<T>();
}
```
`CompileTime` would return a different instance from `Runtime`, even for `Runtime<string>()` cuz we can't map back to the compile time instance.
Supporting this would require adding some internal way of getting all frozen objects made during compile in NAOT.
Additionally, handling instance methods on generic types requires the same support too.
cc @MichalStrehovsky on how possible would that be.

> We should shoot for a design that works for generics too. We do not want generics to have a perf cliff.

Well both solutions have different perf drawbacks:
- Generic on type (not supported today) requires an object instance - which is more memory overhead - and fetches the generic context from the object which AFAIR is slower than from hidden arg.
- Generic on method uses a hidden arg which is faster but for indirect calls like here requires an instantiation stub so calling itself becomes slower.

I do think it'd be better to handle both, it's just gonna be "more work" to do so cuz of the need for separate instance objects.

**Comment by jkotas** [comment]
> and fetches the generic context from the object which AFAIR is slower than from hidden arg

Yes, it is an extra direction. You can do a lot of extra indirections for the cost of a call (instantiating stub). I think fetching the generic context from the object is a better perf tradeoff, and it matches what Roslyn does today.

**Comment by jkotas** [comment]
The most recent update of the proposal from https://github.com/dotnet/runtime/pull/125901:

> `public static Delegate GetDelegate(nint method, ref Delegate? storage)`

- The API is expected to be always called in a sequence "ldftn + ldsflda + call GetDelegate" and it is expected to be always expanded as intrinsic by the codegen.
- The static field is there to simplify runtime implementation and diagnostics/funceval. The static field can be inspected as any other field.
- The API signature is non-generic to minimize binary footprint. The field is expected be of the actual delegate type, and the return value from the API can be assumed to have the actual delegate type (no explicit cast for actual delegate type required at the callsite)

@michalstrehovsky @davidwrighton What do you think about this design?

This design minimizes binary footprint and startup costs (some numbers https://github.com/dotnet/runtime/pull/125901#issuecomment-4654411729 ). The question on my mind is whether it is worth it, or whether it would be better to give up some of the perf and go with more pure and general purpose design (e.g. a type with a single readonly field and a static constructor that is marked as side-effect free).

**Comment by KalleOlaviNiemitalo** [comment]
> The field is expected be of the actual delegate type, and the return value from the API can be assumed to have the actual delegate type (no explicit cast for actual delegate type required at the callsite)

That seems to require special-casing the intrinsic in ILVerify too.

**Comment by MichalPetryka** [comment]
> > The field is expected be of the actual delegate type, and the return value from the API can be assumed to have the actual delegate type (no explicit cast for actual delegate type required at the callsite)
> 
> That seems to require special-casing the intrinsic in ILVerify too.

I assume that's one of the smallest complications here.

**Comment by MichalStrehovsky** [comment]
> This design minimizes binary footprint and startup costs (some numbers [#125901 (comment)](https://github.com/dotnet/runtime/pull/125901#issuecomment-4654411729) ). The question on my mind is whether it is worth it, or whether it would be better to give up some of the perf and go with more pure and general purpose design (e.g. a type with a single readonly field and a static constructor that is marked as side-effect free).

From native AOT perspective, I think these two approaches are close to each other. In _unshared code_, the combination of static preinitialization and codegen reading the preinit blobs means that we can optimize away the static constructor and storage type/field. This also works if the storage is not single-field, but multiple fields reusing a single container type. In shared code, we _might_ be able to optimize the type with single/multiple readonly fields shape too, but that's not something we do today, so the static constructor and fields currently prevail. What we cannot optimize away is the dummy `<>c` instance that Roslyn creates to make the lambda an instance method.

The intrinsic is nice because it would allow eliminating the dummy instance in addition to what we eliminate today.

The math on the native AOT side:
* Current cost: lazy logic to RhNewObj the delegate: 65 bytes + DelegateCtorHelper 12 bytes (plus 4 for alignment). The `<>c` holder is a frozen object (24 bytes), it's MethodTable is 56 bytes. Totals to 161 bytes per lambda.
* Static readonly would eliminate the lazy logic (-65 + (-16)) and instead we would get a frozen delegate (+48 bytes). Totals to 128 bytes
* Intrinsic would also eliminate the frozen `<>c` holder and MethodTable (-24 + (-56)). Totals to 48 bytes (just the frozen delegate).

**Comment by MichalPetryka** [comment]
> The most recent update of the proposal from [#125901](https://github.com/dotnet/runtime/pull/125901):
> 
> > `public static Delegate GetDelegate(nint method, ref Delegate? storage)`
> 
> * The API is expected to be always called in a sequence "ldftn + ldsflda + call GetDelegate" and it is expected to be always expanded as intrinsic by the codegen.
> * The static field is there to simplify runtime implementation and diagnostics/funceval. The static field can be inspected as any other field.
> * The API signature is non-generic to minimize binary footprint. The field is expected be of the actual delegate type, and the return value from the API can be assumed to have the actual delegate type (no explicit cast for actual delegate type required at the callsite)
> 
> [@MichalStrehovsky](https://github.com/MichalStrehovsky) [@davidwrighton](https://github.com/davidwrighton) What do you think about this design?
> 
> This design minimizes binary footprint and startup costs (some numbers [#125901 (comment)](https://github.com/dotnet/runtime/pull/125901#issuecomment-4654411729) ). The question on my mind is whether it is worth it, or whether it would be better to give up some of the perf and go with more pure and general purpose design (e.g. a type with a single readonly field and a static constructor that is marked as side-effect free).

@davidwrighton bump, cc @jkoritzinsky like we discussed

**Comment by davidwrighton** [comment]
@MichalPetryka @jkotas Sorry about missing this. GitHub notifications slip past me pretty easily.

My opinion on the proposal.
1. This looks reasonable for making this all faster.
2. I need to see a specification about how the "storage" is handled. Notably, what is undefined behavior around reading/writing the field. Is it required that the runtime fill the field in at all? What diagnostic scenarios does it exist for? What happens if the field has a longer lifetime than the required by the delegate type/Method pair. What happens if it has a shorter lifetime?
3. If this isn't called via an intrinsic usage... what is the expected result? Would an implementation be free to allocate all the time in that situation?
4. With regards to implementation, I see no truly good reason why we couldn't make the entire delegate caching scheme be internal to the runtime/implementation of the intrinsic. If we cared to, we could actually smuggle the storage into the generic dictionary, and make lookup as simple as a single generic dictionary lookup in both coreclr/native aot. (and then RyuJit would probably be able to hoist the load out of loops, etc.) Obviously I'm coming in after you have all looked at this, but I don't see making internal hidden storage for unloadable assemblies/shared generics as a particularly difficult problem to solve, and having a visible storage field comes with a whole collection of weird details that I don't particularly like.
A sketch of the solution would be...

1. Given a method/delegate type pair that is attempted to be used during compilation determine if it is collectible or not, and determine if it is generic or not, and determine if the caller knows statically the exact target
Expansion is done in 3 ways.
1. Non-collectible and exact delegate can be known at compile time. 
  - Load the pointer to a Frozen instance of the delegate.
2. Collectible and exact delegate can be known at compile time.
  - Allocate a WeakTrackResurrection GCHandle to the target delegate embed it as a pointer. Then to access, add an extra indirection to the load. Also, allocate a LOADERALLOCATORHANDLE to the target delegate to keep it alive for the appropriate lifetime.
3. Shared generic codegen
  - Use a generic dictionary slot to point at a pointer sized region which holds the correct pointer. This would require teaching the nativeaot/coreclr runtimes about a new generic dictionary slot type, which hasn't been done on CoreCLR in a very long time, but it isn't actually particularly difficult. Treat access like the unloadable scenario, where we add an extra indirection so that we don't have distinguish between the cases in the generated code.

This would require a runtime data structure to keep track of the allocated delegates in the CoreCLR codebase + work to allow NativeAOT to expand its dictionaries as needed.

Then implement the public api as some bit of reflection that always allocates (with the appropriate trim warnings caused by it being a form of reflection/a tweak to detect the intrinsic scenario and not emit the warning.)

**Comment by MichalPetryka** [comment]
> * I need to see a specification about how the "storage" is handled. Notably, what is undefined behavior around reading/writing the field. Is it required that the runtime fill the field in at all? What diagnostic scenarios does it exist for? What happens if the field has a longer lifetime than the required by the delegate type/Method pair. What happens if it has a shorter lifetime?

The storage follows the same lifetime rules as the current field emitted by Roslyn, extending the lifetime of delegates to the lifetime of containing type.
The runtime is free to optimize out accesses to the storage field, it will do so when expanding intrinsic to frozen.
Setting the field to a delegate pointing to a different method is undefined behaviour and will cause incorrect behaviour from the JIT assuming it points to one method.

> 3\. If this isn't called via an intrinsic usage... what is the expected result? Would an implementation be free to allocate all the time in that situation?

@jkotas Wanted the method to always throw when non expanded, if we want to add a non expanded path back in then we need to add 2 generic variables:
1. for the delegate type (when expanding we can get it from the field instead).
2. for the closure type (it is required for instance methods on generic types, when expanding we can get it from ldftn instead).
Additionally, on NAOT it can only work for reflection visible delgates.

> 4\. With regards to implementation, I see no truly good reason why we couldn't make the entire delegate caching scheme be internal to the runtime/implementation of the intrinsic. If we cared to, we could actually smuggle the storage into the generic dictionary, and make lookup as simple as a single generic dictionary lookup in both coreclr/native aot. (and then RyuJit would probably be able to hoist the load out of loops, etc.) Obviously I'm coming in after you have all looked at this, but I don't see making internal hidden storage for unloadable assemblies/shared generics as a particularly difficult problem to solve, and having a visible storage field comes with a whole collection of weird details that I don't particularly like.

The decision to use the field was to simplify the implementation due to the complexity needed to handle shared generics and collectible assemblies, as far as I understood @jkotas preferred to avoid the work needed to avoid performance regressions and ensure correct unloadability using a totally new generic dictionary type. If you believe that it's worth it to handle this case and Jan agrees, I agree that we can change it to work like that, but in such case I'd like to ask if you could help out with the implementation then (we'd use the same helper as today, just get the ref for it from the generic dictionary instead of field).

> 6\. Non-collectible and exact delegate can be known at compile time.
> 
> * Load the pointer to a Frozen instance of the delegate.

@jkotas wanted to handle that in a followup to make review easier to I removed it from the prototype but the impl is half ready in the revert commit there (it requires making CoreCLR delegates FOH friendly and NAOT needs a way to reconcile compile vs runtime instances).

> 3\. Collectible and exact delegate can be known at compile time.
> 
> * Allocate a WeakTrackResurrection GCHandle to the target delegate embed it as a pointer. Then to access, add an extra indirection to the load. Also, allocate a LOADERALLOCATORHANDLE to the target delegate to keep it alive for the appropriate lifetime.

I think this would potentially have an issue when you emit a DynamicMethod that uses the intrinsic to get a delegate to an unloadable assembly, since the weak handle could be freed while the DynamicMethod is alive. I'd leave such optimizations to a followup that considers all edge cases while keeping the helper for initial impl.

> * Use a generic dictionary slot to point at a pointer sized region which holds the correct pointer. This would require teaching the nativeaot/coreclr runtimes about a new generic dictionary slot type, which hasn't been done on CoreCLR in a very long time, but it isn't actually particularly difficult. Treat access like the unloadable scenario, where we add an extra indirection so that we don't have distinguish between the cases in the generated code.

That's the complexity part that @jkotas AFAIR preferred to avoid, important part is to make sure that we don't regress hotpath fetching perf for shared generics.

> Then implement the public api as some bit of reflection that always allocates (with the appropriate trim warnings caused by it being a form of reflection/a tweak to detect the intrinsic scenario and not emit the warning.)

Currently we just always throw due to needing generics for fallback like I said earlier. The API is annotated as AOT unsafe there but I didn't implement suppressions for it.

**Comment by jkotas** [comment]
The intrinsic-only design ended up requiring special-casing or alternative implementations in many places that deal with static fields. That did not feel like the right trade-off to me - a lot of complexity for relatively little benefit.

Out of all the options we've discussed, I think the cleanest approach would be to emit a dedicated type with single field and a static constructor for each lambda. These types could be marked as side-effect free, allowing the JIT to execute the static constructor during compilation. We could then special case these types in a few targeted places to squeeze out additional performance (for example, we can recognize the static lambda initialization IL and create the lambda without JITing the constructor).

This approach would increase metadata size somewhat, but it would also provide a much more flexible foundation. I expect we'd find many more opportunities to leverage it for future performance optimizations.

**Comment by MichalPetryka** [comment]
> The intrinsic-only design ended up requiring special-casing or alternative implementations in many places that deal with static fields. That did not feel like the right trade-off to me - a lot of complexity for relatively little benefit.
> 
> Out of all the options we've discussed, I think the cleanest approach would be to emit a dedicated type with single field and a static constructor for each lambda. These types could be marked as side-effect free, allowing the JIT to execute the static constructor during compilation. We could then special case these types in a few targeted places to squeeze out additional performance (for example, we can recognize the static lambda initialization IL and create the lambda without JITing the constructor).
> 
> This approach would increase metadata size somewhat, but it would also provide a much more flexible foundation. I expect we'd find many more opportunities to leverage it for future performance optimizations.

I think most complexity could just be removed by readding the 2 generic parameters, then we don't need to always expand outside NAOT either. I think it'd be still smaller in metadata size than a class per lambda.

Additionally, doing it with a cctor requires us to not do the null instance optimization, unless we'd still do an intrinsic but with just creation and not caching.

**Comment by jkotas** [comment]
> we don't need to always expand outside NAOT either

I think the steady state path needs to be expanded (ie no calls to helpers, etc.) for both NAOT and !NAOT. We would see throughput perf regressions otherwise.

> doing it with a cctor requires us to not do the null instance optimization, unless we'd still do an intrinsic but with just creation and not caching

Right. I am not worried about this local detail - we can make it work.

**Comment by MichalPetryka** [comment]
> I think the steady state path needs to be expanded (ie no calls to helpers, etc.) for both NAOT and !NAOT. We would see throughput perf regressions otherwise.

Yeah but I've meant that it'd not be needed for correctness, it could just be Tier1 only and such.
It'd also be much simpler to just use the generics in JIT, NAOT scanner and such.

> I am not worried about this local detail - we can make it work.

How would you see this in IL then? Would it be something like:
```cs
[EagerInit]
public class CompilerGenerated
{
  public static readonly Action a = RuntimeHelpers.CreateDelegate<Action, CompilerGenerated>(&Lambda);

  public void Lambda() {}
}

Action a = CompilerGenerated.a;
```
or
```cs
public class CompilerGenerated
{
  public static Action a;

  public static void Init()
  {
    a = RuntimeHelpers.CreateDelegate<Action, CompilerGenerated>(&Lambda);
  }

  public void Lambda() {}
}

Action a = RuntimeHelpers.EagerInit(ref CompilerGenerated.a, &CompilerGenerated.Init);
```
if we wanted to avoid checking for custom attributes on every type?

**Comment by MichalPetryka** [comment]
> Out of all the options we've discussed, I think the cleanest approach would be to emit a dedicated type with single field and a static constructor for each lambda. These types could be marked as side-effect free, allowing the JIT to execute the static constructor during compilation. We could then special case these types in a few targeted places to squeeze out additional performance (for example, we can recognize the static lambda initialization IL and create the lambda without JITing the constructor).
> 
> This approach would increase metadata size somewhat, but it would also provide a much more flexible foundation. I expect we'd find many more opportunities to leverage it for future performance optimizations.

Thinking more about it, it feels to me like giving up and using cctors would introduce a lot of bloat and complicated recognition to JIT would be a bit premature.
Even the simplest and most explicit `GetDelegate<TDelegate, TCapture>(nint method, ref TDelegate? storage)` gets us like 80% of the benefits more complicated variants have while requiring little work and no magic.
As such, I think it might be still worth it to use that to avoid the cctor bloat, especially single it'd not prevent us adding some `[EagerInit]` in the future for the more general case.
