### ISSUE TITLE
Tracking issue for enabling the Windows thread pool

### ISSUE THREAD

**Issue by eduardo-vp** [dotnet/runtime#85485]
Track current work of https://github.com/dotnet/runtime/pull/85373

- [x] Isolate Portable thread pool implementation and Windows thread pool implementation such that a new file can handle a switch which just forwards to one of the thread pools based on an environment variable
- [x] Successfully build on every os/runtime configuration
  - [x] Clr on windows
  - [x] Mono on windows 
  - [x] NativeAOT on windows 
  - [x] Clr on linux
  - [x] Mono on linux
  - [x] NativeAOT on linux
- [x] Pass current tests
- [x] Add tests that use the Windows thread pool for NativeAOT, CLR and Mono
- [x] Integrate with trimming to discard the thread pool implementation the app does not need
