### ISSUE TITLE
[Mono] Implement support for UnsafeAccessorAttribute

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#86040]
Implement support for "zero overhead member access with suppressed visibility checks" https://github.com/dotnet/runtime/issues/81741 for the mono JIT/AOT and interp

- [x] Add `UnsafeAccessorAttribute` as a well-known attribute to the runtime
  We will need to extract a named string-value property from the custom attribute (https://github.com/dotnet/runtime/pull/88626)
- [x] Add code to JIT/AOT and the interp transform to detect `static extern` methods with the attribute and trigger emitting the method wrapper for UnsafeAccessor (https://github.com/dotnet/runtime/pull/88626)
- [x] Implement some ilgen code to generate the method bodies for these methods for the non-generic case
    - [x] Field (https://github.com/dotnet/runtime/pull/88626)
    - [x] StaticField (https://github.com/dotnet/runtime/pull/88626)
    - [x] Constructor, Method, StaticMethod (https://github.com/dotnet/runtime/pull/88925)
    - [x] #89098
        (test cases: `Verify_IgnoreCustomModifier`, `Verify_UnmanagedCallConvBitAreTreatedAsCustomModifiersAndIgnored`, `Verify_ManagedUnmanagedFunctionPointersDontMatch` and `Verify_InvalidTargetUnsafeAccessorAmbiguousMatch`)
 - [ ] (post .NET 8) implement support for generic accessor methods (`ref T[] GetPrivateArrayField<T>(SomeContainer<T> @this)`) - https://github.com/dotnet/runtime/issues/89439

There might be some mild complication here for working with generics (the `static extern` method will be generic in that case) - our ilgen method builder might not support generics (in which case it will have to be extended)

**Comment by lambdageek** [comment]
It doesn't look like we will need anything special to skip accessibility checks for fields

For something like

```csharp
class MyClass {
  private MyFieldType MyField;
  ...
}

[UnasafeAccessor(UnsafeAccessorKind.Field, Name="MyField")]
static extern ref MyFieldType GetMyField(MyClass c);
```

the ilgen could use `mono_mb_emit_ldarg` and `mono_mb_emit_ldflda` which would emit

```
  ldarg.0
  mono_custom_prefix . mono_ldobjaddr
  add <field_offset>
```

---

for method calls, `mono_mb_emit_managed_call` just uses a normal IL `call` instruction (nit: we actually want `callvirt`) so we might need some prefix opcode to skip accessibility checks.  (or we understand that this ilgen'd method should skip accessibility checks entirely - I think we already have that for wrappers)

**Comment by lambdageek** [comment]
For generic field access we can't use `mono_objaddr` + `add <constant>`, so we'll have to use a real `ldflda` instruction.  Which probably means we should just have a tag on the method to bypass access checks and then do things with normal IL opcodes.

**Comment by AaronRobinsonMSFT** [comment]
@lambdageek I've added https://github.com/dotnet/runtime/issues/86161 for CoreCLR.

**Comment by lambdageek** [comment]
There's also a question of _when_ do we create the IL for this "extern" method which is sort of interesting.  I think for JIT/AOT we can actually do it during the call to `mono_compile_method_checked`. Not sure when to do it in the interpreter.  

I guess the question is whether the same logic that we use for dllimports and icalls will work for plain "extern" methods. (I'm pretty sure that's not the case - we look for the `internalcall` or `pinvokeimpl` flags, not just methods with no code)

**Comment by lambdageek** [comment]
I guess the thing to pattern this on is where we call `mono_marshal_get_delegate_begin_invoke`: in `mono_interp_transform_method` and `compile_special`

**Comment by AaronRobinsonMSFT** [comment]
@lambdageek See the updates to [`jitinterface.cpp`](https://github.com/dotnet/runtime/pull/86932/files#diff-98b4e379205d747e922689cb993f985be190fedb509fd486e99280c842703472). The final `else` branch in `getMethodInfoHelper()` is when we generate this information (that is, at JIT time). It calls `MethodDesc::GenerateUnsafeAccessor()` in `prestub.cpp`.

**Comment by fanyang-mono** [comment]
All the work planned for .NET8 has been completed. Moving this tracking issue to 9.0.0

**Comment by jkotas** [comment]
This can be closed. The remaining work is tracked by https://github.com/dotnet/runtime/issues/89439
