### ISSUE TITLE
JIT-EE interface clean up (tracking issue)

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#86672]
I suggest to use this issue to store ideas of what we can clean up in the JIT-EE interface. So, when someone modifies it they can address these issues along the way to avoid bumping JIT-EE guid for single minor things:

**To do:**
- [ ] `recordRelocation` has unused arg `slotNum`
- [ ] `isCompatibleDelegate` is unused
- [ ] `mergeClasses` is unused
- [ ] `satisfiesClassConstraints` is unused
- [ ] `findNameOfToken` is unused
- [ ] `getInlinedCallFrameVptr` is unused
- [ ] `canAccessFamily` is unused
- [ ] `isRIDClassDomainID` is unused
- [ ] `isValidToken` is unused (verification artifact?)
- [ ] `isValidStringRef` is unused (verification artifact?)
- [ ] `tryResolveToken` is unused
- [ ] `CORINFO_DESKTOP_ABI`
- [ ] `getMethodModule`

Initially, I wanted to file this issue with just 2 items but found more.

cc @dotnet/jit-contrib @jkotas

**Comment by jkotas** [comment]
> classMustBeLoadedBeforeCodeIsRun and methodMustBeLoadedBeforeCodeIsRun are likely some NGen artifacts?

These are still used by R2R compiler. It may be possible to get rid of them by refactoring the protocol, but I do not think it is safe to just delete them.

**Comment by BruceForstall** [comment]
Looks like `isValidToken` is still referenced as an implementation detail of `tryResolveToken`. Maybe doesn't need to be exposed on the public interface, though.

**Comment by BruceForstall** [comment]
Fixed with https://github.com/dotnet/runtime/pull/87588
