### ISSUE TITLE
[Tracking] Expose a `Lock` type

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#87673]
- [x] Proposal for the `Lock` API - https://github.com/dotnet/runtime/issues/34812
  - Partially approved, may need further discussion/changes based on other items
- [x] Expose a `Lock` type in preview mode - PR: https://github.com/dotnet/runtime/pull/87672
- [ ] Diagnostics - PRs: https://github.com/dotnet/runtime/pull/101192, https://github.com/dotnet/runtime/pull/101501
- [x] Proposal for integrating with the C# `lock` keyword - https://github.com/dotnet/csharplang/issues/7104
- [ ] Basic performance tests
- [x] Make the `Lock` type non-preview - PR: https://github.com/dotnet/runtime/pull/102222
- [x] Document the `Lock` API surface - PR: https://github.com/dotnet/dotnet-api-docs/pull/9912
- [ ] Document the new config vars

**Comment by mangod9** [comment]
Closing since new Lock Type is now enabled in 9.
