### ISSUE TITLE
[debugger][mono] Tracking issue for debugger new features and improvements

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#90587]
The features are working but not with 100% the same behavior as in coreclr:
- [ ] https://github.com/dotnet/runtime/issues/77965
- [ ] https://github.com/dotnet/runtime/issues/76876
- [ ] https://github.com/dotnet/runtime/issues/69300

Missing features/tests:
- [ ] https://github.com/dotnet/runtime/issues/77768
- [ ] https://github.com/dotnet/runtime/issues/77536
- [ ] https://github.com/dotnet/runtime/issues/77315
- [ ] https://github.com/dotnet/runtime/issues/76062
- [ ] https://github.com/dotnet/runtime/issues/76015
- [ ] https://github.com/dotnet/runtime/issues/75959
- [ ] https://github.com/dotnet/runtime/issues/69640
- [ ] https://github.com/dotnet/runtime/issues/69299
- [ ] https://github.com/dotnet/runtime/issues/57085
- [ ] https://github.com/dotnet/runtime/issues/65864

Bugs:
- [ ] https://github.com/dotnet/runtime/issues/73298
- [ ] https://github.com/dotnet/runtime/issues/69543
