### ISSUE TITLE
InlineArray documentation tracking

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#91012]
Tracking bug to finalize InlineArray documentation.

- [ ] Convert the proposal into a document and move to appropriate place.
- [ ] Add some info about layout of the inline array instance (i.e. pointer to the entire struct and to the first element are equal,...)
- [ ] Add a note on readonly element. This has no any special semantics and as such unsupported.

**Comment by Civilianstealth** [comment]
src/native/corehost/CMakeLists.txt

**Comment by mangod9** [comment]
@VSadov do you plan on documenting this in 8? Perhaps we can move to 9 and track it as out-of-band work?

**Comment by VSadov** [comment]
Let's move to 9. This is not blocking.
