### ISSUE TITLE
Tracking issue for remaining AssemblyBuilder.Save work in .NET 9

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#92975]
See https://github.com/dotnet/runtime/issues/62956 for work done in .NET 8 for adding `AssemblyBuilder.Save(string/stream)` support. Remaining work include:
- [x] Add new `ILGenerator` implementation
  - [x] [Initial ILGenerator implementation, save minimal/simple IL](https://github.com/dotnet/runtime/pull/92846).
  - [x] [Calculate the maxstack appropriately](https://github.com/dotnet/runtime/pull/93244)
  - [x] [Add support for emitting a call to method, constructor, field, type references](https://github.com/dotnet/runtime/pull/94116)  
  - [x] [Add local variables support](https://github.com/dotnet/runtime/pull/93809)
  - [x] [Add label (branching) support](https://github.com/dotnet/runtime/pull/93565)
  - [x] [Add Try/Catch/Finally/Filter/Fault block support](https://github.com/dotnet/runtime/pull/94366)
  - [x] [Add support for remaining Emit APIs (EmitCall, EmitCalli, Emit Signatures)](https://github.com/dotnet/runtime/pull/96362)
- [x] Add support for remaining members
  - [x] [Add `ConstructorBuilderImpl` and save it to file/stream (this should include `Emit(OpCode opcode, ConstructorInfo con)` implementation)](https://github.com/dotnet/runtime/pull/94732)
  - [x] [Add `PropertyBuilderImp`l and save it to file/stream](https://github.com/dotnet/runtime/pull/95303)
  - [x] [Add `EventBuildterImpl` and save it to file/stream](https://github.com/dotnet/runtime/pull/95936)
  - [x] [Add implementation for remaining unimplemented APIs in `AssemblyBuilder`/`ModuleBuilder` (`CreateGlobalFuntions`, `DefineGlobalMethod` etc)](https://github.com/dotnet/runtime/pull/96805)
  - [x] [Add implementation for remaining unimplemented APIs for a `MethodBuilder`/`TypeBuilder`/`FieldBuilder` (like `SignatureCallingConvention`, `*RequiredCustomModifiers`, `*OptionalCustomModifiers`)](https://github.com/dotnet/runtime/pull/96805)
- [x] Add [approved public APIs](https://github.com/dotnet/runtime/issues/83988): https://github.com/dotnet/runtime/pull/97177
- [x] Entry point support
  - [x] Get[ API shape approved](https://github.com/dotnet/runtime/issues/97015) and implemented
- [x] Add PDBs support
  - [x] Prototype possible solutions to make the design decisions and propose [API shape](https://github.com/dotnet/runtime/issues/99935), get proposal approved
  - [x] Implementation and testing

**Comment by masonwheeler** [comment]
An important part of `Reflection.Emit` that I don't see listed here was PDB generation.  Is this on the menu anywhere?

**Comment by buyaa-n** [comment]
Look the last bullet of the list.

**Comment by masonwheeler** [comment]
Oops!  Not sure how I missed that.  Good to see it got included.

**Comment by Xyncgas** [comment]
What can I save using AssemblyBuilder.Save

Am I now seeing a new era of computing, where a server sends a manifesto about a sandbox's capability, meanwhile the distributed app creates an assembly out of no where and saving it to bytes sends it to the server, so it can execute in the server's sandbox without the server knowing about this application, so people can choose whatever cloud provider, applications needs simply pay a fee in crypto to use the server's resource therefore user is paying for what they use and having their privacy.

If that's the happening here, wow great work!

**Comment by buyaa-n** [comment]
We are making a good progress, planning to finish the main functionality (excluding entry point and PDB) and [make related APIs public](https://github.com/dotnet/runtime/issues/83988) in preview 1.

Now it would be great to test the implementation with a real-life scenario. I would really appreciate if you could:
- Prepare a simple app with your use case and share with me (in this thread or email me)
- Dogfood the [daily build](https://github.com/dotnet/installer#installers-and-binaries) and try out the new AssemblyBuilder implementation yourself and give feedback. (The APIs are still internal so need to use reflection for now as [mentioned in the sample](https://github.com/dotnet/runtime/issues/15704#issuecomment-1644571703))

Thank you in advance!

**Comment by masonwheeler** [comment]
Here's my real-life scenario: https://github.com/boo-lang/boo

This is not a "simple app" but rather a thorough, comprehensive test of the system: a compiler that uses `System.Reflection.Emit` as its code generator, with thousands of test cases in its automated test suite, including some scenarios that are supported by refemit but not found in the C# language.

Last I checked, all the tests pass under .NET Framework.  So seeing how many pass under this project is a good benchmark for how correct your implementation is.

**Comment by buyaa-n** [comment]
The feature is now available in https://dotnet.microsoft.com/en-us/download/dotnet/9.0, please give it a try and give us a feedback. We also adding bunch of fixes: https://github.com/dotnet/runtime/pull/97350 and https://github.com/dotnet/runtime/pull/98393 in preview 2 mostly related to complex generic types/methods

**Comment by GGG-KILLER** [comment]
Is there an ETA for `SetEntryPoint`?

I need that otherwise my use case is still not covered (an optimizing compiler that compiles to CIL).

**Comment by buyaa-n** [comment]
> Is there an ETA for SetEntryPoint?

We decided to add completely different API for setting `SetEntryPoint` and other options for generated assembly. See more details from the [API proposal](https://github.com/dotnet/runtime/issues/97015). This will be added as soon as the API approved (within preview 3).

**Comment by leppie** [comment]
`TypeBuilderInstantiation` needs to be implemented.

It currently fails when doing the following (very simple and common scenario):

- Define new type `A` (simple poco)
- Use existing generic type `B<T>` to create `B<A>`
- When trying to reflect on `B<A>` (ie to get constructor) NotSupported is thrown

Will add code soon.

**Comment by buyaa-n** [comment]
Thank you @leppie that should have been fixed in preview 2, I can double check when you share the code.

**Comment by leppie** [comment]
> Thank you @leppie that should have been fixed in preview 2, I can double check when you share the code.

Sorrry, was not aware there was  a second  preview already.  But  keep  them  coming!

**Comment by buyaa-n** [comment]
> Sorrry, was not aware there was a second preview already. But keep them coming!
> 
> Edit: I see preview 2 not out yet. You can just grab the code from the PR ([IronScheme/IronScheme#160](https://github.com/IronScheme/IronScheme/pull/160)) and follow the steps.

Sorry @leppie I mistaken, we had similar fixes made in preview 2, but your scenario was not covered, I put up [a PR](https://github.com/dotnet/runtime/pull/99771) and it will be fixed in preview 3

**Comment by buyaa-n** [comment]
> > Is there an ETA for SetEntryPoint?
> 
> We decided to add completely different API for setting `SetEntryPoint` and other options for generated assembly. See more details from the [API proposal](https://github.com/dotnet/runtime/issues/97015). This will be added as soon as the API approved (within preview 3).

@GGG-KILLER this change now [merged](https://github.com/dotnet/runtime/pull/99660) and will be available in preview 3

**Comment by GGG-KILLER** [comment]
> > > Is there an ETA for SetEntryPoint?
> > 
> > 
> > We decided to add completely different API for setting `SetEntryPoint` and other options for generated assembly. See more details from the [API proposal](https://github.com/dotnet/runtime/issues/97015). This will be added as soon as the API approved (within preview 3).
> 
> @GGG-KILLER this change now [merged](https://github.com/dotnet/runtime/pull/99660) and will be available in preview 3

Thanks! In the meantime I ended up [vendoring](https://github.com/GGG-KILLER/SimpleCompiler/tree/main/src/SimpleCompiler.Backends.Cil/Emit) System.Reflection.Emit into my project to be able to do that with the suggested API, so I should be able to migrate to it when .NET 9 p3 comes out

**Comment by leppie** [comment]
> Sorry @leppie I mistaken, we had similar fixes made in preview 2, but your scenario was not covered, I put up [a PR](https://github.com/dotnet/runtime/pull/99771) and it will be fixed in preview 3

@buyaa-n Still throwing  NotSupported.

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilderInstantiation.cs#L165

**Comment by jl0pd** [comment]
> > Sorry @leppie I mistaken, we had similar fixes made in preview 2, but your scenario was not covered, I put up [a PR](https://github.com/dotnet/runtime/pull/99771) and it will be fixed in preview 3
> 
> @buyaa-n Still throwing NotSupported.
> 
> https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilderInstantiation.cs#L165

I guess that's general issue with reflection.emit that exists longer that netcore does. This may help https://stackoverflow.com/a/40221032/10339675

**Comment by leppie** [comment]
> This may help

It has indeed. At least for the 1 specific blocker I have had.

**Comment by buyaa-n** [comment]
Last item in the list: PDB support is added in preview 4. Closing the issue as completed, if you see any bug/issue please file a new issue

**Comment by masonwheeler** [comment]
So when is preview 4 expected to be available?

**Comment by buyaa-n** [comment]
Around 21-May

**Comment by Xyncgas** [comment]
anymore works on AssemblyBuilder.Save for now or we are done for now

**Comment by masonwheeler** [comment]
One bit of API surface that's still noticeably missing is resources.  `AssemblyBuilder.DefineUnmanagedResource`, `ModuleBuilder.DefineManifestResource`, and `ModuleBuilder.DefineResource` are all in use in the compiler I'm trying to port, and none of these are available in the .NET Core version.  Are there any plans to implement these?  If not, what is the "right way" to set up resources in your PE file in Core?

**Comment by jkotas** [comment]
The recommended replacement is to pass the resource blobs as `managedResources` and `nativeResources` arguments directly to the `ManagedPEBuilder` constructor.

**Comment by masonwheeler** [comment]
@jkotas Sure, but where do you get "the resource blobs" from?  There doesn't seem to be much information out there on the subject.  Googling "c# create resource blobs" gives you a bunch of results about using Azure blob storage, and "c# create resources" gives you results about working with RESX files.

**Comment by Xyncgas** [comment]
Creating resource blobs in the context of .NET typically refers to embedding resources directly into your assembly as binary data. This could include images, XML files, localization strings, or any other data that you want to include with your application.

**Comment by jkotas** [comment]
> where do you get "the resource blobs" from?

- If you called `ModuleBuilder.DefineManifestResource` before, the stream is the blob. 
- If you called `ModuleBuilder.DefineResource` before, create ResourceWriter and save it into a memory stream that will be the blob. (`ModuleBuilder.DefineResource` was a thin wrapper over `ResourceWriter` and `DefineManifestResource`.)
- Add entries for all resources using `MetadataBuilder.AddManifestResource`. All streams have to be concatenated together into one `BlobBuilder` that you pass into `ManagedPEBuilder`. The offset within the `BlobBuilder` is argument for `AddManifestResource`.

@buyaa-n Could you please look into creating a sample for this?

**Comment by masonwheeler** [comment]
@jkotas Thanks, that's very helpful.  And what about the unmanaged resources?  It's not at all clear from the API or documentation how `ResourceSectionBuilder` is supposed to work.  I have a bunch of bytes already that are trivial to write to a `BlobBuilder`, but what in the world am I supposed to do with those two offset values?!?

**Comment by jkotas** [comment]
If you have the raw bytes, you can just write them out. Here is how it is done in Roslyn: https://github.com/dotnet/roslyn/blob/7a96b1530744f6637ad6bb6bf5b8dfa33ea15b81/src/Compilers/Core/Portable/PEWriter/PeWriter.cs#L431-L447 . 

The two offsets are for cases where the native resources have relocs.

**Comment by masonwheeler** [comment]
@jkotas OK, thanks!

**Comment by buyaa-n** [comment]
> @buyaa-n Could you please look into creating a sample for this?

Added with https://github.com/dotnet/docs/pull/40735

**Comment by leppie** [comment]
> > An important part of `Reflection.Emit` that I don't see listed here was PDB generation. Is this on the menu anywhere?
> 
> @masonwheeler and others, have you tried the PDB generation with the new PersistedAssemblyBuilder? How was it and any feedback so far?

I gave it a quick shot on the first preview it came out, but was hoping an extension for the Save method would be added to behave like .NET Desktop. 

Not sure if something was added or if someone has made one.

**Comment by buyaa-n** [comment]
> was hoping an extension for the Save method would be added to behave like .NET Desktop.

Are you talking about `Save(String, PortableExecutableKinds, ImageFileMachine)` constructor? 

Instead that we added `GenerateMetadata` overloads that outputs generated metadata which user could use populating the assembly with various settings they want, not only limited to `PortableExecutableKinds`, `ImageFileMachine` enums

```cs
public sealed class PersistedAssemblyBuilder : AssemblyBuilder
{
    public MetadataBuilder GenerateMetadata(out BlobBuilder ilStream, out BlobBuilder mappedFieldData);
    public MetadataBuilder GenerateMetadata(out BlobBuilder ilStream, out BlobBuilder mappedFieldData, out MetadataBuilder pdbBuilder) { }
}
```
See examples here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-reflection-emit-persistedassemblybuilder#emit-symbols-and-generate-pdb

**Comment by leppie** [comment]
> Instead that we added `GenerateMetadata` overloads

That is seriously complicated :D 

I was hoping for `Save(string, bool emitDebugInfo)` that takes care of all the `GenerateMetadata` stuff in a way PDB files was done in .NET 4.x . Or something on `DefineDynamicModule` . 

Hoping for too much?

**Comment by buyaa-n** [comment]
> That is seriously complicated :D
> 
> I was hoping for `Save(string, bool emitDebugInfo)` that takes care of all the `GenerateMetadata` stuff in a way PDB files was done in .NET 4.x . Or something on `DefineDynamicModule` .
>
> Hoping for too much?

Well, we could add an API that cover the basic scenarios by defaulting assembly and PDB generation options. The question is which options should be defaulted and which options would be available for the user, somebody should file an issue for that as a start.

Meanwhile you could create and use a helper method that does what that `Save(string, bool emitDebugInfo)` method would do for you, for example:

```cs
public static void Save(PersistedAssemblyBuilder ab, string assemblyFileName, bool emitDebugInfo)
{
    MetadataBuilder metadataBuilder = ab.GenerateMetadata(out BlobBuilder ilStream, out _, out MetadataBuilder pdbBuilder);

    BlobBuilder portablePdbBlob = new BlobBuilder();
    PortablePdbBuilder portablePdbBuilder = new PortablePdbBuilder(pdbBuilder, metadataBuilder.GetRowCounts(), entryPoint: default);
    BlobContentId pdbContentId = portablePdbBuilder.Serialize(portablePdbBlob);
    using FileStream pdbFileStream = new FileStream($"{assemblyFileName}.pdb", FileMode.Create, FileAccess.Write);
    portablePdbBlob.WriteContentTo(pdbFileStream);

    DebugDirectoryBuilder debugDirectoryBuilder = new DebugDirectoryBuilder();
    debugDirectoryBuilder.AddCodeViewEntry($"{assemblyFileName}.pdb", pdbContentId, portablePdbBuilder.FormatVersion);

    ManagedPEBuilder peBuilder = new ManagedPEBuilder(
                    header: new PEHeaderBuilder(imageCharacteristics: Characteristics.ExecutableImage | Characteristics.Dll),
                    metadataRootBuilder: new MetadataRootBuilder(metadataBuilder),
                    ilStream: ilStream,
                    debugDirectoryBuilder: debugDirectoryBuilder);

    BlobBuilder peBlob = new BlobBuilder();
    peBuilder.Serialize(peBlob);
    using var dllFileStream = new FileStream($"{assemblyFileName}.dll", FileMode.Create, FileAccess.Write);
    peBlob.WriteContentTo(dllFileStream);
}
```

**Comment by leppie** [comment]
> use a helper method

Thanks, helped a lot.

There were 2 issues, but seems to work from a small testcase.

1. field data was not mapped
2. emitDebugInfo was not used

Here is my current version's body (got some other stuff around it):

```
MetadataBuilder metadataBuilder = ab.GenerateMetadata(out BlobBuilder ilStream, out BlobBuilder fieldData, out MetadataBuilder pdbBuilder);

DebugDirectoryBuilder debugDirectoryBuilder = null;

if (emitDebugInfo)
{
  BlobBuilder portablePdbBlob = new BlobBuilder();
  PortablePdbBuilder portablePdbBuilder = new PortablePdbBuilder(pdbBuilder, metadataBuilder.GetRowCounts(), entryPoint: default);
  BlobContentId pdbContentId = portablePdbBuilder.Serialize(portablePdbBlob);
  using FileStream pdbFileStream = new FileStream($"{assemblyFileName}.pdb", FileMode.Create, FileAccess.Write);
  portablePdbBlob.WriteContentTo(pdbFileStream);

  debugDirectoryBuilder = new DebugDirectoryBuilder();
  debugDirectoryBuilder.AddCodeViewEntry($"{assemblyFileName}.pdb", pdbContentId, portablePdbBuilder.FormatVersion);
}

ManagedPEBuilder peBuilder = new ManagedPEBuilder(
                header: new PEHeaderBuilder(imageCharacteristics: Characteristics.ExecutableImage | Characteristics.Dll),
                metadataRootBuilder: new MetadataRootBuilder(metadataBuilder),
                ilStream: ilStream,
                mappedFieldData: fieldData,
                debugDirectoryBuilder: debugDirectoryBuilder);

BlobBuilder peBlob = new BlobBuilder();
peBuilder.Serialize(peBlob);
using var dllFileStream = new FileStream($"{assemblyFileName}.dll", FileMode.Create, FileAccess.Write);
peBlob.WriteContentTo(dllFileStream);
```

**Comment by leppie** [comment]
@buyaa-n Is there anything planned for embedded/manifest resources? Or is this something we need to add manually too with the PE builder? 

Not a deal breaker for me as I can just put it in initialized data.

**Comment by buyaa-n** [comment]
Nothing planned for now as user can add them manually, there is an instruction above: https://github.com/dotnet/runtime/issues/92975#issuecomment-2081309054 

And a sample added in doc: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-reflection-emit-persistedassemblybuilder#add-resources-with-persistedassemblybuilder

**Comment by leppie** [comment]
@buyaa-n I think I have found an issue, but unfortunately I dont have a small repro.

Steps for repro:

1. Say you create 2 assemblies, and 1 depend on another. B depends on A. 
2. You create A
3. You create B 
4. You save A
5. You save B (kaboom)

B references a MethodBuilderImpl in A. The module scopename refers to the correct filename, but Name says `"<In Memory Module>"`.  When emitted, it strangely emits the static constructor of the class I am calling from in B. 

This scenario works correctly on .NET 2/4. And if I rememebr correctly it even allows for cyclic references where A and B can both reference each other.

**Comment by buyaa-n** [comment]
Thanks @leppie, there is no valid token populated until the assembly is saved, could you try:

1. Say you create 2 assemblies, and 1 depend on another. B depends on A.
2. You create A
3. You save A
4. You create B, calls a method in A
5. You save B

> And if I remember correctly it even allows for cyclic references where A and B can both reference each other.

With current design probably we could not support cyclic references

**Comment by jkotas** [comment]
> With current design probably we could not support cyclic references

Why not? https://github.com/dotnet/runtime/issues/92975#issuecomment-2329310557 sounds like a bug to me. The ref tokens are separate from the def token. We should be able to populated the ref token independently on the def token to allow creating cycles.

**Comment by buyaa-n** [comment]
I will see what I can for fix.

**Comment by leppie** [comment]
> I will see what I can for fix.

Not sure if this is related, but I feel it might be. 

This time I am trying to emit a cast to a type in a referenced assembly (same scenario as above).

```
System.NotSupportedException: The invoked member is not supported in a dynamic module.
   at System.Reflection.Emit.TypeBuilderImpl.GetElementType()
   at System.Reflection.Emit.ModuleBuilderImpl.IsConstructedFromTypeBuilder(Type type)
   at System.Reflection.Emit.ModuleBuilderImpl.TryGetTypeHandle(Type type)
   at System.Reflection.Emit.ILGeneratorImpl.Emit(OpCode opcode, Type cls)
```

From what @jkotas said, this should also be a ref and not a def token I think.

**Comment by buyaa-n** [comment]
Thank you @leppie for reporting the bug, the [fix is up](https://github.com/dotnet/runtime/pull/107661) and also created separate [issue](https://github.com/dotnet/runtime/issues/107658) for tacking the issue and porting the fix into 9.0

**Comment by leppie** [comment]
Can confirm there is no more outstanding issues for me. 

@buyaa-n if you interested in the result of your work: https://github.com/IronScheme/IronScheme/releases/tag/1.0.385
