### ISSUE TITLE
CodeGen infrastructure work planned for .NET 9

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#93141]
This issue collects a set of CLR CodeGen (JIT) inner-loop infrastructure improvements we are planning for .NET 9.

# Planned for .NET 9

## SuperPMI-related features

- [ ] superpmi: automated TechEmpower collection https://github.com/dotnet/runtime/issues/47545
- [ ] SuperPMI: Investigate MISSING data for Linux/arm collection https://github.com/dotnet/runtime/issues/80162
- [x] SuperPMI: Improve superpmi-diffs pipeline parallelism https://github.com/dotnet/runtime/issues/93137
- [ ] SPMI collections need to use release System.Private.Corelib https://github.com/dotnet/runtime/issues/60947
- [ ] Investigate including the SPMI collector as part of the core runtime https://github.com/dotnet/runtime/issues/85537

# Other related work that is not planned

## SuperPMI-related features

- [ ] SuperPMI: add JIT memory diff measurements in per-PR pipeline runs https://github.com/dotnet/runtime/issues/95767
- [ ] Enable post back of JIT test pipeline results to triggering GitHub PR https://github.com/dotnet/runtime/issues/93138
- [ ] SPMI: Give specific context examples for tpdiff https://github.com/dotnet/runtime/issues/85755
- [ ] SPMI: Enable replay filter by attribute or metric https://github.com/dotnet/runtime/issues/93140
- [ ] Add a SPMI collection for pre-AVX512 hardware https://github.com/dotnet/runtime/issues/87145

# Related

.NET 7 work was tracked with https://github.com/dotnet/runtime/issues/64832.
.NET 8 work was tracked with https://github.com/dotnet/runtime/issues/79018.

**Comment by JulieLeeMSFT** [comment]
For .NET 9, we will add SPMI collection for ASP.NET. Moving this issue to .NET 10.
