### ISSUE TITLE
Improve JIT loop optimizations (.NET 9)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#93144]
We plan to continue improving JIT optimization capabilities for loop code. An overview of many JIT optimization possibilities is [here](https://github.com/dotnet/runtime/issues/65342); this issue will focus on issues we choose to address in .NET 9.

# Planned for .NET 9

## Loop recognition and canonicalization
- [x] **(Q4 '23)** https://github.com/dotnet/runtime/issues/43713 Describes two cases where loops are missed due to various issues.
  - [x] https://github.com/dotnet/runtime/issues/58941 F# loops not recognized

## Loop cloning
- [x] https://github.com/dotnet/runtime/issues/62615 Consider rebuilding loop table after loop cloning

## Induction variables
- [X] https://github.com/dotnet/runtime/issues/7312 RyuJIT: Index Variable Widening optimization for array accesses
- [X] https://github.com/dotnet/runtime/issues/93143 RyuJIT: Implement induction variable analysis
- [x] **(Q2'24)** https://github.com/dotnet/runtime/issues/100913 JIT: Add support for strength reduction
  - [x] https://github.com/dotnet/runtime/pull/104243
  - [x] https://github.com/dotnet/runtime/pull/104679
  - [x] https://github.com/dotnet/runtime/pull/104687
  - [x] https://github.com/dotnet/runtime/pull/104800
  - [x] https://github.com/dotnet/performance/pull/4317
  - [x] https://github.com/dotnet/runtime/pull/105107
  - [x] https://github.com/dotnet/runtime/pull/105108
  - [x] https://github.com/dotnet/runtime/pull/105131
  - [x] https://github.com/dotnet/runtime/pull/105169

# Pushed out of .NET 9

## Loop cloning
- [ ] **(Q4 '23)** https://github.com/dotnet/runtime/issues/82946 Support loop cloning for Span
- [ ] https://github.com/dotnet/runtime/issues/77071 Support loop cloning of class member arrays
- [ ] https://github.com/dotnet/runtime/issues/85552 Support loop cloning with non-int iteration variables

## Multi-dimensional array improvements
- [ ] https://github.com/dotnet/runtime/issues/71674 RyuJIT: support cloning loop nests with multi-dimensional array accesses
- [ ] https://github.com/dotnet/runtime/issues/71676 Improve hoisting, CSE, LSRA for MD array accesses

## Loop peeling
- [ ] (Stretch) https://github.com/dotnet/runtime/issues/93142 Implement loop peeling

**Comment by jakobbotsch** [comment]
With recent work we are close to having moved from the old lexical representation of loop to a more general graph-based one. Since I'll be out until New Year's, here's a more detailed list of work done and expected future work.

* Remove duplicated dominator and DFS implementations
  * #95251 
  * #95299 (remove a dependency on old dominators)
  * #95507
  * #95726
  * Currently the old dominators are still used by `optSetBlockWeights` and by `optFindAndScaleGeneralLoopBlocks`, but should be switchable to the new dominator implementation relatively easily.
  * `optFindAndScaleGeneralLoopBlocks` also depends on dense reachability sets; in common cases (where the flow graph does not have irreducible loops) we may be able to replace them by loop containment checks. Eventually we'd like all of this to be replaced by profile synthesis.
* Port old loop-based optimizations to new representation
  * #95326
  * #95589 
  * #95729
  * #95734 
  * #95836
  * [ ] Loop unrolling
    * This turns out to be hard if we also have to maintain the old loop table, so I am removing dependencies on the old loop table first; see below
* Switch loop optimizations to run on newly recognized loops
  * Remove remaining dependencies on old loop table to avoid maintaining it
    * #95854 
    * #95809
    * #95925
    * [ ] Port loop unrolling and get it down to only `m_newToOldLoop[x] != nullptr`-style quirks
    * [ ] Replace `m_newToOldLoop[x] != nullptr`-style quirks with `BBF_OLD_LOOP_HEADER_QUIRK`
    * [ ] Delete `m_oldToNewLoop` and `m_newToOldLoop`
    * [ ] Invalidate old loop table immediately after old loop finding (but still set `BBF_OLD_LOOP_HEADER_QUIRK`, and still do old loop canonicalization)
  * [ ] Port loop canonicalization (creating preheaders for all loops recognized by new loop-finding, and stopping some of the "extra" canonicalization that we do not need anymore, like canonicalization of top blocks)
  * [ ] Switch loop cloning
  * [ ] Switch loop unrolling
  * [ ] Switch loop hoisting
  * [ ] Switch loop alignment
  * [ ] Delete `BBF_OLD_LOOP_HEADER_QUIRK`
  * [ ] Delete old loop finding
* [ ] Replace remaining old dominators with new dominator implementation
* [ ] Delete old dominator implementation
* [ ] See if we can remove uses of dense reachability sets

**Comment by JulieLeeMSFT** [comment]
.NET9 work is complete. Closing.

**Comment by JulieLeeMSFT** [comment]
Will move the pushed-out items to .NET 10 user story during .NET 10 planning.
