### ISSUE TITLE
Intel architecture improvements for .NET 9

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#93196]
This issue describes planned improvements to Intel architecture (x86, x64) ISA support for .NET 9.

In .NET 8, AVX-512 ISA support was added (see https://github.com/dotnet/runtime/issues/77034). In .NET 9, this support will be further improved and leveraged for improved performance, especially with expanded libraries utilization of the recently implemented AVX-512 support. Investigations and implementation will start to support the newly announced AVX10.

## Libraries work

- [x] **(Q4'23)** Light up BitArray with Vector512
  - https://github.com/dotnet/runtime/pull/91903
- [x] **(Q4'23)** Light up String with Vector512
  - https://github.com/dotnet/runtime/pull/93043
- [x] **(Q4'23)** Light up Base64 encode/decode with Vector512
  - https://github.com/dotnet/runtime/pull/92241
- [x] Consider SIMD/AVX optimization for Tensor (https://github.com/dotnet/runtime/issues/89639)

## AVX10

AVX10 is a new set of vector ISA extensions, described [here](https://www.intel.com/content/www/us/en/content-details/784267/intel-advanced-vector-extensions-10-intel-avx10-architecture-specification.html). We expect to begin preliminary work to support AVX10 in .NET 9, at least the parts that most directly map to the already supported AVX-512. An `arch-avx10` GitHub label is defined to be added to all related PRs and issues: https://github.com/dotnet/runtime/labels/arch-avx10

- [x] Add VM/JIT AVX10 awareness: CPUID enumeration and detection https://github.com/dotnet/runtime/pull/99784
- [x] Propose a new AVX10 API: https://github.com/dotnet/runtime/issues/98069
- [x] **(Q2'24)** Do JIT codegen implementation of the API
- [x] **(Q2'24)** Add AVX10 APIs https://github.com/dotnet/runtime/pull/101938 https://github.com/dotnet/runtime/pull/103241
- [x] Enhance Vector256 codegen with AVX10 instructions (related to what has already been done for AVX512VL) https://github.com/dotnet/runtime/pull/101938 https://github.com/dotnet/runtime/pull/103241
- [x] **(Q2'24)** Allow additional 16 YMM registers for AVX10 https://github.com/dotnet/runtime/pull/101938 https://github.com/dotnet/runtime/pull/103241
- [x] Allow AVX-512 optimizations for YMM (e.g., scalar conversion, vpternlog) https://github.com/dotnet/runtime/pull/101938 https://github.com/dotnet/runtime/pull/103241
**-- The current avx512 optimizations is working for avx10 targets**
- [x] Identify test plan for .NET 9 sign-off
**-- @tannergooding has identified a set of tests and @khushal1996 has successfully completed all stress tests getting expected results.**

## RyuJIT feature work

- [x] **(Q4'23)** Enable EVEX embedded rounding support in xarch emitter. https://github.com/dotnet/runtime/issues/93154
  - https://github.com/dotnet/runtime/pull/94684
- [x] **(Q4'23)** Add optimization for scalar/vector conversion of uint32/uint64 to/from packed float/double. https://github.com/dotnet/runtime/issues/80829
- [x] **(Q4'23)** Finish AVX-512 specific light-up for `Vector128/256/512<T>` https://github.com/dotnet/runtime/issues/85207
  - https://github.com/dotnet/runtime/pull/87851
  - https://github.com/dotnet/runtime/pull/95568
  **- All done except for Vector512.Dot, which will be pushed out to future item.** 
- [x] Add EVEX encoding opmask (k) register masking for per-instruction opmask to xarch emitter. https://github.com/dotnet/runtime/issues/80821

## RyuJIT optimization work

- [x] AVX512: Fold some bitwise operations to vpternlogq https://github.com/dotnet/runtime/issues/84534 (@tannergooding  to open a future work item for further optimizations)
- [x] Add optimization for scalar conversion of float/double to ulong https://github.com/dotnet/runtime/issues/89279

## API design work

- [x] https://github.com/dotnet/runtime/issues/73604
- [x] (Reconsider implementing?) https://github.com/dotnet/runtime/issues/74613
- [x] https://github.com/dotnet/runtime/issues/76579

## Future Work
Some of the planned work for .NET 9 have been pushed out to future work.
### Libraries work
- [ ] Light up IndexOfAnyAsciiSearcher for AVX512. https://github.com/dotnet/runtime/issues/93222 (@MihaZupan) 
- [ ] Consider SIMD JSON acceleration **(Owner: Intel)**
- [ ] Consider XML API acceleration **(Owner: Intel)**
- [ ] (**Help Wanted**) Light up Utf8/Utf16 code with Vector512. https://github.com/dotnet/runtime/issues/86119
- [ ] (**Help Wanted**) Light up Ascii.Utility methods with Vector512 code paths. https://github.com/dotnet/runtime/issues/89280
  - https://github.com/dotnet/runtime/pull/99982
  - https://github.com/dotnet/runtime/pull/88532 
  - https://github.com/dotnet/runtime/pull/89892

### AVX10

- [ ] Allow embedded rounding for YMM/ZMM (related: https://github.com/dotnet/runtime/issues/93154) (**Owner: Intel**, Starting AVX10.2)
- [ ]  (**Help Wanted**) Convert remaining AVX2 implementations to Vector256 https://github.com/dotnet/runtime/issues/101251

### RyuJIT feature work
- [ ] `Vector512.Dot`: AVX-512 specific light-up for `Vector512.Dot` https://github.com/dotnet/runtime/issues/85207

## `Vector<T>`

- [ ] Consider `Vector<T>` expanding to `Vector512<T>`, either automatically or opt-in. (@tannergooding plans to get back to it as a best effort.)

## JCC erratum

- [ ] https://github.com/dotnet/runtime/issues/93243 (@TIHan)

### Debugging / diagnostics work (@BruceForstall)
- [ ] https://github.com/dotnet/runtime/issues/87854
- [ ] Ensure ELT (enter/leave/tailcall hooks, for profiling) works.

**Comment by BruceForstall** [comment]
> Is there maybe any interest in adding the workaround for the JCC erratum (#35730) in .Net 9? I've seen minor codegen improvements be reported as huge regressions because the code started to hit this issue.

@AndyAyersMS has expressed a desire to at least have a mode that could be used for performance testing to avoid the JCC erratum. Whether we could enable this always would depend on how uniform the improvements would be. It is expected there would be some code size regressions -- possibly significant -- due to the need to insert NOPs.

**Comment by BruceForstall** [comment]
> Didn't we already accept that tradeoff with loop alignment?

Yes, but this could be a very different magnitude of regression that will need to be measured.

**Comment by BruceForstall** [comment]
I went ahead and created https://github.com/dotnet/runtime/issues/93243 related to adding a JIT mode to avoid the JCC erratum, and linked it here.

**Comment by Spacefish** [comment]
I added Vector512 support for Min/Max of simple numeric datatypes in this PR: https://github.com/dotnet/runtime/pull/93369

**Comment by huoyaoyuan** [comment]
What about the upcoming APX extension? It looks like a major change of x86-64. I can see discussions around ABI for APX in GCC mail thread: https://gcc.gnu.org/pipermail/gcc/2023-July/242154.html https://gcc.gnu.org/pipermail/gcc-help/2023-August/142801.html

Maybe it's too early for .NET to adopt APX, but I'd like to see the estimated timeline. Should we wait for MSVC to define the calling convention?

**Comment by tannergooding** [comment]
We want to have hardware available on which it can run. 

While Intel hasn't given an official timeline as of yet, such hardware is most likely not in the .NET 9 lifetime which ships in November 2024 and will be out of support around May 2026. 

I expect this work will be done for .NET 10 which will likely ship around November 2025 (assuming we don't change our current pacing of releases) and be out of support November 2028.

**Comment by MichalPetryka** [comment]
> We want to have hardware available on which it can run.

Would using [Intel SDE](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html) not be enough for testing the support for it?

**Comment by tannergooding** [comment]
There's no point in scheduling work to be done for hardware that doesn't exist yet, particularly if that hardware is unlikely to exist within the lifetime of a release.

That is, we know that AVX10 is going to exist for Granite Rapids, as per the official announcement: https://www.intel.com/content/www/us/en/content-details/784267/intel-advanced-vector-extensions-10-intel-avx10-architecture-specification.html. The AVX10.1 work is correspondingly happening in .NET 9

While no official release date has been announced for APX, it is unlikely to happen in a timeframe that makes .NET 9 a good choice to target.

**Comment by JulieLeeMSFT** [comment]
Updated the Planned work with the current status. Marked completed work and moved items that will be pushed out to **Future Work** section.

**Comment by JulieLeeMSFT** [comment]
Moved JCC erratum and Vector<T> work to future work becasue we don't have time to work on them in .NET 9. 
Closing this user story as completed.

**Comment by JulieLeeMSFT** [comment]
@tommcdon, Debugger team, mentioned: "The debugger has logic to [decode](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fblob%2F7911e709c0d7d38f17faf46fa21cecc9c25f1e3a%2Fsrc%2Fcoreclr%2Fdebug%2Fee%2Famd64%2Fwalker.cpp%23L24&data=05%7C02%7CJulie.Lee%40microsoft.com%7C36c1afb963d34ed2ebec08dcb1b208b2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638580625429187860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nN0aucqoUpchU0nb5mMt%2BshYKdv7R53br7ynBAVAplg%3D&reserved=0) x64 instructions for the purposes of setting breakpoints and determining if there are instruction-relative read/writes/jumps.  Whenever the JIT generates new instruction encodings that our logic does not understand, we need to regenerate the decoder.  Fortunately, we have a tool that can automatically generate the instruction decoder logic - [runtime/src/coreclr/debug/ee/amd64/gen_amd64InstrDecode/README.md at main · dotnet/runtime (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fblob%2Fmain%2Fsrc%2Fcoreclr%2Fdebug%2Fee%2Famd64%2Fgen_amd64InstrDecode%2FREADME.md&data=05%7C02%7CJulie.Lee%40microsoft.com%7C36c1afb963d34ed2ebec08dcb1b208b2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638580625429201535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=R38YMeqlBtC6Who33DfzgJ718g9EmlTf1jge4WXAFj4%3D&reserved=0).  Work was done in .NET 8 to support AVX512 EVEX instruction encodings - [Support breakpoints on AVX-512 instructions by BruceForstall · Pull Request #89705 · dotnet/runtime (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fpull%2F89705&data=05%7C02%7CJulie.Lee%40microsoft.com%7C36c1afb963d34ed2ebec08dcb1b208b2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638580625429206578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=6mwlnM0%2FvOEAm806sOznFe%2Fsw%2Fyw%2F249p7lwsMIXvcI%3D&reserved=0).  It’s our current belief that the existing instruction decoder will correctly decode AVX10.1."
