### ISSUE TITLE
Fatal runtime errors do not always generate crashes/Watson reports

### ISSUE THREAD

**Issue by leculver** [dotnet/runtime#93682]
### Work Items

- [ ] Fix `CrashDumpAndTerminateProcess` to properly generate Watson reports and launch the registered JIT debugger (AeDebug).
- [ ] Change the behavior of `GCCToOSInterface::DebugBreak()` in the GC.  This should only call ::DebugBreak or raise(SIGTRAP) in debug builds.  Many calls to this method should be converted to `FATAL_GC_ERROR();`.
- [x] Investigate whether to change the behavior of raw RaiseFailFastException in the runtime should call out to CreateDump on Linux.
- [ ] Ensure that we always call HandleFatalError with a sensible error code (and not 0 or 1, which the user may want to use in their application).

### Description

We've received off and on reports for years that when the runtime "crashes", we don't always invoke AeDebug (just in time debugging) and those issues do not make it to Watson.  I took another look at the issue by generating a wide variety of runtime crashes, ExecutionEngineExcecptions, and similar and have finally narrowed the issue down two a few issues, though there may be more lurking.

First, a call to `EEPolicy::HandleFatalError` will make its way to `SafeExitProcess(exitCode, SCA_TerminateProcessWhenShutdownComplete)`, which calls `CrashDumpAndTerminateProcess(exitCode)`, which finally calls `TerminateProcess`.  On Linux, this works as expected, because on this platform `TerminateProcess()` resolves down to a call to `abort()`.  On Windows, we call the real `TerminateProcess` method on our own process and provide the failing error code, but this does not count as a "crash" as the Windows operating system sees it.  This means specifically on Windows, anything ending up in `CrashDumpAndTerminateProcess` will not generate AeDebug events or make its way to Watson.

Second, the GC to EE interface has a `GCToOSInterface::DebugBreak();` which seems to be called when we also reach fatal conditions, and this isn't compiled out on non-debug builds.  On Windows, this function calls out to raw `DebugBreak` and `raise(SIG_TRAP)` elsewhere.  In both cases, this does generate a real crash (and probably a Watson event...though I can't seem to find them).  However, this call to `GCToOSInterface::DebugBreak` also steps in between our normal exception handling/event/etc code.  We don't end up in HandleFatalError or SafeExitProcess, which does work to push ETW events, or call out to create-dump, or even set `g_fForbidEnterEE` or `g_fNoExceptions`.

Third, there are a few raw calls to `RaiseFailFastException` in the runtime.  Anything on non-Windows which makes its way there will _not_ end up triggering CreateDump on unix platforms.  We need to code review those calls and see if we should shell out to CreateDump, or if we should really just _fail fast_ instead.  On the one hand, hitting stack corruption might be malicious software, so we don't want to run any more code than we have to.  On the other hand, this means something like stack corruption on linux (which runs through `RaiseFailFastException` in JitHelpers.cpp) won't get a coredump generated.

Fourth, we end up calling `EEPOLICY_HANDLE_FATAL_ERROR` with a lot of odd error codes.  For example, `EEPOLICY_HANDLE_FATAL_ERROR(1)` or `(0)` is sprinkled in several places in the runtime.  On Linux, we'll still end up in `abort()`, but on Windows this means that we currently just quietly exit with a return code of 1 or 0 instead of an obvious HRESULT.  If we change the behavior of `HandleFatalError` to call `RaiseFailFastException`, we don't want the exception code to be 0 or 1, but something more meaningful, so all of that should be investigated.

### Reproduction Steps

I eventually found this by causing massive amounts of heap corruption until I got a repro.  The behavior can be reproduced more easily by adding `FATAL_GC_ERROR();` to `gc_heap::mark_object_simple1`, then commenting out the _ASSERTE and calls to DebugBreak in `FATAL_GC_ERROR();`.  This makes every GC trigger a call to `GCToEEInterface::HandleFatalError((unsigned int)COR_E_EXECUTIONENGINE);`.

### Expected behavior

On Windows, any time the runtime encounters a fatal error, we should always trigger Watson and invoke the AeDebugger.
On Linux, any time the runtime encounters a fatal error, we should always trigger createdump (if requested).

### Actual behavior

We do not always trigger AeDebug and/or createdump due to the issues outlined above.

### Regression?

This seems to be long standing behavior, probably as far back as 3.1 if not before.

**Comment by mikem8361** [comment]
>> - [ ] Investigate whether to change the behavior of raw RaiseFailFastException in the runtime should call out to CreateDump on Linux.

RaiseFailFastException does generate a coredump with createdump on Linux and MacOS.  The call to PROCAbort in that function does this.

**Comment by leculver** [comment]
Ah, you are right!  I didn't fully dig through that callchain.  I'll check that off the list.

**Comment by mangod9** [comment]
Hi @leculver, is this something you are planning on fixing for 9?

**Comment by leculver** [comment]
A lot of this has changed with the exception changes this release.  I did not get around to this issue due to security work.  I'm going to close this issue and just open a PR when it's ready so this isn't floating forever.
