### ISSUE TITLE
[mono][wasi] Wasi size improvements

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#94803]
The wasi build needs several steps to reduce the final binary size.

- [ ] Icall linking: https://github.com/dotnet/runtime/pull/91843
  - [ ] blocked by https://github.com/dotnet/runtime/pull/92095
- [ ] runtime components: https://github.com/dotnet/runtime/pull/94738
  - [ ] add ilgen component tasks to wasi
- [ ] disabling MonoEnableAssertMessages for release builds
  - [ ] use resource strings for mono assertions/logs/tracing
- [ ] Optional wasm-opt pass

**Comment by lewing** [comment]
cc @SamMonoRT
