### ISSUE TITLE
[mono][wasm] wasm interop tracking

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#95084]
Tracking issue for WasmInterop:

- [x] #95087
- [x] PInvokeTableGenerator improvements
    - [x] Handle DllImport function pointers properly https://github.com/dotnet/runtime/pull/94446
    - [x] Support Wasm module imports when WasmLinkageAttribute is applied to DllImport
    - [x] Fix DllImport marshaling
    - [x] Support EntryPoint on UnmanagedCallersOnly
      - [x] Export UCO entry point in WASM module

**Comment by silesmo** [comment]
https://github.com/dotnet/runtime/issues/96419

**Comment by maxkatz6** [comment]
Right now DllImport on WASM throws a compiler error, if there is an unsupported pinvoke or marshaling. Such as com interop, or some windows specific marshaling. 

Since on other platforms DllImport seems to be lazily evaluates, unsupported DllImport would crash in runtime when executed. Which is fine, since such code would commonly be hidden under platform conditions, and never actually be executed. But with WASM it’s not possible. 

Was there an idea to, possible, replace such pinvokes with stubs that would throw an exception in runtime? Mimicking behavior of non-wasm platforms.

**Comment by lewing** [comment]
> Right now DllImport on WASM throws a compiler error, if there is an unsupported pinvoke or marshaling. Such as com interop, or some windows specific marshaling.
> 
> Since on other platforms DllImport seems to be lazily evaluates, unsupported DllImport would crash in runtime when executed. Which is fine, since such code would commonly be hidden under platform conditions, and never actually be executed. But with WASM it’s not possible.
> 
> Was there an idea to, possible, replace such pinvokes with stubs that would throw an exception in runtime? Mimicking behavior of non-wasm platforms.

I'm not sure what .NET version or runtime you are referring to but the WASM runtimes definitely support most DLLImports when the build is correctly configured.

**Comment by pavelsavara** [comment]
maybe this is already fixed @lewing @mkhamoyan ?

**Comment by mkhamoyan** [comment]
I am not sure about `Fix DllImport marshaling`.
If that is related to this https://github.com/dotnet/runtime/issues/94895 I guess we can close this ticket, and follow up in #94895.

**Comment by maxkatz6** [comment]
@lewing hi. I found that I didn't answer to your question about unsupported DllImports. 
Just created an issue with more details and repro: https://github.com/dotnet/runtime/issues/104463
