### ISSUE TITLE
Projection tooling for Swift interop in .NET 10

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#95633]
## Overview

This issue tracks the progress of implementing and shipping the [projection tooling](https://github.com/dotnet/runtimelab/tree/feature/swift-bindings) for .NET 10. The primary goal is to release the projection tooling as an experimental NuGet CLI capable of generating bindings for a specific set of Swift frameworks, as defined in the use cases. It should follow general principles outlined in the [Swift interop proposal](https://github.com/dotnet/designs/blob/main/proposed/swift-interop.md).

Currently, the projection tooling is available as an experimental NuGet CLI in [dotnet-experimental feed](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-experimental/NuGet/Swift.Bindings/overview/1.0.0-alpha.24176.3).

### Workstream: Swift language features
Based on the selected frameworks, the following Swift language features are in use:
 - [x] dotnet/runtimelab#2822
 - [x] https://github.com/dotnet/runtimelab/issues/2930
 - [x] https://github.com/dotnet/runtimelab/issues/2931
 - [x] https://github.com/dotnet/runtimelab/issues/2837
 - [x] Built-in types
   - [x] https://github.com/dotnet/runtimelab/issues/2832
   - [x] https://github.com/dotnet/runtimelab/issues/2831
   - [x] https://github.com/dotnet/runtimelab/issues/2833
   - [x] https://github.com/dotnet/runtimelab/issues/2834
   - [x] https://github.com/dotnet/runtimelab/issues/2929

### Workstream: Swift runtime features
To support the mentioned language features, the following runtime features are required:
 - [x] https://github.com/dotnet/runtimelab/issues/2838
 - [x] https://github.com/dotnet/runtimelab/issues/2840

### Workstream: Projection tooling
To generate bindings, we need projection tooling that includes the following components (based on the current design):
 - [x] https://github.com/dotnet/runtimelab/issues/2842
 - [x] https://github.com/dotnet/runtimelab/issues/2918

### Workstream: Shipping
We need the following infrastructure:
 - [x] https://github.com/dotnet/runtimelab/issues/2849
 - [x] https://github.com/dotnet/runtimelab/issues/2850

> [!NOTE]  
> The projection tooling will be experimental in .NET 10.

**Comment by stephen-hawley** [comment]
Might want to include "Update BTfS to run on .NET 7 and later" - I'm in the middle of that right now.
