### ISSUE TITLE
Epic: Trimming and Native AOT in .NET 9

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#96511]
This is an in-progress record of work planned for Native AOT in .NET 9. As always, nothing is promised until it's done and shipped.

- [ ] **Bugs**
- [x] https://github.com/dotnet/runtime/issues/96859
- [ ] Source-build support
- [x] https://github.com/dotnet/runtime/issues/77178

**Comment by hez2010** [comment]
Any chance to finalize and ship the NativeAOT-android experiment with JNI support in .NET 9?

**Comment by slxdy** [comment]
This might be something for .NET 10, but any plans on optimizing the initialization process in the entry point of DLLs (the real entry point, not the managed one)? Specifically talking about `crt_process_attach`.

This might be a bit specific, but for example, when I tried to manually map a simple NativeAOT DLL into memory (aka replicate the process of LoadLibrary but manually), I ran into many errors. But one error that really caught my attention was `Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.`. How and why does this error even exist in NativeAOT, and why is it being trigger when the entry point isn't called from the real LoadLibrary?
I feel like there is a lot of unnecessary stuff going on there.

**Comment by agocke** [comment]
> Any chance to finalize the NativeAOT-android experiment with JNI support and ship it in .NET 9?

Sorry, didn't see this question earlier. Answer is no. Getting the JNI support requires having Java interop work with CoreCLR (not just Mono) and that's a large feature. In particular, the existing support uses direct interaction with the Mono GC (sgen), so it needs to be rewritten to either use the CoreCLR GC, or ideally rewritten to not depend on specific unmanaged GC APIs at all.

**Comment by agocke** [comment]
@slxdy 

> I feel like there is a lot of unnecessary stuff going on there.

There isn't/shouldn't be. If you walk through the Native AOT code in a native debugger you can see the entire chain. There's not much going on. Your case sounds more like a bug to me. I would try debugging it and figure out exactly what's going wrong.

**Comment by agocke** [comment]
Closing out as we're still working on bugs, but it's unlikely that we're bringing in anything new and big for net9
