### ISSUE TITLE
Libraries work to support Cloud Native effort for .NET 9

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#97522]
### OpenTelemetry
- [x] https://github.com/dotnet/runtime/issues/63650 
- [x] https://github.com/dotnet/runtime/issues/53641 
- [x] https://github.com/dotnet/runtime/issues/92625 
- [x] https://github.com/dotnet/runtime/issues/97680 

### Logging
- [x] https://github.com/dotnet/runtime/issues/104129

### Metrics
- [x] https://github.com/dotnet/runtime/issues/85372 - https://github.com/dotnet/runtime/issues/104844
- [x] https://github.com/dotnet/runtime/issues/93795 

###  MetricsEventSource
- [x] https://github.com/dotnet/runtime/issues/93767 
- [x] https://github.com/dotnet/runtime/issues/93097 

---

##  MetricsEventSource
- [ ] https://github.com/dotnet/runtime/issues/71563 

## Logging
- [ ] https://github.com/dotnet/runtime/issues/85116 
- [ ] https://github.com/dotnet/runtime/issues/82465 
- [ ] https://github.com/dotnet/runtime/issues/87250 

## Logging Source Gen
Consolidating all source gen work for logging, options, and configuration - L

- [ ] https://github.com/dotnet/runtime/issues/93309
- [ ] https://github.com/dotnet/runtime/issues/76119
- [ ] https://github.com/dotnet/runtime/issues/91178

## Analyzers
- [ ] https://github.com/dotnet/runtime/issues/78402 
- [ ] https://github.com/dotnet/runtime/issues/78406

**Comment by ericstj** [comment]
@tarekgh should we close this and move some of the future work into a 10.0 issue?
