### ISSUE TITLE
[Linux/arm32 R2R] Cross-Bitness Support for CrossGen

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#9786]
Currently, when build  Linux/arm coreclr on Linux/x64 dev machine the following two sets of user environments must be installed:
1. x64/arm compiler for native build;
2. x64/x84 for cross-components used for crossgen/AOT to improve performance.

**Purpose:** Adapting crossgen and coreclr to be able to generate 32-bit ReadyToRun images on a 64-bit host without requiring to install x64/x84 Linux environment. 

**Backlog:**

- [x] Replace expessions like `sizeof(void*)` with target specific macro `TARGET_POINTER_SIZE` (#16514 dotnet/coreclr#18028)
- [x] Replace usages of macro `_WIN64` with `_TARGET_64BIT_` (as we do in RyuJIT) (#16531 dotnet/coreclr#16660)
- [x] Use `emitter::code_t` rather than `ssize_t` and `size_t` in emitarm.cpp and emitarm.h (#16617)
- [x] Initial cross-bitness support for RyuJIT (#17005)
- [x] Enable building of Ubuntu/arm crossarch components in CI and official build (#16729 dotnet/coreclr#16839 dotnet/coreclr#16859 dotnet/coreclr#16953 dotnet/coreclr#17375)
- [x] Replace `sizeof(TADDR)` with `TARGET_POINTER_SIZE` in Zapper (#18028)
- [x] Replace `sizeof(ObjHeader)` `sizeof(Object)` etc with target-specific constants `OBJHEADER_SIZE` `OBJECT_SIZE` (#18245)
- [x] Use target-specific `OFFSETOF__DelegateObject__target` `OFFSETOF__DelegateObject__methodPtr` constants etc in JitInterface (#18329) 
- [x] Use target-specific constants during instance fields placement (#18366)
- [x] Use target-specific constants during regular and thread static fields placement (#18636)
- [x] Use `TARGET_POINTER_TYPE` `TARGET_POINTER_SIZE` during ZapWriteReloc (#18665)
- [x] Code cleanup in ARM32 and ARM64 emitters (#18878)
- [x] Handle MovRelocatableImmediate as a special case (IF_T2_N3) in JIT (#19013)
- [x] Stop using `size_t` in `GcInfoEncoder::Build()` (#19206)
- [x] Initial support for cross-bitness crossgen validation against native crossgen (#19514)
- [x] Return target-specific NaN during constant folding in JIT when target ARM32/ARM64 (#19395)
- [ ] Disable constant folding in JIT resulting in NaN, infinities etc
(#19483)
- [ ] Split `CodeGen::instGen_Set_Reg_To_Imm` into relocatable immediate/non-relocatable immediate cases (#19091)
- [x] Add support in CMakeLists.txt, src/pal/src/CMakeLists.txt, build.sh and build.cmd for building x64_arm crosscomponents
- [x] Enable some definitions and disable unreachable code causing compilation warnings/errors, do upcasts to suppress such warnings during cross-bitness crossgen compilation (#18707):
* For example, `RtlUnwindEx` `RtlVirtualUnwind` are needed during x86_arm on Windows and on x64_arm on Linux but not on `x64_arm` on Windows
* Many functions in src/inc/regdisp.h never reachable from crossgen but causes compilation errors
- [ ] Consider splitting `GenTreeIntCon` into "a tree node that holds handles (i.e. pointers to host functions)" and "a tree node that never holds host pointers - i.e. pure integer constant"
- [x] Handling `VNForPtrSizeIntCon` and `genTreeHashAdd` in JIT in crossbitness scenario
- [x] Even after these some code in JIT would cause compilation warnings - requires either explicit casting or refactoring (e.g. `roundUp`)

- [x] `EEClass::AddChunk` must append methods (not prepend them as it now) in order to produce same output in both same-bitness and cross-bitness scenarios
