### ISSUE TITLE
Enable .NET 9 developers to build more intelligent apps

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#97896]
This epic issue will track other areas of work that contribute to the .NET library's intelligent apps effort

### Tensors
- [ ] https://github.com/dotnet/runtime/issues/93286
- [x] https://github.com/dotnet/runtime/issues/24385

### Tokenizers
- [ ] https://github.com/dotnet/machinelearning/issues/6984

**Comment by ericstj** [comment]
The subset of this work planned for 9.0 is complete.
