### ISSUE TITLE
.NET 9 Host Improvements

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#97931]
- [ ] https://github.com/dotnet/runtime/issues/77800
- [ ] https://github.com/dotnet/runtime/issues/64430
- [ ] https://github.com/dotnet/sdk/issues/34917
- [ ] [Support local SDK installs in global.json](https://github.com/dotnet/designs/pull/303)
- [x] https://github.com/dotnet/runtime/issues/99027

**Comment by xoofx** [comment]
Hey @agocke, I have a question:

is:

- #99027 

the implementation of https://github.com/dotnet/designs/pull/303 ?

**Comment by agocke** [comment]
Nope that’s just an API the sdk can use to find installed runtimes. Unfortunately have not had time to implement the local sdk support yet.

**Comment by agocke** [comment]
We're pretty much out of time for .NET 9. I'll close this out. Unfortunately most of the above issues will need to move to 10.
