### ISSUE TITLE
[mono] Implement generic support for `UnsafeAccessorAttribute`

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#99830]
Refer to the main tracking issue: #89439

There are two types scenarios here regarding to the extern static method marked with UnsafeAccessorAttribute:

- [x] Non-generic instance: the extern static method itself doesn't have a type parameter (https://github.com/dotnet/runtime/pull/101265)
- [x] Generic instance: the extern static method itself has a type parameter 
    - [x] JIT/interpreter (https://github.com/dotnet/runtime/pull/101442)
    - [x] AOT - related test failure issue (https://github.com/dotnet/runtime/issues/92883)
    - [x] AOT infrastructure work - https://github.com/dotnet/runtime/pull/101732
- [x] Handle negative cases (https://github.com/dotnet/runtime/pull/101850)

**Comment by fanyang-mono** [comment]
Removed  https://github.com/dotnet/runtime/issues/102942 and https://github.com/dotnet/runtime/issues/102045 from the list since it can be done separately / not at all.
