### ISSUE TITLE
[mono] [infra] Mono/Mobile infrastructure improvements.

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#99949]
## Description
This issue lists improvements needed to gain reliable and comprehensive coverage on Mobile platforms.

## Goals
The purpose of the following improvements is to improve experience with Mono/Mobile testing. Specifically, minimize failures occurring on `runtime-extra-platforms` CI pipeline so that its status can be monitored using Build Analysis and be used regularly by contributors.

## Tasks
The list will be updated as the progress continues...
- [ ] Apple mobile test coverage improvements: https://github.com/dotnet/runtime/issues/84254
- [ ] Enable x64/arm64 fullAOT-llvm pipelines: https://github.com/dotnet/runtime/issues/90427
- [ ] Unify console and device output logs for mobile platforms: https://github.com/dotnet/runtime/issues/99947
- [ ] Triage failing tests to get knowledge about issues related to: infrastructure (e.g., device not found, time-out), flakiness (tests are nor reliable), runtime (real failures caused by Runtime), etc.

**Comment by matouskozak** [comment]
Issue mostly completed or outdated
